/* -----------------------------------------------------------------------------

 Portions of this software may have been derived from the UCD-SNMP
 project,  <http://www.net-snmp.org/>  from the University of
 California at Davis, which was originally based on the Carnegie Mellon
 University SNMP implementation.  Portions of this software are therefore
 covered by the appropriate copyright disclaimers included herein.

 The release used was version 5.0.11.2 of June 2008.  "net-snmp-5.0.11.2"

 -------------------------------------------------------------------------------
*/

/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf
 */


#include <main.h>
#include <cyg/hal/hal_io.h>
#include <cyg/infra/cyg_type.h>
#include <cyg/hal/hal_arch.h>
#include <cyg/infra/diag.h>
#include <cyg/hal/drv_api.h>
#include <cyg/io/eth/netdev.h>
#include <cyg/io/eth/eth_drv.h>
#include <cyg/infra/cyg_ass.h>
#include <sys/param.h>

#include <ucd-snmp/config.h>
#if HAVE_STDLIB_H
#include <stdlib.h>
#endif                          /* HAVE_STDLIB_H */
#if HAVE_STRING_H
#include <string.h>
#else
#include <strings.h>
#endif                          /* HAVE_STRING_H */

#include <ucd-snmp/mibincl.h>   /* Standard set of SNMP includes */
#include <ucd-snmp/mibgroup/util_funcs.h>       /* utility function declarations */

#include "vtss_snmp_api.h"
#include "rfc3411_framework.h"
#include "ucd_snmp_rfc3411_framework.h"

#if VTSS_SWITCH_STACKABLE
#include "topo_api.h"
#endif

#include "msg_api.h"

/*
 * +++ Start (Internal implementation declarations)
 */
#if RFC3411_SUPPORTED_FRAMEWORK_SNMPENGINE
#include <ucd-snmp/snmpv3.h>
#include "rfc1213_mib2.h"
#include "ucd_snmp_rfc1213_mib2.h"
#endif /* RFC3411_SUPPORTED_FRAMEWORK_SNMPENGINE */
/*
 * --- End (Internal implementation declarations)
 */

#if RFC3411_SUPPORTED_FRAMEWORK_SNMPENGINE
/*
 * snmpEngine_variables_oid:
 *   this is the top level oid that we want to register under.  This
 *   is essentially a prefix, with the suffix appearing in the
 *   variable below.
 */

oid             snmpEngine_variables_oid[] =
{ 1, 3, 6, 1, 6, 3, 10, 2, 1 };

/*
 * variable4 snmpEngine_variables:
 *   this variable defines function callbacks and type return information
 *   for the snmpEngine mib section
 */

struct variable4 snmpEngine_variables[] = {
    /*
     * magic number        , variable type , ro/rw , callback fn  , L, oidsuffix
     */
#define SNMPENGINEID                1
    {SNMPENGINEID, ASN_OCTET_STR, RONLY, var_snmpEngine, 1, {1}},
#define SNMPENGINEBOOTS             2
    {SNMPENGINEBOOTS, ASN_INTEGER, RONLY, var_snmpEngine, 1, {2}},
#define SNMPENGINETIME              3
    {SNMPENGINETIME, ASN_INTEGER, RONLY, var_snmpEngine, 1, {3}},
#define SNMPENGINEMAXMESSAGESIZE    4
    {SNMPENGINEMAXMESSAGESIZE, ASN_INTEGER, RONLY, var_snmpEngine, 1, {4}},
};

/*
 * (L = length of the oidsuffix)
 */

/*
 * Initializes the snmpEngine module
 */
void
ucd_snmp_init_snmpEngine(void)
{
    DEBUGMSGTL(("snmpEngine", "Initializing\n"));

    /*
     * register ourselves with the agent to handle our mib tree
     */
    REGISTER_MIB("snmpEngine", snmpEngine_variables, variable4,
                 snmpEngine_variables_oid);
}

/*
 * var_snmpEngine():
 *   This function is called every time the agent gets a request for
 *   a scalar variable that might be found within your mib section
 *   registered above.  It is up to you to do the right thing and
 *   return the correct value.
 *     You should also correct the value of "var_len" if necessary.
 *
 *   Please see the documentation for more information about writing
 *   module extensions, and check out the examples in the examples
 *   and mibII directories.
 */
u_char         *
var_snmpEngine(struct variable *vp,
               oid *name,
               size_t *length,
               int exact, size_t *var_len, WriteMethod **write_method)
{
    /*
     * variables we may use later
     * static long long_ret;
     * static u_long ulong_ret;
     * static u_char string[SPRINT_MAX_LEN];
     * static oid objid[MAX_OID_LEN];
     * static struct counter64 c64;
     */
    static long long_ret;
    static u_char engineID[SNMP_MAXBUF];

    if (header_generic(vp, name, length, exact, var_len, write_method)
        == MATCH_FAILED) {
        return NULL;
    }

    /*
     * this is where we do the value assignments for the mib results.
     */
    switch (vp->magic) {
    case SNMPENGINEMAXMESSAGESIZE: {
        long_ret = 1500;
        return (u_char *) &long_ret;
    }
    case SNMPENGINEID: {
        *var_len = snmpv3_get_engineID(engineID, SNMP_MAXBUF);
        return (u_char *) engineID;
    }
    case SNMPENGINEBOOTS: {
        long_ret = snmpv3_local_snmpEngineBoots();
        return (u_char *) &long_ret;
    }
    case SNMPENGINETIME: {
        long_ret = snmpv3_local_snmpEngineTime();
        return (u_char *) &long_ret;
    }
    default:
        DEBUGMSGTL(("snmpd", "unknown sub-id %d in var_snmpEngine\n",
                    vp->magic));
    }
    return NULL;
}
#endif /* RFC3411_SUPPORTED_FRAMEWORK_SNMPENGINE */

