/* -----------------------------------------------------------------------------

 Portions of this software may have been derived from the UCD-SNMP
 project,  <http://www.net-snmp.org/>  from the University of
 California at Davis, which was originally based on the Carnegie Mellon
 University SNMP implementation.  Portions of this software are therefore
 covered by the appropriate copyright disclaimers included herein.

 The release used was version 5.0.11.2 of June 2008.  "net-snmp-5.0.11.2"

 -------------------------------------------------------------------------------
*/

/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf
 */


#ifndef UCD_SNMP_RFC3411_FRAMEWORK_H
#define UCD_SNMP_RFC3411_FRAMEWORK_H

/*
 * function declarations
 */
#if RFC3411_SUPPORTED_FRAMEWORK_SNMPENGINE
void            ucd_snmp_init_snmpEngine(void);
FindVarMethod   var_snmpEngine;
#endif /* RFC3411_SUPPORTED_FRAMEWORK_SNMPENGINE */

#endif /* UCD_SNMP_RFC3411_FRAMEWORK_H */

