#ifndef _VTSS_SERVAL_REGS_ICPU_CFG_H_
#define _VTSS_SERVAL_REGS_ICPU_CFG_H_

/*
 *
 * VCore-III Register Definitions
 *
 #####ECOSGPLCOPYRIGHTBEGIN#####
 -------------------------------------------
 This file is part of eCos, the Embedded Configurable Operating System.
 Copyright (C) 1998-2012 Free Software Foundation, Inc.

 eCos is free software; you can redistribute it and/or modify it under
 the terms of the GNU General Public License as published by the Free
 Software Foundation; either version 2 or (at your option) any later
 version.

 eCos is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 for more details.

 You should have received a copy of the GNU General Public License
 along with eCos; if not, write to the Free Software Foundation, Inc.,
 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

 As a special exception, if other files instantiate templates or use
 macros or inline functions from this file, or you compile this file
 and link it with other works to produce a work based on this file,
 this file does not by itself cause the resulting work to be covered by
 the GNU General Public License. However the source code for this file
 must still be made available in accordance with section (3) of the GNU
 General Public License v2.

 This exception does not invalidate any other reasons why a work based
 on this file might be covered by the GNU General Public License.
 -------------------------------------------
 #####ECOSGPLCOPYRIGHTEND#####
 */

#include "vtss_serval_regs_common.h"

#define VTSS_ICPU_CFG_CPU_SYSTEM_CTRL_GPR(ri)  VTSS_IOREG(VTSS_TO_CFG,0x0 + (ri))

#define VTSS_ICPU_CFG_CPU_SYSTEM_CTRL_RESET  VTSS_IOREG(VTSS_TO_CFG,0x8)
#define  VTSS_F_ICPU_CFG_CPU_SYSTEM_CTRL_RESET_CORE_RST_CPU_ONLY  VTSS_BIT(3)
#define  VTSS_F_ICPU_CFG_CPU_SYSTEM_CTRL_RESET_CORE_RST_PROTECT  VTSS_BIT(2)
#define  VTSS_F_ICPU_CFG_CPU_SYSTEM_CTRL_RESET_CORE_RST_FORCE  VTSS_BIT(1)
#define  VTSS_F_ICPU_CFG_CPU_SYSTEM_CTRL_RESET_MEM_RST_FORCE  VTSS_BIT(0)

#define VTSS_ICPU_CFG_CPU_SYSTEM_CTRL_GENERAL_CTRL  VTSS_IOREG(VTSS_TO_CFG,0x9)
#define  VTSS_F_ICPU_CFG_CPU_SYSTEM_CTRL_GENERAL_CTRL_CPU_MIPS_DIS  VTSS_BIT(8)
#define  VTSS_F_ICPU_CFG_CPU_SYSTEM_CTRL_GENERAL_CTRL_IF_MIIM_SLV_ENA  VTSS_BIT(7)
#define  VTSS_F_ICPU_CFG_CPU_SYSTEM_CTRL_GENERAL_CTRL_IF_SI_MST_ENA  VTSS_BIT(3)
#define  VTSS_F_ICPU_CFG_CPU_SYSTEM_CTRL_GENERAL_CTRL_CPU_BE_ENA  VTSS_BIT(2)
#define  VTSS_F_ICPU_CFG_CPU_SYSTEM_CTRL_GENERAL_CTRL_CPU_DIS  VTSS_BIT(1)
#define  VTSS_F_ICPU_CFG_CPU_SYSTEM_CTRL_GENERAL_CTRL_BOOT_MODE_ENA  VTSS_BIT(0)

#define VTSS_ICPU_CFG_CPU_SYSTEM_CTRL_GENERAL_STAT  VTSS_IOREG(VTSS_TO_CFG,0xa)
#define  VTSS_F_ICPU_CFG_CPU_SYSTEM_CTRL_GENERAL_STAT_VCORE_CFG(x)  VTSS_ENCODE_BITFIELD(x,4,4)
#define  VTSS_M_ICPU_CFG_CPU_SYSTEM_CTRL_GENERAL_STAT_VCORE_CFG     VTSS_ENCODE_BITMASK(4,4)
#define  VTSS_X_ICPU_CFG_CPU_SYSTEM_CTRL_GENERAL_STAT_VCORE_CFG(x)  VTSS_EXTRACT_BITFIELD(x,4,4)
#define  VTSS_F_ICPU_CFG_CPU_SYSTEM_CTRL_GENERAL_STAT_REG_IF_ERR(x)  VTSS_ENCODE_BITFIELD(x,1,3)
#define  VTSS_M_ICPU_CFG_CPU_SYSTEM_CTRL_GENERAL_STAT_REG_IF_ERR     VTSS_ENCODE_BITMASK(1,3)
#define  VTSS_X_ICPU_CFG_CPU_SYSTEM_CTRL_GENERAL_STAT_REG_IF_ERR(x)  VTSS_EXTRACT_BITFIELD(x,1,3)
#define  VTSS_F_ICPU_CFG_CPU_SYSTEM_CTRL_GENERAL_STAT_CPU_SLEEP  VTSS_BIT(0)

#define VTSS_ICPU_CFG_PI_MST_PI_MST_CFG      VTSS_IOREG(VTSS_TO_CFG,0xb)
#define  VTSS_F_ICPU_CFG_PI_MST_PI_MST_CFG_CLK_DIV(x)  VTSS_ENCODE_BITFIELD(x,0,5)
#define  VTSS_M_ICPU_CFG_PI_MST_PI_MST_CFG_CLK_DIV     VTSS_ENCODE_BITMASK(0,5)
#define  VTSS_X_ICPU_CFG_PI_MST_PI_MST_CFG_CLK_DIV(x)  VTSS_EXTRACT_BITFIELD(x,0,5)

#define VTSS_ICPU_CFG_SPI_MST_SPI_MST_CFG    VTSS_IOREG(VTSS_TO_CFG,0xf)
#define  VTSS_F_ICPU_CFG_SPI_MST_SPI_MST_CFG_FAST_READ_ENA  VTSS_BIT(10)
#define  VTSS_F_ICPU_CFG_SPI_MST_SPI_MST_CFG_CS_DESELECT_TIME(x)  VTSS_ENCODE_BITFIELD(x,5,5)
#define  VTSS_M_ICPU_CFG_SPI_MST_SPI_MST_CFG_CS_DESELECT_TIME     VTSS_ENCODE_BITMASK(5,5)
#define  VTSS_X_ICPU_CFG_SPI_MST_SPI_MST_CFG_CS_DESELECT_TIME(x)  VTSS_EXTRACT_BITFIELD(x,5,5)
#define  VTSS_F_ICPU_CFG_SPI_MST_SPI_MST_CFG_CLK_DIV(x)  VTSS_ENCODE_BITFIELD(x,0,5)
#define  VTSS_M_ICPU_CFG_SPI_MST_SPI_MST_CFG_CLK_DIV     VTSS_ENCODE_BITMASK(0,5)
#define  VTSS_X_ICPU_CFG_SPI_MST_SPI_MST_CFG_CLK_DIV(x)  VTSS_EXTRACT_BITFIELD(x,0,5)

#define VTSS_ICPU_CFG_SPI_MST_SW_MODE        VTSS_IOREG(VTSS_TO_CFG,0x14)
#define  VTSS_F_ICPU_CFG_SPI_MST_SW_MODE_SW_PIN_CTRL_MODE  VTSS_BIT(13)
#define  VTSS_F_ICPU_CFG_SPI_MST_SW_MODE_SW_SPI_SCK  VTSS_BIT(12)
#define  VTSS_F_ICPU_CFG_SPI_MST_SW_MODE_SW_SPI_SCK_OE  VTSS_BIT(11)
#define  VTSS_F_ICPU_CFG_SPI_MST_SW_MODE_SW_SPI_SDO  VTSS_BIT(10)
#define  VTSS_F_ICPU_CFG_SPI_MST_SW_MODE_SW_SPI_SDO_OE  VTSS_BIT(9)
#define  VTSS_F_ICPU_CFG_SPI_MST_SW_MODE_SW_SPI_CS(x)  VTSS_ENCODE_BITFIELD(x,5,4)
#define  VTSS_M_ICPU_CFG_SPI_MST_SW_MODE_SW_SPI_CS     VTSS_ENCODE_BITMASK(5,4)
#define  VTSS_X_ICPU_CFG_SPI_MST_SW_MODE_SW_SPI_CS(x)  VTSS_EXTRACT_BITFIELD(x,5,4)
#define  VTSS_F_ICPU_CFG_SPI_MST_SW_MODE_SW_SPI_CS_OE(x)  VTSS_ENCODE_BITFIELD(x,1,4)
#define  VTSS_M_ICPU_CFG_SPI_MST_SW_MODE_SW_SPI_CS_OE     VTSS_ENCODE_BITMASK(1,4)
#define  VTSS_X_ICPU_CFG_SPI_MST_SW_MODE_SW_SPI_CS_OE(x)  VTSS_EXTRACT_BITFIELD(x,1,4)
#define  VTSS_F_ICPU_CFG_SPI_MST_SW_MODE_SW_SPI_SDI  VTSS_BIT(0)

#define VTSS_ICPU_CFG_MPU8051_MPU8051_STAT   VTSS_IOREG(VTSS_TO_CFG,0x16)
#define  VTSS_F_ICPU_CFG_MPU8051_MPU8051_STAT_MPU8051_STOP  VTSS_BIT(8)
#define  VTSS_F_ICPU_CFG_MPU8051_MPU8051_STAT_MPU8051_GPR(x)  VTSS_ENCODE_BITFIELD(x,0,8)
#define  VTSS_M_ICPU_CFG_MPU8051_MPU8051_STAT_MPU8051_GPR     VTSS_ENCODE_BITMASK(0,8)
#define  VTSS_X_ICPU_CFG_MPU8051_MPU8051_STAT_MPU8051_GPR(x)  VTSS_EXTRACT_BITFIELD(x,0,8)

#define VTSS_ICPU_CFG_MPU8051_MPU8051_MMAP   VTSS_IOREG(VTSS_TO_CFG,0x17)
#define  VTSS_F_ICPU_CFG_MPU8051_MPU8051_MMAP_MSADDR_CODE_HIGH  VTSS_BIT(7)
#define  VTSS_F_ICPU_CFG_MPU8051_MPU8051_MMAP_MSADDR_CODE_LOW  VTSS_BIT(6)
#define  VTSS_F_ICPU_CFG_MPU8051_MPU8051_MMAP_MSADDR_DATA_HIGH  VTSS_BIT(5)
#define  VTSS_F_ICPU_CFG_MPU8051_MPU8051_MMAP_MSADDR_DATA_LOW  VTSS_BIT(4)
#define  VTSS_F_ICPU_CFG_MPU8051_MPU8051_MMAP_MAP_CODE_HIGH  VTSS_BIT(3)
#define  VTSS_F_ICPU_CFG_MPU8051_MPU8051_MMAP_MAP_CODE_LOW  VTSS_BIT(2)
#define  VTSS_F_ICPU_CFG_MPU8051_MPU8051_MMAP_MAP_DATA_HIGH  VTSS_BIT(1)
#define  VTSS_F_ICPU_CFG_MPU8051_MPU8051_MMAP_MAP_DATA_LOW  VTSS_BIT(0)

#define VTSS_ICPU_CFG_MPU8051_MEMACC_CTRL    VTSS_IOREG(VTSS_TO_CFG,0x18)
#define  VTSS_F_ICPU_CFG_MPU8051_MEMACC_CTRL_MEMACC_EXAMINE  VTSS_BIT(1)
#define  VTSS_F_ICPU_CFG_MPU8051_MEMACC_CTRL_MEMACC_DO  VTSS_BIT(0)

#define VTSS_ICPU_CFG_MPU8051_MEMACC         VTSS_IOREG(VTSS_TO_CFG,0x19)
#define  VTSS_F_ICPU_CFG_MPU8051_MEMACC_MEMACC_STOP(x)  VTSS_ENCODE_BITFIELD(x,18,14)
#define  VTSS_M_ICPU_CFG_MPU8051_MEMACC_MEMACC_STOP     VTSS_ENCODE_BITMASK(18,14)
#define  VTSS_X_ICPU_CFG_MPU8051_MEMACC_MEMACC_STOP(x)  VTSS_EXTRACT_BITFIELD(x,18,14)
#define  VTSS_F_ICPU_CFG_MPU8051_MEMACC_MEMACC_START(x)  VTSS_ENCODE_BITFIELD(x,2,14)
#define  VTSS_M_ICPU_CFG_MPU8051_MEMACC_MEMACC_START     VTSS_ENCODE_BITMASK(2,14)
#define  VTSS_X_ICPU_CFG_MPU8051_MEMACC_MEMACC_START(x)  VTSS_EXTRACT_BITFIELD(x,2,14)

#define VTSS_ICPU_CFG_MPU8051_MEMACC_SBA     VTSS_IOREG(VTSS_TO_CFG,0x1a)
#define  VTSS_F_ICPU_CFG_MPU8051_MEMACC_SBA_MEMACC_SBA_START(x)  VTSS_ENCODE_BITFIELD(x,2,30)
#define  VTSS_M_ICPU_CFG_MPU8051_MEMACC_SBA_MEMACC_SBA_START     VTSS_ENCODE_BITMASK(2,30)
#define  VTSS_X_ICPU_CFG_MPU8051_MEMACC_SBA_MEMACC_SBA_START(x)  VTSS_EXTRACT_BITFIELD(x,2,30)

#define VTSS_ICPU_CFG_INTR_INTR_RAW          VTSS_IOREG(VTSS_TO_CFG,0x1c)
#define  VTSS_F_ICPU_CFG_INTR_INTR_RAW_INTR_RAW(x)  VTSS_ENCODE_BITFIELD(x,0,25)
#define  VTSS_M_ICPU_CFG_INTR_INTR_RAW_INTR_RAW     VTSS_ENCODE_BITMASK(0,25)
#define  VTSS_X_ICPU_CFG_INTR_INTR_RAW_INTR_RAW(x)  VTSS_EXTRACT_BITFIELD(x,0,25)

#define VTSS_ICPU_CFG_INTR_INTR_TRIGGER      VTSS_IOREG(VTSS_TO_CFG,0x1d)
#define  VTSS_F_ICPU_CFG_INTR_INTR_TRIGGER_INTR_TRIGGER(x)  VTSS_ENCODE_BITFIELD(x,0,25)
#define  VTSS_M_ICPU_CFG_INTR_INTR_TRIGGER_INTR_TRIGGER     VTSS_ENCODE_BITMASK(0,25)
#define  VTSS_X_ICPU_CFG_INTR_INTR_TRIGGER_INTR_TRIGGER(x)  VTSS_EXTRACT_BITFIELD(x,0,25)

#define VTSS_ICPU_CFG_INTR_INTR_FORCE        VTSS_IOREG(VTSS_TO_CFG,0x1e)
#define  VTSS_F_ICPU_CFG_INTR_INTR_FORCE_INTR_FORCE(x)  VTSS_ENCODE_BITFIELD(x,0,25)
#define  VTSS_M_ICPU_CFG_INTR_INTR_FORCE_INTR_FORCE     VTSS_ENCODE_BITMASK(0,25)
#define  VTSS_X_ICPU_CFG_INTR_INTR_FORCE_INTR_FORCE(x)  VTSS_EXTRACT_BITFIELD(x,0,25)

#define VTSS_ICPU_CFG_INTR_INTR_STICKY       VTSS_IOREG(VTSS_TO_CFG,0x1f)
#define  VTSS_F_ICPU_CFG_INTR_INTR_STICKY_INTR_STICKY(x)  VTSS_ENCODE_BITFIELD(x,0,25)
#define  VTSS_M_ICPU_CFG_INTR_INTR_STICKY_INTR_STICKY     VTSS_ENCODE_BITMASK(0,25)
#define  VTSS_X_ICPU_CFG_INTR_INTR_STICKY_INTR_STICKY(x)  VTSS_EXTRACT_BITFIELD(x,0,25)

#define VTSS_ICPU_CFG_INTR_INTR_BYPASS       VTSS_IOREG(VTSS_TO_CFG,0x20)
#define  VTSS_F_ICPU_CFG_INTR_INTR_BYPASS_INTR_BYPASS(x)  VTSS_ENCODE_BITFIELD(x,0,25)
#define  VTSS_M_ICPU_CFG_INTR_INTR_BYPASS_INTR_BYPASS     VTSS_ENCODE_BITMASK(0,25)
#define  VTSS_X_ICPU_CFG_INTR_INTR_BYPASS_INTR_BYPASS(x)  VTSS_EXTRACT_BITFIELD(x,0,25)

#define VTSS_ICPU_CFG_INTR_INTR_ENA          VTSS_IOREG(VTSS_TO_CFG,0x21)
#define  VTSS_F_ICPU_CFG_INTR_INTR_ENA_INTR_ENA(x)  VTSS_ENCODE_BITFIELD(x,0,25)
#define  VTSS_M_ICPU_CFG_INTR_INTR_ENA_INTR_ENA     VTSS_ENCODE_BITMASK(0,25)
#define  VTSS_X_ICPU_CFG_INTR_INTR_ENA_INTR_ENA(x)  VTSS_EXTRACT_BITFIELD(x,0,25)

#define VTSS_ICPU_CFG_INTR_INTR_ENA_CLR      VTSS_IOREG(VTSS_TO_CFG,0x22)
#define  VTSS_F_ICPU_CFG_INTR_INTR_ENA_CLR_INTR_ENA_CLR(x)  VTSS_ENCODE_BITFIELD(x,0,25)
#define  VTSS_M_ICPU_CFG_INTR_INTR_ENA_CLR_INTR_ENA_CLR     VTSS_ENCODE_BITMASK(0,25)
#define  VTSS_X_ICPU_CFG_INTR_INTR_ENA_CLR_INTR_ENA_CLR(x)  VTSS_EXTRACT_BITFIELD(x,0,25)

#define VTSS_ICPU_CFG_INTR_INTR_ENA_SET      VTSS_IOREG(VTSS_TO_CFG,0x23)
#define  VTSS_F_ICPU_CFG_INTR_INTR_ENA_SET_INTR_ENA_SET(x)  VTSS_ENCODE_BITFIELD(x,0,25)
#define  VTSS_M_ICPU_CFG_INTR_INTR_ENA_SET_INTR_ENA_SET     VTSS_ENCODE_BITMASK(0,25)
#define  VTSS_X_ICPU_CFG_INTR_INTR_ENA_SET_INTR_ENA_SET(x)  VTSS_EXTRACT_BITFIELD(x,0,25)

#define VTSS_ICPU_CFG_INTR_INTR_IDENT        VTSS_IOREG(VTSS_TO_CFG,0x24)
#define  VTSS_F_ICPU_CFG_INTR_INTR_IDENT_INTR_IDENT(x)  VTSS_ENCODE_BITFIELD(x,0,25)
#define  VTSS_M_ICPU_CFG_INTR_INTR_IDENT_INTR_IDENT     VTSS_ENCODE_BITMASK(0,25)
#define  VTSS_X_ICPU_CFG_INTR_INTR_IDENT_INTR_IDENT(x)  VTSS_EXTRACT_BITFIELD(x,0,25)

#define VTSS_ICPU_CFG_INTR_DST_INTR_MAP(ri)  VTSS_IOREG(VTSS_TO_CFG,0x25 + (ri))
#define  VTSS_F_ICPU_CFG_INTR_DST_INTR_MAP_DST_INTR_MAP(x)  VTSS_ENCODE_BITFIELD(x,0,25)
#define  VTSS_M_ICPU_CFG_INTR_DST_INTR_MAP_DST_INTR_MAP     VTSS_ENCODE_BITMASK(0,25)
#define  VTSS_X_ICPU_CFG_INTR_DST_INTR_MAP_DST_INTR_MAP(x)  VTSS_EXTRACT_BITFIELD(x,0,25)

#define VTSS_ICPU_CFG_INTR_DST_INTR_IDENT(ri)  VTSS_IOREG(VTSS_TO_CFG,0x29 + (ri))
#define  VTSS_F_ICPU_CFG_INTR_DST_INTR_IDENT_DST_INTR_IDENT(x)  VTSS_ENCODE_BITFIELD(x,0,25)
#define  VTSS_M_ICPU_CFG_INTR_DST_INTR_IDENT_DST_INTR_IDENT     VTSS_ENCODE_BITMASK(0,25)
#define  VTSS_X_ICPU_CFG_INTR_DST_INTR_IDENT_DST_INTR_IDENT(x)  VTSS_EXTRACT_BITFIELD(x,0,25)

#define VTSS_ICPU_CFG_INTR_EXT_INTR_POL      VTSS_IOREG(VTSS_TO_CFG,0x2d)
#define  VTSS_F_ICPU_CFG_INTR_EXT_INTR_POL_EXT_INTR_POL(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_ICPU_CFG_INTR_EXT_INTR_POL_EXT_INTR_POL     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_ICPU_CFG_INTR_EXT_INTR_POL_EXT_INTR_POL(x)  VTSS_EXTRACT_BITFIELD(x,0,2)

#define VTSS_ICPU_CFG_INTR_EXT_INTR_DRV      VTSS_IOREG(VTSS_TO_CFG,0x2e)
#define  VTSS_F_ICPU_CFG_INTR_EXT_INTR_DRV_EXT_INTR_DRV(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_ICPU_CFG_INTR_EXT_INTR_DRV_EXT_INTR_DRV     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_ICPU_CFG_INTR_EXT_INTR_DRV_EXT_INTR_DRV(x)  VTSS_EXTRACT_BITFIELD(x,0,2)

#define VTSS_ICPU_CFG_INTR_EXT_INTR_DIR      VTSS_IOREG(VTSS_TO_CFG,0x2f)
#define  VTSS_F_ICPU_CFG_INTR_EXT_INTR_DIR_EXT_INTR_DIR(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_ICPU_CFG_INTR_EXT_INTR_DIR_EXT_INTR_DIR     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_ICPU_CFG_INTR_EXT_INTR_DIR_EXT_INTR_DIR(x)  VTSS_EXTRACT_BITFIELD(x,0,2)

#define VTSS_ICPU_CFG_INTR_DEV_INTR_POL      VTSS_IOREG(VTSS_TO_CFG,0x30)
#define  VTSS_F_ICPU_CFG_INTR_DEV_INTR_POL_DEV_INTR_POL(x)  VTSS_ENCODE_BITFIELD(x,0,11)
#define  VTSS_M_ICPU_CFG_INTR_DEV_INTR_POL_DEV_INTR_POL     VTSS_ENCODE_BITMASK(0,11)
#define  VTSS_X_ICPU_CFG_INTR_DEV_INTR_POL_DEV_INTR_POL(x)  VTSS_EXTRACT_BITFIELD(x,0,11)

#define VTSS_ICPU_CFG_INTR_DEV_INTR_RAW      VTSS_IOREG(VTSS_TO_CFG,0x31)
#define  VTSS_F_ICPU_CFG_INTR_DEV_INTR_RAW_DEV_INTR_RAW(x)  VTSS_ENCODE_BITFIELD(x,0,11)
#define  VTSS_M_ICPU_CFG_INTR_DEV_INTR_RAW_DEV_INTR_RAW     VTSS_ENCODE_BITMASK(0,11)
#define  VTSS_X_ICPU_CFG_INTR_DEV_INTR_RAW_DEV_INTR_RAW(x)  VTSS_EXTRACT_BITFIELD(x,0,11)

#define VTSS_ICPU_CFG_INTR_DEV_INTR_TRIGGER  VTSS_IOREG(VTSS_TO_CFG,0x32)
#define  VTSS_F_ICPU_CFG_INTR_DEV_INTR_TRIGGER_DEV_INTR_TRIGGER(x)  VTSS_ENCODE_BITFIELD(x,0,11)
#define  VTSS_M_ICPU_CFG_INTR_DEV_INTR_TRIGGER_DEV_INTR_TRIGGER     VTSS_ENCODE_BITMASK(0,11)
#define  VTSS_X_ICPU_CFG_INTR_DEV_INTR_TRIGGER_DEV_INTR_TRIGGER(x)  VTSS_EXTRACT_BITFIELD(x,0,11)

#define VTSS_ICPU_CFG_INTR_DEV_INTR_STICKY   VTSS_IOREG(VTSS_TO_CFG,0x33)
#define  VTSS_F_ICPU_CFG_INTR_DEV_INTR_STICKY_DEV_INTR_STICKY(x)  VTSS_ENCODE_BITFIELD(x,0,11)
#define  VTSS_M_ICPU_CFG_INTR_DEV_INTR_STICKY_DEV_INTR_STICKY     VTSS_ENCODE_BITMASK(0,11)
#define  VTSS_X_ICPU_CFG_INTR_DEV_INTR_STICKY_DEV_INTR_STICKY(x)  VTSS_EXTRACT_BITFIELD(x,0,11)

#define VTSS_ICPU_CFG_INTR_DEV_INTR_BYPASS   VTSS_IOREG(VTSS_TO_CFG,0x34)
#define  VTSS_F_ICPU_CFG_INTR_DEV_INTR_BYPASS_DEV_INTR_BYPASS(x)  VTSS_ENCODE_BITFIELD(x,0,11)
#define  VTSS_M_ICPU_CFG_INTR_DEV_INTR_BYPASS_DEV_INTR_BYPASS     VTSS_ENCODE_BITMASK(0,11)
#define  VTSS_X_ICPU_CFG_INTR_DEV_INTR_BYPASS_DEV_INTR_BYPASS(x)  VTSS_EXTRACT_BITFIELD(x,0,11)

#define VTSS_ICPU_CFG_INTR_DEV_INTR_ENA      VTSS_IOREG(VTSS_TO_CFG,0x35)
#define  VTSS_F_ICPU_CFG_INTR_DEV_INTR_ENA_DEV_INTR_ENA(x)  VTSS_ENCODE_BITFIELD(x,0,11)
#define  VTSS_M_ICPU_CFG_INTR_DEV_INTR_ENA_DEV_INTR_ENA     VTSS_ENCODE_BITMASK(0,11)
#define  VTSS_X_ICPU_CFG_INTR_DEV_INTR_ENA_DEV_INTR_ENA(x)  VTSS_EXTRACT_BITFIELD(x,0,11)

#define VTSS_ICPU_CFG_INTR_DEV_INTR_IDENT    VTSS_IOREG(VTSS_TO_CFG,0x36)
#define  VTSS_F_ICPU_CFG_INTR_DEV_INTR_IDENT_DEV_INTR_IDENT(x)  VTSS_ENCODE_BITFIELD(x,0,11)
#define  VTSS_M_ICPU_CFG_INTR_DEV_INTR_IDENT_DEV_INTR_IDENT     VTSS_ENCODE_BITMASK(0,11)
#define  VTSS_X_ICPU_CFG_INTR_DEV_INTR_IDENT_DEV_INTR_IDENT(x)  VTSS_EXTRACT_BITFIELD(x,0,11)

#define VTSS_ICPU_CFG_TIMERS_WDT             VTSS_IOREG(VTSS_TO_CFG,0x37)
#define  VTSS_F_ICPU_CFG_TIMERS_WDT_WDT_STATUS  VTSS_BIT(9)
#define  VTSS_F_ICPU_CFG_TIMERS_WDT_WDT_ENABLE  VTSS_BIT(8)
#define  VTSS_F_ICPU_CFG_TIMERS_WDT_WDT_LOCK(x)  VTSS_ENCODE_BITFIELD(x,0,8)
#define  VTSS_M_ICPU_CFG_TIMERS_WDT_WDT_LOCK     VTSS_ENCODE_BITMASK(0,8)
#define  VTSS_X_ICPU_CFG_TIMERS_WDT_WDT_LOCK(x)  VTSS_EXTRACT_BITFIELD(x,0,8)

#define VTSS_ICPU_CFG_TIMERS_TIMER_TICK_DIV  VTSS_IOREG(VTSS_TO_CFG,0x38)
#define  VTSS_F_ICPU_CFG_TIMERS_TIMER_TICK_DIV_TIMER_TICK_DIV(x)  VTSS_ENCODE_BITFIELD(x,0,18)
#define  VTSS_M_ICPU_CFG_TIMERS_TIMER_TICK_DIV_TIMER_TICK_DIV     VTSS_ENCODE_BITMASK(0,18)
#define  VTSS_X_ICPU_CFG_TIMERS_TIMER_TICK_DIV_TIMER_TICK_DIV(x)  VTSS_EXTRACT_BITFIELD(x,0,18)

#define VTSS_ICPU_CFG_TIMERS_TIMER_VALUE(ri)  VTSS_IOREG(VTSS_TO_CFG,0x39 + (ri))

#define VTSS_ICPU_CFG_TIMERS_TIMER_RELOAD_VALUE(ri)  VTSS_IOREG(VTSS_TO_CFG,0x3c + (ri))

#define VTSS_ICPU_CFG_TIMERS_TIMER_CTRL(ri)  VTSS_IOREG(VTSS_TO_CFG,0x3f + (ri))
#define  VTSS_F_ICPU_CFG_TIMERS_TIMER_CTRL_ONE_SHOT_ENA  VTSS_BIT(2)
#define  VTSS_F_ICPU_CFG_TIMERS_TIMER_CTRL_TIMER_ENA  VTSS_BIT(1)
#define  VTSS_F_ICPU_CFG_TIMERS_TIMER_CTRL_FORCE_RELOAD  VTSS_BIT(0)

#define VTSS_ICPU_CFG_MEMCTRL_MEMCTRL_CTRL   VTSS_IOREG(VTSS_TO_CFG,0x42)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_CTRL_PWR_DOWN  VTSS_BIT(3)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_CTRL_MDSET  VTSS_BIT(2)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_CTRL_STALL_REF_ENA  VTSS_BIT(1)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_CTRL_INITIALIZE  VTSS_BIT(0)

#define VTSS_ICPU_CFG_MEMCTRL_MEMCTRL_CFG    VTSS_IOREG(VTSS_TO_CFG,0x43)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_CFG_DDR_512MBYTE_PLUS  VTSS_BIT(16)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_CFG_DDR_ECC_ERR_ENA  VTSS_BIT(15)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_CFG_DDR_ECC_COR_ENA  VTSS_BIT(14)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_CFG_DDR_ECC_ENA  VTSS_BIT(13)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_CFG_DDR_WIDTH  VTSS_BIT(12)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_CFG_DDR_MODE  VTSS_BIT(11)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_CFG_BURST_SIZE  VTSS_BIT(10)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_CFG_BURST_LEN  VTSS_BIT(9)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_CFG_BANK_CNT  VTSS_BIT(8)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_CFG_MSB_ROW_ADDR(x)  VTSS_ENCODE_BITFIELD(x,4,4)
#define  VTSS_M_ICPU_CFG_MEMCTRL_MEMCTRL_CFG_MSB_ROW_ADDR     VTSS_ENCODE_BITMASK(4,4)
#define  VTSS_X_ICPU_CFG_MEMCTRL_MEMCTRL_CFG_MSB_ROW_ADDR(x)  VTSS_EXTRACT_BITFIELD(x,4,4)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_CFG_MSB_COL_ADDR(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_ICPU_CFG_MEMCTRL_MEMCTRL_CFG_MSB_COL_ADDR     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_ICPU_CFG_MEMCTRL_MEMCTRL_CFG_MSB_COL_ADDR(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_ICPU_CFG_MEMCTRL_MEMCTRL_STAT   VTSS_IOREG(VTSS_TO_CFG,0x44)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_STAT_RDATA_MASKED  VTSS_BIT(5)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_STAT_RDATA_DUMMY  VTSS_BIT(4)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_STAT_RDATA_ECC_ERR  VTSS_BIT(3)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_STAT_RDATA_ECC_COR  VTSS_BIT(2)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_STAT_PWR_DOWN_ACK  VTSS_BIT(1)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_STAT_INIT_DONE  VTSS_BIT(0)

#define VTSS_ICPU_CFG_MEMCTRL_MEMCTRL_REF_PERIOD  VTSS_IOREG(VTSS_TO_CFG,0x45)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_REF_PERIOD_MAX_PEND_REF(x)  VTSS_ENCODE_BITFIELD(x,16,4)
#define  VTSS_M_ICPU_CFG_MEMCTRL_MEMCTRL_REF_PERIOD_MAX_PEND_REF     VTSS_ENCODE_BITMASK(16,4)
#define  VTSS_X_ICPU_CFG_MEMCTRL_MEMCTRL_REF_PERIOD_MAX_PEND_REF(x)  VTSS_EXTRACT_BITFIELD(x,16,4)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_REF_PERIOD_REF_PERIOD(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_ICPU_CFG_MEMCTRL_MEMCTRL_REF_PERIOD_REF_PERIOD     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_ICPU_CFG_MEMCTRL_MEMCTRL_REF_PERIOD_REF_PERIOD(x)  VTSS_EXTRACT_BITFIELD(x,0,16)

#define VTSS_ICPU_CFG_MEMCTRL_MEMCTRL_ZQCAL  VTSS_IOREG(VTSS_TO_CFG,0x46)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_ZQCAL_ZQCAL_LONG  VTSS_BIT(1)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_ZQCAL_ZQCAL_SHORT  VTSS_BIT(0)

#define VTSS_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING0  VTSS_IOREG(VTSS_TO_CFG,0x47)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING0_RD_TO_WR_DLY(x)  VTSS_ENCODE_BITFIELD(x,28,4)
#define  VTSS_M_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING0_RD_TO_WR_DLY     VTSS_ENCODE_BITMASK(28,4)
#define  VTSS_X_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING0_RD_TO_WR_DLY(x)  VTSS_EXTRACT_BITFIELD(x,28,4)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING0_WR_CS_CHANGE_DLY(x)  VTSS_ENCODE_BITFIELD(x,24,4)
#define  VTSS_M_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING0_WR_CS_CHANGE_DLY     VTSS_ENCODE_BITMASK(24,4)
#define  VTSS_X_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING0_WR_CS_CHANGE_DLY(x)  VTSS_EXTRACT_BITFIELD(x,24,4)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING0_RD_CS_CHANGE_DLY(x)  VTSS_ENCODE_BITFIELD(x,20,4)
#define  VTSS_M_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING0_RD_CS_CHANGE_DLY     VTSS_ENCODE_BITMASK(20,4)
#define  VTSS_X_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING0_RD_CS_CHANGE_DLY(x)  VTSS_EXTRACT_BITFIELD(x,20,4)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING0_RAS_TO_PRECH_DLY(x)  VTSS_ENCODE_BITFIELD(x,16,4)
#define  VTSS_M_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING0_RAS_TO_PRECH_DLY     VTSS_ENCODE_BITMASK(16,4)
#define  VTSS_X_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING0_RAS_TO_PRECH_DLY(x)  VTSS_EXTRACT_BITFIELD(x,16,4)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING0_WR_TO_PRECH_DLY(x)  VTSS_ENCODE_BITFIELD(x,12,4)
#define  VTSS_M_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING0_WR_TO_PRECH_DLY     VTSS_ENCODE_BITMASK(12,4)
#define  VTSS_X_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING0_WR_TO_PRECH_DLY(x)  VTSS_EXTRACT_BITFIELD(x,12,4)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING0_RD_TO_PRECH_DLY(x)  VTSS_ENCODE_BITFIELD(x,8,4)
#define  VTSS_M_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING0_RD_TO_PRECH_DLY     VTSS_ENCODE_BITMASK(8,4)
#define  VTSS_X_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING0_RD_TO_PRECH_DLY(x)  VTSS_EXTRACT_BITFIELD(x,8,4)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING0_WR_DATA_XFR_DLY(x)  VTSS_ENCODE_BITFIELD(x,4,4)
#define  VTSS_M_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING0_WR_DATA_XFR_DLY     VTSS_ENCODE_BITMASK(4,4)
#define  VTSS_X_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING0_WR_DATA_XFR_DLY(x)  VTSS_EXTRACT_BITFIELD(x,4,4)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING0_RD_DATA_XFR_DLY(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING0_RD_DATA_XFR_DLY     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING0_RD_DATA_XFR_DLY(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING1  VTSS_IOREG(VTSS_TO_CFG,0x48)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING1_RAS_TO_RAS_SAME_BANK_DLY(x)  VTSS_ENCODE_BITFIELD(x,24,8)
#define  VTSS_M_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING1_RAS_TO_RAS_SAME_BANK_DLY     VTSS_ENCODE_BITMASK(24,8)
#define  VTSS_X_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING1_RAS_TO_RAS_SAME_BANK_DLY(x)  VTSS_EXTRACT_BITFIELD(x,24,8)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING1_BANK8_FAW_DLY(x)  VTSS_ENCODE_BITFIELD(x,16,8)
#define  VTSS_M_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING1_BANK8_FAW_DLY     VTSS_ENCODE_BITMASK(16,8)
#define  VTSS_X_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING1_BANK8_FAW_DLY(x)  VTSS_EXTRACT_BITFIELD(x,16,8)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING1_PRECH_TO_RAS_DLY(x)  VTSS_ENCODE_BITFIELD(x,12,4)
#define  VTSS_M_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING1_PRECH_TO_RAS_DLY     VTSS_ENCODE_BITMASK(12,4)
#define  VTSS_X_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING1_PRECH_TO_RAS_DLY(x)  VTSS_EXTRACT_BITFIELD(x,12,4)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING1_RAS_TO_RAS_DLY(x)  VTSS_ENCODE_BITFIELD(x,8,4)
#define  VTSS_M_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING1_RAS_TO_RAS_DLY     VTSS_ENCODE_BITMASK(8,4)
#define  VTSS_X_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING1_RAS_TO_RAS_DLY(x)  VTSS_EXTRACT_BITFIELD(x,8,4)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING1_RAS_TO_CAS_DLY(x)  VTSS_ENCODE_BITFIELD(x,4,4)
#define  VTSS_M_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING1_RAS_TO_CAS_DLY     VTSS_ENCODE_BITMASK(4,4)
#define  VTSS_X_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING1_RAS_TO_CAS_DLY(x)  VTSS_EXTRACT_BITFIELD(x,4,4)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING1_WR_TO_RD_DLY(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING1_WR_TO_RD_DLY     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING1_WR_TO_RD_DLY(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING2  VTSS_IOREG(VTSS_TO_CFG,0x49)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING2_PRECH_ALL_DLY(x)  VTSS_ENCODE_BITFIELD(x,28,4)
#define  VTSS_M_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING2_PRECH_ALL_DLY     VTSS_ENCODE_BITMASK(28,4)
#define  VTSS_X_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING2_PRECH_ALL_DLY(x)  VTSS_EXTRACT_BITFIELD(x,28,4)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING2_MDSET_DLY(x)  VTSS_ENCODE_BITFIELD(x,24,4)
#define  VTSS_M_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING2_MDSET_DLY     VTSS_ENCODE_BITMASK(24,4)
#define  VTSS_X_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING2_MDSET_DLY(x)  VTSS_EXTRACT_BITFIELD(x,24,4)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING2_REF_DLY(x)  VTSS_ENCODE_BITFIELD(x,16,8)
#define  VTSS_M_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING2_REF_DLY     VTSS_ENCODE_BITMASK(16,8)
#define  VTSS_X_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING2_REF_DLY(x)  VTSS_EXTRACT_BITFIELD(x,16,8)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING2_INIT_DLY(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING2_INIT_DLY     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING2_INIT_DLY(x)  VTSS_EXTRACT_BITFIELD(x,0,16)

#define VTSS_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING3  VTSS_IOREG(VTSS_TO_CFG,0x4a)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING3_ODT_RD_DLY(x)  VTSS_ENCODE_BITFIELD(x,12,4)
#define  VTSS_M_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING3_ODT_RD_DLY     VTSS_ENCODE_BITMASK(12,4)
#define  VTSS_X_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING3_ODT_RD_DLY(x)  VTSS_EXTRACT_BITFIELD(x,12,4)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING3_ODT_WR_DLY(x)  VTSS_ENCODE_BITFIELD(x,8,4)
#define  VTSS_M_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING3_ODT_WR_DLY     VTSS_ENCODE_BITMASK(8,4)
#define  VTSS_X_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING3_ODT_WR_DLY(x)  VTSS_EXTRACT_BITFIELD(x,8,4)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING3_LOCAL_ODT_RD_DLY(x)  VTSS_ENCODE_BITFIELD(x,4,4)
#define  VTSS_M_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING3_LOCAL_ODT_RD_DLY     VTSS_ENCODE_BITMASK(4,4)
#define  VTSS_X_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING3_LOCAL_ODT_RD_DLY(x)  VTSS_EXTRACT_BITFIELD(x,4,4)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING3_WR_TO_RD_CS_CHANGE_DLY(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING3_WR_TO_RD_CS_CHANGE_DLY     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_ICPU_CFG_MEMCTRL_MEMCTRL_TIMING3_WR_TO_RD_CS_CHANGE_DLY(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_ICPU_CFG_MEMCTRL_MEMCTRL_MR0_VAL  VTSS_IOREG(VTSS_TO_CFG,0x4c)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_MR0_VAL_MR0_VAL(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_ICPU_CFG_MEMCTRL_MEMCTRL_MR0_VAL_MR0_VAL     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_ICPU_CFG_MEMCTRL_MEMCTRL_MR0_VAL_MR0_VAL(x)  VTSS_EXTRACT_BITFIELD(x,0,16)

#define VTSS_ICPU_CFG_MEMCTRL_MEMCTRL_MR1_VAL  VTSS_IOREG(VTSS_TO_CFG,0x4d)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_MR1_VAL_MR1_VAL(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_ICPU_CFG_MEMCTRL_MEMCTRL_MR1_VAL_MR1_VAL     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_ICPU_CFG_MEMCTRL_MEMCTRL_MR1_VAL_MR1_VAL(x)  VTSS_EXTRACT_BITFIELD(x,0,16)

#define VTSS_ICPU_CFG_MEMCTRL_MEMCTRL_MR2_VAL  VTSS_IOREG(VTSS_TO_CFG,0x4e)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_MR2_VAL_MR2_VAL(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_ICPU_CFG_MEMCTRL_MEMCTRL_MR2_VAL_MR2_VAL     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_ICPU_CFG_MEMCTRL_MEMCTRL_MR2_VAL_MR2_VAL(x)  VTSS_EXTRACT_BITFIELD(x,0,16)

#define VTSS_ICPU_CFG_MEMCTRL_MEMCTRL_MR3_VAL  VTSS_IOREG(VTSS_TO_CFG,0x4f)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_MR3_VAL_MR3_VAL(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_ICPU_CFG_MEMCTRL_MEMCTRL_MR3_VAL_MR3_VAL     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_ICPU_CFG_MEMCTRL_MEMCTRL_MR3_VAL_MR3_VAL(x)  VTSS_EXTRACT_BITFIELD(x,0,16)

#define VTSS_ICPU_CFG_MEMCTRL_MEMCTRL_TERMRES_CTRL  VTSS_IOREG(VTSS_TO_CFG,0x50)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_TERMRES_CTRL_ODT_RD_EXT  VTSS_BIT(11)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_TERMRES_CTRL_ODT_RD_ENA(x)  VTSS_ENCODE_BITFIELD(x,7,4)
#define  VTSS_M_ICPU_CFG_MEMCTRL_MEMCTRL_TERMRES_CTRL_ODT_RD_ENA     VTSS_ENCODE_BITMASK(7,4)
#define  VTSS_X_ICPU_CFG_MEMCTRL_MEMCTRL_TERMRES_CTRL_ODT_RD_ENA(x)  VTSS_EXTRACT_BITFIELD(x,7,4)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_TERMRES_CTRL_ODT_WR_EXT  VTSS_BIT(6)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_TERMRES_CTRL_ODT_WR_ENA(x)  VTSS_ENCODE_BITFIELD(x,2,4)
#define  VTSS_M_ICPU_CFG_MEMCTRL_MEMCTRL_TERMRES_CTRL_ODT_WR_ENA     VTSS_ENCODE_BITMASK(2,4)
#define  VTSS_X_ICPU_CFG_MEMCTRL_MEMCTRL_TERMRES_CTRL_ODT_WR_ENA(x)  VTSS_EXTRACT_BITFIELD(x,2,4)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_TERMRES_CTRL_LOCAL_ODT_RD_EXT  VTSS_BIT(1)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_TERMRES_CTRL_LOCAL_ODT_RD_ENA  VTSS_BIT(0)

#define VTSS_ICPU_CFG_MEMCTRL_MEMCTRL_DQS_DLY(ri)  VTSS_IOREG(VTSS_TO_CFG,0x52 + (ri))
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMCTRL_DQS_DLY_DQS_DLY(x)  VTSS_ENCODE_BITFIELD(x,0,5)
#define  VTSS_M_ICPU_CFG_MEMCTRL_MEMCTRL_DQS_DLY_DQS_DLY     VTSS_ENCODE_BITMASK(0,5)
#define  VTSS_X_ICPU_CFG_MEMCTRL_MEMCTRL_DQS_DLY_DQS_DLY(x)  VTSS_EXTRACT_BITFIELD(x,0,5)

#define VTSS_ICPU_CFG_MEMCTRL_MEMPHY_CFG     VTSS_IOREG(VTSS_TO_CFG,0x56)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMPHY_CFG_PHY_ODT_OE  VTSS_BIT(4)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMPHY_CFG_PHY_CK_OE  VTSS_BIT(3)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMPHY_CFG_PHY_CL_OE  VTSS_BIT(2)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMPHY_CFG_PHY_SSTL_ENA  VTSS_BIT(1)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMPHY_CFG_PHY_RST  VTSS_BIT(0)

#define VTSS_ICPU_CFG_MEMCTRL_MEMPHY_ZCAL    VTSS_IOREG(VTSS_TO_CFG,0x60)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMPHY_ZCAL_ZCAL_PROG_ODT(x)  VTSS_ENCODE_BITFIELD(x,5,4)
#define  VTSS_M_ICPU_CFG_MEMCTRL_MEMPHY_ZCAL_ZCAL_PROG_ODT     VTSS_ENCODE_BITMASK(5,4)
#define  VTSS_X_ICPU_CFG_MEMCTRL_MEMPHY_ZCAL_ZCAL_PROG_ODT(x)  VTSS_EXTRACT_BITFIELD(x,5,4)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMPHY_ZCAL_ZCAL_PROG(x)  VTSS_ENCODE_BITFIELD(x,1,4)
#define  VTSS_M_ICPU_CFG_MEMCTRL_MEMPHY_ZCAL_ZCAL_PROG     VTSS_ENCODE_BITMASK(1,4)
#define  VTSS_X_ICPU_CFG_MEMCTRL_MEMPHY_ZCAL_ZCAL_PROG(x)  VTSS_EXTRACT_BITFIELD(x,1,4)
#define  VTSS_F_ICPU_CFG_MEMCTRL_MEMPHY_ZCAL_ZCAL_ENA  VTSS_BIT(0)

#define VTSS_ICPU_CFG_TWI_DELAY_TWI_CONFIG   VTSS_IOREG(VTSS_TO_CFG,0x64)
#define  VTSS_F_ICPU_CFG_TWI_DELAY_TWI_CONFIG_TWI_CNT_RELOAD(x)  VTSS_ENCODE_BITFIELD(x,1,8)
#define  VTSS_M_ICPU_CFG_TWI_DELAY_TWI_CONFIG_TWI_CNT_RELOAD     VTSS_ENCODE_BITMASK(1,8)
#define  VTSS_X_ICPU_CFG_TWI_DELAY_TWI_CONFIG_TWI_CNT_RELOAD(x)  VTSS_EXTRACT_BITFIELD(x,1,8)
#define  VTSS_F_ICPU_CFG_TWI_DELAY_TWI_CONFIG_TWI_DELAY_ENABLE  VTSS_BIT(0)

#define VTSS_ICPU_CFG_TWI_SPIKE_FILTER_TWI_SPIKE_FILTER_CFG  VTSS_IOREG(VTSS_TO_CFG,0x65)
#define  VTSS_F_ICPU_CFG_TWI_SPIKE_FILTER_TWI_SPIKE_FILTER_CFG_SPIKE_FILTER_CFG(x)  VTSS_ENCODE_BITFIELD(x,0,5)
#define  VTSS_M_ICPU_CFG_TWI_SPIKE_FILTER_TWI_SPIKE_FILTER_CFG_SPIKE_FILTER_CFG     VTSS_ENCODE_BITMASK(0,5)
#define  VTSS_X_ICPU_CFG_TWI_SPIKE_FILTER_TWI_SPIKE_FILTER_CFG_SPIKE_FILTER_CFG(x)  VTSS_EXTRACT_BITFIELD(x,0,5)

#define VTSS_ICPU_CFG_FDMA_FDMA_DCB_LLP(ri)  VTSS_IOREG(VTSS_TO_CFG,0x66 + (ri))

#define VTSS_ICPU_CFG_FDMA_FDMA_DCB_DATAP(ri)  VTSS_IOREG(VTSS_TO_CFG,0x6a + (ri))

#define VTSS_ICPU_CFG_FDMA_FDMA_DCB_DATAL(ri)  VTSS_IOREG(VTSS_TO_CFG,0x6e + (ri))
#define  VTSS_F_ICPU_CFG_FDMA_FDMA_DCB_DATAL_TOKEN  VTSS_BIT(17)
#define  VTSS_F_ICPU_CFG_FDMA_FDMA_DCB_DATAL_DATAL(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_ICPU_CFG_FDMA_FDMA_DCB_DATAL_DATAL     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_ICPU_CFG_FDMA_FDMA_DCB_DATAL_DATAL(x)  VTSS_EXTRACT_BITFIELD(x,0,16)

#define VTSS_ICPU_CFG_FDMA_FDMA_DCB_STAT(ri)  VTSS_IOREG(VTSS_TO_CFG,0x72 + (ri))
#define  VTSS_F_ICPU_CFG_FDMA_FDMA_DCB_STAT_BLOCKO(x)  VTSS_ENCODE_BITFIELD(x,20,12)
#define  VTSS_M_ICPU_CFG_FDMA_FDMA_DCB_STAT_BLOCKO     VTSS_ENCODE_BITMASK(20,12)
#define  VTSS_X_ICPU_CFG_FDMA_FDMA_DCB_STAT_BLOCKO(x)  VTSS_EXTRACT_BITFIELD(x,20,12)
#define  VTSS_F_ICPU_CFG_FDMA_FDMA_DCB_STAT_PD  VTSS_BIT(19)
#define  VTSS_F_ICPU_CFG_FDMA_FDMA_DCB_STAT_ABORT  VTSS_BIT(18)
#define  VTSS_F_ICPU_CFG_FDMA_FDMA_DCB_STAT_EOF  VTSS_BIT(17)
#define  VTSS_F_ICPU_CFG_FDMA_FDMA_DCB_STAT_SOF  VTSS_BIT(16)
#define  VTSS_F_ICPU_CFG_FDMA_FDMA_DCB_STAT_BLOCKL(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_ICPU_CFG_FDMA_FDMA_DCB_STAT_BLOCKL     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_ICPU_CFG_FDMA_FDMA_DCB_STAT_BLOCKL(x)  VTSS_EXTRACT_BITFIELD(x,0,16)

#define VTSS_ICPU_CFG_FDMA_FDMA_DCB_LLP_PREV(ri)  VTSS_IOREG(VTSS_TO_CFG,0x76 + (ri))
#define  VTSS_F_ICPU_CFG_FDMA_FDMA_DCB_LLP_PREV_LLP_PREV(x)  VTSS_ENCODE_BITFIELD(x,2,30)
#define  VTSS_M_ICPU_CFG_FDMA_FDMA_DCB_LLP_PREV_LLP_PREV     VTSS_ENCODE_BITMASK(2,30)
#define  VTSS_X_ICPU_CFG_FDMA_FDMA_DCB_LLP_PREV_LLP_PREV(x)  VTSS_EXTRACT_BITFIELD(x,2,30)

#define VTSS_ICPU_CFG_FDMA_FDMA_CH_STAT      VTSS_IOREG(VTSS_TO_CFG,0x7a)
#define  VTSS_F_ICPU_CFG_FDMA_FDMA_CH_STAT_CH_STAT(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_ICPU_CFG_FDMA_FDMA_CH_STAT_CH_STAT     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_ICPU_CFG_FDMA_FDMA_CH_STAT_CH_STAT(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_ICPU_CFG_FDMA_FDMA_CH_SAFE      VTSS_IOREG(VTSS_TO_CFG,0x7b)
#define  VTSS_F_ICPU_CFG_FDMA_FDMA_CH_SAFE_CH_SAFE(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_ICPU_CFG_FDMA_FDMA_CH_SAFE_CH_SAFE     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_ICPU_CFG_FDMA_FDMA_CH_SAFE_CH_SAFE(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_ICPU_CFG_FDMA_FDMA_CH_ACTIVATE  VTSS_IOREG(VTSS_TO_CFG,0x7c)
#define  VTSS_F_ICPU_CFG_FDMA_FDMA_CH_ACTIVATE_CH_ACTIVATE(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_ICPU_CFG_FDMA_FDMA_CH_ACTIVATE_CH_ACTIVATE     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_ICPU_CFG_FDMA_FDMA_CH_ACTIVATE_CH_ACTIVATE(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_ICPU_CFG_FDMA_FDMA_CH_DISABLE   VTSS_IOREG(VTSS_TO_CFG,0x7d)
#define  VTSS_F_ICPU_CFG_FDMA_FDMA_CH_DISABLE_CH_DISABLE(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_ICPU_CFG_FDMA_FDMA_CH_DISABLE_CH_DISABLE     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_ICPU_CFG_FDMA_FDMA_CH_DISABLE_CH_DISABLE(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_ICPU_CFG_FDMA_FDMA_CH_FORCEDIS  VTSS_IOREG(VTSS_TO_CFG,0x7e)
#define  VTSS_F_ICPU_CFG_FDMA_FDMA_CH_FORCEDIS_CH_FORCEDIS(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_ICPU_CFG_FDMA_FDMA_CH_FORCEDIS_CH_FORCEDIS     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_ICPU_CFG_FDMA_FDMA_CH_FORCEDIS_CH_FORCEDIS(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_ICPU_CFG_FDMA_FDMA_CH_CNT(ri)   VTSS_IOREG(VTSS_TO_CFG,0x7f + (ri))
#define  VTSS_F_ICPU_CFG_FDMA_FDMA_CH_CNT_CH_CNT_FRM(x)  VTSS_ENCODE_BITFIELD(x,16,16)
#define  VTSS_M_ICPU_CFG_FDMA_FDMA_CH_CNT_CH_CNT_FRM     VTSS_ENCODE_BITMASK(16,16)
#define  VTSS_X_ICPU_CFG_FDMA_FDMA_CH_CNT_CH_CNT_FRM(x)  VTSS_EXTRACT_BITFIELD(x,16,16)
#define  VTSS_F_ICPU_CFG_FDMA_FDMA_CH_CNT_CH_CNT_DCB(x)  VTSS_ENCODE_BITFIELD(x,8,8)
#define  VTSS_M_ICPU_CFG_FDMA_FDMA_CH_CNT_CH_CNT_DCB     VTSS_ENCODE_BITMASK(8,8)
#define  VTSS_X_ICPU_CFG_FDMA_FDMA_CH_CNT_CH_CNT_DCB(x)  VTSS_EXTRACT_BITFIELD(x,8,8)
#define  VTSS_F_ICPU_CFG_FDMA_FDMA_CH_CNT_CH_CNT_SIG(x)  VTSS_ENCODE_BITFIELD(x,0,8)
#define  VTSS_M_ICPU_CFG_FDMA_FDMA_CH_CNT_CH_CNT_SIG     VTSS_ENCODE_BITMASK(0,8)
#define  VTSS_X_ICPU_CFG_FDMA_FDMA_CH_CNT_CH_CNT_SIG(x)  VTSS_EXTRACT_BITFIELD(x,0,8)

#define VTSS_ICPU_CFG_FDMA_FDMA_CH_INJ_TOKEN_CNT(ri)  VTSS_IOREG(VTSS_TO_CFG,0x83 + (ri))
#define  VTSS_F_ICPU_CFG_FDMA_FDMA_CH_INJ_TOKEN_CNT_CH_INJ_TOKEN_CNT(x)  VTSS_ENCODE_BITFIELD(x,0,8)
#define  VTSS_M_ICPU_CFG_FDMA_FDMA_CH_INJ_TOKEN_CNT_CH_INJ_TOKEN_CNT     VTSS_ENCODE_BITMASK(0,8)
#define  VTSS_X_ICPU_CFG_FDMA_FDMA_CH_INJ_TOKEN_CNT_CH_INJ_TOKEN_CNT(x)  VTSS_EXTRACT_BITFIELD(x,0,8)

#define VTSS_ICPU_CFG_FDMA_FDMA_CH_INJ_TOKEN_TICK_RLD(ri)  VTSS_IOREG(VTSS_TO_CFG,0x85 + (ri))

#define VTSS_ICPU_CFG_FDMA_FDMA_CH_INJ_TOKEN_TICK_CNT(ri)  VTSS_IOREG(VTSS_TO_CFG,0x87 + (ri))

#define VTSS_ICPU_CFG_FDMA_FDMA_EVT_ERR      VTSS_IOREG(VTSS_TO_CFG,0x89)
#define  VTSS_F_ICPU_CFG_FDMA_FDMA_EVT_ERR_EVT_ERR(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_ICPU_CFG_FDMA_FDMA_EVT_ERR_EVT_ERR     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_ICPU_CFG_FDMA_FDMA_EVT_ERR_EVT_ERR(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_ICPU_CFG_FDMA_FDMA_EVT_ERR_CODE  VTSS_IOREG(VTSS_TO_CFG,0x8a)
#define  VTSS_F_ICPU_CFG_FDMA_FDMA_EVT_ERR_CODE_EVT_ERR_CODE(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_ICPU_CFG_FDMA_FDMA_EVT_ERR_CODE_EVT_ERR_CODE     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_ICPU_CFG_FDMA_FDMA_EVT_ERR_CODE_EVT_ERR_CODE(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_ICPU_CFG_FDMA_FDMA_INTR_LLP     VTSS_IOREG(VTSS_TO_CFG,0x8b)
#define  VTSS_F_ICPU_CFG_FDMA_FDMA_INTR_LLP_INTR_LLP(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_ICPU_CFG_FDMA_FDMA_INTR_LLP_INTR_LLP     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_ICPU_CFG_FDMA_FDMA_INTR_LLP_INTR_LLP(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_ICPU_CFG_FDMA_FDMA_INTR_LLP_ENA  VTSS_IOREG(VTSS_TO_CFG,0x8c)
#define  VTSS_F_ICPU_CFG_FDMA_FDMA_INTR_LLP_ENA_INTR_LLP_ENA(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_ICPU_CFG_FDMA_FDMA_INTR_LLP_ENA_INTR_LLP_ENA     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_ICPU_CFG_FDMA_FDMA_INTR_LLP_ENA_INTR_LLP_ENA(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_ICPU_CFG_FDMA_FDMA_INTR_FRM     VTSS_IOREG(VTSS_TO_CFG,0x8d)
#define  VTSS_F_ICPU_CFG_FDMA_FDMA_INTR_FRM_INTR_FRM(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_ICPU_CFG_FDMA_FDMA_INTR_FRM_INTR_FRM     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_ICPU_CFG_FDMA_FDMA_INTR_FRM_INTR_FRM(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_ICPU_CFG_FDMA_FDMA_INTR_FRM_ENA  VTSS_IOREG(VTSS_TO_CFG,0x8e)
#define  VTSS_F_ICPU_CFG_FDMA_FDMA_INTR_FRM_ENA_INTR_FRM_ENA(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_ICPU_CFG_FDMA_FDMA_INTR_FRM_ENA_INTR_FRM_ENA     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_ICPU_CFG_FDMA_FDMA_INTR_FRM_ENA_INTR_FRM_ENA(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_ICPU_CFG_FDMA_FDMA_INTR_SIG     VTSS_IOREG(VTSS_TO_CFG,0x8f)
#define  VTSS_F_ICPU_CFG_FDMA_FDMA_INTR_SIG_INTR_SIG(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_ICPU_CFG_FDMA_FDMA_INTR_SIG_INTR_SIG     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_ICPU_CFG_FDMA_FDMA_INTR_SIG_INTR_SIG(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_ICPU_CFG_FDMA_FDMA_INTR_SIG_ENA  VTSS_IOREG(VTSS_TO_CFG,0x90)
#define  VTSS_F_ICPU_CFG_FDMA_FDMA_INTR_SIG_ENA_INTR_SIG_ENA(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_ICPU_CFG_FDMA_FDMA_INTR_SIG_ENA_INTR_SIG_ENA     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_ICPU_CFG_FDMA_FDMA_INTR_SIG_ENA_INTR_SIG_ENA(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_ICPU_CFG_FDMA_FDMA_INTR_ENA     VTSS_IOREG(VTSS_TO_CFG,0x91)
#define  VTSS_F_ICPU_CFG_FDMA_FDMA_INTR_ENA_INTR_ENA(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_ICPU_CFG_FDMA_FDMA_INTR_ENA_INTR_ENA     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_ICPU_CFG_FDMA_FDMA_INTR_ENA_INTR_ENA(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_ICPU_CFG_FDMA_FDMA_INTR_IDENT   VTSS_IOREG(VTSS_TO_CFG,0x92)
#define  VTSS_F_ICPU_CFG_FDMA_FDMA_INTR_IDENT_INTR_IDENT(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_ICPU_CFG_FDMA_FDMA_INTR_IDENT_INTR_IDENT     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_ICPU_CFG_FDMA_FDMA_INTR_IDENT_INTR_IDENT(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_ICPU_CFG_FDMA_FDMA_CH_CFG(ri)   VTSS_IOREG(VTSS_TO_CFG,0x93 + (ri))
#define  VTSS_F_ICPU_CFG_FDMA_FDMA_CH_CFG_STAT_IN_DATA_ENA  VTSS_BIT(4)
#define  VTSS_F_ICPU_CFG_FDMA_FDMA_CH_CFG_CH_PRIO(x)  VTSS_ENCODE_BITFIELD(x,2,2)
#define  VTSS_M_ICPU_CFG_FDMA_FDMA_CH_CFG_CH_PRIO     VTSS_ENCODE_BITMASK(2,2)
#define  VTSS_X_ICPU_CFG_FDMA_FDMA_CH_CFG_CH_PRIO(x)  VTSS_EXTRACT_BITFIELD(x,2,2)
#define  VTSS_F_ICPU_CFG_FDMA_FDMA_CH_CFG_DONE_STOP_ENA  VTSS_BIT(1)
#define  VTSS_F_ICPU_CFG_FDMA_FDMA_CH_CFG_DONEEOF_STOP_ENA  VTSS_BIT(0)

#define VTSS_ICPU_CFG_FDMA_FDMA_GCFG         VTSS_IOREG(VTSS_TO_CFG,0x97)
#define  VTSS_F_ICPU_CFG_FDMA_FDMA_GCFG_INJ_RF_WM(x)  VTSS_ENCODE_BITFIELD(x,7,5)
#define  VTSS_M_ICPU_CFG_FDMA_FDMA_GCFG_INJ_RF_WM     VTSS_ENCODE_BITMASK(7,5)
#define  VTSS_X_ICPU_CFG_FDMA_FDMA_GCFG_INJ_RF_WM(x)  VTSS_EXTRACT_BITFIELD(x,7,5)
#define  VTSS_F_ICPU_CFG_FDMA_FDMA_GCFG_PD_IGNORE  VTSS_BIT(0)

#define VTSS_ICPU_CFG_FDMA_FDMA_GSTAT        VTSS_IOREG(VTSS_TO_CFG,0x98)
#define  VTSS_F_ICPU_CFG_FDMA_FDMA_GSTAT_INJ_RF_HIGH(x)  VTSS_ENCODE_BITFIELD(x,5,6)
#define  VTSS_M_ICPU_CFG_FDMA_FDMA_GSTAT_INJ_RF_HIGH     VTSS_ENCODE_BITMASK(5,6)
#define  VTSS_X_ICPU_CFG_FDMA_FDMA_GSTAT_INJ_RF_HIGH(x)  VTSS_EXTRACT_BITFIELD(x,5,6)

#define VTSS_ICPU_CFG_FDMA_FDMA_IDLECNT      VTSS_IOREG(VTSS_TO_CFG,0x99)
#define  VTSS_F_ICPU_CFG_FDMA_FDMA_IDLECNT_IDLECNT(x)  VTSS_ENCODE_BITFIELD(x,0,24)
#define  VTSS_M_ICPU_CFG_FDMA_FDMA_IDLECNT_IDLECNT     VTSS_ENCODE_BITMASK(0,24)
#define  VTSS_X_ICPU_CFG_FDMA_FDMA_IDLECNT_IDLECNT(x)  VTSS_EXTRACT_BITFIELD(x,0,24)

#define VTSS_ICPU_CFG_FDMA_FDMA_CONST        VTSS_IOREG(VTSS_TO_CFG,0x9a)
#define  VTSS_F_ICPU_CFG_FDMA_FDMA_CONST_CH_INJ_CNT(x)  VTSS_ENCODE_BITFIELD(x,8,8)
#define  VTSS_M_ICPU_CFG_FDMA_FDMA_CONST_CH_INJ_CNT     VTSS_ENCODE_BITMASK(8,8)
#define  VTSS_X_ICPU_CFG_FDMA_FDMA_CONST_CH_INJ_CNT(x)  VTSS_EXTRACT_BITFIELD(x,8,8)
#define  VTSS_F_ICPU_CFG_FDMA_FDMA_CONST_CH_XTR_CNT(x)  VTSS_ENCODE_BITFIELD(x,0,8)
#define  VTSS_M_ICPU_CFG_FDMA_FDMA_CONST_CH_XTR_CNT     VTSS_ENCODE_BITMASK(0,8)
#define  VTSS_X_ICPU_CFG_FDMA_FDMA_CONST_CH_XTR_CNT(x)  VTSS_EXTRACT_BITFIELD(x,0,8)

#define VTSS_ICPU_CFG_PCIe_PCIE_CFG          VTSS_IOREG(VTSS_TO_CFG,0x9c)
#define  VTSS_F_ICPU_CFG_PCIe_PCIE_CFG_PCIE_BAR_WR_ENA  VTSS_BIT(2)
#define  VTSS_F_ICPU_CFG_PCIe_PCIE_CFG_LTSSM_DIS  VTSS_BIT(1)
#define  VTSS_F_ICPU_CFG_PCIe_PCIE_CFG_MEM_RING_CORE_ENA  VTSS_BIT(0)

#define VTSS_ICPU_CFG_PCIe_PCIE_STAT         VTSS_IOREG(VTSS_TO_CFG,0x9d)
#define  VTSS_F_ICPU_CFG_PCIe_PCIE_STAT_PM_STATE(x)  VTSS_ENCODE_BITFIELD(x,0,3)
#define  VTSS_M_ICPU_CFG_PCIe_PCIE_STAT_PM_STATE     VTSS_ENCODE_BITMASK(0,3)
#define  VTSS_X_ICPU_CFG_PCIe_PCIE_STAT_PM_STATE(x)  VTSS_EXTRACT_BITFIELD(x,0,3)

#define VTSS_ICPU_CFG_PCIe_PCIE_AUX_CFG      VTSS_IOREG(VTSS_TO_CFG,0x9e)
#define  VTSS_F_ICPU_CFG_PCIe_PCIE_AUX_CFG_AUX_POWER_FORCE  VTSS_BIT(1)
#define  VTSS_F_ICPU_CFG_PCIe_PCIE_AUX_CFG_AUX_POWER_VAL  VTSS_BIT(0)

#define VTSS_ICPU_CFG_PCIe_PCIESLV_FDMA      VTSS_IOREG(VTSS_TO_CFG,0xa5)
#define  VTSS_F_ICPU_CFG_PCIe_PCIESLV_FDMA_FDMA_OFFSET(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_ICPU_CFG_PCIe_PCIESLV_FDMA_FDMA_OFFSET     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_ICPU_CFG_PCIe_PCIESLV_FDMA_FDMA_OFFSET(x)  VTSS_EXTRACT_BITFIELD(x,0,2)

#define VTSS_ICPU_CFG_PCIe_PCIESLV_SBA       VTSS_IOREG(VTSS_TO_CFG,0xa6)
#define  VTSS_F_ICPU_CFG_PCIe_PCIESLV_SBA_SBA_BE(x)  VTSS_ENCODE_BITFIELD(x,24,4)
#define  VTSS_M_ICPU_CFG_PCIe_PCIESLV_SBA_SBA_BE     VTSS_ENCODE_BITMASK(24,4)
#define  VTSS_X_ICPU_CFG_PCIe_PCIESLV_SBA_SBA_BE(x)  VTSS_EXTRACT_BITFIELD(x,24,4)
#define  VTSS_F_ICPU_CFG_PCIe_PCIESLV_SBA_SBA_MSG_CODE(x)  VTSS_ENCODE_BITFIELD(x,15,8)
#define  VTSS_M_ICPU_CFG_PCIe_PCIESLV_SBA_SBA_MSG_CODE     VTSS_ENCODE_BITMASK(15,8)
#define  VTSS_X_ICPU_CFG_PCIe_PCIESLV_SBA_SBA_MSG_CODE(x)  VTSS_EXTRACT_BITFIELD(x,15,8)
#define  VTSS_F_ICPU_CFG_PCIe_PCIESLV_SBA_SBA_TC(x)  VTSS_ENCODE_BITFIELD(x,12,3)
#define  VTSS_M_ICPU_CFG_PCIe_PCIESLV_SBA_SBA_TC     VTSS_ENCODE_BITMASK(12,3)
#define  VTSS_X_ICPU_CFG_PCIe_PCIESLV_SBA_SBA_TC(x)  VTSS_EXTRACT_BITFIELD(x,12,3)
#define  VTSS_F_ICPU_CFG_PCIe_PCIESLV_SBA_SBA_EP  VTSS_BIT(8)
#define  VTSS_F_ICPU_CFG_PCIe_PCIESLV_SBA_SBA_OFFSET(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_ICPU_CFG_PCIe_PCIESLV_SBA_SBA_OFFSET     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_ICPU_CFG_PCIe_PCIESLV_SBA_SBA_OFFSET(x)  VTSS_EXTRACT_BITFIELD(x,0,2)

#define VTSS_ICPU_CFG_PCIe_PCIEPCS_CFG       VTSS_IOREG(VTSS_TO_CFG,0xa7)
#define  VTSS_F_ICPU_CFG_PCIe_PCIEPCS_CFG_WAKE_POL  VTSS_BIT(2)
#define  VTSS_F_ICPU_CFG_PCIe_PCIEPCS_CFG_WAKE_OE  VTSS_BIT(1)
#define  VTSS_F_ICPU_CFG_PCIe_PCIEPCS_CFG_BEACON_DIS  VTSS_BIT(0)

#define VTSS_ICPU_CFG_PCIe_PCIE_INTR         VTSS_IOREG(VTSS_TO_CFG,0xa9)
#define  VTSS_F_ICPU_CFG_PCIe_PCIE_INTR_INTR_PM_STATE  VTSS_BIT(0)

#define VTSS_ICPU_CFG_PCIe_PCIE_INTR_ENA     VTSS_IOREG(VTSS_TO_CFG,0xaa)
#define  VTSS_F_ICPU_CFG_PCIe_PCIE_INTR_ENA_INTR_PM_STATE_ENA  VTSS_BIT(0)

#define VTSS_ICPU_CFG_PCIe_PCIE_INTR_IDENT   VTSS_IOREG(VTSS_TO_CFG,0xab)
#define  VTSS_F_ICPU_CFG_PCIe_PCIE_INTR_IDENT_INTR_PM_STATE_IDENT  VTSS_BIT(0)

#define VTSS_ICPU_CFG_PCIe_PCIE_INTR_COMMON_CFG  VTSS_IOREG(VTSS_TO_CFG,0xac)
#define  VTSS_F_ICPU_CFG_PCIe_PCIE_INTR_COMMON_CFG_WAKEUP_ON_INTR_DIS  VTSS_BIT(2)
#define  VTSS_F_ICPU_CFG_PCIe_PCIE_INTR_COMMON_CFG_LEGACY_MODE_INTR_SEL  VTSS_BIT(1)
#define  VTSS_F_ICPU_CFG_PCIe_PCIE_INTR_COMMON_CFG_PCIE_INTR_ENA  VTSS_BIT(0)

#define VTSS_ICPU_CFG_PCIe_PCIE_INTR_CFG(ri)  VTSS_IOREG(VTSS_TO_CFG,0xad + (ri))
#define  VTSS_F_ICPU_CFG_PCIe_PCIE_INTR_CFG_TRAFFIC_CLASS(x)  VTSS_ENCODE_BITFIELD(x,12,3)
#define  VTSS_M_ICPU_CFG_PCIe_PCIE_INTR_CFG_TRAFFIC_CLASS     VTSS_ENCODE_BITMASK(12,3)
#define  VTSS_X_ICPU_CFG_PCIe_PCIE_INTR_CFG_TRAFFIC_CLASS(x)  VTSS_EXTRACT_BITFIELD(x,12,3)
#define  VTSS_F_ICPU_CFG_PCIe_PCIE_INTR_CFG_FALLING_VECTOR_VAL(x)  VTSS_ENCODE_BITFIELD(x,7,5)
#define  VTSS_M_ICPU_CFG_PCIe_PCIE_INTR_CFG_FALLING_VECTOR_VAL     VTSS_ENCODE_BITMASK(7,5)
#define  VTSS_X_ICPU_CFG_PCIe_PCIE_INTR_CFG_FALLING_VECTOR_VAL(x)  VTSS_EXTRACT_BITFIELD(x,7,5)
#define  VTSS_F_ICPU_CFG_PCIe_PCIE_INTR_CFG_RISING_VECTOR_VAL(x)  VTSS_ENCODE_BITFIELD(x,2,5)
#define  VTSS_M_ICPU_CFG_PCIe_PCIE_INTR_CFG_RISING_VECTOR_VAL     VTSS_ENCODE_BITMASK(2,5)
#define  VTSS_X_ICPU_CFG_PCIe_PCIE_INTR_CFG_RISING_VECTOR_VAL(x)  VTSS_EXTRACT_BITFIELD(x,2,5)
#define  VTSS_F_ICPU_CFG_PCIe_PCIE_INTR_CFG_INTR_FALLING_ENA  VTSS_BIT(1)
#define  VTSS_F_ICPU_CFG_PCIe_PCIE_INTR_CFG_INTR_RISING_ENA  VTSS_BIT(0)

#define VTSS_ICPU_CFG_MANUAL_XTRINJ_MANUAL_XTR(ri)  VTSS_IOREG(VTSS_TO_CFG,0x1000 + (ri))

#define VTSS_ICPU_CFG_MANUAL_XTRINJ_MANUAL_INJ(ri)  VTSS_IOREG(VTSS_TO_CFG,0x2000 + (ri))

#define VTSS_ICPU_CFG_MANUAL_XTRINJ_MANUAL_CFG  VTSS_IOREG(VTSS_TO_CFG,0x3000)
#define  VTSS_F_ICPU_CFG_MANUAL_XTRINJ_MANUAL_CFG_INJ_ENA  VTSS_BIT(1)
#define  VTSS_F_ICPU_CFG_MANUAL_XTRINJ_MANUAL_CFG_XTR_ENA  VTSS_BIT(0)

#define VTSS_ICPU_CFG_MANUAL_XTRINJ_MANUAL_INTR  VTSS_IOREG(VTSS_TO_CFG,0x3001)
#define  VTSS_F_ICPU_CFG_MANUAL_XTRINJ_MANUAL_INTR_INTR_INJ_RDY  VTSS_BIT(2)
#define  VTSS_F_ICPU_CFG_MANUAL_XTRINJ_MANUAL_INTR_INTR_XTR_ANY_RDY  VTSS_BIT(1)
#define  VTSS_F_ICPU_CFG_MANUAL_XTRINJ_MANUAL_INTR_INTR_XTR_SOF_RDY  VTSS_BIT(0)

#define VTSS_ICPU_CFG_MANUAL_XTRINJ_MANUAL_INTR_ENA  VTSS_IOREG(VTSS_TO_CFG,0x3002)
#define  VTSS_F_ICPU_CFG_MANUAL_XTRINJ_MANUAL_INTR_ENA_INTR_INJ_RDY_ENA  VTSS_BIT(2)
#define  VTSS_F_ICPU_CFG_MANUAL_XTRINJ_MANUAL_INTR_ENA_INTR_XTR_ANY_RDY_ENA  VTSS_BIT(1)
#define  VTSS_F_ICPU_CFG_MANUAL_XTRINJ_MANUAL_INTR_ENA_INTR_XTR_SOF_RDY_ENA  VTSS_BIT(0)


#endif /* _VTSS_SERVAL_REGS_ICPU_CFG_H_ */
