#ifndef _VTSS_SERVAL_REGS_HSIO_H_
#define _VTSS_SERVAL_REGS_HSIO_H_

/*
 *
 * VCore-III Register Definitions
 *
 #####ECOSGPLCOPYRIGHTBEGIN#####
 -------------------------------------------
 This file is part of eCos, the Embedded Configurable Operating System.
 Copyright (C) 1998-2012 Free Software Foundation, Inc.

 eCos is free software; you can redistribute it and/or modify it under
 the terms of the GNU General Public License as published by the Free
 Software Foundation; either version 2 or (at your option) any later
 version.

 eCos is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 for more details.

 You should have received a copy of the GNU General Public License
 along with eCos; if not, write to the Free Software Foundation, Inc.,
 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

 As a special exception, if other files instantiate templates or use
 macros or inline functions from this file, or you compile this file
 and link it with other works to produce a work based on this file,
 this file does not by itself cause the resulting work to be covered by
 the GNU General Public License. However the source code for this file
 must still be made available in accordance with section (3) of the GNU
 General Public License v2.

 This exception does not invalidate any other reasons why a work based
 on this file might be covered by the GNU General Public License.
 -------------------------------------------
 #####ECOSGPLCOPYRIGHTEND#####
 */

#include "vtss_serval_regs_common.h"

#define VTSS_HSIO_PLL5G_CFG_PLL5G_CFG0       VTSS_IOREG(VTSS_TO_HSIO,0x0)

#define VTSS_HSIO_PLL5G_CFG_PLL5G_CFG1       VTSS_IOREG(VTSS_TO_HSIO,0x1)

#define VTSS_HSIO_PLL5G_CFG_PLL5G_CFG2       VTSS_IOREG(VTSS_TO_HSIO,0x2)

#define VTSS_HSIO_PLL5G_CFG_PLL5G_CFG3       VTSS_IOREG(VTSS_TO_HSIO,0x3)

#define VTSS_HSIO_PLL5G_CFG_PLL5G_CFG4       VTSS_IOREG(VTSS_TO_HSIO,0x4)

#define VTSS_HSIO_PLL5G_CFG_PLL5G_CFG5       VTSS_IOREG(VTSS_TO_HSIO,0x5)

#define VTSS_HSIO_PLL5G_CFG_PLL5G_CFG6       VTSS_IOREG(VTSS_TO_HSIO,0x6)

#define VTSS_HSIO_PLL5G_STATUS_PLL5G_STATUS0  VTSS_IOREG(VTSS_TO_HSIO,0x7)
#define  VTSS_F_HSIO_PLL5G_STATUS_PLL5G_STATUS0_LOCK_STATUS  VTSS_BIT(0)
#define  VTSS_F_HSIO_PLL5G_STATUS_PLL5G_STATUS0_READBACK_DATA(x)  VTSS_ENCODE_BITFIELD(x,1,8)
#define  VTSS_M_HSIO_PLL5G_STATUS_PLL5G_STATUS0_READBACK_DATA     VTSS_ENCODE_BITMASK(1,8)
#define  VTSS_X_HSIO_PLL5G_STATUS_PLL5G_STATUS0_READBACK_DATA(x)  VTSS_EXTRACT_BITFIELD(x,1,8)
#define  VTSS_F_HSIO_PLL5G_STATUS_PLL5G_STATUS0_CALIBRATION_DONE  VTSS_BIT(9)
#define  VTSS_F_HSIO_PLL5G_STATUS_PLL5G_STATUS0_CALIBRATION_ERR  VTSS_BIT(10)
#define  VTSS_F_HSIO_PLL5G_STATUS_PLL5G_STATUS0_OUT_OF_RANGE_ERR  VTSS_BIT(11)
#define  VTSS_F_HSIO_PLL5G_STATUS_PLL5G_STATUS0_RANGE_LIM  VTSS_BIT(12)

#define VTSS_HSIO_RCOMP_CFG_RCOMP_CFG0       VTSS_IOREG(VTSS_TO_HSIO,0x9)
#define  VTSS_F_HSIO_RCOMP_CFG_RCOMP_CFG0_RUN_CAL  VTSS_BIT(12)
#define  VTSS_F_HSIO_RCOMP_CFG_RCOMP_CFG0_MODE_SEL(x)  VTSS_ENCODE_BITFIELD(x,8,2)
#define  VTSS_M_HSIO_RCOMP_CFG_RCOMP_CFG0_MODE_SEL     VTSS_ENCODE_BITMASK(8,2)
#define  VTSS_X_HSIO_RCOMP_CFG_RCOMP_CFG0_MODE_SEL(x)  VTSS_EXTRACT_BITFIELD(x,8,2)

#define VTSS_HSIO_RCOMP_STATUS_RCOMP_STATUS  VTSS_IOREG(VTSS_TO_HSIO,0xa)
#define  VTSS_F_HSIO_RCOMP_STATUS_RCOMP_STATUS_BUSY  VTSS_BIT(12)
#define  VTSS_F_HSIO_RCOMP_STATUS_RCOMP_STATUS_DELTA_ALERT  VTSS_BIT(7)
#define  VTSS_F_HSIO_RCOMP_STATUS_RCOMP_STATUS_RCOMP(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_HSIO_RCOMP_STATUS_RCOMP_STATUS_RCOMP     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_HSIO_RCOMP_STATUS_RCOMP_STATUS_RCOMP(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_HSIO_SYNC_ETH_CFG_SYNC_ETH_CFG0  VTSS_IOREG(VTSS_TO_HSIO,0xb)
#define  VTSS_F_HSIO_SYNC_ETH_CFG_SYNC_ETH_CFG0_RECO_CLK_ENA(x)  VTSS_ENCODE_BITFIELD(x,0,10)
#define  VTSS_M_HSIO_SYNC_ETH_CFG_SYNC_ETH_CFG0_RECO_CLK_ENA     VTSS_ENCODE_BITMASK(0,10)
#define  VTSS_X_HSIO_SYNC_ETH_CFG_SYNC_ETH_CFG0_RECO_CLK_ENA(x)  VTSS_EXTRACT_BITFIELD(x,0,10)

#define VTSS_HSIO_SYNC_ETH_CFG_SYNC_ETH_CFG1  VTSS_IOREG(VTSS_TO_HSIO,0xc)
#define  VTSS_F_HSIO_SYNC_ETH_CFG_SYNC_ETH_CFG1_RECO_CLK_SEL0(x)  VTSS_ENCODE_BITFIELD(x,16,4)
#define  VTSS_M_HSIO_SYNC_ETH_CFG_SYNC_ETH_CFG1_RECO_CLK_SEL0     VTSS_ENCODE_BITMASK(16,4)
#define  VTSS_X_HSIO_SYNC_ETH_CFG_SYNC_ETH_CFG1_RECO_CLK_SEL0(x)  VTSS_EXTRACT_BITFIELD(x,16,4)
#define  VTSS_F_HSIO_SYNC_ETH_CFG_SYNC_ETH_CFG1_RECO_CLK_SEL(x)  VTSS_ENCODE_BITFIELD(x,0,10)
#define  VTSS_M_HSIO_SYNC_ETH_CFG_SYNC_ETH_CFG1_RECO_CLK_SEL     VTSS_ENCODE_BITMASK(0,10)
#define  VTSS_X_HSIO_SYNC_ETH_CFG_SYNC_ETH_CFG1_RECO_CLK_SEL(x)  VTSS_EXTRACT_BITFIELD(x,0,10)

#define VTSS_HSIO_SYNC_ETH_CFG_SYNC_ETH_CFG2  VTSS_IOREG(VTSS_TO_HSIO,0xd)
#define  VTSS_F_HSIO_SYNC_ETH_CFG_SYNC_ETH_CFG2_SEL_RECO_CLK_B(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_HSIO_SYNC_ETH_CFG_SYNC_ETH_CFG2_SEL_RECO_CLK_B     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_HSIO_SYNC_ETH_CFG_SYNC_ETH_CFG2_SEL_RECO_CLK_B(x)  VTSS_EXTRACT_BITFIELD(x,0,2)

#define VTSS_HSIO_MCB_PLL5G_RCOMP_CFG_MCB_PLL5G_RCOMP_ADDR_CFG  VTSS_IOREG(VTSS_TO_HSIO,0xe)
#define  VTSS_F_HSIO_MCB_PLL5G_RCOMP_CFG_MCB_PLL5G_RCOMP_ADDR_CFG_PLL5G_RCOMP_WR_ONE_SHOT  VTSS_BIT(31)
#define  VTSS_F_HSIO_MCB_PLL5G_RCOMP_CFG_MCB_PLL5G_RCOMP_ADDR_CFG_PLL5G_RCOMP_RD_ONE_SHOT  VTSS_BIT(30)
#define  VTSS_F_HSIO_MCB_PLL5G_RCOMP_CFG_MCB_PLL5G_RCOMP_ADDR_CFG_PLL5G_RCOMP_ADDR(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_HSIO_MCB_PLL5G_RCOMP_CFG_MCB_PLL5G_RCOMP_ADDR_CFG_PLL5G_RCOMP_ADDR     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_HSIO_MCB_PLL5G_RCOMP_CFG_MCB_PLL5G_RCOMP_ADDR_CFG_PLL5G_RCOMP_ADDR(x)  VTSS_EXTRACT_BITFIELD(x,0,2)

#define VTSS_HSIO_SERDES1G_ANA_CFG_SERDES1G_DES_CFG  VTSS_IOREG(VTSS_TO_HSIO,0xf)
#define  VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_DES_CFG_DES_PHS_CTRL(x)  VTSS_ENCODE_BITFIELD(x,13,4)
#define  VTSS_M_HSIO_SERDES1G_ANA_CFG_SERDES1G_DES_CFG_DES_PHS_CTRL     VTSS_ENCODE_BITMASK(13,4)
#define  VTSS_X_HSIO_SERDES1G_ANA_CFG_SERDES1G_DES_CFG_DES_PHS_CTRL(x)  VTSS_EXTRACT_BITFIELD(x,13,4)
#define  VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_DES_CFG_DES_CPMD_SEL(x)  VTSS_ENCODE_BITFIELD(x,11,2)
#define  VTSS_M_HSIO_SERDES1G_ANA_CFG_SERDES1G_DES_CFG_DES_CPMD_SEL     VTSS_ENCODE_BITMASK(11,2)
#define  VTSS_X_HSIO_SERDES1G_ANA_CFG_SERDES1G_DES_CFG_DES_CPMD_SEL(x)  VTSS_EXTRACT_BITFIELD(x,11,2)
#define  VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_DES_CFG_DES_MBTR_CTRL(x)  VTSS_ENCODE_BITFIELD(x,8,3)
#define  VTSS_M_HSIO_SERDES1G_ANA_CFG_SERDES1G_DES_CFG_DES_MBTR_CTRL     VTSS_ENCODE_BITMASK(8,3)
#define  VTSS_X_HSIO_SERDES1G_ANA_CFG_SERDES1G_DES_CFG_DES_MBTR_CTRL(x)  VTSS_EXTRACT_BITFIELD(x,8,3)
#define  VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_DES_CFG_DES_BW_ANA(x)  VTSS_ENCODE_BITFIELD(x,5,3)
#define  VTSS_M_HSIO_SERDES1G_ANA_CFG_SERDES1G_DES_CFG_DES_BW_ANA     VTSS_ENCODE_BITMASK(5,3)
#define  VTSS_X_HSIO_SERDES1G_ANA_CFG_SERDES1G_DES_CFG_DES_BW_ANA(x)  VTSS_EXTRACT_BITFIELD(x,5,3)
#define  VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_DES_CFG_DES_BW_HYST(x)  VTSS_ENCODE_BITFIELD(x,1,3)
#define  VTSS_M_HSIO_SERDES1G_ANA_CFG_SERDES1G_DES_CFG_DES_BW_HYST     VTSS_ENCODE_BITMASK(1,3)
#define  VTSS_X_HSIO_SERDES1G_ANA_CFG_SERDES1G_DES_CFG_DES_BW_HYST(x)  VTSS_EXTRACT_BITFIELD(x,1,3)

#define VTSS_HSIO_SERDES1G_ANA_CFG_SERDES1G_IB_CFG  VTSS_IOREG(VTSS_TO_HSIO,0x10)
#define  VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_IB_CFG_IB_FX100_ENA  VTSS_BIT(27)
#define  VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_IB_CFG_IB_DET_LEV(x)  VTSS_ENCODE_BITFIELD(x,19,3)
#define  VTSS_M_HSIO_SERDES1G_ANA_CFG_SERDES1G_IB_CFG_IB_DET_LEV     VTSS_ENCODE_BITMASK(19,3)
#define  VTSS_X_HSIO_SERDES1G_ANA_CFG_SERDES1G_IB_CFG_IB_DET_LEV(x)  VTSS_EXTRACT_BITFIELD(x,19,3)
#define  VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_IB_CFG_IB_HYST_LEV  VTSS_BIT(14)
#define  VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_IB_CFG_IB_ENA_CMV_TERM  VTSS_BIT(13)
#define  VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_IB_CFG_IB_ENA_DC_COUPLING  VTSS_BIT(12)
#define  VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_IB_CFG_IB_ENA_DETLEV  VTSS_BIT(11)
#define  VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_IB_CFG_IB_ENA_HYST  VTSS_BIT(10)
#define  VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_IB_CFG_IB_ENA_OFFSET_COMP  VTSS_BIT(9)
#define  VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_IB_CFG_IB_EQ_GAIN(x)  VTSS_ENCODE_BITFIELD(x,6,3)
#define  VTSS_M_HSIO_SERDES1G_ANA_CFG_SERDES1G_IB_CFG_IB_EQ_GAIN     VTSS_ENCODE_BITMASK(6,3)
#define  VTSS_X_HSIO_SERDES1G_ANA_CFG_SERDES1G_IB_CFG_IB_EQ_GAIN(x)  VTSS_EXTRACT_BITFIELD(x,6,3)
#define  VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_IB_CFG_IB_SEL_CORNER_FREQ(x)  VTSS_ENCODE_BITFIELD(x,4,2)
#define  VTSS_M_HSIO_SERDES1G_ANA_CFG_SERDES1G_IB_CFG_IB_SEL_CORNER_FREQ     VTSS_ENCODE_BITMASK(4,2)
#define  VTSS_X_HSIO_SERDES1G_ANA_CFG_SERDES1G_IB_CFG_IB_SEL_CORNER_FREQ(x)  VTSS_EXTRACT_BITFIELD(x,4,2)
#define  VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_IB_CFG_IB_RESISTOR_CTRL(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_HSIO_SERDES1G_ANA_CFG_SERDES1G_IB_CFG_IB_RESISTOR_CTRL     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_HSIO_SERDES1G_ANA_CFG_SERDES1G_IB_CFG_IB_RESISTOR_CTRL(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_HSIO_SERDES1G_ANA_CFG_SERDES1G_OB_CFG  VTSS_IOREG(VTSS_TO_HSIO,0x11)
#define  VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_OB_CFG_OB_SLP(x)  VTSS_ENCODE_BITFIELD(x,17,2)
#define  VTSS_M_HSIO_SERDES1G_ANA_CFG_SERDES1G_OB_CFG_OB_SLP     VTSS_ENCODE_BITMASK(17,2)
#define  VTSS_X_HSIO_SERDES1G_ANA_CFG_SERDES1G_OB_CFG_OB_SLP(x)  VTSS_EXTRACT_BITFIELD(x,17,2)
#define  VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_OB_CFG_OB_AMP_CTRL(x)  VTSS_ENCODE_BITFIELD(x,13,4)
#define  VTSS_M_HSIO_SERDES1G_ANA_CFG_SERDES1G_OB_CFG_OB_AMP_CTRL     VTSS_ENCODE_BITMASK(13,4)
#define  VTSS_X_HSIO_SERDES1G_ANA_CFG_SERDES1G_OB_CFG_OB_AMP_CTRL(x)  VTSS_EXTRACT_BITFIELD(x,13,4)
#define  VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_OB_CFG_OB_VCM_CTRL(x)  VTSS_ENCODE_BITFIELD(x,4,4)
#define  VTSS_M_HSIO_SERDES1G_ANA_CFG_SERDES1G_OB_CFG_OB_VCM_CTRL     VTSS_ENCODE_BITMASK(4,4)
#define  VTSS_X_HSIO_SERDES1G_ANA_CFG_SERDES1G_OB_CFG_OB_VCM_CTRL(x)  VTSS_EXTRACT_BITFIELD(x,4,4)
#define  VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_OB_CFG_OB_RESISTOR_CTRL(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_HSIO_SERDES1G_ANA_CFG_SERDES1G_OB_CFG_OB_RESISTOR_CTRL     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_HSIO_SERDES1G_ANA_CFG_SERDES1G_OB_CFG_OB_RESISTOR_CTRL(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_HSIO_SERDES1G_ANA_CFG_SERDES1G_SER_CFG  VTSS_IOREG(VTSS_TO_HSIO,0x12)
#define  VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_SER_CFG_SER_IDLE  VTSS_BIT(9)
#define  VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_SER_CFG_SER_DEEMPH  VTSS_BIT(8)
#define  VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_SER_CFG_SER_ENHYS  VTSS_BIT(3)
#define  VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_SER_CFG_SER_BIG_WIN  VTSS_BIT(2)
#define  VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_SER_CFG_SER_EN_WIN  VTSS_BIT(1)
#define  VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_SER_CFG_SER_ENALI  VTSS_BIT(0)

#define VTSS_HSIO_SERDES1G_ANA_CFG_SERDES1G_COMMON_CFG  VTSS_IOREG(VTSS_TO_HSIO,0x13)
#define  VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_COMMON_CFG_SYS_RST  VTSS_BIT(31)
#define  VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_COMMON_CFG_SE_AUTO_SQUELCH_B_ENA  VTSS_BIT(22)
#define  VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_COMMON_CFG_SE_AUTO_SQUELCH_A_ENA  VTSS_BIT(21)
#define  VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_COMMON_CFG_RECO_SEL_B  VTSS_BIT(20)
#define  VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_COMMON_CFG_RECO_SEL_A  VTSS_BIT(19)
#define  VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_COMMON_CFG_ENA_LANE  VTSS_BIT(18)
#define  VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_COMMON_CFG_ENA_ELOOP  VTSS_BIT(11)
#define  VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_COMMON_CFG_ENA_FLOOP  VTSS_BIT(10)

#define VTSS_HSIO_SERDES1G_ANA_CFG_SERDES1G_PLL_CFG  VTSS_IOREG(VTSS_TO_HSIO,0x14)
#define  VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_PLL_CFG_PLL_FSM_CTRL_DATA(x)  VTSS_ENCODE_BITFIELD(x,8,8)
#define  VTSS_M_HSIO_SERDES1G_ANA_CFG_SERDES1G_PLL_CFG_PLL_FSM_CTRL_DATA     VTSS_ENCODE_BITMASK(8,8)
#define  VTSS_X_HSIO_SERDES1G_ANA_CFG_SERDES1G_PLL_CFG_PLL_FSM_CTRL_DATA(x)  VTSS_EXTRACT_BITFIELD(x,8,8)
#define  VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_PLL_CFG_PLL_FSM_ENA  VTSS_BIT(7)

#define VTSS_HSIO_SERDES1G_ANA_STATUS_SERDES1G_PLL_STATUS  VTSS_IOREG(VTSS_TO_HSIO,0x15)

#define VTSS_HSIO_SERDES1G_DIG_CFG_SERDES1G_DFT_CFG0  VTSS_IOREG(VTSS_TO_HSIO,0x16)

#define VTSS_HSIO_SERDES1G_DIG_CFG_SERDES1G_DFT_CFG1  VTSS_IOREG(VTSS_TO_HSIO,0x17)

#define VTSS_HSIO_SERDES1G_DIG_CFG_SERDES1G_DFT_CFG2  VTSS_IOREG(VTSS_TO_HSIO,0x18)

#define VTSS_HSIO_SERDES1G_DIG_CFG_SERDES1G_TP_CFG  VTSS_IOREG(VTSS_TO_HSIO,0x19)

#define VTSS_HSIO_SERDES1G_DIG_CFG_SERDES1G_RC_PLL_BIST_CFG  VTSS_IOREG(VTSS_TO_HSIO,0x1a)

#define VTSS_HSIO_SERDES1G_DIG_CFG_SERDES1G_MISC_CFG  VTSS_IOREG(VTSS_TO_HSIO,0x1b)
#define  VTSS_F_HSIO_SERDES1G_DIG_CFG_SERDES1G_MISC_CFG_SEL_RECO_CLK(x)  VTSS_ENCODE_BITFIELD(x,16,2)
#define  VTSS_M_HSIO_SERDES1G_DIG_CFG_SERDES1G_MISC_CFG_SEL_RECO_CLK     VTSS_ENCODE_BITMASK(16,2)
#define  VTSS_X_HSIO_SERDES1G_DIG_CFG_SERDES1G_MISC_CFG_SEL_RECO_CLK(x)  VTSS_EXTRACT_BITFIELD(x,16,2)
#define  VTSS_F_HSIO_SERDES1G_DIG_CFG_SERDES1G_MISC_CFG_DES_100FX_CPMD_ENA  VTSS_BIT(8)
#define  VTSS_F_HSIO_SERDES1G_DIG_CFG_SERDES1G_MISC_CFG_RX_LPI_MODE_ENA  VTSS_BIT(5)
#define  VTSS_F_HSIO_SERDES1G_DIG_CFG_SERDES1G_MISC_CFG_TX_LPI_MODE_ENA  VTSS_BIT(4)
#define  VTSS_F_HSIO_SERDES1G_DIG_CFG_SERDES1G_MISC_CFG_RX_DATA_INV_ENA  VTSS_BIT(3)
#define  VTSS_F_HSIO_SERDES1G_DIG_CFG_SERDES1G_MISC_CFG_TX_DATA_INV_ENA  VTSS_BIT(2)
#define  VTSS_F_HSIO_SERDES1G_DIG_CFG_SERDES1G_MISC_CFG_LANE_RST  VTSS_BIT(0)

#define VTSS_HSIO_SERDES1G_DIG_STATUS_SERDES1G_DFT_STATUS  VTSS_IOREG(VTSS_TO_HSIO,0x1c)
#define  VTSS_F_HSIO_SERDES1G_DIG_STATUS_SERDES1G_DFT_STATUS_BIST_NOSYNC  VTSS_BIT(2)

#define VTSS_HSIO_MCB_SERDES1G_CFG_MCB_SERDES1G_ADDR_CFG  VTSS_IOREG(VTSS_TO_HSIO,0x1d)
#define  VTSS_F_HSIO_MCB_SERDES1G_CFG_MCB_SERDES1G_ADDR_CFG_SERDES1G_WR_ONE_SHOT  VTSS_BIT(31)
#define  VTSS_F_HSIO_MCB_SERDES1G_CFG_MCB_SERDES1G_ADDR_CFG_SERDES1G_RD_ONE_SHOT  VTSS_BIT(30)
#define  VTSS_F_HSIO_MCB_SERDES1G_CFG_MCB_SERDES1G_ADDR_CFG_SERDES1G_ADDR(x)  VTSS_ENCODE_BITFIELD(x,0,25)
#define  VTSS_M_HSIO_MCB_SERDES1G_CFG_MCB_SERDES1G_ADDR_CFG_SERDES1G_ADDR     VTSS_ENCODE_BITMASK(0,25)
#define  VTSS_X_HSIO_MCB_SERDES1G_CFG_MCB_SERDES1G_ADDR_CFG_SERDES1G_ADDR(x)  VTSS_EXTRACT_BITFIELD(x,0,25)

#define VTSS_HSIO_SERDES6G_ANA_CFG_SERDES6G_DES_CFG  VTSS_IOREG(VTSS_TO_HSIO,0x1e)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_DES_CFG_DES_PHS_CTRL(x)  VTSS_ENCODE_BITFIELD(x,13,4)
#define  VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_DES_CFG_DES_PHS_CTRL     VTSS_ENCODE_BITMASK(13,4)
#define  VTSS_X_HSIO_SERDES6G_ANA_CFG_SERDES6G_DES_CFG_DES_PHS_CTRL(x)  VTSS_EXTRACT_BITFIELD(x,13,4)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_DES_CFG_DES_MBTR_CTRL(x)  VTSS_ENCODE_BITFIELD(x,10,3)
#define  VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_DES_CFG_DES_MBTR_CTRL     VTSS_ENCODE_BITMASK(10,3)
#define  VTSS_X_HSIO_SERDES6G_ANA_CFG_SERDES6G_DES_CFG_DES_MBTR_CTRL(x)  VTSS_EXTRACT_BITFIELD(x,10,3)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_DES_CFG_DES_CPMD_SEL(x)  VTSS_ENCODE_BITFIELD(x,8,2)
#define  VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_DES_CFG_DES_CPMD_SEL     VTSS_ENCODE_BITMASK(8,2)
#define  VTSS_X_HSIO_SERDES6G_ANA_CFG_SERDES6G_DES_CFG_DES_CPMD_SEL(x)  VTSS_EXTRACT_BITFIELD(x,8,2)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_DES_CFG_DES_BW_HYST(x)  VTSS_ENCODE_BITFIELD(x,5,3)
#define  VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_DES_CFG_DES_BW_HYST     VTSS_ENCODE_BITMASK(5,3)
#define  VTSS_X_HSIO_SERDES6G_ANA_CFG_SERDES6G_DES_CFG_DES_BW_HYST(x)  VTSS_EXTRACT_BITFIELD(x,5,3)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_DES_CFG_DES_BW_ANA(x)  VTSS_ENCODE_BITFIELD(x,1,3)
#define  VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_DES_CFG_DES_BW_ANA     VTSS_ENCODE_BITMASK(1,3)
#define  VTSS_X_HSIO_SERDES6G_ANA_CFG_SERDES6G_DES_CFG_DES_BW_ANA(x)  VTSS_EXTRACT_BITFIELD(x,1,3)

#define VTSS_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG  VTSS_IOREG(VTSS_TO_HSIO,0x1f)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_IC_AC(x)  VTSS_ENCODE_BITFIELD(x,25,3)
#define  VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_IC_AC     VTSS_ENCODE_BITMASK(25,3)
#define  VTSS_X_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_IC_AC(x)  VTSS_EXTRACT_BITFIELD(x,25,3)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_IC_COM(x)  VTSS_ENCODE_BITFIELD(x,22,3)
#define  VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_IC_COM     VTSS_ENCODE_BITMASK(22,3)
#define  VTSS_X_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_IC_COM(x)  VTSS_EXTRACT_BITFIELD(x,22,3)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_IC_DC(x)  VTSS_ENCODE_BITFIELD(x,19,3)
#define  VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_IC_DC     VTSS_ENCODE_BITMASK(19,3)
#define  VTSS_X_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_IC_DC(x)  VTSS_EXTRACT_BITFIELD(x,19,3)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_RF(x)  VTSS_ENCODE_BITFIELD(x,14,4)
#define  VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_RF     VTSS_ENCODE_BITMASK(14,4)
#define  VTSS_X_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_RF(x)  VTSS_EXTRACT_BITFIELD(x,14,4)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_RT(x)  VTSS_ENCODE_BITFIELD(x,10,4)
#define  VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_RT     VTSS_ENCODE_BITMASK(10,4)
#define  VTSS_X_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_RT(x)  VTSS_EXTRACT_BITFIELD(x,10,4)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_VBAC(x)  VTSS_ENCODE_BITFIELD(x,7,3)
#define  VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_VBAC     VTSS_ENCODE_BITMASK(7,3)
#define  VTSS_X_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_VBAC(x)  VTSS_EXTRACT_BITFIELD(x,7,3)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_VBCOM(x)  VTSS_ENCODE_BITFIELD(x,4,3)
#define  VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_VBCOM     VTSS_ENCODE_BITMASK(4,3)
#define  VTSS_X_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_VBCOM(x)  VTSS_EXTRACT_BITFIELD(x,4,3)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_RESISTOR_CTRL(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_RESISTOR_CTRL     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_RESISTOR_CTRL(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG1  VTSS_IOREG(VTSS_TO_HSIO,0x20)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG1_IB_C(x)  VTSS_ENCODE_BITFIELD(x,8,4)
#define  VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG1_IB_C     VTSS_ENCODE_BITMASK(8,4)
#define  VTSS_X_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG1_IB_C(x)  VTSS_EXTRACT_BITFIELD(x,8,4)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG1_IB_CTERM_ENA  VTSS_BIT(5)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG1_IB_DIS_EQ  VTSS_BIT(4)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG1_IB_ENA_OFFSAC  VTSS_BIT(3)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG1_IB_ENA_OFFSDC  VTSS_BIT(2)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG1_IB_FX100_ENA  VTSS_BIT(1)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG1_IB_RST  VTSS_BIT(0)

#define VTSS_HSIO_SERDES6G_ANA_CFG_SERDES6G_OB_CFG  VTSS_IOREG(VTSS_TO_HSIO,0x21)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_OB_CFG_OB_IDLE  VTSS_BIT(31)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_OB_CFG_OB_ENA1V_MODE  VTSS_BIT(30)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_OB_CFG_OB_POL  VTSS_BIT(29)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_OB_CFG_OB_POST0(x)  VTSS_ENCODE_BITFIELD(x,23,6)
#define  VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_OB_CFG_OB_POST0     VTSS_ENCODE_BITMASK(23,6)
#define  VTSS_X_HSIO_SERDES6G_ANA_CFG_SERDES6G_OB_CFG_OB_POST0(x)  VTSS_EXTRACT_BITFIELD(x,23,6)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_OB_CFG_OB_POST1(x)  VTSS_ENCODE_BITFIELD(x,18,5)
#define  VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_OB_CFG_OB_POST1     VTSS_ENCODE_BITMASK(18,5)
#define  VTSS_X_HSIO_SERDES6G_ANA_CFG_SERDES6G_OB_CFG_OB_POST1(x)  VTSS_EXTRACT_BITFIELD(x,18,5)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_OB_CFG_OB_PREC(x)  VTSS_ENCODE_BITFIELD(x,13,5)
#define  VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_OB_CFG_OB_PREC     VTSS_ENCODE_BITMASK(13,5)
#define  VTSS_X_HSIO_SERDES6G_ANA_CFG_SERDES6G_OB_CFG_OB_PREC(x)  VTSS_EXTRACT_BITFIELD(x,13,5)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_OB_CFG_OB_SR_H  VTSS_BIT(8)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_OB_CFG_OB_RESISTOR_CTRL(x)  VTSS_ENCODE_BITFIELD(x,4,4)
#define  VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_OB_CFG_OB_RESISTOR_CTRL     VTSS_ENCODE_BITMASK(4,4)
#define  VTSS_X_HSIO_SERDES6G_ANA_CFG_SERDES6G_OB_CFG_OB_RESISTOR_CTRL(x)  VTSS_EXTRACT_BITFIELD(x,4,4)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_OB_CFG_OB_SR(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_OB_CFG_OB_SR     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_HSIO_SERDES6G_ANA_CFG_SERDES6G_OB_CFG_OB_SR(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_HSIO_SERDES6G_ANA_CFG_SERDES6G_OB_CFG1  VTSS_IOREG(VTSS_TO_HSIO,0x22)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_OB_CFG1_OB_ENA_CAS(x)  VTSS_ENCODE_BITFIELD(x,6,3)
#define  VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_OB_CFG1_OB_ENA_CAS     VTSS_ENCODE_BITMASK(6,3)
#define  VTSS_X_HSIO_SERDES6G_ANA_CFG_SERDES6G_OB_CFG1_OB_ENA_CAS(x)  VTSS_EXTRACT_BITFIELD(x,6,3)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_OB_CFG1_OB_LEV(x)  VTSS_ENCODE_BITFIELD(x,0,6)
#define  VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_OB_CFG1_OB_LEV     VTSS_ENCODE_BITMASK(0,6)
#define  VTSS_X_HSIO_SERDES6G_ANA_CFG_SERDES6G_OB_CFG1_OB_LEV(x)  VTSS_EXTRACT_BITFIELD(x,0,6)

#define VTSS_HSIO_SERDES6G_ANA_CFG_SERDES6G_SER_CFG  VTSS_IOREG(VTSS_TO_HSIO,0x23)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_SER_CFG_SER_ENHYS  VTSS_BIT(3)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_SER_CFG_SER_EN_WIN  VTSS_BIT(1)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_SER_CFG_SER_ENALI  VTSS_BIT(0)

#define VTSS_HSIO_SERDES6G_ANA_CFG_SERDES6G_COMMON_CFG  VTSS_IOREG(VTSS_TO_HSIO,0x24)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_COMMON_CFG_SYS_RST  VTSS_BIT(31)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_COMMON_CFG_SE_AUTO_SQUELCH_B_ENA  VTSS_BIT(22)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_COMMON_CFG_SE_AUTO_SQUELCH_A_ENA  VTSS_BIT(21)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_COMMON_CFG_RECO_SEL_B  VTSS_BIT(20)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_COMMON_CFG_RECO_SEL_A  VTSS_BIT(19)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_COMMON_CFG_ENA_LANE  VTSS_BIT(18)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_COMMON_CFG_ENA_ELOOP  VTSS_BIT(11)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_COMMON_CFG_ENA_FLOOP  VTSS_BIT(10)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_COMMON_CFG_HRATE  VTSS_BIT(7)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_COMMON_CFG_QRATE  VTSS_BIT(6)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_COMMON_CFG_IF_MODE(x)  VTSS_ENCODE_BITFIELD(x,4,2)
#define  VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_COMMON_CFG_IF_MODE     VTSS_ENCODE_BITMASK(4,2)
#define  VTSS_X_HSIO_SERDES6G_ANA_CFG_SERDES6G_COMMON_CFG_IF_MODE(x)  VTSS_EXTRACT_BITFIELD(x,4,2)

#define VTSS_HSIO_SERDES6G_ANA_CFG_SERDES6G_PLL_CFG  VTSS_IOREG(VTSS_TO_HSIO,0x25)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_PLL_CFG_PLL_DIV4  VTSS_BIT(20)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_PLL_CFG_PLL_ENA_ROT  VTSS_BIT(18)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_PLL_CFG_PLL_FSM_CTRL_DATA(x)  VTSS_ENCODE_BITFIELD(x,8,8)
#define  VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_PLL_CFG_PLL_FSM_CTRL_DATA     VTSS_ENCODE_BITMASK(8,8)
#define  VTSS_X_HSIO_SERDES6G_ANA_CFG_SERDES6G_PLL_CFG_PLL_FSM_CTRL_DATA(x)  VTSS_EXTRACT_BITFIELD(x,8,8)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_PLL_CFG_PLL_FSM_ENA  VTSS_BIT(7)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_PLL_CFG_PLL_ROT_DIR  VTSS_BIT(2)
#define  VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_PLL_CFG_PLL_ROT_FRQ  VTSS_BIT(1)

#define VTSS_HSIO_SERDES6G_ANA_STATUS_SERDES6G_PLL_STATUS  VTSS_IOREG(VTSS_TO_HSIO,0x26)

#define VTSS_HSIO_SERDES6G_DIG_CFG_SERDES6G_DIG_CFG  VTSS_IOREG(VTSS_TO_HSIO,0x27)
#define  VTSS_F_HSIO_SERDES6G_DIG_CFG_SERDES6G_DIG_CFG_SIGDET_AST(x)  VTSS_ENCODE_BITFIELD(x,3,3)
#define  VTSS_M_HSIO_SERDES6G_DIG_CFG_SERDES6G_DIG_CFG_SIGDET_AST     VTSS_ENCODE_BITMASK(3,3)
#define  VTSS_X_HSIO_SERDES6G_DIG_CFG_SERDES6G_DIG_CFG_SIGDET_AST(x)  VTSS_EXTRACT_BITFIELD(x,3,3)
#define  VTSS_F_HSIO_SERDES6G_DIG_CFG_SERDES6G_DIG_CFG_SIGDET_DST(x)  VTSS_ENCODE_BITFIELD(x,0,3)
#define  VTSS_M_HSIO_SERDES6G_DIG_CFG_SERDES6G_DIG_CFG_SIGDET_DST     VTSS_ENCODE_BITMASK(0,3)
#define  VTSS_X_HSIO_SERDES6G_DIG_CFG_SERDES6G_DIG_CFG_SIGDET_DST(x)  VTSS_EXTRACT_BITFIELD(x,0,3)

#define VTSS_HSIO_SERDES6G_DIG_CFG_SERDES6G_DFT_CFG0  VTSS_IOREG(VTSS_TO_HSIO,0x28)

#define VTSS_HSIO_SERDES6G_DIG_CFG_SERDES6G_DFT_CFG1  VTSS_IOREG(VTSS_TO_HSIO,0x29)

#define VTSS_HSIO_SERDES6G_DIG_CFG_SERDES6G_DFT_CFG2  VTSS_IOREG(VTSS_TO_HSIO,0x2a)

#define VTSS_HSIO_SERDES6G_DIG_CFG_SERDES6G_TP_CFG0  VTSS_IOREG(VTSS_TO_HSIO,0x2b)

#define VTSS_HSIO_SERDES6G_DIG_CFG_SERDES6G_TP_CFG1  VTSS_IOREG(VTSS_TO_HSIO,0x2c)

#define VTSS_HSIO_SERDES6G_DIG_CFG_SERDES6G_RC_PLL_BIST_CFG  VTSS_IOREG(VTSS_TO_HSIO,0x2d)

#define VTSS_HSIO_SERDES6G_DIG_CFG_SERDES6G_MISC_CFG  VTSS_IOREG(VTSS_TO_HSIO,0x2e)
#define  VTSS_F_HSIO_SERDES6G_DIG_CFG_SERDES6G_MISC_CFG_SEL_RECO_CLK(x)  VTSS_ENCODE_BITFIELD(x,16,2)
#define  VTSS_M_HSIO_SERDES6G_DIG_CFG_SERDES6G_MISC_CFG_SEL_RECO_CLK     VTSS_ENCODE_BITMASK(16,2)
#define  VTSS_X_HSIO_SERDES6G_DIG_CFG_SERDES6G_MISC_CFG_SEL_RECO_CLK(x)  VTSS_EXTRACT_BITFIELD(x,16,2)
#define  VTSS_F_HSIO_SERDES6G_DIG_CFG_SERDES6G_MISC_CFG_DES_100FX_CPMD_ENA  VTSS_BIT(8)
#define  VTSS_F_HSIO_SERDES6G_DIG_CFG_SERDES6G_MISC_CFG_RX_LPI_MODE_ENA  VTSS_BIT(5)
#define  VTSS_F_HSIO_SERDES6G_DIG_CFG_SERDES6G_MISC_CFG_TX_LPI_MODE_ENA  VTSS_BIT(4)
#define  VTSS_F_HSIO_SERDES6G_DIG_CFG_SERDES6G_MISC_CFG_RX_DATA_INV_ENA  VTSS_BIT(3)
#define  VTSS_F_HSIO_SERDES6G_DIG_CFG_SERDES6G_MISC_CFG_TX_DATA_INV_ENA  VTSS_BIT(2)
#define  VTSS_F_HSIO_SERDES6G_DIG_CFG_SERDES6G_MISC_CFG_LANE_RST  VTSS_BIT(0)

#define VTSS_HSIO_SERDES6G_DIG_CFG_SERDES6G_OB_ANEG_CFG  VTSS_IOREG(VTSS_TO_HSIO,0x2f)

#define VTSS_HSIO_SERDES6G_DIG_STATUS_SERDES6G_DFT_STATUS  VTSS_IOREG(VTSS_TO_HSIO,0x30)

#define VTSS_HSIO_MCB_SERDES6G_CFG_MCB_SERDES6G_ADDR_CFG  VTSS_IOREG(VTSS_TO_HSIO,0x31)
#define  VTSS_F_HSIO_MCB_SERDES6G_CFG_MCB_SERDES6G_ADDR_CFG_SERDES6G_WR_ONE_SHOT  VTSS_BIT(31)
#define  VTSS_F_HSIO_MCB_SERDES6G_CFG_MCB_SERDES6G_ADDR_CFG_SERDES6G_RD_ONE_SHOT  VTSS_BIT(30)
#define  VTSS_F_HSIO_MCB_SERDES6G_CFG_MCB_SERDES6G_ADDR_CFG_SERDES6G_ADDR(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_HSIO_MCB_SERDES6G_CFG_MCB_SERDES6G_ADDR_CFG_SERDES6G_ADDR     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_HSIO_MCB_SERDES6G_CFG_MCB_SERDES6G_ADDR_CFG_SERDES6G_ADDR(x)  VTSS_EXTRACT_BITFIELD(x,0,16)


#endif /* _VTSS_SERVAL_REGS_HSIO_H_ */
