#ifndef _VTSS_SERVAL_REGS_OAM_MEP_H_
#define _VTSS_SERVAL_REGS_OAM_MEP_H_

/*
 *
 * VCore-III Register Definitions
 *
 #####ECOSGPLCOPYRIGHTBEGIN#####
 -------------------------------------------
 This file is part of eCos, the Embedded Configurable Operating System.
 Copyright (C) 1998-2012 Free Software Foundation, Inc.

 eCos is free software; you can redistribute it and/or modify it under
 the terms of the GNU General Public License as published by the Free
 Software Foundation; either version 2 or (at your option) any later
 version.

 eCos is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 for more details.

 You should have received a copy of the GNU General Public License
 along with eCos; if not, write to the Free Software Foundation, Inc.,
 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

 As a special exception, if other files instantiate templates or use
 macros or inline functions from this file, or you compile this file
 and link it with other works to produce a work based on this file,
 this file does not by itself cause the resulting work to be covered by
 the GNU General Public License. However the source code for this file
 must still be made available in accordance with section (3) of the GNU
 General Public License v2.

 This exception does not invalidate any other reasons why a work based
 on this file might be covered by the GNU General Public License.
 -------------------------------------------
 #####ECOSGPLCOPYRIGHTEND#####
 */

#include "vtss_serval_regs_common.h"

#define VTSS_OAM_MEP_COMMON_MEP_CTRL         VTSS_IOREG(VTSS_TO_OAM_MEP,0x1800)
#define  VTSS_F_OAM_MEP_COMMON_MEP_CTRL_CCM_LM_UPD_RSV_ENA  VTSS_BIT(14)
#define  VTSS_F_OAM_MEP_COMMON_MEP_CTRL_LMR_UPD_RxFcL_ENA  VTSS_BIT(13)
#define  VTSS_F_OAM_MEP_COMMON_MEP_CTRL_CCM_SCAN_ENA  VTSS_BIT(1)
#define  VTSS_F_OAM_MEP_COMMON_MEP_CTRL_MEP_ENA  VTSS_BIT(0)
#define  VTSS_F_OAM_MEP_COMMON_MEP_CTRL_EXT_CPU_PORTMASK(x)  VTSS_ENCODE_BITFIELD(x,2,11)
#define  VTSS_M_OAM_MEP_COMMON_MEP_CTRL_EXT_CPU_PORTMASK     VTSS_ENCODE_BITMASK(2,11)
#define  VTSS_X_OAM_MEP_COMMON_MEP_CTRL_EXT_CPU_PORTMASK(x)  VTSS_EXTRACT_BITFIELD(x,2,11)

#define VTSS_OAM_MEP_COMMON_CPU_CFG          VTSS_IOREG(VTSS_TO_OAM_MEP,0x1801)
#define  VTSS_F_OAM_MEP_COMMON_CPU_CFG_DEF_EXT_PORT_ENA  VTSS_BIT(29)
#define  VTSS_F_OAM_MEP_COMMON_CPU_CFG_DEF_COPY_QU(x)  VTSS_ENCODE_BITFIELD(x,25,4)
#define  VTSS_M_OAM_MEP_COMMON_CPU_CFG_DEF_COPY_QU     VTSS_ENCODE_BITMASK(25,4)
#define  VTSS_X_OAM_MEP_COMMON_CPU_CFG_DEF_COPY_QU(x)  VTSS_EXTRACT_BITFIELD(x,25,4)
#define  VTSS_F_OAM_MEP_COMMON_CPU_CFG_CPU_ERR_EXT_PORT_ENA  VTSS_BIT(24)
#define  VTSS_F_OAM_MEP_COMMON_CPU_CFG_CPU_ERR_QU(x)  VTSS_ENCODE_BITFIELD(x,20,4)
#define  VTSS_M_OAM_MEP_COMMON_CPU_CFG_CPU_ERR_QU     VTSS_ENCODE_BITMASK(20,4)
#define  VTSS_X_OAM_MEP_COMMON_CPU_CFG_CPU_ERR_QU(x)  VTSS_EXTRACT_BITFIELD(x,20,4)
#define  VTSS_F_OAM_MEP_COMMON_CPU_CFG_DMR_EXT_PORT_ENA  VTSS_BIT(19)
#define  VTSS_F_OAM_MEP_COMMON_CPU_CFG_DMR_CPU_QU(x)  VTSS_ENCODE_BITFIELD(x,15,4)
#define  VTSS_M_OAM_MEP_COMMON_CPU_CFG_DMR_CPU_QU     VTSS_ENCODE_BITMASK(15,4)
#define  VTSS_X_OAM_MEP_COMMON_CPU_CFG_DMR_CPU_QU(x)  VTSS_EXTRACT_BITFIELD(x,15,4)
#define  VTSS_F_OAM_MEP_COMMON_CPU_CFG_LMR_EXT_PORT_ENA  VTSS_BIT(14)
#define  VTSS_F_OAM_MEP_COMMON_CPU_CFG_LMR_CPU_QU(x)  VTSS_ENCODE_BITFIELD(x,10,4)
#define  VTSS_M_OAM_MEP_COMMON_CPU_CFG_LMR_CPU_QU     VTSS_ENCODE_BITMASK(10,4)
#define  VTSS_X_OAM_MEP_COMMON_CPU_CFG_LMR_CPU_QU(x)  VTSS_EXTRACT_BITFIELD(x,10,4)
#define  VTSS_F_OAM_MEP_COMMON_CPU_CFG_LBR_EXT_PORT_ENA  VTSS_BIT(9)
#define  VTSS_F_OAM_MEP_COMMON_CPU_CFG_LBR_CPU_QU(x)  VTSS_ENCODE_BITFIELD(x,5,4)
#define  VTSS_M_OAM_MEP_COMMON_CPU_CFG_LBR_CPU_QU     VTSS_ENCODE_BITMASK(5,4)
#define  VTSS_X_OAM_MEP_COMMON_CPU_CFG_LBR_CPU_QU(x)  VTSS_EXTRACT_BITFIELD(x,5,4)
#define  VTSS_F_OAM_MEP_COMMON_CPU_CFG_CCM_LM_EXT_PORT_ENA  VTSS_BIT(4)
#define  VTSS_F_OAM_MEP_COMMON_CPU_CFG_CCM_LM_CPU_QU(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_OAM_MEP_COMMON_CPU_CFG_CCM_LM_CPU_QU     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_OAM_MEP_COMMON_CPU_CFG_CCM_LM_CPU_QU(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_OAM_MEP_COMMON_CPU_CFG_1        VTSS_IOREG(VTSS_TO_OAM_MEP,0x1802)
#define  VTSS_F_OAM_MEP_COMMON_CPU_CFG_1_LT_EXT_PORT_ENA  VTSS_BIT(24)
#define  VTSS_F_OAM_MEP_COMMON_CPU_CFG_1_LT_CPU_QU(x)  VTSS_ENCODE_BITFIELD(x,20,4)
#define  VTSS_M_OAM_MEP_COMMON_CPU_CFG_1_LT_CPU_QU     VTSS_ENCODE_BITMASK(20,4)
#define  VTSS_X_OAM_MEP_COMMON_CPU_CFG_1_LT_CPU_QU(x)  VTSS_EXTRACT_BITFIELD(x,20,4)
#define  VTSS_F_OAM_MEP_COMMON_CPU_CFG_1_DMM_EXT_PORT_ENA  VTSS_BIT(19)
#define  VTSS_F_OAM_MEP_COMMON_CPU_CFG_1_DMM_CPU_QU(x)  VTSS_ENCODE_BITFIELD(x,15,4)
#define  VTSS_M_OAM_MEP_COMMON_CPU_CFG_1_DMM_CPU_QU     VTSS_ENCODE_BITMASK(15,4)
#define  VTSS_X_OAM_MEP_COMMON_CPU_CFG_1_DMM_CPU_QU(x)  VTSS_EXTRACT_BITFIELD(x,15,4)
#define  VTSS_F_OAM_MEP_COMMON_CPU_CFG_1_LMM_EXT_PORT_ENA  VTSS_BIT(14)
#define  VTSS_F_OAM_MEP_COMMON_CPU_CFG_1_LMM_CPU_QU(x)  VTSS_ENCODE_BITFIELD(x,10,4)
#define  VTSS_M_OAM_MEP_COMMON_CPU_CFG_1_LMM_CPU_QU     VTSS_ENCODE_BITMASK(10,4)
#define  VTSS_X_OAM_MEP_COMMON_CPU_CFG_1_LMM_CPU_QU(x)  VTSS_EXTRACT_BITFIELD(x,10,4)
#define  VTSS_F_OAM_MEP_COMMON_CPU_CFG_1_LBM_EXT_PORT_ENA  VTSS_BIT(9)
#define  VTSS_F_OAM_MEP_COMMON_CPU_CFG_1_LBM_CPU_QU(x)  VTSS_ENCODE_BITFIELD(x,5,4)
#define  VTSS_M_OAM_MEP_COMMON_CPU_CFG_1_LBM_CPU_QU     VTSS_ENCODE_BITMASK(5,4)
#define  VTSS_X_OAM_MEP_COMMON_CPU_CFG_1_LBM_CPU_QU(x)  VTSS_EXTRACT_BITFIELD(x,5,4)
#define  VTSS_F_OAM_MEP_COMMON_CPU_CFG_1_CCM_EXT_PORT_ENA  VTSS_BIT(4)
#define  VTSS_F_OAM_MEP_COMMON_CPU_CFG_1_CCM_CPU_QU(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_OAM_MEP_COMMON_CPU_CFG_1_CCM_CPU_QU     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_OAM_MEP_COMMON_CPU_CFG_1_CCM_CPU_QU(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_OAM_MEP_COMMON_OAM_SDLB_CPU_COPY  VTSS_IOREG(VTSS_TO_OAM_MEP,0x1803)
#define  VTSS_F_OAM_MEP_COMMON_OAM_SDLB_CPU_COPY_OAM_SDLB_CPU_IDX(x)  VTSS_ENCODE_BITFIELD(x,0,10)
#define  VTSS_M_OAM_MEP_COMMON_OAM_SDLB_CPU_COPY_OAM_SDLB_CPU_IDX     VTSS_ENCODE_BITMASK(0,10)
#define  VTSS_X_OAM_MEP_COMMON_OAM_SDLB_CPU_COPY_OAM_SDLB_CPU_IDX(x)  VTSS_EXTRACT_BITFIELD(x,0,10)

#define VTSS_OAM_MEP_COMMON_OAM_GENERIC_CFG(ri)  VTSS_IOREG(VTSS_TO_OAM_MEP,0x1804 + (ri))
#define  VTSS_F_OAM_MEP_COMMON_OAM_GENERIC_CFG_GENERIC_OPCODE_EXT_PORT_ENA  VTSS_BIT(16)
#define  VTSS_F_OAM_MEP_COMMON_OAM_GENERIC_CFG_GENERIC_OPCODE_CPU_QU(x)  VTSS_ENCODE_BITFIELD(x,8,4)
#define  VTSS_M_OAM_MEP_COMMON_OAM_GENERIC_CFG_GENERIC_OPCODE_CPU_QU     VTSS_ENCODE_BITMASK(8,4)
#define  VTSS_X_OAM_MEP_COMMON_OAM_GENERIC_CFG_GENERIC_OPCODE_CPU_QU(x)  VTSS_EXTRACT_BITFIELD(x,8,4)
#define  VTSS_F_OAM_MEP_COMMON_OAM_GENERIC_CFG_GENERIC_OPCODE_VAL(x)  VTSS_ENCODE_BITFIELD(x,0,8)
#define  VTSS_M_OAM_MEP_COMMON_OAM_GENERIC_CFG_GENERIC_OPCODE_VAL     VTSS_ENCODE_BITMASK(0,8)
#define  VTSS_X_OAM_MEP_COMMON_OAM_GENERIC_CFG_GENERIC_OPCODE_VAL(x)  VTSS_EXTRACT_BITFIELD(x,0,8)
#define  VTSS_F_OAM_MEP_COMMON_OAM_GENERIC_CFG_GENERIC_DMAC_CHK_DIS  VTSS_BIT(17)

#define VTSS_OAM_MEP_COMMON_CCM_PERIOD_CFG(ri)  VTSS_IOREG(VTSS_TO_OAM_MEP,0x180c + (ri))

#define VTSS_OAM_MEP_COMMON_CCM_CTRL         VTSS_IOREG(VTSS_TO_OAM_MEP,0x1813)
#define  VTSS_F_OAM_MEP_COMMON_CCM_CTRL_CCM_BASE_TICK_CNT(x)  VTSS_ENCODE_BITFIELD(x,24,8)
#define  VTSS_M_OAM_MEP_COMMON_CCM_CTRL_CCM_BASE_TICK_CNT     VTSS_ENCODE_BITMASK(24,8)
#define  VTSS_X_OAM_MEP_COMMON_CCM_CTRL_CCM_BASE_TICK_CNT(x)  VTSS_EXTRACT_BITFIELD(x,24,8)
#define  VTSS_F_OAM_MEP_COMMON_CCM_CTRL_CCM_SPACE_BETWEEN_ENTRY_SCAN(x)  VTSS_ENCODE_BITFIELD(x,16,8)
#define  VTSS_M_OAM_MEP_COMMON_CCM_CTRL_CCM_SPACE_BETWEEN_ENTRY_SCAN     VTSS_ENCODE_BITMASK(16,8)
#define  VTSS_X_OAM_MEP_COMMON_CCM_CTRL_CCM_SPACE_BETWEEN_ENTRY_SCAN(x)  VTSS_EXTRACT_BITFIELD(x,16,8)
#define  VTSS_F_OAM_MEP_COMMON_CCM_CTRL_CCM_FORCE_HW_SCAN_ENA(x)  VTSS_ENCODE_BITFIELD(x,8,7)
#define  VTSS_M_OAM_MEP_COMMON_CCM_CTRL_CCM_FORCE_HW_SCAN_ENA     VTSS_ENCODE_BITMASK(8,7)
#define  VTSS_X_OAM_MEP_COMMON_CCM_CTRL_CCM_FORCE_HW_SCAN_ENA(x)  VTSS_EXTRACT_BITFIELD(x,8,7)
#define  VTSS_F_OAM_MEP_COMMON_CCM_CTRL_CCM_FORCE_HW_SCAN_STOP_ENA  VTSS_BIT(0)

#define VTSS_OAM_MEP_COMMON_CCM_SCAN_STICKY  VTSS_IOREG(VTSS_TO_OAM_MEP,0x1814)
#define  VTSS_F_OAM_MEP_COMMON_CCM_SCAN_STICKY_CCM_SCAN_ONGOING_STATUS(x)  VTSS_ENCODE_BITFIELD(x,24,7)
#define  VTSS_M_OAM_MEP_COMMON_CCM_SCAN_STICKY_CCM_SCAN_ONGOING_STATUS     VTSS_ENCODE_BITMASK(24,7)
#define  VTSS_X_OAM_MEP_COMMON_CCM_SCAN_STICKY_CCM_SCAN_ONGOING_STATUS(x)  VTSS_EXTRACT_BITFIELD(x,24,7)
#define  VTSS_F_OAM_MEP_COMMON_CCM_SCAN_STICKY_CCM_SCAN_COMPLETED_STICKY  VTSS_BIT(2)
#define  VTSS_F_OAM_MEP_COMMON_CCM_SCAN_STICKY_CCM_SCAN_STARTED_STICKY  VTSS_BIT(1)
#define  VTSS_F_OAM_MEP_COMMON_CCM_SCAN_STICKY_CCM_SCAN_START_DELAYED_STICKY  VTSS_BIT(0)

#define VTSS_OAM_MEP_COMMON_MASTER_INTR_CTRL  VTSS_IOREG(VTSS_TO_OAM_MEP,0x1815)
#define  VTSS_F_OAM_MEP_COMMON_MASTER_INTR_CTRL_OAM_MEP_INTR  VTSS_BIT(8)
#define  VTSS_F_OAM_MEP_COMMON_MASTER_INTR_CTRL_OAM_MEP_INTR_ENA  VTSS_BIT(25)

#define VTSS_OAM_MEP_COMMON_INTR(ri)         VTSS_IOREG(VTSS_TO_OAM_MEP,0x1816 + (ri))

#define VTSS_OAM_MEP_COMMON_VOE_CFG(ri)      VTSS_IOREG(VTSS_TO_OAM_MEP,0x1819 + (ri))
#define  VTSS_F_OAM_MEP_COMMON_VOE_CFG_UPMEP_VOE  VTSS_BIT(0)

#define VTSS_OAM_MEP_COMMON_UPMEP_LM_CNT_VLD(ri)  VTSS_IOREG(VTSS_TO_OAM_MEP,0x1859 + (ri))
#define  VTSS_F_OAM_MEP_COMMON_UPMEP_LM_CNT_VLD_CCM_LM_RX_CNT_VLD  VTSS_BIT(2)
#define  VTSS_F_OAM_MEP_COMMON_UPMEP_LM_CNT_VLD_LMM_RX_CNT_VLD  VTSS_BIT(1)
#define  VTSS_F_OAM_MEP_COMMON_UPMEP_LM_CNT_VLD_LMR_RX_CNT_VLD  VTSS_BIT(0)

#define VTSS_OAM_MEP_COMMON_VOE_MAP_CTRL(ri)  VTSS_IOREG(VTSS_TO_OAM_MEP,0x1899 + (ri))
#define  VTSS_F_OAM_MEP_COMMON_VOE_MAP_CTRL_PATH_VOEID(x)  VTSS_ENCODE_BITFIELD(x,7,6)
#define  VTSS_M_OAM_MEP_COMMON_VOE_MAP_CTRL_PATH_VOEID     VTSS_ENCODE_BITMASK(7,6)
#define  VTSS_X_OAM_MEP_COMMON_VOE_MAP_CTRL_PATH_VOEID(x)  VTSS_EXTRACT_BITFIELD(x,7,6)
#define  VTSS_F_OAM_MEP_COMMON_VOE_MAP_CTRL_PATH_VOEID_P(x)  VTSS_ENCODE_BITFIELD(x,1,6)
#define  VTSS_M_OAM_MEP_COMMON_VOE_MAP_CTRL_PATH_VOEID_P     VTSS_ENCODE_BITMASK(1,6)
#define  VTSS_X_OAM_MEP_COMMON_VOE_MAP_CTRL_PATH_VOEID_P(x)  VTSS_EXTRACT_BITFIELD(x,1,6)
#define  VTSS_F_OAM_MEP_COMMON_VOE_MAP_CTRL_PATH_VOEID_ENA  VTSS_BIT(0)

#define VTSS_OAM_MEP_COMMON_VOE_CNT_CTRL(ri)  VTSS_IOREG(VTSS_TO_OAM_MEP,0x18d9 + (ri))
#define  VTSS_F_OAM_MEP_COMMON_VOE_CNT_CTRL_CNT_YELLOW_ENA  VTSS_BIT(8)
#define  VTSS_F_OAM_MEP_COMMON_VOE_CNT_CTRL_PRIO_CNT_MASK(x)  VTSS_ENCODE_BITFIELD(x,0,8)
#define  VTSS_M_OAM_MEP_COMMON_VOE_CNT_CTRL_PRIO_CNT_MASK     VTSS_ENCODE_BITMASK(0,8)
#define  VTSS_X_OAM_MEP_COMMON_VOE_CNT_CTRL_PRIO_CNT_MASK(x)  VTSS_EXTRACT_BITFIELD(x,0,8)

#define VTSS_OAM_MEP_COMMON_COMMON_MEP_MC_MAC_LSB  VTSS_IOREG(VTSS_TO_OAM_MEP,0x1924)
#define  VTSS_F_OAM_MEP_COMMON_COMMON_MEP_MC_MAC_LSB_MEP_MC_MAC_LSB(x)  VTSS_ENCODE_BITFIELD(x,3,28)
#define  VTSS_M_OAM_MEP_COMMON_COMMON_MEP_MC_MAC_LSB_MEP_MC_MAC_LSB     VTSS_ENCODE_BITMASK(3,28)
#define  VTSS_X_OAM_MEP_COMMON_COMMON_MEP_MC_MAC_LSB_MEP_MC_MAC_LSB(x)  VTSS_EXTRACT_BITFIELD(x,3,28)

#define VTSS_OAM_MEP_COMMON_COMMON_MEP_MC_MAC_MSB  VTSS_IOREG(VTSS_TO_OAM_MEP,0x1925)
#define  VTSS_F_OAM_MEP_COMMON_COMMON_MEP_MC_MAC_MSB_MEP_MC_MAC_MSB(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_OAM_MEP_COMMON_COMMON_MEP_MC_MAC_MSB_MEP_MC_MAC_MSB     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_OAM_MEP_COMMON_COMMON_MEP_MC_MAC_MSB_MEP_MC_MAC_MSB(x)  VTSS_EXTRACT_BITFIELD(x,0,16)

#define VTSS_OAM_MEP_VOE_BASIC_CTRL(gi)      VTSS_IOREG_IX(VTSS_TO_OAM_MEP,0x0,gi,64,0,0)
#define  VTSS_F_OAM_MEP_VOE_BASIC_CTRL_MAC_ADDR_ERR_REDIR_ENA  VTSS_BIT(10)
#define  VTSS_F_OAM_MEP_VOE_BASIC_CTRL_RX_DMAC_CHK_SEL(x)  VTSS_ENCODE_BITFIELD(x,8,2)
#define  VTSS_M_OAM_MEP_VOE_BASIC_CTRL_RX_DMAC_CHK_SEL     VTSS_ENCODE_BITMASK(8,2)
#define  VTSS_X_OAM_MEP_VOE_BASIC_CTRL_RX_DMAC_CHK_SEL(x)  VTSS_EXTRACT_BITFIELD(x,8,2)
#define  VTSS_F_OAM_MEP_VOE_BASIC_CTRL_CPU_HITME_ONCE_CCM_TLV  VTSS_BIT(7)
#define  VTSS_F_OAM_MEP_VOE_BASIC_CTRL_CCM_ERR_CPU_HITME_ONCE  VTSS_BIT(6)
#define  VTSS_F_OAM_MEP_VOE_BASIC_CTRL_CCM_ERR_CPU_COPY_ENA  VTSS_BIT(5)
#define  VTSS_F_OAM_MEP_VOE_BASIC_CTRL_CCM_NXT_CPU_HITME_ONCE  VTSS_BIT(4)
#define  VTSS_F_OAM_MEP_VOE_BASIC_CTRL_MIP_UNICAST_ONLY_COPY_ENA  VTSS_BIT(3)
#define  VTSS_F_OAM_MEP_VOE_BASIC_CTRL_VOE_AS_MIP_ENA  VTSS_BIT(2)
#define  VTSS_F_OAM_MEP_VOE_BASIC_CTRL_VOE_ENA  VTSS_BIT(1)
#define  VTSS_F_OAM_MEP_VOE_BASIC_CTRL_UPMEP_KILL_ALL_RX  VTSS_BIT(0)

#define VTSS_OAM_MEP_VOE_MEL_CTRL(gi)        VTSS_IOREG_IX(VTSS_TO_OAM_MEP,0x0,gi,64,0,1)
#define  VTSS_F_OAM_MEP_VOE_MEL_CTRL_MEL_VAL(x)  VTSS_ENCODE_BITFIELD(x,17,3)
#define  VTSS_M_OAM_MEP_VOE_MEL_CTRL_MEL_VAL     VTSS_ENCODE_BITMASK(17,3)
#define  VTSS_X_OAM_MEP_VOE_MEL_CTRL_MEL_VAL(x)  VTSS_EXTRACT_BITFIELD(x,17,3)
#define  VTSS_F_OAM_MEP_VOE_MEL_CTRL_UPMEP_LB  VTSS_BIT(16)
#define  VTSS_F_OAM_MEP_VOE_MEL_CTRL_MEP_PORTMASK(x)  VTSS_ENCODE_BITFIELD(x,5,11)
#define  VTSS_M_OAM_MEP_VOE_MEL_CTRL_MEP_PORTMASK     VTSS_ENCODE_BITMASK(5,11)
#define  VTSS_X_OAM_MEP_VOE_MEL_CTRL_MEP_PORTMASK(x)  VTSS_EXTRACT_BITFIELD(x,5,11)
#define  VTSS_F_OAM_MEP_VOE_MEL_CTRL_CPU_HITME_ONCE_MEL_TOO_LOW  VTSS_BIT(3)
#define  VTSS_F_OAM_MEP_VOE_MEL_CTRL_CPU_COPY_MEL_TOO_LOW  VTSS_BIT(2)
#define  VTSS_F_OAM_MEP_VOE_MEL_CTRL_CPU_HITME_ONCE_CCM_MEL_TOO_LOW  VTSS_BIT(1)
#define  VTSS_F_OAM_MEP_VOE_MEL_CTRL_CPU_COPY_CCM_MEL_TOO_LOW  VTSS_BIT(0)

#define VTSS_OAM_MEP_VOE_OAM_CPU_COPY_CTRL(gi)  VTSS_IOREG_IX(VTSS_TO_OAM_MEP,0x0,gi,64,0,2)
#define  VTSS_F_OAM_MEP_VOE_OAM_CPU_COPY_CTRL_GENERIC_COPY_MASK(x)  VTSS_ENCODE_BITFIELD(x,12,8)
#define  VTSS_M_OAM_MEP_VOE_OAM_CPU_COPY_CTRL_GENERIC_COPY_MASK     VTSS_ENCODE_BITMASK(12,8)
#define  VTSS_X_OAM_MEP_VOE_OAM_CPU_COPY_CTRL_GENERIC_COPY_MASK(x)  VTSS_EXTRACT_BITFIELD(x,12,8)
#define  VTSS_F_OAM_MEP_VOE_OAM_CPU_COPY_CTRL_UNK_OPCODE_CPU_COPY_ENA  VTSS_BIT(11)
#define  VTSS_F_OAM_MEP_VOE_OAM_CPU_COPY_CTRL_LTM_CPU_COPY_ENA  VTSS_BIT(10)
#define  VTSS_F_OAM_MEP_VOE_OAM_CPU_COPY_CTRL_LTR_CPU_COPY_ENA  VTSS_BIT(9)
#define  VTSS_F_OAM_MEP_VOE_OAM_CPU_COPY_CTRL_LMM_CPU_COPY_ENA  VTSS_BIT(8)
#define  VTSS_F_OAM_MEP_VOE_OAM_CPU_COPY_CTRL_LMR_CPU_COPY_ENA  VTSS_BIT(7)
#define  VTSS_F_OAM_MEP_VOE_OAM_CPU_COPY_CTRL_LBM_CPU_COPY_ENA  VTSS_BIT(6)
#define  VTSS_F_OAM_MEP_VOE_OAM_CPU_COPY_CTRL_LBR_CPU_COPY_ENA  VTSS_BIT(5)
#define  VTSS_F_OAM_MEP_VOE_OAM_CPU_COPY_CTRL_DMM_CPU_COPY_ENA  VTSS_BIT(4)
#define  VTSS_F_OAM_MEP_VOE_OAM_CPU_COPY_CTRL_DMR_CPU_COPY_ENA  VTSS_BIT(3)
#define  VTSS_F_OAM_MEP_VOE_OAM_CPU_COPY_CTRL_SM_CPU_COPY_ENA  VTSS_BIT(2)
#define  VTSS_F_OAM_MEP_VOE_OAM_CPU_COPY_CTRL_CCM_CPU_COPY_ENA  VTSS_BIT(1)
#define  VTSS_F_OAM_MEP_VOE_OAM_CPU_COPY_CTRL_CCM_LM_CPU_COPY_ENA  VTSS_BIT(0)

#define VTSS_OAM_MEP_VOE_OAM_FWD_CTRL(gi)    VTSS_IOREG_IX(VTSS_TO_OAM_MEP,0x0,gi,64,0,3)
#define  VTSS_F_OAM_MEP_VOE_OAM_FWD_CTRL_GENERIC_FWD_MASK(x)  VTSS_ENCODE_BITFIELD(x,11,8)
#define  VTSS_M_OAM_MEP_VOE_OAM_FWD_CTRL_GENERIC_FWD_MASK     VTSS_ENCODE_BITMASK(11,8)
#define  VTSS_X_OAM_MEP_VOE_OAM_FWD_CTRL_GENERIC_FWD_MASK(x)  VTSS_EXTRACT_BITFIELD(x,11,8)
#define  VTSS_F_OAM_MEP_VOE_OAM_FWD_CTRL_LTM_FWD_ENA  VTSS_BIT(10)
#define  VTSS_F_OAM_MEP_VOE_OAM_FWD_CTRL_LTR_FWD_ENA  VTSS_BIT(9)
#define  VTSS_F_OAM_MEP_VOE_OAM_FWD_CTRL_LMM_FWD_ENA  VTSS_BIT(8)
#define  VTSS_F_OAM_MEP_VOE_OAM_FWD_CTRL_LMR_FWD_ENA  VTSS_BIT(7)
#define  VTSS_F_OAM_MEP_VOE_OAM_FWD_CTRL_LBM_FWD_ENA  VTSS_BIT(6)
#define  VTSS_F_OAM_MEP_VOE_OAM_FWD_CTRL_LBR_FWD_ENA  VTSS_BIT(5)
#define  VTSS_F_OAM_MEP_VOE_OAM_FWD_CTRL_DMM_FWD_ENA  VTSS_BIT(4)
#define  VTSS_F_OAM_MEP_VOE_OAM_FWD_CTRL_DMR_FWD_ENA  VTSS_BIT(3)
#define  VTSS_F_OAM_MEP_VOE_OAM_FWD_CTRL_SM_FWD_ENA  VTSS_BIT(2)
#define  VTSS_F_OAM_MEP_VOE_OAM_FWD_CTRL_CCM_FWD_ENA  VTSS_BIT(1)
#define  VTSS_F_OAM_MEP_VOE_OAM_FWD_CTRL_CCM_LM_FWD_ENA  VTSS_BIT(0)

#define VTSS_OAM_MEP_VOE_OAM_SDLB_CTRL(gi)   VTSS_IOREG_IX(VTSS_TO_OAM_MEP,0x0,gi,64,0,4)
#define  VTSS_F_OAM_MEP_VOE_OAM_SDLB_CTRL_OAM_SDLB_ENA  VTSS_BIT(10)
#define  VTSS_F_OAM_MEP_VOE_OAM_SDLB_CTRL_OAM_SDLB_IDX(x)  VTSS_ENCODE_BITFIELD(x,0,10)
#define  VTSS_M_OAM_MEP_VOE_OAM_SDLB_CTRL_OAM_SDLB_IDX     VTSS_ENCODE_BITMASK(0,10)
#define  VTSS_X_OAM_MEP_VOE_OAM_SDLB_CTRL_OAM_SDLB_IDX(x)  VTSS_EXTRACT_BITFIELD(x,0,10)

#define VTSS_OAM_MEP_VOE_OAM_CNT_OAM_CTRL(gi)  VTSS_IOREG_IX(VTSS_TO_OAM_MEP,0x0,gi,64,0,5)
#define  VTSS_F_OAM_MEP_VOE_OAM_CNT_OAM_CTRL_GENERIC_OAM_CNT_MASK(x)  VTSS_ENCODE_BITFIELD(x,12,8)
#define  VTSS_M_OAM_MEP_VOE_OAM_CNT_OAM_CTRL_GENERIC_OAM_CNT_MASK     VTSS_ENCODE_BITMASK(12,8)
#define  VTSS_X_OAM_MEP_VOE_OAM_CNT_OAM_CTRL_GENERIC_OAM_CNT_MASK(x)  VTSS_EXTRACT_BITFIELD(x,12,8)
#define  VTSS_F_OAM_MEP_VOE_OAM_CNT_OAM_CTRL_UNK_OPCODE_OAM_CNT_ENA  VTSS_BIT(11)
#define  VTSS_F_OAM_MEP_VOE_OAM_CNT_OAM_CTRL_LTM_OAM_CNT_ENA  VTSS_BIT(10)
#define  VTSS_F_OAM_MEP_VOE_OAM_CNT_OAM_CTRL_LTR_OAM_CNT_ENA  VTSS_BIT(9)
#define  VTSS_F_OAM_MEP_VOE_OAM_CNT_OAM_CTRL_LMM_OAM_CNT_ENA  VTSS_BIT(8)
#define  VTSS_F_OAM_MEP_VOE_OAM_CNT_OAM_CTRL_LMR_OAM_CNT_ENA  VTSS_BIT(7)
#define  VTSS_F_OAM_MEP_VOE_OAM_CNT_OAM_CTRL_LBM_OAM_CNT_ENA  VTSS_BIT(6)
#define  VTSS_F_OAM_MEP_VOE_OAM_CNT_OAM_CTRL_LBR_OAM_CNT_ENA  VTSS_BIT(5)
#define  VTSS_F_OAM_MEP_VOE_OAM_CNT_OAM_CTRL_DMM_OAM_CNT_ENA  VTSS_BIT(4)
#define  VTSS_F_OAM_MEP_VOE_OAM_CNT_OAM_CTRL_DMR_OAM_CNT_ENA  VTSS_BIT(3)
#define  VTSS_F_OAM_MEP_VOE_OAM_CNT_OAM_CTRL_SM_OAM_CNT_ENA  VTSS_BIT(2)
#define  VTSS_F_OAM_MEP_VOE_OAM_CNT_OAM_CTRL_CCM_OAM_CNT_ENA  VTSS_BIT(1)
#define  VTSS_F_OAM_MEP_VOE_OAM_CNT_OAM_CTRL_CCM_LM_OAM_CNT_ENA  VTSS_BIT(0)

#define VTSS_OAM_MEP_VOE_OAM_CNT_DATA_CTRL(gi)  VTSS_IOREG_IX(VTSS_TO_OAM_MEP,0x0,gi,64,0,6)
#define  VTSS_F_OAM_MEP_VOE_OAM_CNT_DATA_CTRL_GENERIC_DATA_CNT_MASK(x)  VTSS_ENCODE_BITFIELD(x,11,8)
#define  VTSS_M_OAM_MEP_VOE_OAM_CNT_DATA_CTRL_GENERIC_DATA_CNT_MASK     VTSS_ENCODE_BITMASK(11,8)
#define  VTSS_X_OAM_MEP_VOE_OAM_CNT_DATA_CTRL_GENERIC_DATA_CNT_MASK(x)  VTSS_EXTRACT_BITFIELD(x,11,8)
#define  VTSS_F_OAM_MEP_VOE_OAM_CNT_DATA_CTRL_UNK_OPCODE_DATA_CNT_ENA  VTSS_BIT(10)
#define  VTSS_F_OAM_MEP_VOE_OAM_CNT_DATA_CTRL_LTM_DATA_CNT_ENA  VTSS_BIT(9)
#define  VTSS_F_OAM_MEP_VOE_OAM_CNT_DATA_CTRL_LTR_DATA_CNT_ENA  VTSS_BIT(8)
#define  VTSS_F_OAM_MEP_VOE_OAM_CNT_DATA_CTRL_LMM_DATA_CNT_ENA  VTSS_BIT(7)
#define  VTSS_F_OAM_MEP_VOE_OAM_CNT_DATA_CTRL_LMR_DATA_CNT_ENA  VTSS_BIT(6)
#define  VTSS_F_OAM_MEP_VOE_OAM_CNT_DATA_CTRL_LBM_DATA_CNT_ENA  VTSS_BIT(5)
#define  VTSS_F_OAM_MEP_VOE_OAM_CNT_DATA_CTRL_LBR_DATA_CNT_ENA  VTSS_BIT(4)
#define  VTSS_F_OAM_MEP_VOE_OAM_CNT_DATA_CTRL_DMM_DATA_CNT_ENA  VTSS_BIT(3)
#define  VTSS_F_OAM_MEP_VOE_OAM_CNT_DATA_CTRL_DMR_DATA_CNT_ENA  VTSS_BIT(2)
#define  VTSS_F_OAM_MEP_VOE_OAM_CNT_DATA_CTRL_SM_DATA_CNT_ENA  VTSS_BIT(1)
#define  VTSS_F_OAM_MEP_VOE_OAM_CNT_DATA_CTRL_CCM_DATA_CNT_ENA  VTSS_BIT(0)

#define VTSS_OAM_MEP_VOE_MEP_UC_MAC_LSB(gi)  VTSS_IOREG_IX(VTSS_TO_OAM_MEP,0x0,gi,64,0,7)

#define VTSS_OAM_MEP_VOE_MEP_UC_MAC_MSB(gi)  VTSS_IOREG_IX(VTSS_TO_OAM_MEP,0x0,gi,64,0,8)
#define  VTSS_F_OAM_MEP_VOE_MEP_UC_MAC_MSB_MEP_UC_MAC_MSB(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_OAM_MEP_VOE_MEP_UC_MAC_MSB_MEP_UC_MAC_MSB     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_OAM_MEP_VOE_MEP_UC_MAC_MSB_MEP_UC_MAC_MSB(x)  VTSS_EXTRACT_BITFIELD(x,0,16)

#define VTSS_OAM_MEP_VOE_OAM_HW_CTRL(gi)     VTSS_IOREG_IX(VTSS_TO_OAM_MEP,0x0,gi,64,0,9)
#define  VTSS_F_OAM_MEP_VOE_OAM_HW_CTRL_LMM_ENA  VTSS_BIT(8)
#define  VTSS_F_OAM_MEP_VOE_OAM_HW_CTRL_LMR_ENA  VTSS_BIT(7)
#define  VTSS_F_OAM_MEP_VOE_OAM_HW_CTRL_LBM_ENA  VTSS_BIT(6)
#define  VTSS_F_OAM_MEP_VOE_OAM_HW_CTRL_LBR_ENA  VTSS_BIT(5)
#define  VTSS_F_OAM_MEP_VOE_OAM_HW_CTRL_DMM_ENA  VTSS_BIT(4)
#define  VTSS_F_OAM_MEP_VOE_OAM_HW_CTRL_DMR_ENA  VTSS_BIT(3)
#define  VTSS_F_OAM_MEP_VOE_OAM_HW_CTRL_SDM_ENA  VTSS_BIT(2)
#define  VTSS_F_OAM_MEP_VOE_OAM_HW_CTRL_CCM_ENA  VTSS_BIT(1)
#define  VTSS_F_OAM_MEP_VOE_OAM_HW_CTRL_CCM_LM_ENA  VTSS_BIT(0)

#define VTSS_OAM_MEP_VOE_LOOPBACK_CTRL(gi)   VTSS_IOREG_IX(VTSS_TO_OAM_MEP,0x0,gi,64,0,10)
#define  VTSS_F_OAM_MEP_VOE_LOOPBACK_CTRL_LB_LMM_ENA  VTSS_BIT(25)
#define  VTSS_F_OAM_MEP_VOE_LOOPBACK_CTRL_LB_DMM_ENA  VTSS_BIT(24)
#define  VTSS_F_OAM_MEP_VOE_LOOPBACK_CTRL_LB_ISDX(x)  VTSS_ENCODE_BITFIELD(x,14,10)
#define  VTSS_M_OAM_MEP_VOE_LOOPBACK_CTRL_LB_ISDX     VTSS_ENCODE_BITMASK(14,10)
#define  VTSS_X_OAM_MEP_VOE_LOOPBACK_CTRL_LB_ISDX(x)  VTSS_EXTRACT_BITFIELD(x,14,10)
#define  VTSS_F_OAM_MEP_VOE_LOOPBACK_CTRL_LB_ISDX_P(x)  VTSS_ENCODE_BITFIELD(x,4,10)
#define  VTSS_M_OAM_MEP_VOE_LOOPBACK_CTRL_LB_ISDX_P     VTSS_ENCODE_BITMASK(4,10)
#define  VTSS_X_OAM_MEP_VOE_LOOPBACK_CTRL_LB_ISDX_P(x)  VTSS_EXTRACT_BITFIELD(x,4,10)
#define  VTSS_F_OAM_MEP_VOE_LOOPBACK_CTRL_LB_PORTNUM_P(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_OAM_MEP_VOE_LOOPBACK_CTRL_LB_PORTNUM_P     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_OAM_MEP_VOE_LOOPBACK_CTRL_LB_PORTNUM_P(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_OAM_MEP_VOE_LBR_RX_FRM_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_OAM_MEP,0x0,gi,64,0,11)

#define VTSS_OAM_MEP_VOE_LBR_RX_TRANSID_CFG(gi)  VTSS_IOREG_IX(VTSS_TO_OAM_MEP,0x0,gi,64,0,12)

#define VTSS_OAM_MEP_VOE_LBM_TX_TRANSID_UPDATE(gi)  VTSS_IOREG_IX(VTSS_TO_OAM_MEP,0x0,gi,64,0,13)
#define  VTSS_F_OAM_MEP_VOE_LBM_TX_TRANSID_UPDATE_LBM_TRANSID_UPDATE_ENA  VTSS_BIT(0)

#define VTSS_OAM_MEP_VOE_LBM_TX_TRANSID_CFG(gi)  VTSS_IOREG_IX(VTSS_TO_OAM_MEP,0x0,gi,64,0,14)

#define VTSS_OAM_MEP_VOE_CCM_CFG(gi)         VTSS_IOREG_IX(VTSS_TO_OAM_MEP,0x0,gi,64,0,15)
#define  VTSS_F_OAM_MEP_VOE_CCM_CFG_CCM_LM_PERIOD(x)  VTSS_ENCODE_BITFIELD(x,24,3)
#define  VTSS_M_OAM_MEP_VOE_CCM_CFG_CCM_LM_PERIOD     VTSS_ENCODE_BITMASK(24,3)
#define  VTSS_X_OAM_MEP_VOE_CCM_CFG_CCM_LM_PERIOD(x)  VTSS_EXTRACT_BITFIELD(x,24,3)
#define  VTSS_F_OAM_MEP_VOE_CCM_CFG_CCM_LM_INSERT_NXT  VTSS_BIT(23)
#define  VTSS_F_OAM_MEP_VOE_CCM_CFG_CCM_SEQ_INCR_ENA  VTSS_BIT(22)
#define  VTSS_F_OAM_MEP_VOE_CCM_CFG_CCM_SEQ_UPD_ENA  VTSS_BIT(21)
#define  VTSS_F_OAM_MEP_VOE_CCM_CFG_CCM_RX_SEQ_CHK_ENA  VTSS_BIT(20)
#define  VTSS_F_OAM_MEP_VOE_CCM_CFG_CCM_TX_RDI  VTSS_BIT(19)
#define  VTSS_F_OAM_MEP_VOE_CCM_CFG_CCM_MISS_CNT(x)  VTSS_ENCODE_BITFIELD(x,16,3)
#define  VTSS_M_OAM_MEP_VOE_CCM_CFG_CCM_MISS_CNT     VTSS_ENCODE_BITMASK(16,3)
#define  VTSS_X_OAM_MEP_VOE_CCM_CFG_CCM_MISS_CNT(x)  VTSS_EXTRACT_BITFIELD(x,16,3)
#define  VTSS_F_OAM_MEP_VOE_CCM_CFG_CCM_PRIO(x)  VTSS_ENCODE_BITFIELD(x,13,3)
#define  VTSS_M_OAM_MEP_VOE_CCM_CFG_CCM_PRIO     VTSS_ENCODE_BITMASK(13,3)
#define  VTSS_X_OAM_MEP_VOE_CCM_CFG_CCM_PRIO(x)  VTSS_EXTRACT_BITFIELD(x,13,3)
#define  VTSS_F_OAM_MEP_VOE_CCM_CFG_CCM_PERIOD(x)  VTSS_ENCODE_BITFIELD(x,10,3)
#define  VTSS_M_OAM_MEP_VOE_CCM_CFG_CCM_PERIOD     VTSS_ENCODE_BITMASK(10,3)
#define  VTSS_X_OAM_MEP_VOE_CCM_CFG_CCM_PERIOD(x)  VTSS_EXTRACT_BITFIELD(x,10,3)
#define  VTSS_F_OAM_MEP_VOE_CCM_CFG_CCM_MEGID_CHK_ENA  VTSS_BIT(9)
#define  VTSS_F_OAM_MEP_VOE_CCM_CFG_CCM_MEPID_CHK_ENA  VTSS_BIT(8)
#define  VTSS_F_OAM_MEP_VOE_CCM_CFG_CCM_PERIOD_ERR  VTSS_BIT(7)
#define  VTSS_F_OAM_MEP_VOE_CCM_CFG_CCM_PRIO_ERR  VTSS_BIT(6)
#define  VTSS_F_OAM_MEP_VOE_CCM_CFG_CCM_ZERO_PERIOD_ERR  VTSS_BIT(5)
#define  VTSS_F_OAM_MEP_VOE_CCM_CFG_CCM_RX_RDI  VTSS_BIT(4)
#define  VTSS_F_OAM_MEP_VOE_CCM_CFG_CCM_LOC_DEFECT  VTSS_BIT(3)
#define  VTSS_F_OAM_MEP_VOE_CCM_CFG_CCM_MEPID_ERR  VTSS_BIT(2)
#define  VTSS_F_OAM_MEP_VOE_CCM_CFG_CCM_MEGID_ERR  VTSS_BIT(1)
#define  VTSS_F_OAM_MEP_VOE_CCM_CFG_OAM_MEL_ERR  VTSS_BIT(0)

#define VTSS_OAM_MEP_VOE_CCM_RX_VLD_FC_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_OAM_MEP,0x0,gi,64,0,16)

#define VTSS_OAM_MEP_VOE_CCM_RX_INVLD_FC_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_OAM_MEP,0x0,gi,64,0,17)

#define VTSS_OAM_MEP_VOE_CCM_CAP_TX_FCf(gi)  VTSS_IOREG_IX(VTSS_TO_OAM_MEP,0x0,gi,64,0,18)

#define VTSS_OAM_MEP_VOE_CCM_CAP_RX_FCl(gi)  VTSS_IOREG_IX(VTSS_TO_OAM_MEP,0x0,gi,64,0,19)

#define VTSS_OAM_MEP_VOE_UPMEP_LMR_RX_LM_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_OAM_MEP,0x0,gi,64,0,20)

#define VTSS_OAM_MEP_VOE_CCM_TX_SEQ_CFG(gi)  VTSS_IOREG_IX(VTSS_TO_OAM_MEP,0x0,gi,64,0,21)

#define VTSS_OAM_MEP_VOE_CCM_RX_SEQ_CFG(gi)  VTSS_IOREG_IX(VTSS_TO_OAM_MEP,0x0,gi,64,0,22)

#define VTSS_OAM_MEP_VOE_CCM_MEPID_CFG(gi)   VTSS_IOREG_IX(VTSS_TO_OAM_MEP,0x0,gi,64,0,23)
#define  VTSS_F_OAM_MEP_VOE_CCM_MEPID_CFG_CCM_MEPID(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_OAM_MEP_VOE_CCM_MEPID_CFG_CCM_MEPID     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_OAM_MEP_VOE_CCM_MEPID_CFG_CCM_MEPID(x)  VTSS_EXTRACT_BITFIELD(x,0,16)

#define VTSS_OAM_MEP_VOE_CCM_MEGID_CFG(gi,ri)  VTSS_IOREG_IX(VTSS_TO_OAM_MEP,0x0,gi,64,ri,24)

#define VTSS_OAM_MEP_VOE_OAM_RX_STICKY(gi)   VTSS_IOREG_IX(VTSS_TO_OAM_MEP,0x0,gi,64,0,36)
#define  VTSS_F_OAM_MEP_VOE_OAM_RX_STICKY_GENERIC_RX_STICKY_MASK(x)  VTSS_ENCODE_BITFIELD(x,17,8)
#define  VTSS_M_OAM_MEP_VOE_OAM_RX_STICKY_GENERIC_RX_STICKY_MASK     VTSS_ENCODE_BITMASK(17,8)
#define  VTSS_X_OAM_MEP_VOE_OAM_RX_STICKY_GENERIC_RX_STICKY_MASK(x)  VTSS_EXTRACT_BITFIELD(x,17,8)
#define  VTSS_F_OAM_MEP_VOE_OAM_RX_STICKY_UNK_OPCODE_RX_STICKY  VTSS_BIT(16)
#define  VTSS_F_OAM_MEP_VOE_OAM_RX_STICKY_LTM_RX_STICKY  VTSS_BIT(15)
#define  VTSS_F_OAM_MEP_VOE_OAM_RX_STICKY_LTR_RX_STICKY  VTSS_BIT(14)
#define  VTSS_F_OAM_MEP_VOE_OAM_RX_STICKY_LMM_RX_STICKY  VTSS_BIT(13)
#define  VTSS_F_OAM_MEP_VOE_OAM_RX_STICKY_LMR_RX_STICKY  VTSS_BIT(12)
#define  VTSS_F_OAM_MEP_VOE_OAM_RX_STICKY_LBM_RX_STICKY  VTSS_BIT(11)
#define  VTSS_F_OAM_MEP_VOE_OAM_RX_STICKY_LBR_RX_STICKY  VTSS_BIT(10)
#define  VTSS_F_OAM_MEP_VOE_OAM_RX_STICKY_DMM_RX_STICKY  VTSS_BIT(9)
#define  VTSS_F_OAM_MEP_VOE_OAM_RX_STICKY_DMR_RX_STICKY  VTSS_BIT(8)
#define  VTSS_F_OAM_MEP_VOE_OAM_RX_STICKY_SM_RX_STICKY  VTSS_BIT(7)
#define  VTSS_F_OAM_MEP_VOE_OAM_RX_STICKY_CCM_RX_STICKY  VTSS_BIT(6)
#define  VTSS_F_OAM_MEP_VOE_OAM_RX_STICKY_CCM_LM_RX_STICKY  VTSS_BIT(5)
#define  VTSS_F_OAM_MEP_VOE_OAM_RX_STICKY_LBR_TRANSID_ERR_STICKY  VTSS_BIT(4)
#define  VTSS_F_OAM_MEP_VOE_OAM_RX_STICKY_CCM_RX_SEQ_ERR_STICKY  VTSS_BIT(3)
#define  VTSS_F_OAM_MEP_VOE_OAM_RX_STICKY_OAM_AS_DATA_STICKY  VTSS_BIT(2)
#define  VTSS_F_OAM_MEP_VOE_OAM_RX_STICKY_MEP_EGR_BLOCK_STICKY  VTSS_BIT(1)
#define  VTSS_F_OAM_MEP_VOE_OAM_RX_STICKY_MAC_ADDR_ERR_STICKY  VTSS_BIT(0)

#define VTSS_OAM_MEP_VOE_STICKY(gi)          VTSS_IOREG_IX(VTSS_TO_OAM_MEP,0x0,gi,64,0,37)
#define  VTSS_F_OAM_MEP_VOE_STICKY_CCM_PERIOD_STICKY  VTSS_BIT(7)
#define  VTSS_F_OAM_MEP_VOE_STICKY_CCM_PRIO_STICKY  VTSS_BIT(6)
#define  VTSS_F_OAM_MEP_VOE_STICKY_CCM_ZERO_PERIOD_STICKY  VTSS_BIT(5)
#define  VTSS_F_OAM_MEP_VOE_STICKY_CCM_RX_RDI_STICKY  VTSS_BIT(4)
#define  VTSS_F_OAM_MEP_VOE_STICKY_CCM_LOC_STICKY  VTSS_BIT(3)
#define  VTSS_F_OAM_MEP_VOE_STICKY_CCM_MEPID_STICKY  VTSS_BIT(2)
#define  VTSS_F_OAM_MEP_VOE_STICKY_CCM_MEGID_STICKY  VTSS_BIT(1)
#define  VTSS_F_OAM_MEP_VOE_STICKY_OAM_MEL_STICKY  VTSS_BIT(0)

#define VTSS_OAM_MEP_VOE_UPMEP_LM_CNT_STICKY(gi)  VTSS_IOREG_IX(VTSS_TO_OAM_MEP,0x0,gi,64,0,38)
#define  VTSS_F_OAM_MEP_VOE_UPMEP_LM_CNT_STICKY_CCM_LM_RX_CNT_STICKY  VTSS_BIT(2)
#define  VTSS_F_OAM_MEP_VOE_UPMEP_LM_CNT_STICKY_LMM_RX_CNT_STICKY  VTSS_BIT(1)
#define  VTSS_F_OAM_MEP_VOE_UPMEP_LM_CNT_STICKY_LMR_RX_CNT_STICKY  VTSS_BIT(0)

#define VTSS_OAM_MEP_VOE_INTR_ENA(gi)        VTSS_IOREG_IX(VTSS_TO_OAM_MEP,0x0,gi,64,0,39)
#define  VTSS_F_OAM_MEP_VOE_INTR_ENA_CCM_PERIOD_INTR_ENA  VTSS_BIT(7)
#define  VTSS_F_OAM_MEP_VOE_INTR_ENA_CCM_PRIO_INTR_ENA  VTSS_BIT(6)
#define  VTSS_F_OAM_MEP_VOE_INTR_ENA_CCM_ZERO_PERIOD_INTR_ENA  VTSS_BIT(5)
#define  VTSS_F_OAM_MEP_VOE_INTR_ENA_CCM_RX_RDI_INTR_ENA  VTSS_BIT(4)
#define  VTSS_F_OAM_MEP_VOE_INTR_ENA_CCM_LOC_INTR_ENA  VTSS_BIT(3)
#define  VTSS_F_OAM_MEP_VOE_INTR_ENA_CCM_MEPID_INTR_ENA  VTSS_BIT(2)
#define  VTSS_F_OAM_MEP_VOE_INTR_ENA_CCM_MEGID_INTR_ENA  VTSS_BIT(1)
#define  VTSS_F_OAM_MEP_VOE_INTR_ENA_OAM_MEL_INTR_ENA  VTSS_BIT(0)

#define VTSS_OAM_MEP_VOE_RX_SEL_OAM_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_OAM_MEP,0x0,gi,64,0,40)

#define VTSS_OAM_MEP_VOE_RX_OAM_FRM_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_OAM_MEP,0x0,gi,64,0,41)

#define VTSS_OAM_MEP_VOE_TX_SEL_OAM_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_OAM_MEP,0x0,gi,64,0,42)

#define VTSS_OAM_MEP_VOE_TX_OAM_FRM_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_OAM_MEP,0x0,gi,64,0,43)

#define VTSS_OAM_MEP_PORT_PM_PORT_RX_FRM_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_OAM_MEP,0x1300,gi,2,0,0)

#define VTSS_OAM_MEP_PORT_PM_PORT_TX_FRM_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_OAM_MEP,0x1300,gi,2,0,1)

#define VTSS_OAM_MEP_RX_VOE_PM_MEP_RX_FRM_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_OAM_MEP,0x1400,gi,1,0,0)

#define VTSS_OAM_MEP_TX_VOE_PM_MEP_TX_FRM_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_OAM_MEP,0x1600,gi,1,0,0)


#endif /* _VTSS_SERVAL_REGS_OAM_MEP_H_ */
