#ifndef _VTSS_JAGUAR2_REGS_XFI_SHELL_H_
#define _VTSS_JAGUAR2_REGS_XFI_SHELL_H_

/*
 *
 * VCore-III Register Definitions
 *
 * Copyright (C) 2012 Vitesse Semiconductor Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#include "vtss_jaguar2_regs_common.h"

#define VTSS_XFI_SHELL_XFI_CONTROL_KR_CONTROL(target)  VTSS_IOREG(target,0x0)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_KR_CONTROL_KR_RATE(x)  VTSS_ENCODE_BITFIELD(x,17,2)
#define  VTSS_M_XFI_SHELL_XFI_CONTROL_KR_CONTROL_KR_RATE     VTSS_ENCODE_BITMASK(17,2)
#define  VTSS_X_XFI_SHELL_XFI_CONTROL_KR_CONTROL_KR_RATE(x)  VTSS_EXTRACT_BITFIELD(x,17,2)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_KR_CONTROL_KR_FEC_ENABLE  VTSS_BIT(16)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_KR_CONTROL_KR_INT_MASK  VTSS_BIT(15)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_KR_CONTROL_KR_INT_POL  VTSS_BIT(14)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_KR_CONTROL_KR_RATE_INT_MASK  VTSS_BIT(13)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_KR_CONTROL_KR_FEC_INT_MASK  VTSS_BIT(12)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_KR_CONTROL_KR_MODE_INT_MASK  VTSS_BIT(11)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_KR_CONTROL_KR_ANEG_RATE_STICKY  VTSS_BIT(10)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_KR_CONTROL_KR_ANEG_FEC_STICKY  VTSS_BIT(9)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_KR_CONTROL_KR_ANEG_10G_STICKY  VTSS_BIT(8)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_KR_CONTROL_KR_ANEG_TX10G_STICKY  VTSS_BIT(7)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_KR_CONTROL_KR_ANEG_RX10G_STICKY  VTSS_BIT(6)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_KR_CONTROL_KR_ANEG_3G_STICKY  VTSS_BIT(5)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_KR_CONTROL_KR_ANEG_TX3G_STICKY  VTSS_BIT(4)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_KR_CONTROL_KR_ANEG_RX3G_STICKY  VTSS_BIT(3)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_KR_CONTROL_KR_ANEG_1G_STICKY  VTSS_BIT(2)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_KR_CONTROL_KR_ANEG_TX1G_STICKY  VTSS_BIT(1)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_KR_CONTROL_KR_ANEG_RX1G_STICKY  VTSS_BIT(0)

#define VTSS_XFI_SHELL_XFI_CONTROL_XFI_MODE(target)  VTSS_IOREG(target,0x1)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_XFI_MODE_DES_100FX_PHASE_SEL  VTSS_BIT(31)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_XFI_MODE_EXT_SYNC_CTRL_SEL(x)  VTSS_ENCODE_BITFIELD(x,27,4)
#define  VTSS_M_XFI_SHELL_XFI_CONTROL_XFI_MODE_EXT_SYNC_CTRL_SEL     VTSS_ENCODE_BITMASK(27,4)
#define  VTSS_X_XFI_SHELL_XFI_CONTROL_XFI_MODE_EXT_SYNC_CTRL_SEL(x)  VTSS_EXTRACT_BITFIELD(x,27,4)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_XFI_MODE_FX100_ENA  VTSS_BIT(26)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_XFI_MODE_FX100_MODE  VTSS_BIT(25)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_XFI_MODE_FX100_KICK_MODE(x)  VTSS_ENCODE_BITFIELD(x,23,2)
#define  VTSS_M_XFI_SHELL_XFI_CONTROL_XFI_MODE_FX100_KICK_MODE     VTSS_ENCODE_BITMASK(23,2)
#define  VTSS_X_XFI_SHELL_XFI_CONTROL_XFI_MODE_FX100_KICK_MODE(x)  VTSS_EXTRACT_BITFIELD(x,23,2)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_XFI_MODE_FX100_SWAP_CP_MD  VTSS_BIT(22)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_XFI_MODE_PORT_SEL  VTSS_BIT(21)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_XFI_MODE_TX_USE_FIFO  VTSS_BIT(20)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_XFI_MODE_SPI_CLK_DIV(x)  VTSS_ENCODE_BITFIELD(x,16,4)
#define  VTSS_M_XFI_SHELL_XFI_CONTROL_XFI_MODE_SPI_CLK_DIV     VTSS_ENCODE_BITMASK(16,4)
#define  VTSS_X_XFI_SHELL_XFI_CONTROL_XFI_MODE_SPI_CLK_DIV(x)  VTSS_EXTRACT_BITFIELD(x,16,4)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_XFI_MODE_RX_INVERT  VTSS_BIT(9)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_XFI_MODE_TX_INVERT  VTSS_BIT(8)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_XFI_MODE_SEL_LINELB  VTSS_BIT(6)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_XFI_MODE_TXF_ERR_MODE  VTSS_BIT(5)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_XFI_MODE_ENDIAN  VTSS_BIT(4)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_XFI_MODE_TX_AUTORESYNC  VTSS_BIT(3)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_XFI_MODE_TX_RESYNC_SHOT  VTSS_BIT(2)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_XFI_MODE_SW_ENA  VTSS_BIT(1)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_XFI_MODE_SW_RST  VTSS_BIT(0)

#define VTSS_XFI_SHELL_XFI_CONTROL_XFI_STATUS(target)  VTSS_IOREG(target,0x2)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_XFI_STATUS_RECEIVER_DETECT_STATUS  VTSS_BIT(24)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_XFI_STATUS_SSF_STATUS  VTSS_BIT(20)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_XFI_STATUS_ANEG_KR_INT_STATUS  VTSS_BIT(18)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_XFI_STATUS_ANEG_ACTIVE_STATUS  VTSS_BIT(16)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_XFI_STATUS_XFIINT_STATUS  VTSS_BIT(0)

#define VTSS_XFI_SHELL_XFI_CONTROL_INT_CTRL(target)  VTSS_IOREG(target,0x3)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_INT_CTRL_TX_PLL_LOCK_INV  VTSS_BIT(31)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_INT_CTRL_TX_PLL_LOCK_MASK  VTSS_BIT(30)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_INT_CTRL_RX_PLL_LOCK_INV  VTSS_BIT(29)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_INT_CTRL_RX_PLL_LOCK_MASK  VTSS_BIT(28)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_INT_CTRL_RXSIGDET_INV  VTSS_BIT(27)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_INT_CTRL_RXSIGDET_MASK  VTSS_BIT(26)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_INT_CTRL_RX_LOS_INV  VTSS_BIT(25)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_INT_CTRL_RX_LOS_MASK  VTSS_BIT(24)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_INT_CTRL_SSF_MASK  VTSS_BIT(20)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_INT_CTRL_ANEG_KR_INT_MASK  VTSS_BIT(18)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_INT_CTRL_ANEG_ACTIVE_MASK  VTSS_BIT(16)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_INT_CTRL_XFI_MASK  VTSS_BIT(0)

#define VTSS_XFI_SHELL_XFI_CONTROL_SSF_HYST_ENA_CTRL(target)  VTSS_IOREG(target,0x4)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_SSF_HYST_ENA_CTRL_SSF_HYST_ENA  VTSS_BIT(0)

#define VTSS_XFI_SHELL_XFI_CONTROL_SSF_HYST_TIMING_CTRL(target)  VTSS_IOREG(target,0x5)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_SSF_HYST_TIMING_CTRL_SSF_DEASSERT_TIMING(x)  VTSS_ENCODE_BITFIELD(x,16,12)
#define  VTSS_M_XFI_SHELL_XFI_CONTROL_SSF_HYST_TIMING_CTRL_SSF_DEASSERT_TIMING     VTSS_ENCODE_BITMASK(16,12)
#define  VTSS_X_XFI_SHELL_XFI_CONTROL_SSF_HYST_TIMING_CTRL_SSF_DEASSERT_TIMING(x)  VTSS_EXTRACT_BITFIELD(x,16,12)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_SSF_HYST_TIMING_CTRL_SSF_ASSERT_TIMING(x)  VTSS_ENCODE_BITFIELD(x,0,12)
#define  VTSS_M_XFI_SHELL_XFI_CONTROL_SSF_HYST_TIMING_CTRL_SSF_ASSERT_TIMING     VTSS_ENCODE_BITMASK(0,12)
#define  VTSS_X_XFI_SHELL_XFI_CONTROL_SSF_HYST_TIMING_CTRL_SSF_ASSERT_TIMING(x)  VTSS_EXTRACT_BITFIELD(x,0,12)

#define VTSS_XFI_SHELL_XFI_CONTROL_HSS_STICKY(target)  VTSS_IOREG(target,0x6)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_HSS_STICKY_DFT_NO_SYNC_HI_STICKY  VTSS_BIT(31)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_HSS_STICKY_DFT_NO_SYNC_LO_STICKY  VTSS_BIT(30)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_HSS_STICKY_DFT_INSTABLE_HI_STICKY  VTSS_BIT(29)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_HSS_STICKY_DFT_INSTABLE_LO_STICKY  VTSS_BIT(28)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_HSS_STICKY_DFT_INCOMPLETE_HI_STICKY  VTSS_BIT(27)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_HSS_STICKY_DFT_INCOMPLETE_LO_STICKY  VTSS_BIT(26)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_HSS_STICKY_DFT_ACTIVE_HI_STICKY  VTSS_BIT(25)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_HSS_STICKY_DFT_ACTIVE_LO_STICKY  VTSS_BIT(24)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_HSS_STICKY_DFT_STUCK_AT_HI_STICKY  VTSS_BIT(22)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_HSS_STICKY_TX_FIFO_LOS_HI_STICKY  VTSS_BIT(21)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_HSS_STICKY_TX_PLL_LOCK_HI_STICKY  VTSS_BIT(19)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_HSS_STICKY_TX_PLL_LOCK_LO_STICKY  VTSS_BIT(18)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_HSS_STICKY_RX_PLL_LOCK_HI_STICKY  VTSS_BIT(17)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_HSS_STICKY_RX_PLL_LOCK_LO_STICKY  VTSS_BIT(16)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_HSS_STICKY_RX_LOS_HI_STICKY  VTSS_BIT(15)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_HSS_STICKY_RX_LOS_LO_STICKY  VTSS_BIT(14)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_HSS_STICKY_RXSIGDET_HI_STICKY  VTSS_BIT(13)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_HSS_STICKY_RXSIGDET_LO_STICKY  VTSS_BIT(12)

#define VTSS_XFI_SHELL_XFI_CONTROL_HSS_MASK(target)  VTSS_IOREG(target,0x7)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_HSS_MASK_DFT_NO_SYNC_HI_MASK  VTSS_BIT(31)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_HSS_MASK_DFT_NO_SYNC_LO_MASK  VTSS_BIT(30)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_HSS_MASK_DFT_INSTABLE_HI_MASK  VTSS_BIT(29)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_HSS_MASK_DFT_INSTABLE_LO_MASK  VTSS_BIT(28)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_HSS_MASK_DFT_INCOMPLETE_HI_MASK  VTSS_BIT(27)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_HSS_MASK_DFT_INCOMPLETE_LO_MASK  VTSS_BIT(26)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_HSS_MASK_DFT_ACTIVE_HI_MASK  VTSS_BIT(25)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_HSS_MASK_DFT_ACTIVE_LO_MASK  VTSS_BIT(24)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_HSS_MASK_DFT_STUCK_AT_HI_MASK  VTSS_BIT(22)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_HSS_MASK_TX_FIFO_LOS_HI_MASK  VTSS_BIT(21)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_HSS_MASK_TX_PLL_LOCK_HI_MASK  VTSS_BIT(19)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_HSS_MASK_TX_PLL_LOCK_LO_MASK  VTSS_BIT(18)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_HSS_MASK_RX_PLL_LOCK_HI_MASK  VTSS_BIT(17)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_HSS_MASK_RX_PLL_LOCK_LO_MASK  VTSS_BIT(16)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_HSS_MASK_RX_LOS_HI_MASK  VTSS_BIT(15)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_HSS_MASK_RX_LOS_LO_MASK  VTSS_BIT(14)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_HSS_MASK_RXSIGDET_HI_MASK  VTSS_BIT(13)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_HSS_MASK_RXSIGDET_LO_MASK  VTSS_BIT(12)

#define VTSS_XFI_SHELL_XFI_CONTROL_HSS_STATUS(target)  VTSS_IOREG(target,0x8)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_HSS_STATUS_TX_FIFO_LOS_STATUS  VTSS_BIT(20)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_HSS_STATUS_TX_PLL_LOCK_STATUS  VTSS_BIT(18)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_HSS_STATUS_RX_PLL_LOCK_STATUS  VTSS_BIT(16)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_HSS_STATUS_RX_LOS_STATUS  VTSS_BIT(14)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_HSS_STATUS_RXSIGDET_STATUS  VTSS_BIT(12)

#define VTSS_XFI_SHELL_XFI_CONTROL_DATA_VALID_DETECT_CTRL(target)  VTSS_IOREG(target,0x9)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_DATA_VALID_DETECT_CTRL_OTN_DETECT_MASK  VTSS_BIT(2)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_DATA_VALID_DETECT_CTRL_EWIS_DETECT_MASK  VTSS_BIT(1)
#define  VTSS_F_XFI_SHELL_XFI_CONTROL_DATA_VALID_DETECT_CTRL_PCS_DETECT_MASK  VTSS_BIT(0)


#endif /* _VTSS_JAGUAR2_REGS_XFI_SHELL_H_ */
