#ifndef _VTSS_JAGUAR2_REGS_DEV10G_H_
#define _VTSS_JAGUAR2_REGS_DEV10G_H_

/*
 *
 * VCore-III Register Definitions
 *
 * Copyright (C) 2012 Vitesse Semiconductor Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#include "vtss_jaguar2_regs_common.h"

#define VTSS_DEV10G_MAC_CFG_STATUS_MAC_ENA_CFG(target)  VTSS_IOREG(target,0x0)
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_ENA_CFG_RX_ENA  VTSS_BIT(4)
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_ENA_CFG_TX_ENA  VTSS_BIT(0)

#define VTSS_DEV10G_MAC_CFG_STATUS_MAC_MODE_CFG(target)  VTSS_IOREG(target,0x1)
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_MODE_CFG_TUNNEL_PAUSE_FRAMES  VTSS_BIT(16)
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_MODE_CFG_MAC_PREAMBLE_CFG(x)  VTSS_ENCODE_BITFIELD(x,12,3)
#define  VTSS_M_DEV10G_MAC_CFG_STATUS_MAC_MODE_CFG_MAC_PREAMBLE_CFG     VTSS_ENCODE_BITMASK(12,3)
#define  VTSS_X_DEV10G_MAC_CFG_STATUS_MAC_MODE_CFG_MAC_PREAMBLE_CFG(x)  VTSS_EXTRACT_BITFIELD(x,12,3)
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_MODE_CFG_MAC_IPG_CFG  VTSS_BIT(8)
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_MODE_CFG_XGMII_GEN_MODE_ENA  VTSS_BIT(4)
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_MODE_CFG_HIH_CRC_CHECK  VTSS_BIT(0)

#define VTSS_DEV10G_MAC_CFG_STATUS_MAC_MAXLEN_CFG(target)  VTSS_IOREG(target,0x2)
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_MAXLEN_CFG_MAX_LEN_TAG_CHK  VTSS_BIT(16)
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_MAXLEN_CFG_MAX_LEN(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_DEV10G_MAC_CFG_STATUS_MAC_MAXLEN_CFG_MAX_LEN     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_DEV10G_MAC_CFG_STATUS_MAC_MAXLEN_CFG_MAX_LEN(x)  VTSS_EXTRACT_BITFIELD(x,0,16)

#define VTSS_DEV10G_MAC_CFG_STATUS_MAC_NUM_TAGS_CFG(target)  VTSS_IOREG(target,0x3)
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_NUM_TAGS_CFG_NUM_TAGS(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_DEV10G_MAC_CFG_STATUS_MAC_NUM_TAGS_CFG_NUM_TAGS     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_DEV10G_MAC_CFG_STATUS_MAC_NUM_TAGS_CFG_NUM_TAGS(x)  VTSS_EXTRACT_BITFIELD(x,0,2)

#define VTSS_DEV10G_MAC_CFG_STATUS_MAC_TAGS_CFG(target,ri)  VTSS_IOREG(target,0x4 + (ri))
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_TAGS_CFG_TAG_ID(x)  VTSS_ENCODE_BITFIELD(x,16,16)
#define  VTSS_M_DEV10G_MAC_CFG_STATUS_MAC_TAGS_CFG_TAG_ID     VTSS_ENCODE_BITMASK(16,16)
#define  VTSS_X_DEV10G_MAC_CFG_STATUS_MAC_TAGS_CFG_TAG_ID(x)  VTSS_EXTRACT_BITFIELD(x,16,16)
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_TAGS_CFG_TAG_ENA  VTSS_BIT(4)

#define VTSS_DEV10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG(target)  VTSS_IOREG(target,0x7)
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_EXT_EOP_CHK_ENA  VTSS_BIT(24)
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_EXT_SOP_CHK_ENA  VTSS_BIT(20)
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_SFD_CHK_ENA  VTSS_BIT(16)
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_PRM_SHK_CHK_DIS  VTSS_BIT(12)
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_PRM_CHK_ENA  VTSS_BIT(8)
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_OOR_ERR_ENA  VTSS_BIT(4)
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_INR_ERR_ENA  VTSS_BIT(0)

#define VTSS_DEV10G_MAC_CFG_STATUS_MAC_LFS_CFG(target)  VTSS_IOREG(target,0x8)
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_LFS_CFG_LFS_UNIDIR_ENA  VTSS_BIT(3)
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_LFS_CFG_USE_LEADING_EDGE_DETECT  VTSS_BIT(2)
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_LFS_CFG_SPURIOUS_Q_DIS  VTSS_BIT(1)
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_LFS_CFG_LFS_MODE_ENA  VTSS_BIT(0)

#define VTSS_DEV10G_MAC_CFG_STATUS_MAC_LB_CFG(target)  VTSS_IOREG(target,0x9)
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_LB_CFG_XGMII_HOST_LB_ENA  VTSS_BIT(4)
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_LB_CFG_XGMII_PHY_LB_ENA  VTSS_BIT(0)

#define VTSS_DEV10G_MAC_CFG_STATUS_MAC_RX_LANE_STICKY_0(target)  VTSS_IOREG(target,0xa)
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_RX_LANE_STICKY_0_LANE3_STICKY(x)  VTSS_ENCODE_BITFIELD(x,24,7)
#define  VTSS_M_DEV10G_MAC_CFG_STATUS_MAC_RX_LANE_STICKY_0_LANE3_STICKY     VTSS_ENCODE_BITMASK(24,7)
#define  VTSS_X_DEV10G_MAC_CFG_STATUS_MAC_RX_LANE_STICKY_0_LANE3_STICKY(x)  VTSS_EXTRACT_BITFIELD(x,24,7)
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_RX_LANE_STICKY_0_LANE2_STICKY(x)  VTSS_ENCODE_BITFIELD(x,16,7)
#define  VTSS_M_DEV10G_MAC_CFG_STATUS_MAC_RX_LANE_STICKY_0_LANE2_STICKY     VTSS_ENCODE_BITMASK(16,7)
#define  VTSS_X_DEV10G_MAC_CFG_STATUS_MAC_RX_LANE_STICKY_0_LANE2_STICKY(x)  VTSS_EXTRACT_BITFIELD(x,16,7)
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_RX_LANE_STICKY_0_LANE1_STICKY(x)  VTSS_ENCODE_BITFIELD(x,8,7)
#define  VTSS_M_DEV10G_MAC_CFG_STATUS_MAC_RX_LANE_STICKY_0_LANE1_STICKY     VTSS_ENCODE_BITMASK(8,7)
#define  VTSS_X_DEV10G_MAC_CFG_STATUS_MAC_RX_LANE_STICKY_0_LANE1_STICKY(x)  VTSS_EXTRACT_BITFIELD(x,8,7)
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_RX_LANE_STICKY_0_LANE0_STICKY(x)  VTSS_ENCODE_BITFIELD(x,0,7)
#define  VTSS_M_DEV10G_MAC_CFG_STATUS_MAC_RX_LANE_STICKY_0_LANE0_STICKY     VTSS_ENCODE_BITMASK(0,7)
#define  VTSS_X_DEV10G_MAC_CFG_STATUS_MAC_RX_LANE_STICKY_0_LANE0_STICKY(x)  VTSS_EXTRACT_BITFIELD(x,0,7)

#define VTSS_DEV10G_MAC_CFG_STATUS_MAC_RX_LANE_STICKY_1(target)  VTSS_IOREG(target,0xb)
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_RX_LANE_STICKY_1_LANE7_STICKY(x)  VTSS_ENCODE_BITFIELD(x,24,7)
#define  VTSS_M_DEV10G_MAC_CFG_STATUS_MAC_RX_LANE_STICKY_1_LANE7_STICKY     VTSS_ENCODE_BITMASK(24,7)
#define  VTSS_X_DEV10G_MAC_CFG_STATUS_MAC_RX_LANE_STICKY_1_LANE7_STICKY(x)  VTSS_EXTRACT_BITFIELD(x,24,7)
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_RX_LANE_STICKY_1_LANE6_STICKY(x)  VTSS_ENCODE_BITFIELD(x,16,7)
#define  VTSS_M_DEV10G_MAC_CFG_STATUS_MAC_RX_LANE_STICKY_1_LANE6_STICKY     VTSS_ENCODE_BITMASK(16,7)
#define  VTSS_X_DEV10G_MAC_CFG_STATUS_MAC_RX_LANE_STICKY_1_LANE6_STICKY(x)  VTSS_EXTRACT_BITFIELD(x,16,7)
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_RX_LANE_STICKY_1_LANE5_STICKY(x)  VTSS_ENCODE_BITFIELD(x,8,7)
#define  VTSS_M_DEV10G_MAC_CFG_STATUS_MAC_RX_LANE_STICKY_1_LANE5_STICKY     VTSS_ENCODE_BITMASK(8,7)
#define  VTSS_X_DEV10G_MAC_CFG_STATUS_MAC_RX_LANE_STICKY_1_LANE5_STICKY(x)  VTSS_EXTRACT_BITFIELD(x,8,7)
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_RX_LANE_STICKY_1_LANE4_STICKY(x)  VTSS_ENCODE_BITFIELD(x,0,7)
#define  VTSS_M_DEV10G_MAC_CFG_STATUS_MAC_RX_LANE_STICKY_1_LANE4_STICKY     VTSS_ENCODE_BITMASK(0,7)
#define  VTSS_X_DEV10G_MAC_CFG_STATUS_MAC_RX_LANE_STICKY_1_LANE4_STICKY(x)  VTSS_EXTRACT_BITFIELD(x,0,7)

#define VTSS_DEV10G_MAC_CFG_STATUS_MAC_TX_MONITOR_STICKY(target)  VTSS_IOREG(target,0xc)
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_TX_MONITOR_STICKY_LOCAL_ERR_STATE_STICKY  VTSS_BIT(4)
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_TX_MONITOR_STICKY_REMOTE_ERR_STATE_STICKY  VTSS_BIT(3)
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_TX_MONITOR_STICKY_IDLE_STATE_STICKY  VTSS_BIT(1)
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_TX_MONITOR_STICKY_DIS_STATE_STICKY  VTSS_BIT(0)

#define VTSS_DEV10G_MAC_CFG_STATUS_MAC_STICKY(target)  VTSS_IOREG(target,0xd)
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_STICKY_RX_IPG_SHRINK_STICKY  VTSS_BIT(9)
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_STICKY_RX_PREAM_SHRINK_STICKY  VTSS_BIT(8)
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_STICKY_RX_PREAM_MISMATCH_STICKY  VTSS_BIT(7)
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_STICKY_RX_PREAM_ERR_STICKY  VTSS_BIT(6)
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_STICKY_RX_NON_STD_PREAM_STICKY  VTSS_BIT(5)
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_STICKY_RX_MPLS_MC_STICKY  VTSS_BIT(4)
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_STICKY_RX_MPLS_UC_STICKY  VTSS_BIT(3)
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_STICKY_RX_TAG_STICKY  VTSS_BIT(2)
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_STICKY_TX_UFLW_STICKY  VTSS_BIT(1)
#define  VTSS_F_DEV10G_MAC_CFG_STATUS_MAC_STICKY_TX_ABORT_STICKY  VTSS_BIT(0)

#define VTSS_DEV10G_DEV_STATISTICS_32BIT_RX_SYMBOL_ERR_CNT(target)  VTSS_IOREG(target,0xe)

#define VTSS_DEV10G_DEV_STATISTICS_32BIT_RX_PAUSE_CNT(target)  VTSS_IOREG(target,0xf)

#define VTSS_DEV10G_DEV_STATISTICS_32BIT_RX_UNSUP_OPCODE_CNT(target)  VTSS_IOREG(target,0x10)

#define VTSS_DEV10G_DEV_STATISTICS_32BIT_RX_UC_CNT(target)  VTSS_IOREG(target,0x11)

#define VTSS_DEV10G_DEV_STATISTICS_32BIT_RX_MC_CNT(target)  VTSS_IOREG(target,0x12)

#define VTSS_DEV10G_DEV_STATISTICS_32BIT_RX_BC_CNT(target)  VTSS_IOREG(target,0x13)

#define VTSS_DEV10G_DEV_STATISTICS_32BIT_RX_CRC_ERR_CNT(target)  VTSS_IOREG(target,0x14)

#define VTSS_DEV10G_DEV_STATISTICS_32BIT_RX_UNDERSIZE_CNT(target)  VTSS_IOREG(target,0x15)

#define VTSS_DEV10G_DEV_STATISTICS_32BIT_RX_FRAGMENTS_CNT(target)  VTSS_IOREG(target,0x16)

#define VTSS_DEV10G_DEV_STATISTICS_32BIT_RX_IN_RANGE_LEN_ERR_CNT(target)  VTSS_IOREG(target,0x17)

#define VTSS_DEV10G_DEV_STATISTICS_32BIT_RX_OUT_OF_RANGE_LEN_ERR_CNT(target)  VTSS_IOREG(target,0x18)

#define VTSS_DEV10G_DEV_STATISTICS_32BIT_RX_OVERSIZE_CNT(target)  VTSS_IOREG(target,0x19)

#define VTSS_DEV10G_DEV_STATISTICS_32BIT_RX_JABBERS_CNT(target)  VTSS_IOREG(target,0x1a)

#define VTSS_DEV10G_DEV_STATISTICS_32BIT_RX_SIZE64_CNT(target)  VTSS_IOREG(target,0x1b)

#define VTSS_DEV10G_DEV_STATISTICS_32BIT_RX_SIZE65TO127_CNT(target)  VTSS_IOREG(target,0x1c)

#define VTSS_DEV10G_DEV_STATISTICS_32BIT_RX_SIZE128TO255_CNT(target)  VTSS_IOREG(target,0x1d)

#define VTSS_DEV10G_DEV_STATISTICS_32BIT_RX_SIZE256TO511_CNT(target)  VTSS_IOREG(target,0x1e)

#define VTSS_DEV10G_DEV_STATISTICS_32BIT_RX_SIZE512TO1023_CNT(target)  VTSS_IOREG(target,0x1f)

#define VTSS_DEV10G_DEV_STATISTICS_32BIT_RX_SIZE1024TO1518_CNT(target)  VTSS_IOREG(target,0x20)

#define VTSS_DEV10G_DEV_STATISTICS_32BIT_RX_SIZE1519TOMAX_CNT(target)  VTSS_IOREG(target,0x21)

#define VTSS_DEV10G_DEV_STATISTICS_32BIT_RX_IPG_SHRINK_CNT(target)  VTSS_IOREG(target,0x22)

#define VTSS_DEV10G_DEV_STATISTICS_32BIT_TX_PAUSE_CNT(target)  VTSS_IOREG(target,0x23)

#define VTSS_DEV10G_DEV_STATISTICS_32BIT_TX_UC_CNT(target)  VTSS_IOREG(target,0x24)

#define VTSS_DEV10G_DEV_STATISTICS_32BIT_TX_MC_CNT(target)  VTSS_IOREG(target,0x25)

#define VTSS_DEV10G_DEV_STATISTICS_32BIT_TX_BC_CNT(target)  VTSS_IOREG(target,0x26)

#define VTSS_DEV10G_DEV_STATISTICS_32BIT_TX_SIZE64_CNT(target)  VTSS_IOREG(target,0x27)

#define VTSS_DEV10G_DEV_STATISTICS_32BIT_TX_SIZE65TO127_CNT(target)  VTSS_IOREG(target,0x28)

#define VTSS_DEV10G_DEV_STATISTICS_32BIT_TX_SIZE128TO255_CNT(target)  VTSS_IOREG(target,0x29)

#define VTSS_DEV10G_DEV_STATISTICS_32BIT_TX_SIZE256TO511_CNT(target)  VTSS_IOREG(target,0x2a)

#define VTSS_DEV10G_DEV_STATISTICS_32BIT_TX_SIZE512TO1023_CNT(target)  VTSS_IOREG(target,0x2b)

#define VTSS_DEV10G_DEV_STATISTICS_32BIT_TX_SIZE1024TO1518_CNT(target)  VTSS_IOREG(target,0x2c)

#define VTSS_DEV10G_DEV_STATISTICS_32BIT_TX_SIZE1519TOMAX_CNT(target)  VTSS_IOREG(target,0x2d)

#define VTSS_DEV10G_DEV_STATISTICS_32BIT_RX_ALIGNMENT_LOST_CNT(target)  VTSS_IOREG(target,0x2e)

#define VTSS_DEV10G_DEV_STATISTICS_32BIT_RX_TAGGED_FRMS_CNT(target)  VTSS_IOREG(target,0x2f)

#define VTSS_DEV10G_DEV_STATISTICS_32BIT_RX_UNTAGGED_FRMS_CNT(target)  VTSS_IOREG(target,0x30)

#define VTSS_DEV10G_DEV_STATISTICS_32BIT_TX_TAGGED_FRMS_CNT(target)  VTSS_IOREG(target,0x31)

#define VTSS_DEV10G_DEV_STATISTICS_32BIT_TX_UNTAGGED_FRMS_CNT(target)  VTSS_IOREG(target,0x32)

#define VTSS_DEV10G_DEV_STATISTICS_32BIT_RX_HIH_CKSM_ERR_CNT(target)  VTSS_IOREG(target,0x33)

#define VTSS_DEV10G_DEV_STATISTICS_32BIT_RX_XGMII_PROT_ERR_CNT(target)  VTSS_IOREG(target,0x34)

#define VTSS_DEV10G_DEV_STATISTICS_40BIT_RX_IN_BYTES_CNT(target)  VTSS_IOREG(target,0x35)

#define VTSS_DEV10G_DEV_STATISTICS_40BIT_RX_IN_BYTES_MSB_CNT(target)  VTSS_IOREG(target,0x36)
#define  VTSS_F_DEV10G_DEV_STATISTICS_40BIT_RX_IN_BYTES_MSB_CNT_RX_IN_BYTES_MSB_CNT(x)  VTSS_ENCODE_BITFIELD(x,0,8)
#define  VTSS_M_DEV10G_DEV_STATISTICS_40BIT_RX_IN_BYTES_MSB_CNT_RX_IN_BYTES_MSB_CNT     VTSS_ENCODE_BITMASK(0,8)
#define  VTSS_X_DEV10G_DEV_STATISTICS_40BIT_RX_IN_BYTES_MSB_CNT_RX_IN_BYTES_MSB_CNT(x)  VTSS_EXTRACT_BITFIELD(x,0,8)

#define VTSS_DEV10G_DEV_STATISTICS_40BIT_RX_OK_BYTES_CNT(target)  VTSS_IOREG(target,0x37)

#define VTSS_DEV10G_DEV_STATISTICS_40BIT_RX_OK_BYTES_MSB_CNT(target)  VTSS_IOREG(target,0x38)
#define  VTSS_F_DEV10G_DEV_STATISTICS_40BIT_RX_OK_BYTES_MSB_CNT_RX_OK_BYTES_MSB_CNT(x)  VTSS_ENCODE_BITFIELD(x,0,8)
#define  VTSS_M_DEV10G_DEV_STATISTICS_40BIT_RX_OK_BYTES_MSB_CNT_RX_OK_BYTES_MSB_CNT     VTSS_ENCODE_BITMASK(0,8)
#define  VTSS_X_DEV10G_DEV_STATISTICS_40BIT_RX_OK_BYTES_MSB_CNT_RX_OK_BYTES_MSB_CNT(x)  VTSS_EXTRACT_BITFIELD(x,0,8)

#define VTSS_DEV10G_DEV_STATISTICS_40BIT_RX_BAD_BYTES_CNT(target)  VTSS_IOREG(target,0x39)

#define VTSS_DEV10G_DEV_STATISTICS_40BIT_RX_BAD_BYTES_MSB_CNT(target)  VTSS_IOREG(target,0x3a)
#define  VTSS_F_DEV10G_DEV_STATISTICS_40BIT_RX_BAD_BYTES_MSB_CNT_RX_BAD_BYTES_MSB_CNT(x)  VTSS_ENCODE_BITFIELD(x,0,8)
#define  VTSS_M_DEV10G_DEV_STATISTICS_40BIT_RX_BAD_BYTES_MSB_CNT_RX_BAD_BYTES_MSB_CNT     VTSS_ENCODE_BITMASK(0,8)
#define  VTSS_X_DEV10G_DEV_STATISTICS_40BIT_RX_BAD_BYTES_MSB_CNT_RX_BAD_BYTES_MSB_CNT(x)  VTSS_EXTRACT_BITFIELD(x,0,8)

#define VTSS_DEV10G_DEV_STATISTICS_40BIT_TX_OUT_BYTES_CNT(target)  VTSS_IOREG(target,0x3b)

#define VTSS_DEV10G_DEV_STATISTICS_40BIT_TX_OUT_BYTES_MSB_CNT(target)  VTSS_IOREG(target,0x3c)
#define  VTSS_F_DEV10G_DEV_STATISTICS_40BIT_TX_OUT_BYTES_MSB_CNT_TX_OUT_BYTES_MSB_CNT(x)  VTSS_ENCODE_BITFIELD(x,0,8)
#define  VTSS_M_DEV10G_DEV_STATISTICS_40BIT_TX_OUT_BYTES_MSB_CNT_TX_OUT_BYTES_MSB_CNT     VTSS_ENCODE_BITMASK(0,8)
#define  VTSS_X_DEV10G_DEV_STATISTICS_40BIT_TX_OUT_BYTES_MSB_CNT_TX_OUT_BYTES_MSB_CNT(x)  VTSS_EXTRACT_BITFIELD(x,0,8)

#define VTSS_DEV10G_DEV_STATISTICS_40BIT_TX_OK_BYTES_CNT(target)  VTSS_IOREG(target,0x3d)

#define VTSS_DEV10G_DEV_STATISTICS_40BIT_TX_OK_BYTES_MSB_CNT(target)  VTSS_IOREG(target,0x3e)
#define  VTSS_F_DEV10G_DEV_STATISTICS_40BIT_TX_OK_BYTES_MSB_CNT_TX_OK_BYTES_MSB_CNT(x)  VTSS_ENCODE_BITFIELD(x,0,8)
#define  VTSS_M_DEV10G_DEV_STATISTICS_40BIT_TX_OK_BYTES_MSB_CNT_TX_OK_BYTES_MSB_CNT     VTSS_ENCODE_BITMASK(0,8)
#define  VTSS_X_DEV10G_DEV_STATISTICS_40BIT_TX_OK_BYTES_MSB_CNT_TX_OK_BYTES_MSB_CNT(x)  VTSS_EXTRACT_BITFIELD(x,0,8)

#define VTSS_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_CFG(target)  VTSS_IOREG(target,0x3f)
#define  VTSS_F_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_CFG_XAUI_LOOP_ENA  VTSS_BIT(20)
#define  VTSS_F_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_CFG_IDLE_SEQ_MODE  VTSS_BIT(12)
#define  VTSS_F_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_CFG_FIFO_RPT_RES  VTSS_BIT(11)
#define  VTSS_F_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_CFG_LF_GEN_DIS  VTSS_BIT(7)
#define  VTSS_F_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_CFG_PT_IPG_SIZE(x)  VTSS_ENCODE_BITFIELD(x,3,3)
#define  VTSS_M_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_CFG_PT_IPG_SIZE     VTSS_ENCODE_BITMASK(3,3)
#define  VTSS_X_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_CFG_PT_IPG_SIZE(x)  VTSS_EXTRACT_BITFIELD(x,3,3)
#define  VTSS_F_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_CFG_PT_DIS  VTSS_BIT(2)
#define  VTSS_F_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_CFG_AN_LINK_CTRL_ENA  VTSS_BIT(1)
#define  VTSS_F_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_CFG_PCS_ENA  VTSS_BIT(0)

#define VTSS_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_EXT_CFG(target)  VTSS_IOREG(target,0x40)
#define  VTSS_F_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_EXT_CFG_RX_INV_HMBUS  VTSS_BIT(3)
#define  VTSS_F_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_EXT_CFG_RX_FLIP_HMBUS  VTSS_BIT(2)
#define  VTSS_F_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_EXT_CFG_TX_INV_HMBUS  VTSS_BIT(1)
#define  VTSS_F_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_EXT_CFG_TX_FLIP_HMBUS  VTSS_BIT(0)

#define VTSS_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_SD_CFG(target)  VTSS_IOREG(target,0x41)
#define  VTSS_F_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_SD_CFG_SD_SEL  VTSS_BIT(8)
#define  VTSS_F_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_SD_CFG_SD_POL  VTSS_BIT(4)
#define  VTSS_F_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_SD_CFG_SD_ENA  VTSS_BIT(0)

#define VTSS_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_TX_SEQ_CFG(target)  VTSS_IOREG(target,0x42)
#define  VTSS_F_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_TX_SEQ_CFG_TX_Q(x)  VTSS_ENCODE_BITFIELD(x,8,24)
#define  VTSS_M_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_TX_SEQ_CFG_TX_Q     VTSS_ENCODE_BITMASK(8,24)
#define  VTSS_X_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_TX_SEQ_CFG_TX_Q(x)  VTSS_EXTRACT_BITFIELD(x,8,24)
#define  VTSS_F_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_TX_SEQ_CFG_TX_Q_DIS  VTSS_BIT(7)

#define VTSS_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_RX_ERR_CNT_CFG(target)  VTSS_IOREG(target,0x43)
#define  VTSS_F_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_RX_ERR_CNT_CFG_DERR_MASK(x)  VTSS_ENCODE_BITFIELD(x,12,4)
#define  VTSS_M_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_RX_ERR_CNT_CFG_DERR_MASK     VTSS_ENCODE_BITMASK(12,4)
#define  VTSS_X_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_RX_ERR_CNT_CFG_DERR_MASK(x)  VTSS_EXTRACT_BITFIELD(x,12,4)
#define  VTSS_F_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_RX_ERR_CNT_CFG_CERR_MASK(x)  VTSS_ENCODE_BITFIELD(x,8,4)
#define  VTSS_M_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_RX_ERR_CNT_CFG_CERR_MASK     VTSS_ENCODE_BITMASK(8,4)
#define  VTSS_X_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_RX_ERR_CNT_CFG_CERR_MASK(x)  VTSS_EXTRACT_BITFIELD(x,8,4)
#define  VTSS_F_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_RX_ERR_CNT_CFG_UFERR_MASK(x)  VTSS_ENCODE_BITFIELD(x,4,4)
#define  VTSS_M_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_RX_ERR_CNT_CFG_UFERR_MASK     VTSS_ENCODE_BITMASK(4,4)
#define  VTSS_X_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_RX_ERR_CNT_CFG_UFERR_MASK(x)  VTSS_EXTRACT_BITFIELD(x,4,4)
#define  VTSS_F_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_RX_ERR_CNT_CFG_OFERR_MASK(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_RX_ERR_CNT_CFG_OFERR_MASK     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_RX_ERR_CNT_CFG_OFERR_MASK(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG(target)  VTSS_IOREG(target,0x44)
#define  VTSS_F_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_COM_ALIGN_POS  VTSS_BIT(18)
#define  VTSS_F_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_DC_A_ALIGN_ENA  VTSS_BIT(17)
#define  VTSS_F_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_K28_5_SYNC_ENA  VTSS_BIT(16)
#define  VTSS_F_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_COMMA_REPL(x)  VTSS_ENCODE_BITFIELD(x,8,8)
#define  VTSS_M_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_COMMA_REPL     VTSS_ENCODE_BITMASK(8,8)
#define  VTSS_X_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_COMMA_REPL(x)  VTSS_EXTRACT_BITFIELD(x,8,8)
#define  VTSS_F_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_TXCHAN_REORD1_ENA  VTSS_BIT(7)
#define  VTSS_F_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_TXCHAN_REORD2_ENA  VTSS_BIT(6)
#define  VTSS_F_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_RXCHAN_REORD1_ENA  VTSS_BIT(5)
#define  VTSS_F_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_RXCHAN_REORD2_ENA  VTSS_BIT(4)
#define  VTSS_F_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_RX_8B10B_ILV_DIS  VTSS_BIT(3)
#define  VTSS_F_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_TX_8B10B_ILV_DIS  VTSS_BIT(2)
#define  VTSS_F_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_ILV_MODE  VTSS_BIT(1)
#define  VTSS_F_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_INTERLEAVE_MODE_CFG_ILV_MODE_ENA  VTSS_BIT(0)

#define VTSS_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_LPI_CFG(target)  VTSS_IOREG(target,0x45)
#define  VTSS_F_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_LPI_CFG_RX_LPI_OUT_DIS  VTSS_BIT(17)
#define  VTSS_F_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_LPI_CFG_LPI_TESTMODE  VTSS_BIT(16)
#define  VTSS_F_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_LPI_CFG_LPI_RX_WTIM(x)  VTSS_ENCODE_BITFIELD(x,4,2)
#define  VTSS_M_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_LPI_CFG_LPI_RX_WTIM     VTSS_ENCODE_BITMASK(4,2)
#define  VTSS_X_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_LPI_CFG_LPI_RX_WTIM(x)  VTSS_EXTRACT_BITFIELD(x,4,2)
#define  VTSS_F_DEV10G_PCS_XAUI_CONFIGURATION_PCS_XAUI_LPI_CFG_TX_ASSERT_LPIDLE  VTSS_BIT(0)

#define VTSS_DEV10G_PCS_XAUI_STATUS_PCS_XAUI_RX_STATUS(target)  VTSS_IOREG(target,0x46)
#define  VTSS_F_DEV10G_PCS_XAUI_STATUS_PCS_XAUI_RX_STATUS_SIGNAL_DETECT(x)  VTSS_ENCODE_BITFIELD(x,12,4)
#define  VTSS_M_DEV10G_PCS_XAUI_STATUS_PCS_XAUI_RX_STATUS_SIGNAL_DETECT     VTSS_ENCODE_BITMASK(12,4)
#define  VTSS_X_DEV10G_PCS_XAUI_STATUS_PCS_XAUI_RX_STATUS_SIGNAL_DETECT(x)  VTSS_EXTRACT_BITFIELD(x,12,4)
#define  VTSS_F_DEV10G_PCS_XAUI_STATUS_PCS_XAUI_RX_STATUS_LOCAL_FAULT_STICKY(x)  VTSS_ENCODE_BITFIELD(x,8,4)
#define  VTSS_M_DEV10G_PCS_XAUI_STATUS_PCS_XAUI_RX_STATUS_LOCAL_FAULT_STICKY     VTSS_ENCODE_BITMASK(8,4)
#define  VTSS_X_DEV10G_PCS_XAUI_STATUS_PCS_XAUI_RX_STATUS_LOCAL_FAULT_STICKY(x)  VTSS_EXTRACT_BITFIELD(x,8,4)
#define  VTSS_F_DEV10G_PCS_XAUI_STATUS_PCS_XAUI_RX_STATUS_ALIGNMENT_STATUS  VTSS_BIT(4)
#define  VTSS_F_DEV10G_PCS_XAUI_STATUS_PCS_XAUI_RX_STATUS_SYNC_STATUS(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_DEV10G_PCS_XAUI_STATUS_PCS_XAUI_RX_STATUS_SYNC_STATUS     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_DEV10G_PCS_XAUI_STATUS_PCS_XAUI_RX_STATUS_SYNC_STATUS(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_DEV10G_PCS_XAUI_STATUS_PCS_XAUI_DESKEW_STATUS(target)  VTSS_IOREG(target,0x47)
#define  VTSS_F_DEV10G_PCS_XAUI_STATUS_PCS_XAUI_DESKEW_STATUS_LANE_DESKEW_DELAY(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_DEV10G_PCS_XAUI_STATUS_PCS_XAUI_DESKEW_STATUS_LANE_DESKEW_DELAY     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_DEV10G_PCS_XAUI_STATUS_PCS_XAUI_DESKEW_STATUS_LANE_DESKEW_DELAY(x)  VTSS_EXTRACT_BITFIELD(x,0,16)

#define VTSS_DEV10G_PCS_XAUI_STATUS_PCS_XAUI_CGALIGN_STATUS(target)  VTSS_IOREG(target,0x48)
#define  VTSS_F_DEV10G_PCS_XAUI_STATUS_PCS_XAUI_CGALIGN_STATUS_LANE_CGALIGN_DELAY(x)  VTSS_ENCODE_BITFIELD(x,0,20)
#define  VTSS_M_DEV10G_PCS_XAUI_STATUS_PCS_XAUI_CGALIGN_STATUS_LANE_CGALIGN_DELAY     VTSS_ENCODE_BITMASK(0,20)
#define  VTSS_X_DEV10G_PCS_XAUI_STATUS_PCS_XAUI_CGALIGN_STATUS_LANE_CGALIGN_DELAY(x)  VTSS_EXTRACT_BITFIELD(x,0,20)

#define VTSS_DEV10G_PCS_XAUI_STATUS_PCS_XAUI_RX_ERROR_STATUS(target)  VTSS_IOREG(target,0x49)
#define  VTSS_F_DEV10G_PCS_XAUI_STATUS_PCS_XAUI_RX_ERROR_STATUS_C8B10B_ERR_STICKY  VTSS_BIT(5)
#define  VTSS_F_DEV10G_PCS_XAUI_STATUS_PCS_XAUI_RX_ERROR_STATUS_ALIGNMENT_LOST_STICKY  VTSS_BIT(4)
#define  VTSS_F_DEV10G_PCS_XAUI_STATUS_PCS_XAUI_RX_ERROR_STATUS_SYNC_LOST_STICKY(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_DEV10G_PCS_XAUI_STATUS_PCS_XAUI_RX_ERROR_STATUS_SYNC_LOST_STICKY     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_DEV10G_PCS_XAUI_STATUS_PCS_XAUI_RX_ERROR_STATUS_SYNC_LOST_STICKY(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_DEV10G_PCS_XAUI_STATUS_PCS_XAUI_RX_SEQ_REC_STATUS(target)  VTSS_IOREG(target,0x4a)
#define  VTSS_F_DEV10G_PCS_XAUI_STATUS_PCS_XAUI_RX_SEQ_REC_STATUS_RX_Q(x)  VTSS_ENCODE_BITFIELD(x,8,24)
#define  VTSS_M_DEV10G_PCS_XAUI_STATUS_PCS_XAUI_RX_SEQ_REC_STATUS_RX_Q     VTSS_ENCODE_BITMASK(8,24)
#define  VTSS_X_DEV10G_PCS_XAUI_STATUS_PCS_XAUI_RX_SEQ_REC_STATUS_RX_Q(x)  VTSS_EXTRACT_BITFIELD(x,8,24)
#define  VTSS_F_DEV10G_PCS_XAUI_STATUS_PCS_XAUI_RX_SEQ_REC_STATUS_RX_Q_CHANGED_STICKY  VTSS_BIT(0)

#define VTSS_DEV10G_PCS_XAUI_STATUS_PCS_XAUI_RX_FIFO_OF_ERR_L0_CNT_STATUS(target)  VTSS_IOREG(target,0x4b)

#define VTSS_DEV10G_PCS_XAUI_STATUS_PCS_XAUI_RX_FIFO_UF_ERR_L1_CNT_STATUS(target)  VTSS_IOREG(target,0x4c)

#define VTSS_DEV10G_PCS_XAUI_STATUS_PCS_XAUI_RX_FIFO_D_ERR_L2_CNT_STATUS(target)  VTSS_IOREG(target,0x4d)

#define VTSS_DEV10G_PCS_XAUI_STATUS_PCS_XAUI_RX_FIFO_CG_ERR_L3_CNT_STATUS(target)  VTSS_IOREG(target,0x4e)

#define VTSS_DEV10G_PCS_XAUI_STATUS_PCS_XAUI_LPI_STATUS(target)  VTSS_IOREG(target,0x4f)
#define  VTSS_F_DEV10G_PCS_XAUI_STATUS_PCS_XAUI_LPI_STATUS_WAKE_ERR_CNT(x)  VTSS_ENCODE_BITFIELD(x,16,16)
#define  VTSS_M_DEV10G_PCS_XAUI_STATUS_PCS_XAUI_LPI_STATUS_WAKE_ERR_CNT     VTSS_ENCODE_BITMASK(16,16)
#define  VTSS_X_DEV10G_PCS_XAUI_STATUS_PCS_XAUI_LPI_STATUS_WAKE_ERR_CNT(x)  VTSS_EXTRACT_BITFIELD(x,16,16)
#define  VTSS_F_DEV10G_PCS_XAUI_STATUS_PCS_XAUI_LPI_STATUS_RX_LPI_EVENT_STICKY  VTSS_BIT(12)
#define  VTSS_F_DEV10G_PCS_XAUI_STATUS_PCS_XAUI_LPI_STATUS_RX_QUIET  VTSS_BIT(9)
#define  VTSS_F_DEV10G_PCS_XAUI_STATUS_PCS_XAUI_LPI_STATUS_RX_LPI_MODE  VTSS_BIT(8)
#define  VTSS_F_DEV10G_PCS_XAUI_STATUS_PCS_XAUI_LPI_STATUS_TX_LPI_EVENT_STICKY  VTSS_BIT(4)
#define  VTSS_F_DEV10G_PCS_XAUI_STATUS_PCS_XAUI_LPI_STATUS_TX_QUIET  VTSS_BIT(1)
#define  VTSS_F_DEV10G_PCS_XAUI_STATUS_PCS_XAUI_LPI_STATUS_TX_LPI_MODE  VTSS_BIT(0)

#define VTSS_DEV10G_PCS_XAUI_TSTPAT_CONFIGURATION_PCS_XAUI_TSTPAT_CFG(target)  VTSS_IOREG(target,0x50)
#define  VTSS_F_DEV10G_PCS_XAUI_TSTPAT_CONFIGURATION_PCS_XAUI_TSTPAT_CFG_FREEZE_ERR_CNT_ENA  VTSS_BIT(8)
#define  VTSS_F_DEV10G_PCS_XAUI_TSTPAT_CONFIGURATION_PCS_XAUI_TSTPAT_CFG_VT_CHK_ENA  VTSS_BIT(7)
#define  VTSS_F_DEV10G_PCS_XAUI_TSTPAT_CONFIGURATION_PCS_XAUI_TSTPAT_CFG_VT_CHK_SEL(x)  VTSS_ENCODE_BITFIELD(x,4,3)
#define  VTSS_M_DEV10G_PCS_XAUI_TSTPAT_CONFIGURATION_PCS_XAUI_TSTPAT_CFG_VT_CHK_SEL     VTSS_ENCODE_BITMASK(4,3)
#define  VTSS_X_DEV10G_PCS_XAUI_TSTPAT_CONFIGURATION_PCS_XAUI_TSTPAT_CFG_VT_CHK_SEL(x)  VTSS_EXTRACT_BITFIELD(x,4,3)
#define  VTSS_F_DEV10G_PCS_XAUI_TSTPAT_CONFIGURATION_PCS_XAUI_TSTPAT_CFG_VT_GEN_ENA  VTSS_BIT(3)
#define  VTSS_F_DEV10G_PCS_XAUI_TSTPAT_CONFIGURATION_PCS_XAUI_TSTPAT_CFG_VT_GEN_SEL(x)  VTSS_ENCODE_BITFIELD(x,0,3)
#define  VTSS_M_DEV10G_PCS_XAUI_TSTPAT_CONFIGURATION_PCS_XAUI_TSTPAT_CFG_VT_GEN_SEL     VTSS_ENCODE_BITMASK(0,3)
#define  VTSS_X_DEV10G_PCS_XAUI_TSTPAT_CONFIGURATION_PCS_XAUI_TSTPAT_CFG_VT_GEN_SEL(x)  VTSS_EXTRACT_BITFIELD(x,0,3)

#define VTSS_DEV10G_PCS_XAUI_TSTPAT_STATUS_PCS_XAUI_TSTPAT_RX_SEQ_CNT_STATUS(target)  VTSS_IOREG(target,0x51)

#define VTSS_DEV10G_PCS_XAUI_TSTPAT_STATUS_PCS_XAUI_TSTPAT_TX_SEQ_CNT_STATUS(target)  VTSS_IOREG(target,0x52)

#define VTSS_DEV10G_PCS2X6G_CONFIGURATION_PCS2X6G_CFG(target)  VTSS_IOREG(target,0x53)
#define  VTSS_F_DEV10G_PCS2X6G_CONFIGURATION_PCS2X6G_CFG_SD_SEL  VTSS_BIT(26)
#define  VTSS_F_DEV10G_PCS2X6G_CONFIGURATION_PCS2X6G_CFG_SD_POL  VTSS_BIT(25)
#define  VTSS_F_DEV10G_PCS2X6G_CONFIGURATION_PCS2X6G_CFG_SD_ENA  VTSS_BIT(24)
#define  VTSS_F_DEV10G_PCS2X6G_CONFIGURATION_PCS2X6G_CFG_PLOOP_RA_ENA  VTSS_BIT(21)
#define  VTSS_F_DEV10G_PCS2X6G_CONFIGURATION_PCS2X6G_CFG_SLOOP_ENA  VTSS_BIT(20)
#define  VTSS_F_DEV10G_PCS2X6G_CONFIGURATION_PCS2X6G_CFG_SCRAM_DIS  VTSS_BIT(17)
#define  VTSS_F_DEV10G_PCS2X6G_CONFIGURATION_PCS2X6G_CFG_RESYNC_ENA  VTSS_BIT(16)
#define  VTSS_F_DEV10G_PCS2X6G_CONFIGURATION_PCS2X6G_CFG_SH_CNT_MAX(x)  VTSS_ENCODE_BITFIELD(x,10,6)
#define  VTSS_M_DEV10G_PCS2X6G_CONFIGURATION_PCS2X6G_CFG_SH_CNT_MAX     VTSS_ENCODE_BITMASK(10,6)
#define  VTSS_X_DEV10G_PCS2X6G_CONFIGURATION_PCS2X6G_CFG_SH_CNT_MAX(x)  VTSS_EXTRACT_BITFIELD(x,10,6)
#define  VTSS_F_DEV10G_PCS2X6G_CONFIGURATION_PCS2X6G_CFG_SYNC_TYPE_SEL(x)  VTSS_ENCODE_BITFIELD(x,8,2)
#define  VTSS_M_DEV10G_PCS2X6G_CONFIGURATION_PCS2X6G_CFG_SYNC_TYPE_SEL     VTSS_ENCODE_BITMASK(8,2)
#define  VTSS_X_DEV10G_PCS2X6G_CONFIGURATION_PCS2X6G_CFG_SYNC_TYPE_SEL(x)  VTSS_EXTRACT_BITFIELD(x,8,2)
#define  VTSS_F_DEV10G_PCS2X6G_CONFIGURATION_PCS2X6G_CFG_LF_GEN_DIS  VTSS_BIT(7)
#define  VTSS_F_DEV10G_PCS2X6G_CONFIGURATION_PCS2X6G_CFG_AN_LINK_CTRL_ENA  VTSS_BIT(1)
#define  VTSS_F_DEV10G_PCS2X6G_CONFIGURATION_PCS2X6G_CFG_PCS_ENA  VTSS_BIT(0)

#define VTSS_DEV10G_PCS2X6G_STATUS_PCS2X6G_STATUS(target)  VTSS_IOREG(target,0x54)
#define  VTSS_F_DEV10G_PCS2X6G_STATUS_PCS2X6G_STATUS_SIGNAL_DETECT(x)  VTSS_ENCODE_BITFIELD(x,12,4)
#define  VTSS_M_DEV10G_PCS2X6G_STATUS_PCS2X6G_STATUS_SIGNAL_DETECT     VTSS_ENCODE_BITMASK(12,4)
#define  VTSS_X_DEV10G_PCS2X6G_STATUS_PCS2X6G_STATUS_SIGNAL_DETECT(x)  VTSS_EXTRACT_BITFIELD(x,12,4)
#define  VTSS_F_DEV10G_PCS2X6G_STATUS_PCS2X6G_STATUS_RX_ALIGNMENT_STATUS  VTSS_BIT(4)
#define  VTSS_F_DEV10G_PCS2X6G_STATUS_PCS2X6G_STATUS_RX_SYNC_STATUS(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_DEV10G_PCS2X6G_STATUS_PCS2X6G_STATUS_RX_SYNC_STATUS     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_DEV10G_PCS2X6G_STATUS_PCS2X6G_STATUS_RX_SYNC_STATUS(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_DEV10G_PCS2X6G_STATUS_PCS2X6G_ERR_STATUS(target)  VTSS_IOREG(target,0x55)
#define  VTSS_F_DEV10G_PCS2X6G_STATUS_PCS2X6G_ERR_STATUS_XGMII_ERR_STICKY  VTSS_BIT(6)
#define  VTSS_F_DEV10G_PCS2X6G_STATUS_PCS2X6G_ERR_STATUS_C64B66B_ERR_STICKY  VTSS_BIT(5)
#define  VTSS_F_DEV10G_PCS2X6G_STATUS_PCS2X6G_ERR_STATUS_ALIGNMENT_LOST_STICKY  VTSS_BIT(4)
#define  VTSS_F_DEV10G_PCS2X6G_STATUS_PCS2X6G_ERR_STATUS_SYNC_LOST_STICKY(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_DEV10G_PCS2X6G_STATUS_PCS2X6G_ERR_STATUS_SYNC_LOST_STICKY     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_DEV10G_PCS2X6G_STATUS_PCS2X6G_ERR_STATUS_SYNC_LOST_STICKY(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_DEV10G_PCS2X6G_STATUS_PCS2X6G_ERR_CNT_STAT(target)  VTSS_IOREG(target,0x56)
#define  VTSS_F_DEV10G_PCS2X6G_STATUS_PCS2X6G_ERR_CNT_STAT_ERR_64B66BDEC(x)  VTSS_ENCODE_BITFIELD(x,0,24)
#define  VTSS_M_DEV10G_PCS2X6G_STATUS_PCS2X6G_ERR_CNT_STAT_ERR_64B66BDEC     VTSS_ENCODE_BITMASK(0,24)
#define  VTSS_X_DEV10G_PCS2X6G_STATUS_PCS2X6G_ERR_CNT_STAT_ERR_64B66BDEC(x)  VTSS_EXTRACT_BITFIELD(x,0,24)

#define VTSS_DEV10G_PCS2X6G_EXT_CONFIGURATION_PCS2X6G_EXT_CFG(target)  VTSS_IOREG(target,0x57)
#define  VTSS_F_DEV10G_PCS2X6G_EXT_CONFIGURATION_PCS2X6G_EXT_CFG_INVERT_HMBUS  VTSS_BIT(1)
#define  VTSS_F_DEV10G_PCS2X6G_EXT_CONFIGURATION_PCS2X6G_EXT_CFG_FLIP_HMBUS  VTSS_BIT(0)

#define VTSS_DEV10G_DEV_CFG_STATUS_DEV_RST_CTRL(target)  VTSS_IOREG(target,0x58)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_DEV_RST_CTRL_PARDET_MODE_ENA  VTSS_BIT(23)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_DEV_RST_CTRL_SPEED_SEL(x)  VTSS_ENCODE_BITFIELD(x,20,3)
#define  VTSS_M_DEV10G_DEV_CFG_STATUS_DEV_RST_CTRL_SPEED_SEL     VTSS_ENCODE_BITMASK(20,3)
#define  VTSS_X_DEV10G_DEV_CFG_STATUS_DEV_RST_CTRL_SPEED_SEL(x)  VTSS_EXTRACT_BITFIELD(x,20,3)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_DEV_RST_CTRL_PCS_TX_RST  VTSS_BIT(12)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_DEV_RST_CTRL_PCS_RX_RST  VTSS_BIT(8)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_DEV_RST_CTRL_MAC_TX_RST  VTSS_BIT(4)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_DEV_RST_CTRL_MAC_RX_RST  VTSS_BIT(0)

#define VTSS_DEV10G_DEV_CFG_STATUS_DEV_PORT_PROTECT(target)  VTSS_IOREG(target,0x59)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_DEV_PORT_PROTECT_PORT_PROTECT_ID(x)  VTSS_ENCODE_BITFIELD(x,4,2)
#define  VTSS_M_DEV10G_DEV_CFG_STATUS_DEV_PORT_PROTECT_PORT_PROTECT_ID     VTSS_ENCODE_BITMASK(4,2)
#define  VTSS_X_DEV10G_DEV_CFG_STATUS_DEV_PORT_PROTECT_PORT_PROTECT_ID(x)  VTSS_EXTRACT_BITFIELD(x,4,2)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_DEV_PORT_PROTECT_PORT_PROTECT_ENA  VTSS_BIT(0)

#define VTSS_DEV10G_DEV_CFG_STATUS_DEV_LB_CFG(target)  VTSS_IOREG(target,0x5a)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_DEV_LB_CFG_TAXI_PHY_LB_ENA  VTSS_BIT(4)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_DEV_LB_CFG_TAXI_HOST_LB_ENA  VTSS_BIT(0)

#define VTSS_DEV10G_DEV_CFG_STATUS_DEV_MISC_CFG(target)  VTSS_IOREG(target,0x5b)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_DEV_MISC_CFG_TX_FCS_UPDATE_SEL(x)  VTSS_ENCODE_BITFIELD(x,16,2)
#define  VTSS_M_DEV10G_DEV_CFG_STATUS_DEV_MISC_CFG_TX_FCS_UPDATE_SEL     VTSS_ENCODE_BITMASK(16,2)
#define  VTSS_X_DEV10G_DEV_CFG_STATUS_DEV_MISC_CFG_TX_FCS_UPDATE_SEL(x)  VTSS_EXTRACT_BITFIELD(x,16,2)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_DEV_MISC_CFG_RX_RESYNC_MAX_FILL_LVL_CLR  VTSS_BIT(13)

#define VTSS_DEV10G_DEV_CFG_STATUS_DEV_STICKY(target)  VTSS_IOREG(target,0x5c)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_DEV_STICKY_RX_RESYNC_FIFO_OFLW_STICKY  VTSS_BIT(12)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_DEV_STICKY_RX_SOF_STICKY  VTSS_BIT(10)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_DEV_STICKY_RX_EOF_STICKY  VTSS_BIT(8)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_DEV_STICKY_TX_EOF_STICKY  VTSS_BIT(3)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_DEV_STICKY_TX_SOF_STICKY  VTSS_BIT(2)

#define VTSS_DEV10G_DEV_CFG_STATUS_INTR(target)  VTSS_IOREG(target,0x5d)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_INTR_PCS_BR_INTR  VTSS_BIT(4)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_INTR_TX_LPI_INTR  VTSS_BIT(3)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_INTR_RX_LPI_INTR  VTSS_BIT(2)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_INTR_LINK_UP_INTR  VTSS_BIT(1)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_INTR_LINK_DWN_INTR  VTSS_BIT(0)

#define VTSS_DEV10G_DEV_CFG_STATUS_INTR_ENA(target)  VTSS_IOREG(target,0x5e)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_INTR_ENA_PCS_BR_INTR_ENA  VTSS_BIT(4)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_INTR_ENA_TX_LPI_INTR_ENA  VTSS_BIT(3)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_INTR_ENA_RX_LPI_INTR_ENA  VTSS_BIT(2)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_INTR_ENA_LINK_UP_INTR_ENA  VTSS_BIT(1)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_INTR_ENA_LINK_DWN_INTR_ENA  VTSS_BIT(0)

#define VTSS_DEV10G_DEV_CFG_STATUS_INTR_IDENT(target)  VTSS_IOREG(target,0x5f)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_INTR_IDENT_PCS_BR_INTR_IDENT  VTSS_BIT(4)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_INTR_IDENT_TX_LPI_INTR_IDENT  VTSS_BIT(3)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_INTR_IDENT_RX_LPI_INTR_IDENT  VTSS_BIT(2)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_INTR_IDENT_LINK_UP_INTR_IDENT  VTSS_BIT(1)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_INTR_IDENT_LINK_DWN_INTR_IDENT  VTSS_BIT(0)

#define VTSS_DEV10G_DEV_CFG_STATUS_DEV_RX_STATUS(target)  VTSS_IOREG(target,0x60)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_DEV_RX_STATUS_RX_RESYNC_MAX_FILL_LVL(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_DEV10G_DEV_CFG_STATUS_DEV_RX_STATUS_RX_RESYNC_MAX_FILL_LVL     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_DEV10G_DEV_CFG_STATUS_DEV_RX_STATUS_RX_RESYNC_MAX_FILL_LVL(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_DEV10G_DEV_CFG_STATUS_EEE_CFG(target)  VTSS_IOREG(target,0x61)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_EEE_CFG_EEE_ENA  VTSS_BIT(22)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_EEE_CFG_EEE_TIMER_AGE(x)  VTSS_ENCODE_BITFIELD(x,15,7)
#define  VTSS_M_DEV10G_DEV_CFG_STATUS_EEE_CFG_EEE_TIMER_AGE     VTSS_ENCODE_BITMASK(15,7)
#define  VTSS_X_DEV10G_DEV_CFG_STATUS_EEE_CFG_EEE_TIMER_AGE(x)  VTSS_EXTRACT_BITFIELD(x,15,7)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_EEE_CFG_EEE_TIMER_WAKEUP(x)  VTSS_ENCODE_BITFIELD(x,8,7)
#define  VTSS_M_DEV10G_DEV_CFG_STATUS_EEE_CFG_EEE_TIMER_WAKEUP     VTSS_ENCODE_BITMASK(8,7)
#define  VTSS_X_DEV10G_DEV_CFG_STATUS_EEE_CFG_EEE_TIMER_WAKEUP(x)  VTSS_EXTRACT_BITFIELD(x,8,7)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_EEE_CFG_EEE_TIMER_HOLDOFF(x)  VTSS_ENCODE_BITFIELD(x,1,7)
#define  VTSS_M_DEV10G_DEV_CFG_STATUS_EEE_CFG_EEE_TIMER_HOLDOFF     VTSS_ENCODE_BITMASK(1,7)
#define  VTSS_X_DEV10G_DEV_CFG_STATUS_EEE_CFG_EEE_TIMER_HOLDOFF(x)  VTSS_EXTRACT_BITFIELD(x,1,7)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_EEE_CFG_PORT_LPI  VTSS_BIT(0)

#define VTSS_DEV10G_DEV_CFG_STATUS_PFC_PAUSE_MODE_CTRL(target)  VTSS_IOREG(target,0x62)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_PFC_PAUSE_MODE_CTRL_PFC_PAUSE_MODE_SELECT  VTSS_BIT(0)

#define VTSS_DEV10G_DEV_CFG_STATUS_PTP_CFG(target)  VTSS_IOREG(target,0x63)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_PTP_CFG_PTP_ENA  VTSS_BIT(20)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_PTP_CFG_PTP_DOM(x)  VTSS_ENCODE_BITFIELD(x,18,2)
#define  VTSS_M_DEV10G_DEV_CFG_STATUS_PTP_CFG_PTP_DOM     VTSS_ENCODE_BITMASK(18,2)
#define  VTSS_X_DEV10G_DEV_CFG_STATUS_PTP_CFG_PTP_DOM(x)  VTSS_EXTRACT_BITFIELD(x,18,2)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_PTP_CFG_PTP_RX_IO_DLY(x)  VTSS_ENCODE_BITFIELD(x,9,9)
#define  VTSS_M_DEV10G_DEV_CFG_STATUS_PTP_CFG_PTP_RX_IO_DLY     VTSS_ENCODE_BITMASK(9,9)
#define  VTSS_X_DEV10G_DEV_CFG_STATUS_PTP_CFG_PTP_RX_IO_DLY(x)  VTSS_EXTRACT_BITFIELD(x,9,9)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_PTP_CFG_PTP_TX_IO_DLY(x)  VTSS_ENCODE_BITFIELD(x,0,9)
#define  VTSS_M_DEV10G_DEV_CFG_STATUS_PTP_CFG_PTP_TX_IO_DLY     VTSS_ENCODE_BITMASK(0,9)
#define  VTSS_X_DEV10G_DEV_CFG_STATUS_PTP_CFG_PTP_TX_IO_DLY(x)  VTSS_EXTRACT_BITFIELD(x,0,9)

#define VTSS_DEV10G_DEV_CFG_STATUS_PTP_CFG_BTDLY(target)  VTSS_IOREG(target,0x64)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_PTP_CFG_BTDLY_PTP_RX_BT_DLY(x)  VTSS_ENCODE_BITFIELD(x,16,4)
#define  VTSS_M_DEV10G_DEV_CFG_STATUS_PTP_CFG_BTDLY_PTP_RX_BT_DLY     VTSS_ENCODE_BITMASK(16,4)
#define  VTSS_X_DEV10G_DEV_CFG_STATUS_PTP_CFG_BTDLY_PTP_RX_BT_DLY(x)  VTSS_EXTRACT_BITFIELD(x,16,4)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_PTP_CFG_BTDLY_PTP_TX_BT_DLY(x)  VTSS_ENCODE_BITFIELD(x,12,4)
#define  VTSS_M_DEV10G_DEV_CFG_STATUS_PTP_CFG_BTDLY_PTP_TX_BT_DLY     VTSS_ENCODE_BITMASK(12,4)
#define  VTSS_X_DEV10G_DEV_CFG_STATUS_PTP_CFG_BTDLY_PTP_TX_BT_DLY(x)  VTSS_EXTRACT_BITFIELD(x,12,4)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_PTP_CFG_BTDLY_PTP_RX_GEARBOX_OFS(x)  VTSS_ENCODE_BITFIELD(x,6,6)
#define  VTSS_M_DEV10G_DEV_CFG_STATUS_PTP_CFG_BTDLY_PTP_RX_GEARBOX_OFS     VTSS_ENCODE_BITMASK(6,6)
#define  VTSS_X_DEV10G_DEV_CFG_STATUS_PTP_CFG_BTDLY_PTP_RX_GEARBOX_OFS(x)  VTSS_EXTRACT_BITFIELD(x,6,6)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_PTP_CFG_BTDLY_PTP_TX_GEARBOX_OFS(x)  VTSS_ENCODE_BITFIELD(x,0,6)
#define  VTSS_M_DEV10G_DEV_CFG_STATUS_PTP_CFG_BTDLY_PTP_TX_GEARBOX_OFS     VTSS_ENCODE_BITMASK(0,6)
#define  VTSS_X_DEV10G_DEV_CFG_STATUS_PTP_CFG_BTDLY_PTP_TX_GEARBOX_OFS(x)  VTSS_EXTRACT_BITFIELD(x,0,6)

#define VTSS_DEV10G_DEV_CFG_STATUS_PTP_EVENTS(target)  VTSS_IOREG(target,0x65)
#define  VTSS_F_DEV10G_DEV_CFG_STATUS_PTP_EVENTS_CF_TOO_BIG_STICKY  VTSS_BIT(0)


#endif /* _VTSS_JAGUAR2_REGS_DEV10G_H_ */
