#ifndef _VTSS_JAGUAR2_REGS_HSCH_H_
#define _VTSS_JAGUAR2_REGS_HSCH_H_

/*
 *
 * VCore-III Register Definitions
 *
 * Copyright (C) 2012 Vitesse Semiconductor Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#include "vtss_jaguar2_regs_common.h"

#define VTSS_HSCH_HSCH_CFG_CIR_CFG(gi)       VTSS_IOREG_IX(VTSS_TO_HSCH,0x0,gi,8,0,0)
#define  VTSS_F_HSCH_HSCH_CFG_CIR_CFG_CIR_RATE(x)  VTSS_ENCODE_BITFIELD(x,6,17)
#define  VTSS_M_HSCH_HSCH_CFG_CIR_CFG_CIR_RATE     VTSS_ENCODE_BITMASK(6,17)
#define  VTSS_X_HSCH_HSCH_CFG_CIR_CFG_CIR_RATE(x)  VTSS_EXTRACT_BITFIELD(x,6,17)
#define  VTSS_F_HSCH_HSCH_CFG_CIR_CFG_CIR_BURST(x)  VTSS_ENCODE_BITFIELD(x,0,6)
#define  VTSS_M_HSCH_HSCH_CFG_CIR_CFG_CIR_BURST     VTSS_ENCODE_BITMASK(0,6)
#define  VTSS_X_HSCH_HSCH_CFG_CIR_CFG_CIR_BURST(x)  VTSS_EXTRACT_BITFIELD(x,0,6)

#define VTSS_HSCH_HSCH_CFG_EIR_CFG(gi)       VTSS_IOREG_IX(VTSS_TO_HSCH,0x0,gi,8,0,1)
#define  VTSS_F_HSCH_HSCH_CFG_EIR_CFG_EIR_RATE(x)  VTSS_ENCODE_BITFIELD(x,7,17)
#define  VTSS_M_HSCH_HSCH_CFG_EIR_CFG_EIR_RATE     VTSS_ENCODE_BITMASK(7,17)
#define  VTSS_X_HSCH_HSCH_CFG_EIR_CFG_EIR_RATE(x)  VTSS_EXTRACT_BITFIELD(x,7,17)
#define  VTSS_F_HSCH_HSCH_CFG_EIR_CFG_EIR_BURST(x)  VTSS_ENCODE_BITFIELD(x,1,6)
#define  VTSS_M_HSCH_HSCH_CFG_EIR_CFG_EIR_BURST     VTSS_ENCODE_BITMASK(1,6)
#define  VTSS_X_HSCH_HSCH_CFG_EIR_CFG_EIR_BURST(x)  VTSS_EXTRACT_BITFIELD(x,1,6)
#define  VTSS_F_HSCH_HSCH_CFG_EIR_CFG_EIR_MARK_ENA  VTSS_BIT(0)

#define VTSS_HSCH_HSCH_CFG_SE_CFG(gi)        VTSS_IOREG_IX(VTSS_TO_HSCH,0x0,gi,8,0,2)
#define  VTSS_F_HSCH_HSCH_CFG_SE_CFG_SE_DWRR_CNT(x)  VTSS_ENCODE_BITFIELD(x,5,6)
#define  VTSS_M_HSCH_HSCH_CFG_SE_CFG_SE_DWRR_CNT     VTSS_ENCODE_BITMASK(5,6)
#define  VTSS_X_HSCH_HSCH_CFG_SE_CFG_SE_DWRR_CNT(x)  VTSS_EXTRACT_BITFIELD(x,5,6)
#define  VTSS_F_HSCH_HSCH_CFG_SE_CFG_SE_AVB_ENA  VTSS_BIT(4)
#define  VTSS_F_HSCH_HSCH_CFG_SE_CFG_SE_FRM_MODE(x)  VTSS_ENCODE_BITFIELD(x,2,2)
#define  VTSS_M_HSCH_HSCH_CFG_SE_CFG_SE_FRM_MODE     VTSS_ENCODE_BITMASK(2,2)
#define  VTSS_X_HSCH_HSCH_CFG_SE_CFG_SE_FRM_MODE(x)  VTSS_EXTRACT_BITFIELD(x,2,2)
#define  VTSS_F_HSCH_HSCH_CFG_SE_CFG_SE_DWRR_FRM_MODE(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_HSCH_HSCH_CFG_SE_CFG_SE_DWRR_FRM_MODE     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_HSCH_HSCH_CFG_SE_CFG_SE_DWRR_FRM_MODE(x)  VTSS_EXTRACT_BITFIELD(x,0,2)

#define VTSS_HSCH_HSCH_CFG_SE_CONNECT(gi)    VTSS_IOREG_IX(VTSS_TO_HSCH,0x0,gi,8,0,3)
#define  VTSS_F_HSCH_HSCH_CFG_SE_CONNECT_SE_INP_IDX(x)  VTSS_ENCODE_BITFIELD(x,18,12)
#define  VTSS_M_HSCH_HSCH_CFG_SE_CONNECT_SE_INP_IDX     VTSS_ENCODE_BITMASK(18,12)
#define  VTSS_X_HSCH_HSCH_CFG_SE_CONNECT_SE_INP_IDX(x)  VTSS_EXTRACT_BITFIELD(x,18,12)
#define  VTSS_F_HSCH_HSCH_CFG_SE_CONNECT_SE_LEAK_IDX(x)  VTSS_ENCODE_BITFIELD(x,12,6)
#define  VTSS_M_HSCH_HSCH_CFG_SE_CONNECT_SE_LEAK_IDX     VTSS_ENCODE_BITMASK(12,6)
#define  VTSS_X_HSCH_HSCH_CFG_SE_CONNECT_SE_LEAK_IDX(x)  VTSS_EXTRACT_BITFIELD(x,12,6)
#define  VTSS_F_HSCH_HSCH_CFG_SE_CONNECT_SE_OUTP_IDX(x)  VTSS_ENCODE_BITFIELD(x,6,6)
#define  VTSS_M_HSCH_HSCH_CFG_SE_CONNECT_SE_OUTP_IDX     VTSS_ENCODE_BITMASK(6,6)
#define  VTSS_X_HSCH_HSCH_CFG_SE_CONNECT_SE_OUTP_IDX(x)  VTSS_EXTRACT_BITFIELD(x,6,6)
#define  VTSS_F_HSCH_HSCH_CFG_SE_CONNECT_SE_OUTP_CON(x)  VTSS_ENCODE_BITFIELD(x,0,6)
#define  VTSS_M_HSCH_HSCH_CFG_SE_CONNECT_SE_OUTP_CON     VTSS_ENCODE_BITMASK(0,6)
#define  VTSS_X_HSCH_HSCH_CFG_SE_CONNECT_SE_OUTP_CON(x)  VTSS_EXTRACT_BITFIELD(x,0,6)

#define VTSS_HSCH_HSCH_CFG_SE_DLB_SENSE(gi)  VTSS_IOREG_IX(VTSS_TO_HSCH,0x0,gi,8,0,4)
#define  VTSS_F_HSCH_HSCH_CFG_SE_DLB_SENSE_SE_DLB_PRIO(x)  VTSS_ENCODE_BITFIELD(x,15,3)
#define  VTSS_M_HSCH_HSCH_CFG_SE_DLB_SENSE_SE_DLB_PRIO     VTSS_ENCODE_BITMASK(15,3)
#define  VTSS_X_HSCH_HSCH_CFG_SE_DLB_SENSE_SE_DLB_PRIO(x)  VTSS_EXTRACT_BITFIELD(x,15,3)
#define  VTSS_F_HSCH_HSCH_CFG_SE_DLB_SENSE_SE_DLB_SPORT(x)  VTSS_ENCODE_BITFIELD(x,9,6)
#define  VTSS_M_HSCH_HSCH_CFG_SE_DLB_SENSE_SE_DLB_SPORT     VTSS_ENCODE_BITMASK(9,6)
#define  VTSS_X_HSCH_HSCH_CFG_SE_DLB_SENSE_SE_DLB_SPORT(x)  VTSS_EXTRACT_BITFIELD(x,9,6)
#define  VTSS_F_HSCH_HSCH_CFG_SE_DLB_SENSE_SE_DLB_DPORT(x)  VTSS_ENCODE_BITFIELD(x,3,6)
#define  VTSS_M_HSCH_HSCH_CFG_SE_DLB_SENSE_SE_DLB_DPORT     VTSS_ENCODE_BITMASK(3,6)
#define  VTSS_X_HSCH_HSCH_CFG_SE_DLB_SENSE_SE_DLB_DPORT(x)  VTSS_EXTRACT_BITFIELD(x,3,6)
#define  VTSS_F_HSCH_HSCH_CFG_SE_DLB_SENSE_SE_DLB_PRIO_ENA  VTSS_BIT(2)
#define  VTSS_F_HSCH_HSCH_CFG_SE_DLB_SENSE_SE_DLB_SPORT_ENA  VTSS_BIT(1)
#define  VTSS_F_HSCH_HSCH_CFG_SE_DLB_SENSE_SE_DLB_DPORT_ENA  VTSS_BIT(0)

#define VTSS_HSCH_HSCH_STATUS_CIR_STATE(gi)  VTSS_IOREG_IX(VTSS_TO_HSCH,0x8000,gi,4,0,0)
#define  VTSS_F_HSCH_HSCH_STATUS_CIR_STATE_CIR_LVL(x)  VTSS_ENCODE_BITFIELD(x,2,24)
#define  VTSS_M_HSCH_HSCH_STATUS_CIR_STATE_CIR_LVL     VTSS_ENCODE_BITMASK(2,24)
#define  VTSS_X_HSCH_HSCH_STATUS_CIR_STATE_CIR_LVL(x)  VTSS_EXTRACT_BITFIELD(x,2,24)
#define  VTSS_F_HSCH_HSCH_STATUS_CIR_STATE_RESERVED(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_HSCH_HSCH_STATUS_CIR_STATE_RESERVED     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_HSCH_HSCH_STATUS_CIR_STATE_RESERVED(x)  VTSS_EXTRACT_BITFIELD(x,0,2)

#define VTSS_HSCH_HSCH_STATUS_EIR_STATE(gi)  VTSS_IOREG_IX(VTSS_TO_HSCH,0x8000,gi,4,0,1)
#define  VTSS_F_HSCH_HSCH_STATUS_EIR_STATE_EIR_LVL(x)  VTSS_ENCODE_BITFIELD(x,0,24)
#define  VTSS_M_HSCH_HSCH_STATUS_EIR_STATE_EIR_LVL     VTSS_ENCODE_BITMASK(0,24)
#define  VTSS_X_HSCH_HSCH_STATUS_EIR_STATE_EIR_LVL(x)  VTSS_EXTRACT_BITFIELD(x,0,24)

#define VTSS_HSCH_HSCH_STATUS_SE_STATE(gi)   VTSS_IOREG_IX(VTSS_TO_HSCH,0x8000,gi,4,0,2)
#define  VTSS_F_HSCH_HSCH_STATUS_SE_STATE_SE_IS_OPEN  VTSS_BIT(1)
#define  VTSS_F_HSCH_HSCH_STATUS_SE_STATE_SE_WAS_YEL  VTSS_BIT(0)

#define VTSS_HSCH_HSCH_INP_STATE_INP_STATE(gi)  VTSS_IOREG_IX(VTSS_TO_HSCH,0xc000,gi,2,0,0)

#define VTSS_HSCH_HSCH_INP_STATE_INP_STATE1(gi)  VTSS_IOREG_IX(VTSS_TO_HSCH,0xc000,gi,2,0,1)

#define VTSS_HSCH_HSCH_DWRR_DWRR_ENTRY(gi)   VTSS_IOREG_IX(VTSS_TO_HSCH,0x7f40,gi,1,0,0)
#define  VTSS_F_HSCH_HSCH_DWRR_DWRR_ENTRY_DWRR_COST(x)  VTSS_ENCODE_BITFIELD(x,20,5)
#define  VTSS_M_HSCH_HSCH_DWRR_DWRR_ENTRY_DWRR_COST     VTSS_ENCODE_BITMASK(20,5)
#define  VTSS_X_HSCH_HSCH_DWRR_DWRR_ENTRY_DWRR_COST(x)  VTSS_EXTRACT_BITFIELD(x,20,5)
#define  VTSS_F_HSCH_HSCH_DWRR_DWRR_ENTRY_DWRR_BALANCE(x)  VTSS_ENCODE_BITFIELD(x,0,20)
#define  VTSS_M_HSCH_HSCH_DWRR_DWRR_ENTRY_DWRR_BALANCE     VTSS_ENCODE_BITMASK(0,20)
#define  VTSS_X_HSCH_HSCH_DWRR_DWRR_ENTRY_DWRR_BALANCE(x)  VTSS_EXTRACT_BITFIELD(x,0,20)

#define VTSS_HSCH_HSCH_MISC_HSCH_MISC_CFG    VTSS_IOREG(VTSS_TO_HSCH,0x7f80)
#define  VTSS_F_HSCH_HSCH_MISC_HSCH_MISC_CFG_SE_CONNECT_VLD  VTSS_BIT(15)
#define  VTSS_F_HSCH_HSCH_MISC_HSCH_MISC_CFG_LEAK_DIS  VTSS_BIT(14)
#define  VTSS_F_HSCH_HSCH_MISC_HSCH_MISC_CFG_FRM_ADJ(x)  VTSS_ENCODE_BITFIELD(x,9,5)
#define  VTSS_M_HSCH_HSCH_MISC_HSCH_MISC_CFG_FRM_ADJ     VTSS_ENCODE_BITMASK(9,5)
#define  VTSS_X_HSCH_HSCH_MISC_HSCH_MISC_CFG_FRM_ADJ(x)  VTSS_EXTRACT_BITFIELD(x,9,5)
#define  VTSS_F_HSCH_HSCH_MISC_HSCH_MISC_CFG_HSCH_LARGE_CNT(x)  VTSS_ENCODE_BITFIELD(x,0,9)
#define  VTSS_M_HSCH_HSCH_MISC_HSCH_MISC_CFG_HSCH_LARGE_CNT     VTSS_ENCODE_BITMASK(0,9)
#define  VTSS_X_HSCH_HSCH_MISC_HSCH_MISC_CFG_HSCH_LARGE_CNT(x)  VTSS_EXTRACT_BITFIELD(x,0,9)

#define VTSS_HSCH_HSCH_MISC_HSCH_CFG_CFG     VTSS_IOREG(VTSS_TO_HSCH,0x7f81)
#define  VTSS_F_HSCH_HSCH_MISC_HSCH_CFG_CFG_DWRR_IDX(x)  VTSS_ENCODE_BITFIELD(x,2,12)
#define  VTSS_M_HSCH_HSCH_MISC_HSCH_CFG_CFG_DWRR_IDX     VTSS_ENCODE_BITMASK(2,12)
#define  VTSS_X_HSCH_HSCH_MISC_HSCH_CFG_CFG_DWRR_IDX(x)  VTSS_EXTRACT_BITFIELD(x,2,12)
#define  VTSS_F_HSCH_HSCH_MISC_HSCH_CFG_CFG_HSCH_LAYER(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_HSCH_HSCH_MISC_HSCH_CFG_CFG_HSCH_LAYER     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_HSCH_HSCH_MISC_HSCH_CFG_CFG_HSCH_LAYER(x)  VTSS_EXTRACT_BITFIELD(x,0,2)

#define VTSS_HSCH_HSCH_MISC_PORT_MODE(ri)    VTSS_IOREG(VTSS_TO_HSCH,0x7f82 + (ri))
#define  VTSS_F_HSCH_HSCH_MISC_PORT_MODE_DEQUEUE_DIS  VTSS_BIT(5)
#define  VTSS_F_HSCH_HSCH_MISC_PORT_MODE_FLUSH_ENA  VTSS_BIT(4)
#define  VTSS_F_HSCH_HSCH_MISC_PORT_MODE_AGE_DIS  VTSS_BIT(3)
#define  VTSS_F_HSCH_HSCH_MISC_PORT_MODE_TRUNC_ENA  VTSS_BIT(2)
#define  VTSS_F_HSCH_HSCH_MISC_PORT_MODE_CPU_PRIO_MODE  VTSS_BIT(1)
#define  VTSS_F_HSCH_HSCH_MISC_PORT_MODE_MIDLAYER_ENA  VTSS_BIT(0)

#define VTSS_HSCH_HSCH_LEAK_LISTS_HSCH_LEAK_CFG(gi,ri)  VTSS_IOREG_IX(VTSS_TO_HSCH,0x7f08,gi,4,ri,0)
#define  VTSS_F_HSCH_HSCH_LEAK_LISTS_HSCH_LEAK_CFG_LEAK_TIME(x)  VTSS_ENCODE_BITFIELD(x,13,16)
#define  VTSS_M_HSCH_HSCH_LEAK_LISTS_HSCH_LEAK_CFG_LEAK_TIME     VTSS_ENCODE_BITMASK(13,16)
#define  VTSS_X_HSCH_HSCH_LEAK_LISTS_HSCH_LEAK_CFG_LEAK_TIME(x)  VTSS_EXTRACT_BITFIELD(x,13,16)
#define  VTSS_F_HSCH_HSCH_LEAK_LISTS_HSCH_LEAK_CFG_LEAK_FIRST(x)  VTSS_ENCODE_BITFIELD(x,1,12)
#define  VTSS_M_HSCH_HSCH_LEAK_LISTS_HSCH_LEAK_CFG_LEAK_FIRST     VTSS_ENCODE_BITMASK(1,12)
#define  VTSS_X_HSCH_HSCH_LEAK_LISTS_HSCH_LEAK_CFG_LEAK_FIRST(x)  VTSS_EXTRACT_BITFIELD(x,1,12)
#define  VTSS_F_HSCH_HSCH_LEAK_LISTS_HSCH_LEAK_CFG_LEAK_ERR  VTSS_BIT(0)

#define VTSS_HSCH_MISC_EVENTS_CORE           VTSS_IOREG(VTSS_TO_HSCH,0x7f14)
#define  VTSS_F_HSCH_MISC_EVENTS_CORE_EV_HSCH(x)  VTSS_ENCODE_BITFIELD(x,5,7)
#define  VTSS_M_HSCH_MISC_EVENTS_CORE_EV_HSCH     VTSS_ENCODE_BITMASK(5,7)
#define  VTSS_X_HSCH_MISC_EVENTS_CORE_EV_HSCH(x)  VTSS_EXTRACT_BITFIELD(x,5,7)
#define  VTSS_F_HSCH_MISC_EVENTS_CORE_EV_FRD(x)  VTSS_ENCODE_BITFIELD(x,1,4)
#define  VTSS_M_HSCH_MISC_EVENTS_CORE_EV_FRD     VTSS_ENCODE_BITMASK(1,4)
#define  VTSS_X_HSCH_MISC_EVENTS_CORE_EV_FRD(x)  VTSS_EXTRACT_BITFIELD(x,1,4)
#define  VTSS_F_HSCH_MISC_EVENTS_CORE_EV_ENQ_ERR  VTSS_BIT(0)

#define VTSS_HSCH_MISC_EVENT_ENQ_ERR         VTSS_IOREG(VTSS_TO_HSCH,0x7f15)
#define  VTSS_F_HSCH_MISC_EVENT_ENQ_ERR_ENQ_ERR_PORT(x)  VTSS_ENCODE_BITFIELD(x,18,6)
#define  VTSS_M_HSCH_MISC_EVENT_ENQ_ERR_ENQ_ERR_PORT     VTSS_ENCODE_BITMASK(18,6)
#define  VTSS_X_HSCH_MISC_EVENT_ENQ_ERR_ENQ_ERR_PORT(x)  VTSS_EXTRACT_BITFIELD(x,18,6)
#define  VTSS_F_HSCH_MISC_EVENT_ENQ_ERR_ENQ_ERR_SE(x)  VTSS_ENCODE_BITFIELD(x,6,12)
#define  VTSS_M_HSCH_MISC_EVENT_ENQ_ERR_ENQ_ERR_SE     VTSS_ENCODE_BITMASK(6,12)
#define  VTSS_X_HSCH_MISC_EVENT_ENQ_ERR_ENQ_ERR_SE(x)  VTSS_EXTRACT_BITFIELD(x,6,12)
#define  VTSS_F_HSCH_MISC_EVENT_ENQ_ERR_ENQ_ERR_INP(x)  VTSS_ENCODE_BITFIELD(x,0,6)
#define  VTSS_M_HSCH_MISC_EVENT_ENQ_ERR_ENQ_ERR_INP     VTSS_ENCODE_BITMASK(0,6)
#define  VTSS_X_HSCH_MISC_EVENT_ENQ_ERR_ENQ_ERR_INP(x)  VTSS_EXTRACT_BITFIELD(x,0,6)


#endif /* _VTSS_JAGUAR2_REGS_HSCH_H_ */
