#ifndef _VTSS_JAGUAR2_REGS_ASM_H_
#define _VTSS_JAGUAR2_REGS_ASM_H_

/*
 *
 * VCore-III Register Definitions
 *
 * Copyright (C) 2012 Vitesse Semiconductor Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#include "vtss_jaguar2_regs_common.h"

#define VTSS_ASM_DEV_STATISTICS_RX_IN_BYTES_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,0)

#define VTSS_ASM_DEV_STATISTICS_RX_SYMBOL_ERR_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,1)

#define VTSS_ASM_DEV_STATISTICS_RX_PAUSE_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,2)

#define VTSS_ASM_DEV_STATISTICS_RX_UNSUP_OPCODE_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,3)

#define VTSS_ASM_DEV_STATISTICS_RX_OK_BYTES_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,4)

#define VTSS_ASM_DEV_STATISTICS_RX_BAD_BYTES_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,5)

#define VTSS_ASM_DEV_STATISTICS_RX_UC_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,6)

#define VTSS_ASM_DEV_STATISTICS_RX_MC_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,7)

#define VTSS_ASM_DEV_STATISTICS_RX_BC_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,8)

#define VTSS_ASM_DEV_STATISTICS_RX_CRC_ERR_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,9)

#define VTSS_ASM_DEV_STATISTICS_RX_UNDERSIZE_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,10)

#define VTSS_ASM_DEV_STATISTICS_RX_FRAGMENTS_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,11)

#define VTSS_ASM_DEV_STATISTICS_RX_IN_RANGE_LEN_ERR_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,12)

#define VTSS_ASM_DEV_STATISTICS_RX_OUT_OF_RANGE_LEN_ERR_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,13)

#define VTSS_ASM_DEV_STATISTICS_RX_OVERSIZE_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,14)

#define VTSS_ASM_DEV_STATISTICS_RX_JABBERS_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,15)

#define VTSS_ASM_DEV_STATISTICS_RX_SIZE64_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,16)

#define VTSS_ASM_DEV_STATISTICS_RX_SIZE65TO127_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,17)

#define VTSS_ASM_DEV_STATISTICS_RX_SIZE128TO255_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,18)

#define VTSS_ASM_DEV_STATISTICS_RX_SIZE256TO511_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,19)

#define VTSS_ASM_DEV_STATISTICS_RX_SIZE512TO1023_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,20)

#define VTSS_ASM_DEV_STATISTICS_RX_SIZE1024TO1518_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,21)

#define VTSS_ASM_DEV_STATISTICS_RX_SIZE1519TOMAX_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,22)

#define VTSS_ASM_DEV_STATISTICS_RX_IPG_SHRINK_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,23)

#define VTSS_ASM_DEV_STATISTICS_TX_OUT_BYTES_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,24)

#define VTSS_ASM_DEV_STATISTICS_TX_PAUSE_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,25)

#define VTSS_ASM_DEV_STATISTICS_TX_OK_BYTES_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,26)

#define VTSS_ASM_DEV_STATISTICS_TX_UC_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,27)

#define VTSS_ASM_DEV_STATISTICS_TX_MC_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,28)

#define VTSS_ASM_DEV_STATISTICS_TX_BC_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,29)

#define VTSS_ASM_DEV_STATISTICS_TX_SIZE64_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,30)

#define VTSS_ASM_DEV_STATISTICS_TX_SIZE65TO127_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,31)

#define VTSS_ASM_DEV_STATISTICS_TX_SIZE128TO255_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,32)

#define VTSS_ASM_DEV_STATISTICS_TX_SIZE256TO511_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,33)

#define VTSS_ASM_DEV_STATISTICS_TX_SIZE512TO1023_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,34)

#define VTSS_ASM_DEV_STATISTICS_TX_SIZE1024TO1518_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,35)

#define VTSS_ASM_DEV_STATISTICS_TX_SIZE1519TOMAX_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,36)

#define VTSS_ASM_DEV_STATISTICS_RX_ALIGNMENT_LOST_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,37)

#define VTSS_ASM_DEV_STATISTICS_RX_TAGGED_FRMS_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,38)

#define VTSS_ASM_DEV_STATISTICS_RX_UNTAGGED_FRMS_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,39)

#define VTSS_ASM_DEV_STATISTICS_TX_TAGGED_FRMS_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,40)

#define VTSS_ASM_DEV_STATISTICS_TX_UNTAGGED_FRMS_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,41)

#define VTSS_ASM_DEV_STATISTICS_TX_MULTI_COLL_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,42)

#define VTSS_ASM_DEV_STATISTICS_TX_LATE_COLL_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,43)

#define VTSS_ASM_DEV_STATISTICS_TX_XCOLL_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,44)

#define VTSS_ASM_DEV_STATISTICS_TX_DEFER_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,45)

#define VTSS_ASM_DEV_STATISTICS_TX_XDEFER_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,46)

#define VTSS_ASM_DEV_STATISTICS_TX_BACKOFF1_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,47)

#define VTSS_ASM_DEV_STATISTICS_TX_CSENSE_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,48)

#define VTSS_ASM_DEV_STATISTICS_RX_IN_BYTES_MSB_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,49)
#define  VTSS_F_ASM_DEV_STATISTICS_RX_IN_BYTES_MSB_CNT_RX_IN_BYTES_MSB_CNT(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_ASM_DEV_STATISTICS_RX_IN_BYTES_MSB_CNT_RX_IN_BYTES_MSB_CNT     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_ASM_DEV_STATISTICS_RX_IN_BYTES_MSB_CNT_RX_IN_BYTES_MSB_CNT(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_ASM_DEV_STATISTICS_RX_OK_BYTES_MSB_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,50)
#define  VTSS_F_ASM_DEV_STATISTICS_RX_OK_BYTES_MSB_CNT_RX_OK_BYTES_MSB_CNT(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_ASM_DEV_STATISTICS_RX_OK_BYTES_MSB_CNT_RX_OK_BYTES_MSB_CNT     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_ASM_DEV_STATISTICS_RX_OK_BYTES_MSB_CNT_RX_OK_BYTES_MSB_CNT(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_ASM_DEV_STATISTICS_RX_BAD_BYTES_MSB_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,51)
#define  VTSS_F_ASM_DEV_STATISTICS_RX_BAD_BYTES_MSB_CNT_RX_BAD_BYTES_MSB_CNT(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_ASM_DEV_STATISTICS_RX_BAD_BYTES_MSB_CNT_RX_BAD_BYTES_MSB_CNT     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_ASM_DEV_STATISTICS_RX_BAD_BYTES_MSB_CNT_RX_BAD_BYTES_MSB_CNT(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_ASM_DEV_STATISTICS_TX_OUT_BYTES_MSB_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,52)
#define  VTSS_F_ASM_DEV_STATISTICS_TX_OUT_BYTES_MSB_CNT_TX_OUT_BYTES_MSB_CNT(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_ASM_DEV_STATISTICS_TX_OUT_BYTES_MSB_CNT_TX_OUT_BYTES_MSB_CNT     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_ASM_DEV_STATISTICS_TX_OUT_BYTES_MSB_CNT_TX_OUT_BYTES_MSB_CNT(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_ASM_DEV_STATISTICS_TX_OK_BYTES_MSB_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,53)
#define  VTSS_F_ASM_DEV_STATISTICS_TX_OK_BYTES_MSB_CNT_TX_OK_BYTES_MSB_CNT(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_ASM_DEV_STATISTICS_TX_OK_BYTES_MSB_CNT_TX_OK_BYTES_MSB_CNT     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_ASM_DEV_STATISTICS_TX_OK_BYTES_MSB_CNT_TX_OK_BYTES_MSB_CNT(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_ASM_DEV_STATISTICS_RX_SYNC_LOST_ERR_CNT(gi)  VTSS_IOREG_IX(VTSS_TO_ASM,0x0,gi,64,0,54)

#define VTSS_ASM_CFG_STAT_CFG                VTSS_IOREG(VTSS_TO_ASM,0xd42)
#define  VTSS_F_ASM_CFG_STAT_CFG_STAT_CNT_CLR_SHOT  VTSS_BIT(0)

#define VTSS_ASM_CFG_MAC_ADDR_HIGH_CFG(ri)   VTSS_IOREG(VTSS_TO_ASM,0xd43 + (ri))
#define  VTSS_F_ASM_CFG_MAC_ADDR_HIGH_CFG_MAC_ADDR_HIGH(x)  VTSS_ENCODE_BITFIELD(x,0,24)
#define  VTSS_M_ASM_CFG_MAC_ADDR_HIGH_CFG_MAC_ADDR_HIGH     VTSS_ENCODE_BITMASK(0,24)
#define  VTSS_X_ASM_CFG_MAC_ADDR_HIGH_CFG_MAC_ADDR_HIGH(x)  VTSS_EXTRACT_BITFIELD(x,0,24)

#define VTSS_ASM_CFG_MAC_ADDR_LOW_CFG(ri)    VTSS_IOREG(VTSS_TO_ASM,0xd7a + (ri))
#define  VTSS_F_ASM_CFG_MAC_ADDR_LOW_CFG_MAC_ADDR_LOW(x)  VTSS_ENCODE_BITFIELD(x,0,24)
#define  VTSS_M_ASM_CFG_MAC_ADDR_LOW_CFG_MAC_ADDR_LOW     VTSS_ENCODE_BITMASK(0,24)
#define  VTSS_X_ASM_CFG_MAC_ADDR_LOW_CFG_MAC_ADDR_LOW(x)  VTSS_EXTRACT_BITFIELD(x,0,24)

#define VTSS_ASM_CFG_PORT_CFG(ri)            VTSS_IOREG(VTSS_TO_ASM,0xdb1 + (ri))
#define  VTSS_F_ASM_CFG_PORT_CFG_CSC_STAT_DIS  VTSS_BIT(11)
#define  VTSS_F_ASM_CFG_PORT_CFG_HIH_AFTER_PREAMBLE_ENA  VTSS_BIT(10)
#define  VTSS_F_ASM_CFG_PORT_CFG_IGN_TAXI_ABORT_ENA  VTSS_BIT(9)
#define  VTSS_F_ASM_CFG_PORT_CFG_NO_PREAMBLE_ENA  VTSS_BIT(8)
#define  VTSS_F_ASM_CFG_PORT_CFG_SKIP_PREAMBLE_ENA  VTSS_BIT(7)
#define  VTSS_F_ASM_CFG_PORT_CFG_FRM_AGING_DIS  VTSS_BIT(6)
#define  VTSS_F_ASM_CFG_PORT_CFG_PAD_ENA      VTSS_BIT(5)
#define  VTSS_F_ASM_CFG_PORT_CFG_INJ_DISCARD_CFG(x)  VTSS_ENCODE_BITFIELD(x,3,2)
#define  VTSS_M_ASM_CFG_PORT_CFG_INJ_DISCARD_CFG     VTSS_ENCODE_BITMASK(3,2)
#define  VTSS_X_ASM_CFG_PORT_CFG_INJ_DISCARD_CFG(x)  VTSS_EXTRACT_BITFIELD(x,3,2)
#define  VTSS_F_ASM_CFG_PORT_CFG_INJ_FORMAT_CFG(x)  VTSS_ENCODE_BITFIELD(x,1,2)
#define  VTSS_M_ASM_CFG_PORT_CFG_INJ_FORMAT_CFG     VTSS_ENCODE_BITMASK(1,2)
#define  VTSS_X_ASM_CFG_PORT_CFG_INJ_FORMAT_CFG(x)  VTSS_EXTRACT_BITFIELD(x,1,2)
#define  VTSS_F_ASM_CFG_PORT_CFG_VSTAX2_AWR_ENA  VTSS_BIT(0)

#define VTSS_ASM_CFG_CPU_FC_CFG              VTSS_IOREG(VTSS_TO_ASM,0xde8)
#define  VTSS_F_ASM_CFG_CPU_FC_CFG_CPU_FC_WM(x)  VTSS_ENCODE_BITFIELD(x,1,3)
#define  VTSS_M_ASM_CFG_CPU_FC_CFG_CPU_FC_WM     VTSS_ENCODE_BITMASK(1,3)
#define  VTSS_X_ASM_CFG_CPU_FC_CFG_CPU_FC_WM(x)  VTSS_EXTRACT_BITFIELD(x,1,3)
#define  VTSS_F_ASM_CFG_CPU_FC_CFG_CPU_FC_ENA  VTSS_BIT(0)

#define VTSS_ASM_CFG_PAUSE_CFG(ri)           VTSS_IOREG(VTSS_TO_ASM,0xde9 + (ri))
#define  VTSS_F_ASM_CFG_PAUSE_CFG_ABORT_PAUSE_ENA  VTSS_BIT(0)
#define  VTSS_F_ASM_CFG_PAUSE_CFG_ABORT_CTRL_ENA  VTSS_BIT(1)

#define VTSS_ASM_CFG_INJ_VLAN_CFG            VTSS_IOREG(VTSS_TO_ASM,0xe20)
#define  VTSS_F_ASM_CFG_INJ_VLAN_CFG_INJ_VID_CFG(x)  VTSS_ENCODE_BITFIELD(x,16,12)
#define  VTSS_M_ASM_CFG_INJ_VLAN_CFG_INJ_VID_CFG     VTSS_ENCODE_BITMASK(16,12)
#define  VTSS_X_ASM_CFG_INJ_VLAN_CFG_INJ_VID_CFG(x)  VTSS_EXTRACT_BITFIELD(x,16,12)
#define  VTSS_F_ASM_CFG_INJ_VLAN_CFG_INJ_TPID_CFG(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_ASM_CFG_INJ_VLAN_CFG_INJ_TPID_CFG     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_ASM_CFG_INJ_VLAN_CFG_INJ_TPID_CFG(x)  VTSS_EXTRACT_BITFIELD(x,0,16)

#define VTSS_ASM_DBG_DBG_CFG                 VTSS_IOREG(VTSS_TO_ASM,0xe21)
#define  VTSS_F_ASM_DBG_DBG_CFG_IDLE_TO_VD    VTSS_BIT(2)
#define  VTSS_F_ASM_DBG_DBG_CFG_FIFO_RST(x)   VTSS_ENCODE_BITFIELD(x,3,9)
#define  VTSS_M_ASM_DBG_DBG_CFG_FIFO_RST      VTSS_ENCODE_BITMASK(3,9)
#define  VTSS_X_ASM_DBG_DBG_CFG_FIFO_RST(x)   VTSS_EXTRACT_BITFIELD(x,3,9)
#define  VTSS_F_ASM_DBG_DBG_CFG_CELL_BUS_DIS  VTSS_BIT(1)
#define  VTSS_F_ASM_DBG_DBG_CFG_ABORT_DIS     VTSS_BIT(0)

#define VTSS_ASM_DBG_ERR_STICKY(ri)          VTSS_IOREG(VTSS_TO_ASM,0xe22 + (ri))
#define  VTSS_F_ASM_DBG_ERR_STICKY_FC_UFLW_STICKY  VTSS_BIT(12)
#define  VTSS_F_ASM_DBG_ERR_STICKY_FC_OFLW_STICKY  VTSS_BIT(11)
#define  VTSS_F_ASM_DBG_ERR_STICKY_CC_INTRN_ERR_STICKY  VTSS_BIT(10)
#define  VTSS_F_ASM_DBG_ERR_STICKY_CC_UFLW_STICKY  VTSS_BIT(9)
#define  VTSS_F_ASM_DBG_ERR_STICKY_CC_OFLW_STICKY  VTSS_BIT(8)
#define  VTSS_F_ASM_DBG_ERR_STICKY_CALENDAR_STICKY  VTSS_BIT(7)
#define  VTSS_F_ASM_DBG_ERR_STICKY_UNUSED_BYTES_STICKY  VTSS_BIT(6)
#define  VTSS_F_ASM_DBG_ERR_STICKY_FRAGMENT_STICKY  VTSS_BIT(5)
#define  VTSS_F_ASM_DBG_ERR_STICKY_MISSING_EOF_STICKY  VTSS_BIT(4)
#define  VTSS_F_ASM_DBG_ERR_STICKY_INVLD_ABORT_STICKY  VTSS_BIT(3)
#define  VTSS_F_ASM_DBG_ERR_STICKY_MISSING_SOF_STICKY  VTSS_BIT(2)
#define  VTSS_F_ASM_DBG_ERR_STICKY_MAIN_SM_INTRN_ERR_STICKY  VTSS_BIT(1)
#define  VTSS_F_ASM_DBG_ERR_STICKY_MAIN_SM_OFLW_STICKY  VTSS_BIT(0)

#define VTSS_ASM_DBG_PRE_CNT_OFLW_STICKY     VTSS_IOREG(VTSS_TO_ASM,0xe2b)
#define  VTSS_F_ASM_DBG_PRE_CNT_OFLW_STICKY_UNSUP_OPCODE_PRE_CNT_OFLW_STICKY  VTSS_BIT(1)
#define  VTSS_F_ASM_DBG_PRE_CNT_OFLW_STICKY_PAUSE_FRM_PRE_CNT_OFLW_STICKY  VTSS_BIT(0)

#define VTSS_ASM_PORT_STATUS_PORT_STICKY(ri)  VTSS_IOREG(VTSS_TO_ASM,0xe2c + (ri))
#define  VTSS_F_ASM_PORT_STATUS_PORT_STICKY_IFH_PREFIX_ERR_STICKY  VTSS_BIT(1)
#define  VTSS_F_ASM_PORT_STATUS_PORT_STICKY_FRM_AGING_STICKY  VTSS_BIT(0)

#define VTSS_ASM_PFC_PFC_CFG(gi)             VTSS_IOREG_IX(VTSS_TO_ASM,0x1000,gi,16,0,0)
#define  VTSS_F_ASM_PFC_PFC_CFG_RX_PFC_ENA(x)  VTSS_ENCODE_BITFIELD(x,3,8)
#define  VTSS_M_ASM_PFC_PFC_CFG_RX_PFC_ENA     VTSS_ENCODE_BITMASK(3,8)
#define  VTSS_X_ASM_PFC_PFC_CFG_RX_PFC_ENA(x)  VTSS_EXTRACT_BITFIELD(x,3,8)
#define  VTSS_F_ASM_PFC_PFC_CFG_FC_LINK_SPEED(x)  VTSS_ENCODE_BITFIELD(x,0,3)
#define  VTSS_M_ASM_PFC_PFC_CFG_FC_LINK_SPEED     VTSS_ENCODE_BITMASK(0,3)
#define  VTSS_X_ASM_PFC_PFC_CFG_FC_LINK_SPEED(x)  VTSS_EXTRACT_BITFIELD(x,0,3)

#define VTSS_ASM_PFC_PFC_TIMER(gi,ri)        VTSS_IOREG_IX(VTSS_TO_ASM,0x1000,gi,16,ri,1)
#define  VTSS_F_ASM_PFC_PFC_TIMER_PFC_TIMER_VAL(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_ASM_PFC_PFC_TIMER_PFC_TIMER_VAL     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_ASM_PFC_PFC_TIMER_PFC_TIMER_VAL(x)  VTSS_EXTRACT_BITFIELD(x,0,16)

#define VTSS_ASM_LBK_WM_CFG_VD_FC_WM(ri)     VTSS_IOREG(VTSS_TO_ASM,0xe63 + (ri))
#define  VTSS_F_ASM_LBK_WM_CFG_VD_FC_WM_VD_FC_WM(x)  VTSS_ENCODE_BITFIELD(x,0,5)
#define  VTSS_M_ASM_LBK_WM_CFG_VD_FC_WM_VD_FC_WM     VTSS_ENCODE_BITMASK(0,5)
#define  VTSS_X_ASM_LBK_WM_CFG_VD_FC_WM_VD_FC_WM(x)  VTSS_EXTRACT_BITFIELD(x,0,5)

#define VTSS_ASM_LBK_MISC_CFG_LBK_AGING_DIS(ri)  VTSS_IOREG(VTSS_TO_ASM,0xe65 + (ri))

#define VTSS_ASM_LBK_MISC_CFG_LBK_FIFO_CFG(ri)  VTSS_IOREG(VTSS_TO_ASM,0xe67 + (ri))
#define  VTSS_F_ASM_LBK_MISC_CFG_LBK_FIFO_CFG_FIFO_FLUSH  VTSS_BIT(0)

#define VTSS_ASM_LBK_STAT_LBK_OVFLW_STICKY(ri)  VTSS_IOREG(VTSS_TO_ASM,0xe6a + (ri))

#define VTSS_ASM_LBK_STAT_LBK_AGING_STICKY(ri)  VTSS_IOREG(VTSS_TO_ASM,0xe6c + (ri))

#define VTSS_ASM_RAM_CTRL_RAM_INIT           VTSS_IOREG(VTSS_TO_ASM,0xe6e)
#define  VTSS_F_ASM_RAM_CTRL_RAM_INIT_RAM_INIT  VTSS_BIT(1)
#define  VTSS_F_ASM_RAM_CTRL_RAM_INIT_RAM_ENA  VTSS_BIT(0)

#define VTSS_ASM_COREMEM_CM_ADDR             VTSS_IOREG(VTSS_TO_ASM,0xd40)
#define  VTSS_F_ASM_COREMEM_CM_ADDR_CM_ID(x)  VTSS_ENCODE_BITFIELD(x,22,8)
#define  VTSS_M_ASM_COREMEM_CM_ADDR_CM_ID     VTSS_ENCODE_BITMASK(22,8)
#define  VTSS_X_ASM_COREMEM_CM_ADDR_CM_ID(x)  VTSS_EXTRACT_BITFIELD(x,22,8)
#define  VTSS_F_ASM_COREMEM_CM_ADDR_CM_ADDR(x)  VTSS_ENCODE_BITFIELD(x,0,22)
#define  VTSS_M_ASM_COREMEM_CM_ADDR_CM_ADDR     VTSS_ENCODE_BITMASK(0,22)
#define  VTSS_X_ASM_COREMEM_CM_ADDR_CM_ADDR(x)  VTSS_EXTRACT_BITFIELD(x,0,22)

#define VTSS_ASM_COREMEM_CM_DATA             VTSS_IOREG(VTSS_TO_ASM,0xd41)


#endif /* _VTSS_JAGUAR2_REGS_ASM_H_ */
