#ifndef _VTSS_JAGUAR2_REGS_DEV1G_H_
#define _VTSS_JAGUAR2_REGS_DEV1G_H_

/*
 *
 * VCore-III Register Definitions
 *
 * Copyright (C) 2012 Vitesse Semiconductor Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#include "vtss_jaguar2_regs_common.h"

#define VTSS_DEV1G_DEV_CFG_STATUS_DEV_RST_CTRL(target)  VTSS_IOREG(target,0x0)
#define  VTSS_F_DEV1G_DEV_CFG_STATUS_DEV_RST_CTRL_SPEED_SEL(x)  VTSS_ENCODE_BITFIELD(x,20,2)
#define  VTSS_M_DEV1G_DEV_CFG_STATUS_DEV_RST_CTRL_SPEED_SEL     VTSS_ENCODE_BITMASK(20,2)
#define  VTSS_X_DEV1G_DEV_CFG_STATUS_DEV_RST_CTRL_SPEED_SEL(x)  VTSS_EXTRACT_BITFIELD(x,20,2)
#define  VTSS_F_DEV1G_DEV_CFG_STATUS_DEV_RST_CTRL_PCS_TX_RST  VTSS_BIT(12)
#define  VTSS_F_DEV1G_DEV_CFG_STATUS_DEV_RST_CTRL_PCS_RX_RST  VTSS_BIT(8)
#define  VTSS_F_DEV1G_DEV_CFG_STATUS_DEV_RST_CTRL_MAC_TX_RST  VTSS_BIT(4)
#define  VTSS_F_DEV1G_DEV_CFG_STATUS_DEV_RST_CTRL_MAC_RX_RST  VTSS_BIT(0)

#define VTSS_DEV1G_DEV_CFG_STATUS_DEV_STICKY(target)  VTSS_IOREG(target,0x1)
#define  VTSS_F_DEV1G_DEV_CFG_STATUS_DEV_STICKY_SD_STICKY  VTSS_BIT(14)
#define  VTSS_F_DEV1G_DEV_CFG_STATUS_DEV_STICKY_TX_TAXI_PROT_ERR_STICKY  VTSS_BIT(12)
#define  VTSS_F_DEV1G_DEV_CFG_STATUS_DEV_STICKY_PRE_CNT_OFLW_STICKY  VTSS_BIT(11)
#define  VTSS_F_DEV1G_DEV_CFG_STATUS_DEV_STICKY_RX_OFLW_STICKY  VTSS_BIT(10)
#define  VTSS_F_DEV1G_DEV_CFG_STATUS_DEV_STICKY_TX_EOF_STICKY  VTSS_BIT(3)
#define  VTSS_F_DEV1G_DEV_CFG_STATUS_DEV_STICKY_TX_SOF_STICKY  VTSS_BIT(2)
#define  VTSS_F_DEV1G_DEV_CFG_STATUS_DEV_STICKY_TX_OFLW_STICKY  VTSS_BIT(1)
#define  VTSS_F_DEV1G_DEV_CFG_STATUS_DEV_STICKY_TX_UFLW_STICKY  VTSS_BIT(0)

#define VTSS_DEV1G_DEV_CFG_STATUS_DEV_DBG_CFG(target)  VTSS_IOREG(target,0x2)
#define  VTSS_F_DEV1G_DEV_CFG_STATUS_DEV_DBG_CFG_PRE_CNT_OFLW_ID(x)  VTSS_ENCODE_BITFIELD(x,24,6)
#define  VTSS_M_DEV1G_DEV_CFG_STATUS_DEV_DBG_CFG_PRE_CNT_OFLW_ID     VTSS_ENCODE_BITMASK(24,6)
#define  VTSS_X_DEV1G_DEV_CFG_STATUS_DEV_DBG_CFG_PRE_CNT_OFLW_ID(x)  VTSS_EXTRACT_BITFIELD(x,24,6)
#define  VTSS_F_DEV1G_DEV_CFG_STATUS_DEV_DBG_CFG_TX_MAX_FILL_LVL_CLR_ONE_SHOT  VTSS_BIT(23)
#define  VTSS_F_DEV1G_DEV_CFG_STATUS_DEV_DBG_CFG_TX_MAX_FILL_LVL(x)  VTSS_ENCODE_BITFIELD(x,16,5)
#define  VTSS_M_DEV1G_DEV_CFG_STATUS_DEV_DBG_CFG_TX_MAX_FILL_LVL     VTSS_ENCODE_BITMASK(16,5)
#define  VTSS_X_DEV1G_DEV_CFG_STATUS_DEV_DBG_CFG_TX_MAX_FILL_LVL(x)  VTSS_EXTRACT_BITFIELD(x,16,5)
#define  VTSS_F_DEV1G_DEV_CFG_STATUS_DEV_DBG_CFG_TX_BUF_HIGH_WM(x)  VTSS_ENCODE_BITFIELD(x,8,5)
#define  VTSS_M_DEV1G_DEV_CFG_STATUS_DEV_DBG_CFG_TX_BUF_HIGH_WM     VTSS_ENCODE_BITMASK(8,5)
#define  VTSS_X_DEV1G_DEV_CFG_STATUS_DEV_DBG_CFG_TX_BUF_HIGH_WM(x)  VTSS_EXTRACT_BITFIELD(x,8,5)
#define  VTSS_F_DEV1G_DEV_CFG_STATUS_DEV_DBG_CFG_FCS_UPDATE_CFG(x)  VTSS_ENCODE_BITFIELD(x,2,2)
#define  VTSS_M_DEV1G_DEV_CFG_STATUS_DEV_DBG_CFG_FCS_UPDATE_CFG     VTSS_ENCODE_BITMASK(2,2)
#define  VTSS_X_DEV1G_DEV_CFG_STATUS_DEV_DBG_CFG_FCS_UPDATE_CFG(x)  VTSS_EXTRACT_BITFIELD(x,2,2)
#define  VTSS_F_DEV1G_DEV_CFG_STATUS_DEV_DBG_CFG_IFG_LEN_DIS  VTSS_BIT(1)
#define  VTSS_F_DEV1G_DEV_CFG_STATUS_DEV_DBG_CFG_BACKOFF_CNT_ENA  VTSS_BIT(0)

#define VTSS_DEV1G_DEV_CFG_STATUS_DEV_PORT_PROTECT(target)  VTSS_IOREG(target,0x3)
#define  VTSS_F_DEV1G_DEV_CFG_STATUS_DEV_PORT_PROTECT_PORT_PROTECT_ID(x)  VTSS_ENCODE_BITFIELD(x,4,3)
#define  VTSS_M_DEV1G_DEV_CFG_STATUS_DEV_PORT_PROTECT_PORT_PROTECT_ID     VTSS_ENCODE_BITMASK(4,3)
#define  VTSS_X_DEV1G_DEV_CFG_STATUS_DEV_PORT_PROTECT_PORT_PROTECT_ID(x)  VTSS_EXTRACT_BITFIELD(x,4,3)
#define  VTSS_F_DEV1G_DEV_CFG_STATUS_DEV_PORT_PROTECT_PORT_PROTECT_ENA  VTSS_BIT(0)

#define VTSS_DEV1G_DEV_CFG_STATUS_EEE_CFG(target)  VTSS_IOREG(target,0x4)
#define  VTSS_F_DEV1G_DEV_CFG_STATUS_EEE_CFG_EEE_ENA  VTSS_BIT(22)
#define  VTSS_F_DEV1G_DEV_CFG_STATUS_EEE_CFG_EEE_TIMER_AGE(x)  VTSS_ENCODE_BITFIELD(x,15,7)
#define  VTSS_M_DEV1G_DEV_CFG_STATUS_EEE_CFG_EEE_TIMER_AGE     VTSS_ENCODE_BITMASK(15,7)
#define  VTSS_X_DEV1G_DEV_CFG_STATUS_EEE_CFG_EEE_TIMER_AGE(x)  VTSS_EXTRACT_BITFIELD(x,15,7)
#define  VTSS_F_DEV1G_DEV_CFG_STATUS_EEE_CFG_EEE_TIMER_WAKEUP(x)  VTSS_ENCODE_BITFIELD(x,8,7)
#define  VTSS_M_DEV1G_DEV_CFG_STATUS_EEE_CFG_EEE_TIMER_WAKEUP     VTSS_ENCODE_BITMASK(8,7)
#define  VTSS_X_DEV1G_DEV_CFG_STATUS_EEE_CFG_EEE_TIMER_WAKEUP(x)  VTSS_EXTRACT_BITFIELD(x,8,7)
#define  VTSS_F_DEV1G_DEV_CFG_STATUS_EEE_CFG_EEE_TIMER_HOLDOFF(x)  VTSS_ENCODE_BITFIELD(x,1,7)
#define  VTSS_M_DEV1G_DEV_CFG_STATUS_EEE_CFG_EEE_TIMER_HOLDOFF     VTSS_ENCODE_BITMASK(1,7)
#define  VTSS_X_DEV1G_DEV_CFG_STATUS_EEE_CFG_EEE_TIMER_HOLDOFF(x)  VTSS_EXTRACT_BITFIELD(x,1,7)
#define  VTSS_F_DEV1G_DEV_CFG_STATUS_EEE_CFG_PORT_LPI  VTSS_BIT(0)

#define VTSS_DEV1G_DEV_CFG_STATUS_PTP_CFG(target)  VTSS_IOREG(target,0x5)
#define  VTSS_F_DEV1G_DEV_CFG_STATUS_PTP_CFG_PTP_ENA  VTSS_BIT(22)
#define  VTSS_F_DEV1G_DEV_CFG_STATUS_PTP_CFG_PTP_DOM(x)  VTSS_ENCODE_BITFIELD(x,20,2)
#define  VTSS_M_DEV1G_DEV_CFG_STATUS_PTP_CFG_PTP_DOM     VTSS_ENCODE_BITMASK(20,2)
#define  VTSS_X_DEV1G_DEV_CFG_STATUS_PTP_CFG_PTP_DOM(x)  VTSS_EXTRACT_BITFIELD(x,20,2)
#define  VTSS_F_DEV1G_DEV_CFG_STATUS_PTP_CFG_PTP_IF_MODE(x)  VTSS_ENCODE_BITFIELD(x,18,2)
#define  VTSS_M_DEV1G_DEV_CFG_STATUS_PTP_CFG_PTP_IF_MODE     VTSS_ENCODE_BITMASK(18,2)
#define  VTSS_X_DEV1G_DEV_CFG_STATUS_PTP_CFG_PTP_IF_MODE(x)  VTSS_EXTRACT_BITFIELD(x,18,2)
#define  VTSS_F_DEV1G_DEV_CFG_STATUS_PTP_CFG_PTP_RX_IO_DLY(x)  VTSS_ENCODE_BITFIELD(x,9,9)
#define  VTSS_M_DEV1G_DEV_CFG_STATUS_PTP_CFG_PTP_RX_IO_DLY     VTSS_ENCODE_BITMASK(9,9)
#define  VTSS_X_DEV1G_DEV_CFG_STATUS_PTP_CFG_PTP_RX_IO_DLY(x)  VTSS_EXTRACT_BITFIELD(x,9,9)
#define  VTSS_F_DEV1G_DEV_CFG_STATUS_PTP_CFG_PTP_TX_IO_DLY(x)  VTSS_ENCODE_BITFIELD(x,0,9)
#define  VTSS_M_DEV1G_DEV_CFG_STATUS_PTP_CFG_PTP_TX_IO_DLY     VTSS_ENCODE_BITMASK(0,9)
#define  VTSS_X_DEV1G_DEV_CFG_STATUS_PTP_CFG_PTP_TX_IO_DLY(x)  VTSS_EXTRACT_BITFIELD(x,0,9)

#define VTSS_DEV1G_DEV_CFG_STATUS_PTP_EVENTS(target)  VTSS_IOREG(target,0x6)
#define  VTSS_F_DEV1G_DEV_CFG_STATUS_PTP_EVENTS_CF_TOO_BIG_STICKY  VTSS_BIT(0)

#define VTSS_DEV1G_MAC_CFG_STATUS_MAC_ENA_CFG(target)  VTSS_IOREG(target,0x7)
#define  VTSS_F_DEV1G_MAC_CFG_STATUS_MAC_ENA_CFG_RX_ENA  VTSS_BIT(4)
#define  VTSS_F_DEV1G_MAC_CFG_STATUS_MAC_ENA_CFG_TX_ENA  VTSS_BIT(0)

#define VTSS_DEV1G_MAC_CFG_STATUS_MAC_MODE_CFG(target)  VTSS_IOREG(target,0x8)
#define  VTSS_F_DEV1G_MAC_CFG_STATUS_MAC_MODE_CFG_FC_WORD_SYNC_ENA  VTSS_BIT(8)
#define  VTSS_F_DEV1G_MAC_CFG_STATUS_MAC_MODE_CFG_GIGA_MODE_ENA  VTSS_BIT(4)
#define  VTSS_F_DEV1G_MAC_CFG_STATUS_MAC_MODE_CFG_FDX_ENA  VTSS_BIT(0)

#define VTSS_DEV1G_MAC_CFG_STATUS_MAC_MAXLEN_CFG(target)  VTSS_IOREG(target,0x9)
#define  VTSS_F_DEV1G_MAC_CFG_STATUS_MAC_MAXLEN_CFG_MAX_LEN(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_DEV1G_MAC_CFG_STATUS_MAC_MAXLEN_CFG_MAX_LEN     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_DEV1G_MAC_CFG_STATUS_MAC_MAXLEN_CFG_MAX_LEN(x)  VTSS_EXTRACT_BITFIELD(x,0,16)

#define VTSS_DEV1G_MAC_CFG_STATUS_MAC_TAGS_CFG(target)  VTSS_IOREG(target,0xa)
#define  VTSS_F_DEV1G_MAC_CFG_STATUS_MAC_TAGS_CFG_TAG_ID(x)  VTSS_ENCODE_BITFIELD(x,16,16)
#define  VTSS_M_DEV1G_MAC_CFG_STATUS_MAC_TAGS_CFG_TAG_ID     VTSS_ENCODE_BITMASK(16,16)
#define  VTSS_X_DEV1G_MAC_CFG_STATUS_MAC_TAGS_CFG_TAG_ID(x)  VTSS_EXTRACT_BITFIELD(x,16,16)
#define  VTSS_F_DEV1G_MAC_CFG_STATUS_MAC_TAGS_CFG_VLAN_LEN_AWR_ENA  VTSS_BIT(3)
#define  VTSS_F_DEV1G_MAC_CFG_STATUS_MAC_TAGS_CFG_PB_ENA(x)  VTSS_ENCODE_BITFIELD(x,1,2)
#define  VTSS_M_DEV1G_MAC_CFG_STATUS_MAC_TAGS_CFG_PB_ENA     VTSS_ENCODE_BITMASK(1,2)
#define  VTSS_X_DEV1G_MAC_CFG_STATUS_MAC_TAGS_CFG_PB_ENA(x)  VTSS_EXTRACT_BITFIELD(x,1,2)
#define  VTSS_F_DEV1G_MAC_CFG_STATUS_MAC_TAGS_CFG_VLAN_AWR_ENA  VTSS_BIT(0)

#define VTSS_DEV1G_MAC_CFG_STATUS_MAC_TAGS_CFG2(target)  VTSS_IOREG(target,0xb)
#define  VTSS_F_DEV1G_MAC_CFG_STATUS_MAC_TAGS_CFG2_TAG_ID3(x)  VTSS_ENCODE_BITFIELD(x,16,16)
#define  VTSS_M_DEV1G_MAC_CFG_STATUS_MAC_TAGS_CFG2_TAG_ID3     VTSS_ENCODE_BITMASK(16,16)
#define  VTSS_X_DEV1G_MAC_CFG_STATUS_MAC_TAGS_CFG2_TAG_ID3(x)  VTSS_EXTRACT_BITFIELD(x,16,16)
#define  VTSS_F_DEV1G_MAC_CFG_STATUS_MAC_TAGS_CFG2_TAG_ID2(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_DEV1G_MAC_CFG_STATUS_MAC_TAGS_CFG2_TAG_ID2     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_DEV1G_MAC_CFG_STATUS_MAC_TAGS_CFG2_TAG_ID2(x)  VTSS_EXTRACT_BITFIELD(x,0,16)

#define VTSS_DEV1G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG(target)  VTSS_IOREG(target,0xc)
#define  VTSS_F_DEV1G_MAC_CFG_STATUS_MAC_ADV_CHK_CFG_LEN_DROP_ENA  VTSS_BIT(0)

#define VTSS_DEV1G_MAC_CFG_STATUS_MAC_IFG_CFG(target)  VTSS_IOREG(target,0xd)
#define  VTSS_F_DEV1G_MAC_CFG_STATUS_MAC_IFG_CFG_RESTORE_OLD_IPG_CHECK  VTSS_BIT(17)
#define  VTSS_F_DEV1G_MAC_CFG_STATUS_MAC_IFG_CFG_TX_IFG(x)  VTSS_ENCODE_BITFIELD(x,8,5)
#define  VTSS_M_DEV1G_MAC_CFG_STATUS_MAC_IFG_CFG_TX_IFG     VTSS_ENCODE_BITMASK(8,5)
#define  VTSS_X_DEV1G_MAC_CFG_STATUS_MAC_IFG_CFG_TX_IFG(x)  VTSS_EXTRACT_BITFIELD(x,8,5)
#define  VTSS_F_DEV1G_MAC_CFG_STATUS_MAC_IFG_CFG_RX_IFG2(x)  VTSS_ENCODE_BITFIELD(x,4,4)
#define  VTSS_M_DEV1G_MAC_CFG_STATUS_MAC_IFG_CFG_RX_IFG2     VTSS_ENCODE_BITMASK(4,4)
#define  VTSS_X_DEV1G_MAC_CFG_STATUS_MAC_IFG_CFG_RX_IFG2(x)  VTSS_EXTRACT_BITFIELD(x,4,4)
#define  VTSS_F_DEV1G_MAC_CFG_STATUS_MAC_IFG_CFG_RX_IFG1(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_DEV1G_MAC_CFG_STATUS_MAC_IFG_CFG_RX_IFG1     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_DEV1G_MAC_CFG_STATUS_MAC_IFG_CFG_RX_IFG1(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_DEV1G_MAC_CFG_STATUS_MAC_HDX_CFG(target)  VTSS_IOREG(target,0xe)
#define  VTSS_F_DEV1G_MAC_CFG_STATUS_MAC_HDX_CFG_BYPASS_COL_SYNC  VTSS_BIT(26)
#define  VTSS_F_DEV1G_MAC_CFG_STATUS_MAC_HDX_CFG_SEED(x)  VTSS_ENCODE_BITFIELD(x,16,8)
#define  VTSS_M_DEV1G_MAC_CFG_STATUS_MAC_HDX_CFG_SEED     VTSS_ENCODE_BITMASK(16,8)
#define  VTSS_X_DEV1G_MAC_CFG_STATUS_MAC_HDX_CFG_SEED(x)  VTSS_EXTRACT_BITFIELD(x,16,8)
#define  VTSS_F_DEV1G_MAC_CFG_STATUS_MAC_HDX_CFG_SEED_LOAD  VTSS_BIT(12)
#define  VTSS_F_DEV1G_MAC_CFG_STATUS_MAC_HDX_CFG_RETRY_AFTER_EXC_COL_ENA  VTSS_BIT(8)
#define  VTSS_F_DEV1G_MAC_CFG_STATUS_MAC_HDX_CFG_LATE_COL_POS(x)  VTSS_ENCODE_BITFIELD(x,0,7)
#define  VTSS_M_DEV1G_MAC_CFG_STATUS_MAC_HDX_CFG_LATE_COL_POS     VTSS_ENCODE_BITMASK(0,7)
#define  VTSS_X_DEV1G_MAC_CFG_STATUS_MAC_HDX_CFG_LATE_COL_POS(x)  VTSS_EXTRACT_BITFIELD(x,0,7)

#define VTSS_DEV1G_MAC_CFG_STATUS_MAC_STICKY(target)  VTSS_IOREG(target,0xf)
#define  VTSS_F_DEV1G_MAC_CFG_STATUS_MAC_STICKY_RX_IPG_SHRINK_STICKY  VTSS_BIT(9)
#define  VTSS_F_DEV1G_MAC_CFG_STATUS_MAC_STICKY_RX_PREAM_SHRINK_STICKY  VTSS_BIT(8)
#define  VTSS_F_DEV1G_MAC_CFG_STATUS_MAC_STICKY_RX_JUNK_STICKY  VTSS_BIT(5)
#define  VTSS_F_DEV1G_MAC_CFG_STATUS_MAC_STICKY_TX_RETRANSMIT_STICKY  VTSS_BIT(4)
#define  VTSS_F_DEV1G_MAC_CFG_STATUS_MAC_STICKY_TX_JAM_STICKY  VTSS_BIT(3)
#define  VTSS_F_DEV1G_MAC_CFG_STATUS_MAC_STICKY_TX_FIFO_OFLW_STICKY  VTSS_BIT(2)
#define  VTSS_F_DEV1G_MAC_CFG_STATUS_MAC_STICKY_TX_ABORT_STICKY  VTSS_BIT(0)

#define VTSS_DEV1G_PCS1G_CFG_STATUS_PCS1G_CFG(target)  VTSS_IOREG(target,0x10)
#define  VTSS_F_DEV1G_PCS1G_CFG_STATUS_PCS1G_CFG_LINK_STATUS_TYPE  VTSS_BIT(4)
#define  VTSS_F_DEV1G_PCS1G_CFG_STATUS_PCS1G_CFG_AN_LINK_CTRL_ENA  VTSS_BIT(1)
#define  VTSS_F_DEV1G_PCS1G_CFG_STATUS_PCS1G_CFG_PCS_ENA  VTSS_BIT(0)

#define VTSS_DEV1G_PCS1G_CFG_STATUS_PCS1G_MODE_CFG(target)  VTSS_IOREG(target,0x11)
#define  VTSS_F_DEV1G_PCS1G_CFG_STATUS_PCS1G_MODE_CFG_UNIDIR_MODE_ENA  VTSS_BIT(4)
#define  VTSS_F_DEV1G_PCS1G_CFG_STATUS_PCS1G_MODE_CFG_SGMII_MODE_ENA  VTSS_BIT(0)

#define VTSS_DEV1G_PCS1G_CFG_STATUS_PCS1G_SD_CFG(target)  VTSS_IOREG(target,0x12)
#define  VTSS_F_DEV1G_PCS1G_CFG_STATUS_PCS1G_SD_CFG_SD_SEL  VTSS_BIT(8)
#define  VTSS_F_DEV1G_PCS1G_CFG_STATUS_PCS1G_SD_CFG_SD_POL  VTSS_BIT(4)
#define  VTSS_F_DEV1G_PCS1G_CFG_STATUS_PCS1G_SD_CFG_SD_ENA  VTSS_BIT(0)

#define VTSS_DEV1G_PCS1G_CFG_STATUS_PCS1G_ANEG_CFG(target)  VTSS_IOREG(target,0x13)
#define  VTSS_F_DEV1G_PCS1G_CFG_STATUS_PCS1G_ANEG_CFG_ADV_ABILITY(x)  VTSS_ENCODE_BITFIELD(x,16,16)
#define  VTSS_M_DEV1G_PCS1G_CFG_STATUS_PCS1G_ANEG_CFG_ADV_ABILITY     VTSS_ENCODE_BITMASK(16,16)
#define  VTSS_X_DEV1G_PCS1G_CFG_STATUS_PCS1G_ANEG_CFG_ADV_ABILITY(x)  VTSS_EXTRACT_BITFIELD(x,16,16)
#define  VTSS_F_DEV1G_PCS1G_CFG_STATUS_PCS1G_ANEG_CFG_SW_RESOLVE_ENA  VTSS_BIT(8)
#define  VTSS_F_DEV1G_PCS1G_CFG_STATUS_PCS1G_ANEG_CFG_ANEG_RESTART_ONE_SHOT  VTSS_BIT(1)
#define  VTSS_F_DEV1G_PCS1G_CFG_STATUS_PCS1G_ANEG_CFG_ANEG_ENA  VTSS_BIT(0)

#define VTSS_DEV1G_PCS1G_CFG_STATUS_PCS1G_ANEG_NP_CFG(target)  VTSS_IOREG(target,0x14)
#define  VTSS_F_DEV1G_PCS1G_CFG_STATUS_PCS1G_ANEG_NP_CFG_NP_TX(x)  VTSS_ENCODE_BITFIELD(x,16,16)
#define  VTSS_M_DEV1G_PCS1G_CFG_STATUS_PCS1G_ANEG_NP_CFG_NP_TX     VTSS_ENCODE_BITMASK(16,16)
#define  VTSS_X_DEV1G_PCS1G_CFG_STATUS_PCS1G_ANEG_NP_CFG_NP_TX(x)  VTSS_EXTRACT_BITFIELD(x,16,16)
#define  VTSS_F_DEV1G_PCS1G_CFG_STATUS_PCS1G_ANEG_NP_CFG_NP_LOADED_ONE_SHOT  VTSS_BIT(0)

#define VTSS_DEV1G_PCS1G_CFG_STATUS_PCS1G_LB_CFG(target)  VTSS_IOREG(target,0x15)
#define  VTSS_F_DEV1G_PCS1G_CFG_STATUS_PCS1G_LB_CFG_RA_ENA  VTSS_BIT(4)
#define  VTSS_F_DEV1G_PCS1G_CFG_STATUS_PCS1G_LB_CFG_GMII_PHY_LB_ENA  VTSS_BIT(1)
#define  VTSS_F_DEV1G_PCS1G_CFG_STATUS_PCS1G_LB_CFG_TBI_HOST_LB_ENA  VTSS_BIT(0)

#define VTSS_DEV1G_PCS1G_CFG_STATUS_PCS1G_DBG_CFG(target)  VTSS_IOREG(target,0x16)
#define  VTSS_F_DEV1G_PCS1G_CFG_STATUS_PCS1G_DBG_CFG_UDLT  VTSS_BIT(0)

#define VTSS_DEV1G_PCS1G_CFG_STATUS_PCS1G_CDET_CFG(target)  VTSS_IOREG(target,0x17)
#define  VTSS_F_DEV1G_PCS1G_CFG_STATUS_PCS1G_CDET_CFG_CDET_ENA  VTSS_BIT(0)

#define VTSS_DEV1G_PCS1G_CFG_STATUS_PCS1G_ANEG_STATUS(target)  VTSS_IOREG(target,0x18)
#define  VTSS_F_DEV1G_PCS1G_CFG_STATUS_PCS1G_ANEG_STATUS_LP_ADV_ABILITY(x)  VTSS_ENCODE_BITFIELD(x,16,16)
#define  VTSS_M_DEV1G_PCS1G_CFG_STATUS_PCS1G_ANEG_STATUS_LP_ADV_ABILITY     VTSS_ENCODE_BITMASK(16,16)
#define  VTSS_X_DEV1G_PCS1G_CFG_STATUS_PCS1G_ANEG_STATUS_LP_ADV_ABILITY(x)  VTSS_EXTRACT_BITFIELD(x,16,16)
#define  VTSS_F_DEV1G_PCS1G_CFG_STATUS_PCS1G_ANEG_STATUS_PR  VTSS_BIT(4)
#define  VTSS_F_DEV1G_PCS1G_CFG_STATUS_PCS1G_ANEG_STATUS_PAGE_RX_STICKY  VTSS_BIT(3)
#define  VTSS_F_DEV1G_PCS1G_CFG_STATUS_PCS1G_ANEG_STATUS_ANEG_COMPLETE  VTSS_BIT(0)

#define VTSS_DEV1G_PCS1G_CFG_STATUS_PCS1G_ANEG_NP_STATUS(target)  VTSS_IOREG(target,0x19)
#define  VTSS_F_DEV1G_PCS1G_CFG_STATUS_PCS1G_ANEG_NP_STATUS_LP_NP_RX(x)  VTSS_ENCODE_BITFIELD(x,16,16)
#define  VTSS_M_DEV1G_PCS1G_CFG_STATUS_PCS1G_ANEG_NP_STATUS_LP_NP_RX     VTSS_ENCODE_BITMASK(16,16)
#define  VTSS_X_DEV1G_PCS1G_CFG_STATUS_PCS1G_ANEG_NP_STATUS_LP_NP_RX(x)  VTSS_EXTRACT_BITFIELD(x,16,16)

#define VTSS_DEV1G_PCS1G_CFG_STATUS_PCS1G_LINK_STATUS(target)  VTSS_IOREG(target,0x1a)
#define  VTSS_F_DEV1G_PCS1G_CFG_STATUS_PCS1G_LINK_STATUS_DELAY_VAR(x)  VTSS_ENCODE_BITFIELD(x,12,4)
#define  VTSS_M_DEV1G_PCS1G_CFG_STATUS_PCS1G_LINK_STATUS_DELAY_VAR     VTSS_ENCODE_BITMASK(12,4)
#define  VTSS_X_DEV1G_PCS1G_CFG_STATUS_PCS1G_LINK_STATUS_DELAY_VAR(x)  VTSS_EXTRACT_BITFIELD(x,12,4)
#define  VTSS_F_DEV1G_PCS1G_CFG_STATUS_PCS1G_LINK_STATUS_SIGNAL_DETECT  VTSS_BIT(8)
#define  VTSS_F_DEV1G_PCS1G_CFG_STATUS_PCS1G_LINK_STATUS_LINK_STATUS  VTSS_BIT(4)
#define  VTSS_F_DEV1G_PCS1G_CFG_STATUS_PCS1G_LINK_STATUS_SYNC_STATUS  VTSS_BIT(0)

#define VTSS_DEV1G_PCS1G_CFG_STATUS_PCS1G_LINK_DOWN_CNT(target)  VTSS_IOREG(target,0x1b)
#define  VTSS_F_DEV1G_PCS1G_CFG_STATUS_PCS1G_LINK_DOWN_CNT_LINK_DOWN_CNT(x)  VTSS_ENCODE_BITFIELD(x,0,8)
#define  VTSS_M_DEV1G_PCS1G_CFG_STATUS_PCS1G_LINK_DOWN_CNT_LINK_DOWN_CNT     VTSS_ENCODE_BITMASK(0,8)
#define  VTSS_X_DEV1G_PCS1G_CFG_STATUS_PCS1G_LINK_DOWN_CNT_LINK_DOWN_CNT(x)  VTSS_EXTRACT_BITFIELD(x,0,8)

#define VTSS_DEV1G_PCS1G_CFG_STATUS_PCS1G_STICKY(target)  VTSS_IOREG(target,0x1c)
#define  VTSS_F_DEV1G_PCS1G_CFG_STATUS_PCS1G_STICKY_LINK_DOWN_STICKY  VTSS_BIT(4)
#define  VTSS_F_DEV1G_PCS1G_CFG_STATUS_PCS1G_STICKY_OUT_OF_SYNC_STICKY  VTSS_BIT(0)

#define VTSS_DEV1G_PCS1G_CFG_STATUS_PCS1G_DEBUG_STATUS(target)  VTSS_IOREG(target,0x1d)
#define  VTSS_F_DEV1G_PCS1G_CFG_STATUS_PCS1G_DEBUG_STATUS_XMIT_MODE(x)  VTSS_ENCODE_BITFIELD(x,12,2)
#define  VTSS_M_DEV1G_PCS1G_CFG_STATUS_PCS1G_DEBUG_STATUS_XMIT_MODE     VTSS_ENCODE_BITMASK(12,2)
#define  VTSS_X_DEV1G_PCS1G_CFG_STATUS_PCS1G_DEBUG_STATUS_XMIT_MODE(x)  VTSS_EXTRACT_BITFIELD(x,12,2)

#define VTSS_DEV1G_PCS1G_CFG_STATUS_PCS1G_LPI_CFG(target)  VTSS_IOREG(target,0x1e)
#define  VTSS_F_DEV1G_PCS1G_CFG_STATUS_PCS1G_LPI_CFG_QSGMII_MS_SEL  VTSS_BIT(20)
#define  VTSS_F_DEV1G_PCS1G_CFG_STATUS_PCS1G_LPI_CFG_RX_LPI_OUT_DIS  VTSS_BIT(17)
#define  VTSS_F_DEV1G_PCS1G_CFG_STATUS_PCS1G_LPI_CFG_LPI_TESTMODE  VTSS_BIT(16)
#define  VTSS_F_DEV1G_PCS1G_CFG_STATUS_PCS1G_LPI_CFG_TX_ASSERT_LPIDLE  VTSS_BIT(0)

#define VTSS_DEV1G_PCS1G_CFG_STATUS_PCS1G_LPI_WAKE_ERROR_CNT(target)  VTSS_IOREG(target,0x1f)
#define  VTSS_F_DEV1G_PCS1G_CFG_STATUS_PCS1G_LPI_WAKE_ERROR_CNT_WAKE_ERROR_CNT(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_DEV1G_PCS1G_CFG_STATUS_PCS1G_LPI_WAKE_ERROR_CNT_WAKE_ERROR_CNT     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_DEV1G_PCS1G_CFG_STATUS_PCS1G_LPI_WAKE_ERROR_CNT_WAKE_ERROR_CNT(x)  VTSS_EXTRACT_BITFIELD(x,0,16)

#define VTSS_DEV1G_PCS1G_CFG_STATUS_PCS1G_LPI_STATUS(target)  VTSS_IOREG(target,0x20)
#define  VTSS_F_DEV1G_PCS1G_CFG_STATUS_PCS1G_LPI_STATUS_RX_LPI_EVENT_STICKY  VTSS_BIT(12)
#define  VTSS_F_DEV1G_PCS1G_CFG_STATUS_PCS1G_LPI_STATUS_RX_QUIET  VTSS_BIT(9)
#define  VTSS_F_DEV1G_PCS1G_CFG_STATUS_PCS1G_LPI_STATUS_RX_LPI_MODE  VTSS_BIT(8)
#define  VTSS_F_DEV1G_PCS1G_CFG_STATUS_PCS1G_LPI_STATUS_TX_LPI_EVENT_STICKY  VTSS_BIT(4)
#define  VTSS_F_DEV1G_PCS1G_CFG_STATUS_PCS1G_LPI_STATUS_TX_QUIET  VTSS_BIT(1)
#define  VTSS_F_DEV1G_PCS1G_CFG_STATUS_PCS1G_LPI_STATUS_TX_LPI_MODE  VTSS_BIT(0)

#define VTSS_DEV1G_PCS1G_TSTPAT_CFG_STATUS_PCS1G_TSTPAT_MODE_CFG(target)  VTSS_IOREG(target,0x21)
#define  VTSS_F_DEV1G_PCS1G_TSTPAT_CFG_STATUS_PCS1G_TSTPAT_MODE_CFG_JTP_SEL(x)  VTSS_ENCODE_BITFIELD(x,0,3)
#define  VTSS_M_DEV1G_PCS1G_TSTPAT_CFG_STATUS_PCS1G_TSTPAT_MODE_CFG_JTP_SEL     VTSS_ENCODE_BITMASK(0,3)
#define  VTSS_X_DEV1G_PCS1G_TSTPAT_CFG_STATUS_PCS1G_TSTPAT_MODE_CFG_JTP_SEL(x)  VTSS_EXTRACT_BITFIELD(x,0,3)

#define VTSS_DEV1G_PCS1G_TSTPAT_CFG_STATUS_PCS1G_TSTPAT_STATUS(target)  VTSS_IOREG(target,0x22)
#define  VTSS_F_DEV1G_PCS1G_TSTPAT_CFG_STATUS_PCS1G_TSTPAT_STATUS_JTP_ERR_CNT(x)  VTSS_ENCODE_BITFIELD(x,8,8)
#define  VTSS_M_DEV1G_PCS1G_TSTPAT_CFG_STATUS_PCS1G_TSTPAT_STATUS_JTP_ERR_CNT     VTSS_ENCODE_BITMASK(8,8)
#define  VTSS_X_DEV1G_PCS1G_TSTPAT_CFG_STATUS_PCS1G_TSTPAT_STATUS_JTP_ERR_CNT(x)  VTSS_EXTRACT_BITFIELD(x,8,8)
#define  VTSS_F_DEV1G_PCS1G_TSTPAT_CFG_STATUS_PCS1G_TSTPAT_STATUS_JTP_ERR  VTSS_BIT(4)
#define  VTSS_F_DEV1G_PCS1G_TSTPAT_CFG_STATUS_PCS1G_TSTPAT_STATUS_JTP_LOCK  VTSS_BIT(0)

#define VTSS_DEV1G_PCS_FX100_CONFIGURATION_PCS_FX100_CFG(target)  VTSS_IOREG(target,0x23)
#define  VTSS_F_DEV1G_PCS_FX100_CONFIGURATION_PCS_FX100_CFG_SD_SEL  VTSS_BIT(26)
#define  VTSS_F_DEV1G_PCS_FX100_CONFIGURATION_PCS_FX100_CFG_SD_POL  VTSS_BIT(25)
#define  VTSS_F_DEV1G_PCS_FX100_CONFIGURATION_PCS_FX100_CFG_SD_ENA  VTSS_BIT(24)
#define  VTSS_F_DEV1G_PCS_FX100_CONFIGURATION_PCS_FX100_CFG_LOOPBACK_ENA  VTSS_BIT(20)
#define  VTSS_F_DEV1G_PCS_FX100_CONFIGURATION_PCS_FX100_CFG_SWAP_MII_ENA  VTSS_BIT(16)
#define  VTSS_F_DEV1G_PCS_FX100_CONFIGURATION_PCS_FX100_CFG_RXBITSEL(x)  VTSS_ENCODE_BITFIELD(x,12,4)
#define  VTSS_M_DEV1G_PCS_FX100_CONFIGURATION_PCS_FX100_CFG_RXBITSEL     VTSS_ENCODE_BITMASK(12,4)
#define  VTSS_X_DEV1G_PCS_FX100_CONFIGURATION_PCS_FX100_CFG_RXBITSEL(x)  VTSS_EXTRACT_BITFIELD(x,12,4)
#define  VTSS_F_DEV1G_PCS_FX100_CONFIGURATION_PCS_FX100_CFG_SIGDET_CFG(x)  VTSS_ENCODE_BITFIELD(x,9,2)
#define  VTSS_M_DEV1G_PCS_FX100_CONFIGURATION_PCS_FX100_CFG_SIGDET_CFG     VTSS_ENCODE_BITMASK(9,2)
#define  VTSS_X_DEV1G_PCS_FX100_CONFIGURATION_PCS_FX100_CFG_SIGDET_CFG(x)  VTSS_EXTRACT_BITFIELD(x,9,2)
#define  VTSS_F_DEV1G_PCS_FX100_CONFIGURATION_PCS_FX100_CFG_LINKHYST_TM_ENA  VTSS_BIT(8)
#define  VTSS_F_DEV1G_PCS_FX100_CONFIGURATION_PCS_FX100_CFG_LINKHYSTTIMER(x)  VTSS_ENCODE_BITFIELD(x,4,4)
#define  VTSS_M_DEV1G_PCS_FX100_CONFIGURATION_PCS_FX100_CFG_LINKHYSTTIMER     VTSS_ENCODE_BITMASK(4,4)
#define  VTSS_X_DEV1G_PCS_FX100_CONFIGURATION_PCS_FX100_CFG_LINKHYSTTIMER(x)  VTSS_EXTRACT_BITFIELD(x,4,4)
#define  VTSS_F_DEV1G_PCS_FX100_CONFIGURATION_PCS_FX100_CFG_UNIDIR_MODE_ENA  VTSS_BIT(3)
#define  VTSS_F_DEV1G_PCS_FX100_CONFIGURATION_PCS_FX100_CFG_FEFCHK_ENA  VTSS_BIT(2)
#define  VTSS_F_DEV1G_PCS_FX100_CONFIGURATION_PCS_FX100_CFG_FEFGEN_ENA  VTSS_BIT(1)
#define  VTSS_F_DEV1G_PCS_FX100_CONFIGURATION_PCS_FX100_CFG_PCS_ENA  VTSS_BIT(0)

#define VTSS_DEV1G_PCS_FX100_STATUS_PCS_FX100_STATUS(target)  VTSS_IOREG(target,0x24)
#define  VTSS_F_DEV1G_PCS_FX100_STATUS_PCS_FX100_STATUS_EDGE_POS_PTP(x)  VTSS_ENCODE_BITFIELD(x,8,4)
#define  VTSS_M_DEV1G_PCS_FX100_STATUS_PCS_FX100_STATUS_EDGE_POS_PTP     VTSS_ENCODE_BITMASK(8,4)
#define  VTSS_X_DEV1G_PCS_FX100_STATUS_PCS_FX100_STATUS_EDGE_POS_PTP(x)  VTSS_EXTRACT_BITFIELD(x,8,4)
#define  VTSS_F_DEV1G_PCS_FX100_STATUS_PCS_FX100_STATUS_PCS_ERROR_STICKY  VTSS_BIT(7)
#define  VTSS_F_DEV1G_PCS_FX100_STATUS_PCS_FX100_STATUS_FEF_FOUND_STICKY  VTSS_BIT(6)
#define  VTSS_F_DEV1G_PCS_FX100_STATUS_PCS_FX100_STATUS_SSD_ERROR_STICKY  VTSS_BIT(5)
#define  VTSS_F_DEV1G_PCS_FX100_STATUS_PCS_FX100_STATUS_SYNC_LOST_STICKY  VTSS_BIT(4)
#define  VTSS_F_DEV1G_PCS_FX100_STATUS_PCS_FX100_STATUS_FEF_STATUS  VTSS_BIT(2)
#define  VTSS_F_DEV1G_PCS_FX100_STATUS_PCS_FX100_STATUS_SIGNAL_DETECT  VTSS_BIT(1)
#define  VTSS_F_DEV1G_PCS_FX100_STATUS_PCS_FX100_STATUS_SYNC_STATUS  VTSS_BIT(0)

#define VTSS_DEV1G_DEV1G_INTR_CFG_STATUS_DEV1G_INTR_CFG(target)  VTSS_IOREG(target,0x25)
#define  VTSS_F_DEV1G_DEV1G_INTR_CFG_STATUS_DEV1G_INTR_CFG_FEF_FOUND_INTR_ENA  VTSS_BIT(8)
#define  VTSS_F_DEV1G_DEV1G_INTR_CFG_STATUS_DEV1G_INTR_CFG_TX_LPI_INTR_ENA  VTSS_BIT(6)
#define  VTSS_F_DEV1G_DEV1G_INTR_CFG_STATUS_DEV1G_INTR_CFG_RX_LPI_INTR_ENA  VTSS_BIT(5)
#define  VTSS_F_DEV1G_DEV1G_INTR_CFG_STATUS_DEV1G_INTR_CFG_AN_PAGE_RX_INTR_ENA  VTSS_BIT(4)
#define  VTSS_F_DEV1G_DEV1G_INTR_CFG_STATUS_DEV1G_INTR_CFG_AN_LINK_UP_INTR_ENA  VTSS_BIT(3)
#define  VTSS_F_DEV1G_DEV1G_INTR_CFG_STATUS_DEV1G_INTR_CFG_AN_LINK_DOWN_INTR_ENA  VTSS_BIT(2)
#define  VTSS_F_DEV1G_DEV1G_INTR_CFG_STATUS_DEV1G_INTR_CFG_LINK_UP_INTR_ENA  VTSS_BIT(1)
#define  VTSS_F_DEV1G_DEV1G_INTR_CFG_STATUS_DEV1G_INTR_CFG_LINK_DOWN_INTR_ENA  VTSS_BIT(0)

#define VTSS_DEV1G_DEV1G_INTR_CFG_STATUS_DEV1G_INTR(target)  VTSS_IOREG(target,0x26)
#define  VTSS_F_DEV1G_DEV1G_INTR_CFG_STATUS_DEV1G_INTR_FEF_FOUND_INTR_STICKY  VTSS_BIT(8)
#define  VTSS_F_DEV1G_DEV1G_INTR_CFG_STATUS_DEV1G_INTR_TX_LPI_INTR_STICKY  VTSS_BIT(6)
#define  VTSS_F_DEV1G_DEV1G_INTR_CFG_STATUS_DEV1G_INTR_RX_LPI_INTR_STICKY  VTSS_BIT(5)
#define  VTSS_F_DEV1G_DEV1G_INTR_CFG_STATUS_DEV1G_INTR_AN_PAGE_RX_INTR_STICKY  VTSS_BIT(4)
#define  VTSS_F_DEV1G_DEV1G_INTR_CFG_STATUS_DEV1G_INTR_AN_LINK_UP_INTR_STICKY  VTSS_BIT(3)
#define  VTSS_F_DEV1G_DEV1G_INTR_CFG_STATUS_DEV1G_INTR_AN_LINK_DOWN_INTR_STICKY  VTSS_BIT(2)
#define  VTSS_F_DEV1G_DEV1G_INTR_CFG_STATUS_DEV1G_INTR_LINK_UP_INTR_STICKY  VTSS_BIT(1)
#define  VTSS_F_DEV1G_DEV1G_INTR_CFG_STATUS_DEV1G_INTR_LINK_DOWN_INTR_STICKY  VTSS_BIT(0)

#define VTSS_DEV1G_DEV1G_INTR_CFG_STATUS_DEV1G_INTR_IDENT(target)  VTSS_IOREG(target,0x27)
#define  VTSS_F_DEV1G_DEV1G_INTR_CFG_STATUS_DEV1G_INTR_IDENT_FEF_FOUND_INTR_IDENT  VTSS_BIT(8)
#define  VTSS_F_DEV1G_DEV1G_INTR_CFG_STATUS_DEV1G_INTR_IDENT_TX_LPI_INTR_IDENT  VTSS_BIT(6)
#define  VTSS_F_DEV1G_DEV1G_INTR_CFG_STATUS_DEV1G_INTR_IDENT_RX_LPI_INTR_IDENT  VTSS_BIT(5)
#define  VTSS_F_DEV1G_DEV1G_INTR_CFG_STATUS_DEV1G_INTR_IDENT_AN_PAGE_RX_INTR_IDENT  VTSS_BIT(4)
#define  VTSS_F_DEV1G_DEV1G_INTR_CFG_STATUS_DEV1G_INTR_IDENT_AN_LINK_UP_INTR_IDENT  VTSS_BIT(3)
#define  VTSS_F_DEV1G_DEV1G_INTR_CFG_STATUS_DEV1G_INTR_IDENT_AN_LINK_DOWN_INTR_IDENT  VTSS_BIT(2)
#define  VTSS_F_DEV1G_DEV1G_INTR_CFG_STATUS_DEV1G_INTR_IDENT_LINK_UP_INTR_IDENT  VTSS_BIT(1)
#define  VTSS_F_DEV1G_DEV1G_INTR_CFG_STATUS_DEV1G_INTR_IDENT_LINK_DOWN_INTR_IDENT  VTSS_BIT(0)


#endif /* _VTSS_JAGUAR2_REGS_DEV1G_H_ */
