#ifndef _VTSS_JAGUAR2_REGS_QSYS_H_
#define _VTSS_JAGUAR2_REGS_QSYS_H_

/*
 *
 * VCore-III Register Definitions
 *
 * Copyright (C) 2012 Vitesse Semiconductor Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#include "vtss_jaguar2_regs_common.h"

#define VTSS_QSYS_SYSTEM_EEE_CFG(ri)         VTSS_IOREG(VTSS_TO_QSYS,0x402 + (ri))
#define  VTSS_F_QSYS_SYSTEM_EEE_CFG_EEE_FAST_QUEUES(x)  VTSS_ENCODE_BITFIELD(x,0,8)
#define  VTSS_M_QSYS_SYSTEM_EEE_CFG_EEE_FAST_QUEUES     VTSS_ENCODE_BITMASK(0,8)
#define  VTSS_X_QSYS_SYSTEM_EEE_CFG_EEE_FAST_QUEUES(x)  VTSS_EXTRACT_BITFIELD(x,0,8)

#define VTSS_QSYS_SYSTEM_EEE_THRES           VTSS_IOREG(VTSS_TO_QSYS,0x43b)
#define  VTSS_F_QSYS_SYSTEM_EEE_THRES_EEE_HIGH_BYTES(x)  VTSS_ENCODE_BITFIELD(x,8,8)
#define  VTSS_M_QSYS_SYSTEM_EEE_THRES_EEE_HIGH_BYTES     VTSS_ENCODE_BITMASK(8,8)
#define  VTSS_X_QSYS_SYSTEM_EEE_THRES_EEE_HIGH_BYTES(x)  VTSS_EXTRACT_BITFIELD(x,8,8)
#define  VTSS_F_QSYS_SYSTEM_EEE_THRES_EEE_HIGH_FRAMES(x)  VTSS_ENCODE_BITFIELD(x,0,8)
#define  VTSS_M_QSYS_SYSTEM_EEE_THRES_EEE_HIGH_FRAMES     VTSS_ENCODE_BITMASK(0,8)
#define  VTSS_X_QSYS_SYSTEM_EEE_THRES_EEE_HIGH_FRAMES(x)  VTSS_EXTRACT_BITFIELD(x,0,8)

#define VTSS_QSYS_SYSTEM_RESET_CFG           VTSS_IOREG(VTSS_TO_QSYS,0x43c)
#define  VTSS_F_QSYS_SYSTEM_RESET_CFG_CORE_ENA  VTSS_BIT(0)

#define VTSS_QSYS_SYSTEM_PMEM_SIZE           VTSS_IOREG(VTSS_TO_QSYS,0x43d)
#define  VTSS_F_QSYS_SYSTEM_PMEM_SIZE_PMEM_SIZE(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_QSYS_SYSTEM_PMEM_SIZE_PMEM_SIZE     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_QSYS_SYSTEM_PMEM_SIZE_PMEM_SIZE(x)  VTSS_EXTRACT_BITFIELD(x,0,16)

#define VTSS_QSYS_SYSTEM_FRM_AGING           VTSS_IOREG(VTSS_TO_QSYS,0x43e)
#define  VTSS_F_QSYS_SYSTEM_FRM_AGING_MAX_AGE(x)  VTSS_ENCODE_BITFIELD(x,0,20)
#define  VTSS_M_QSYS_SYSTEM_FRM_AGING_MAX_AGE     VTSS_ENCODE_BITMASK(0,20)
#define  VTSS_X_QSYS_SYSTEM_FRM_AGING_MAX_AGE(x)  VTSS_EXTRACT_BITFIELD(x,0,20)

#define VTSS_QSYS_SYSTEM_STAT_CFG            VTSS_IOREG(VTSS_TO_QSYS,0x43f)
#define  VTSS_F_QSYS_SYSTEM_STAT_CFG_STAT_CLEAR_SHOT(x)  VTSS_ENCODE_BITFIELD(x,13,4)
#define  VTSS_M_QSYS_SYSTEM_STAT_CFG_STAT_CLEAR_SHOT     VTSS_ENCODE_BITMASK(13,4)
#define  VTSS_X_QSYS_SYSTEM_STAT_CFG_STAT_CLEAR_SHOT(x)  VTSS_EXTRACT_BITFIELD(x,13,4)
#define  VTSS_F_QSYS_SYSTEM_STAT_CFG_STAT_VIEW(x)  VTSS_ENCODE_BITFIELD(x,0,13)
#define  VTSS_M_QSYS_SYSTEM_STAT_CFG_STAT_VIEW     VTSS_ENCODE_BITMASK(0,13)
#define  VTSS_X_QSYS_SYSTEM_STAT_CFG_STAT_VIEW(x)  VTSS_EXTRACT_BITFIELD(x,0,13)

#define VTSS_QSYS_SYSTEM_DP_MAP              VTSS_IOREG(VTSS_TO_QSYS,0x440)
#define  VTSS_F_QSYS_SYSTEM_DP_MAP_DP(x)      VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_QSYS_SYSTEM_DP_MAP_DP         VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_QSYS_SYSTEM_DP_MAP_DP(x)      VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_QSYS_MISC_EVENTS_CORE           VTSS_IOREG(VTSS_TO_QSYS,0x441)
#define  VTSS_F_QSYS_MISC_EVENTS_CORE_EV_FWR  VTSS_BIT(3)
#define  VTSS_F_QSYS_MISC_EVENTS_CORE_EV_FDC(x)  VTSS_ENCODE_BITFIELD(x,0,3)
#define  VTSS_M_QSYS_MISC_EVENTS_CORE_EV_FDC     VTSS_ENCODE_BITMASK(0,3)
#define  VTSS_X_QSYS_MISC_EVENTS_CORE_EV_FDC(x)  VTSS_EXTRACT_BITFIELD(x,0,3)

#define VTSS_QSYS_PAUSE_CFG_PAUSE_CFG(ri)    VTSS_IOREG(VTSS_TO_QSYS,0x442 + (ri))
#define  VTSS_F_QSYS_PAUSE_CFG_PAUSE_CFG_PAUSE_START(x)  VTSS_ENCODE_BITFIELD(x,13,12)
#define  VTSS_M_QSYS_PAUSE_CFG_PAUSE_CFG_PAUSE_START     VTSS_ENCODE_BITMASK(13,12)
#define  VTSS_X_QSYS_PAUSE_CFG_PAUSE_CFG_PAUSE_START(x)  VTSS_EXTRACT_BITFIELD(x,13,12)
#define  VTSS_F_QSYS_PAUSE_CFG_PAUSE_CFG_PAUSE_STOP(x)  VTSS_ENCODE_BITFIELD(x,1,12)
#define  VTSS_M_QSYS_PAUSE_CFG_PAUSE_CFG_PAUSE_STOP     VTSS_ENCODE_BITMASK(1,12)
#define  VTSS_X_QSYS_PAUSE_CFG_PAUSE_CFG_PAUSE_STOP(x)  VTSS_EXTRACT_BITFIELD(x,1,12)
#define  VTSS_F_QSYS_PAUSE_CFG_PAUSE_CFG_PAUSE_ENA  VTSS_BIT(0)

#define VTSS_QSYS_PAUSE_CFG_PAUSE_TOT_CFG    VTSS_IOREG(VTSS_TO_QSYS,0x47b)
#define  VTSS_F_QSYS_PAUSE_CFG_PAUSE_TOT_CFG_PAUSE_TOT_START(x)  VTSS_ENCODE_BITFIELD(x,12,12)
#define  VTSS_M_QSYS_PAUSE_CFG_PAUSE_TOT_CFG_PAUSE_TOT_START     VTSS_ENCODE_BITMASK(12,12)
#define  VTSS_X_QSYS_PAUSE_CFG_PAUSE_TOT_CFG_PAUSE_TOT_START(x)  VTSS_EXTRACT_BITFIELD(x,12,12)
#define  VTSS_F_QSYS_PAUSE_CFG_PAUSE_TOT_CFG_PAUSE_TOT_STOP(x)  VTSS_ENCODE_BITFIELD(x,0,12)
#define  VTSS_M_QSYS_PAUSE_CFG_PAUSE_TOT_CFG_PAUSE_TOT_STOP     VTSS_ENCODE_BITMASK(0,12)
#define  VTSS_X_QSYS_PAUSE_CFG_PAUSE_TOT_CFG_PAUSE_TOT_STOP(x)  VTSS_EXTRACT_BITFIELD(x,0,12)

#define VTSS_QSYS_PAUSE_CFG_ATOP(ri)         VTSS_IOREG(VTSS_TO_QSYS,0x47c + (ri))
#define  VTSS_F_QSYS_PAUSE_CFG_ATOP_ATOP(x)   VTSS_ENCODE_BITFIELD(x,0,12)
#define  VTSS_M_QSYS_PAUSE_CFG_ATOP_ATOP      VTSS_ENCODE_BITMASK(0,12)
#define  VTSS_X_QSYS_PAUSE_CFG_ATOP_ATOP(x)   VTSS_EXTRACT_BITFIELD(x,0,12)

#define VTSS_QSYS_PAUSE_CFG_FWD_PRESSURE(ri)  VTSS_IOREG(VTSS_TO_QSYS,0x4b5 + (ri))
#define  VTSS_F_QSYS_PAUSE_CFG_FWD_PRESSURE_FWD_PRESSURE(x)  VTSS_ENCODE_BITFIELD(x,3,12)
#define  VTSS_M_QSYS_PAUSE_CFG_FWD_PRESSURE_FWD_PRESSURE     VTSS_ENCODE_BITMASK(3,12)
#define  VTSS_X_QSYS_PAUSE_CFG_FWD_PRESSURE_FWD_PRESSURE(x)  VTSS_EXTRACT_BITFIELD(x,3,12)
#define  VTSS_F_QSYS_PAUSE_CFG_FWD_PRESSURE_FWD_PRESSURE_COPYCNT(x)  VTSS_ENCODE_BITFIELD(x,0,3)
#define  VTSS_M_QSYS_PAUSE_CFG_FWD_PRESSURE_FWD_PRESSURE_COPYCNT     VTSS_ENCODE_BITMASK(0,3)
#define  VTSS_X_QSYS_PAUSE_CFG_FWD_PRESSURE_FWD_PRESSURE_COPYCNT(x)  VTSS_EXTRACT_BITFIELD(x,0,3)

#define VTSS_QSYS_PAUSE_CFG_ATOP_TOT_CFG     VTSS_IOREG(VTSS_TO_QSYS,0x4ee)
#define  VTSS_F_QSYS_PAUSE_CFG_ATOP_TOT_CFG_ATOP_TOT(x)  VTSS_ENCODE_BITFIELD(x,0,12)
#define  VTSS_M_QSYS_PAUSE_CFG_ATOP_TOT_CFG_ATOP_TOT     VTSS_ENCODE_BITMASK(0,12)
#define  VTSS_X_QSYS_PAUSE_CFG_ATOP_TOT_CFG_ATOP_TOT(x)  VTSS_EXTRACT_BITFIELD(x,0,12)

#define VTSS_QSYS_MMGT_EQ_STAT               VTSS_IOREG(VTSS_TO_QSYS,0x4ef)
#define  VTSS_F_QSYS_MMGT_EQ_STAT_FP_FREE_CNT(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_QSYS_MMGT_EQ_STAT_FP_FREE_CNT     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_QSYS_MMGT_EQ_STAT_FP_FREE_CNT(x)  VTSS_EXTRACT_BITFIELD(x,0,16)

#define VTSS_QSYS_MMGT_MMGT                  VTSS_IOREG(VTSS_TO_QSYS,0x4f0)
#define  VTSS_F_QSYS_MMGT_MMGT_RELCNT(x)      VTSS_ENCODE_BITFIELD(x,16,16)
#define  VTSS_M_QSYS_MMGT_MMGT_RELCNT         VTSS_ENCODE_BITMASK(16,16)
#define  VTSS_X_QSYS_MMGT_MMGT_RELCNT(x)      VTSS_EXTRACT_BITFIELD(x,16,16)
#define  VTSS_F_QSYS_MMGT_MMGT_FREECNT(x)     VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_QSYS_MMGT_MMGT_FREECNT        VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_QSYS_MMGT_MMGT_FREECNT(x)     VTSS_EXTRACT_BITFIELD(x,0,16)

#define VTSS_QSYS_MMGT_MMGT_FAST             VTSS_IOREG(VTSS_TO_QSYS,0x4f1)
#define  VTSS_F_QSYS_MMGT_MMGT_FAST_FREEVLD(x)  VTSS_ENCODE_BITFIELD(x,4,4)
#define  VTSS_M_QSYS_MMGT_MMGT_FAST_FREEVLD     VTSS_ENCODE_BITMASK(4,4)
#define  VTSS_X_QSYS_MMGT_MMGT_FAST_FREEVLD(x)  VTSS_EXTRACT_BITFIELD(x,4,4)
#define  VTSS_F_QSYS_MMGT_MMGT_FAST_RELVLD(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_QSYS_MMGT_MMGT_FAST_RELVLD     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_QSYS_MMGT_MMGT_FAST_RELVLD(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_QSYS_MMGT_PORT_MMGT_PORT_VIEW   VTSS_IOREG(VTSS_TO_QSYS,0x4f2)
#define  VTSS_F_QSYS_MMGT_PORT_MMGT_PORT_VIEW_MMGT_PORT_VIEW(x)  VTSS_ENCODE_BITFIELD(x,0,6)
#define  VTSS_M_QSYS_MMGT_PORT_MMGT_PORT_VIEW_MMGT_PORT_VIEW     VTSS_ENCODE_BITMASK(0,6)
#define  VTSS_X_QSYS_MMGT_PORT_MMGT_PORT_VIEW_MMGT_PORT_VIEW(x)  VTSS_EXTRACT_BITFIELD(x,0,6)

#define VTSS_QSYS_MMGT_PORT_MMGT_PORT_USE    VTSS_IOREG(VTSS_TO_QSYS,0x4f3)
#define  VTSS_F_QSYS_MMGT_PORT_MMGT_PORT_USE_MMGT_PORT_USE(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_QSYS_MMGT_PORT_MMGT_PORT_USE_MMGT_PORT_USE     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_QSYS_MMGT_PORT_MMGT_PORT_USE_MMGT_PORT_USE(x)  VTSS_EXTRACT_BITFIELD(x,0,16)

#define VTSS_QSYS_MMGT_PORT_MMGT_IQ_STAT     VTSS_IOREG(VTSS_TO_QSYS,0x4f4)
#define  VTSS_F_QSYS_MMGT_PORT_MMGT_IQ_STAT_MMGT_IQ_SIZE(x)  VTSS_ENCODE_BITFIELD(x,0,20)
#define  VTSS_M_QSYS_MMGT_PORT_MMGT_IQ_STAT_MMGT_IQ_SIZE     VTSS_ENCODE_BITMASK(0,20)
#define  VTSS_X_QSYS_MMGT_PORT_MMGT_IQ_STAT_MMGT_IQ_SIZE(x)  VTSS_EXTRACT_BITFIELD(x,0,20)

#define VTSS_QSYS_STAT_CNT(gi)               VTSS_IOREG_IX(VTSS_TO_QSYS,0x0,gi,1,0,0)

#define VTSS_QSYS_CALCFG_CAL_AUTO(ri)        VTSS_IOREG(VTSS_TO_QSYS,0x4f5 + (ri))

#define VTSS_QSYS_CALCFG_CAL_SEQ             VTSS_IOREG(VTSS_TO_QSYS,0x4f9)
#define  VTSS_F_QSYS_CALCFG_CAL_SEQ_CAL_SEQ_LEN(x)  VTSS_ENCODE_BITFIELD(x,13,9)
#define  VTSS_M_QSYS_CALCFG_CAL_SEQ_CAL_SEQ_LEN     VTSS_ENCODE_BITMASK(13,9)
#define  VTSS_X_QSYS_CALCFG_CAL_SEQ_CAL_SEQ_LEN(x)  VTSS_EXTRACT_BITFIELD(x,13,9)
#define  VTSS_F_QSYS_CALCFG_CAL_SEQ_CAL_SEQ_CUR_VAL(x)  VTSS_ENCODE_BITFIELD(x,7,6)
#define  VTSS_M_QSYS_CALCFG_CAL_SEQ_CAL_SEQ_CUR_VAL     VTSS_ENCODE_BITMASK(7,6)
#define  VTSS_X_QSYS_CALCFG_CAL_SEQ_CAL_SEQ_CUR_VAL(x)  VTSS_EXTRACT_BITFIELD(x,7,6)
#define  VTSS_F_QSYS_CALCFG_CAL_SEQ_CAL_SEQ_PGM_VAL(x)  VTSS_ENCODE_BITFIELD(x,1,6)
#define  VTSS_M_QSYS_CALCFG_CAL_SEQ_CAL_SEQ_PGM_VAL     VTSS_ENCODE_BITMASK(1,6)
#define  VTSS_X_QSYS_CALCFG_CAL_SEQ_CAL_SEQ_PGM_VAL(x)  VTSS_EXTRACT_BITFIELD(x,1,6)
#define  VTSS_F_QSYS_CALCFG_CAL_SEQ_CAL_SEQ_PGM_ENA  VTSS_BIT(0)

#define VTSS_QSYS_CALCFG_CAL_CTRL            VTSS_IOREG(VTSS_TO_QSYS,0x4fa)
#define  VTSS_F_QSYS_CALCFG_CAL_CTRL_CAL_MODE(x)  VTSS_ENCODE_BITFIELD(x,9,4)
#define  VTSS_M_QSYS_CALCFG_CAL_CTRL_CAL_MODE     VTSS_ENCODE_BITMASK(9,4)
#define  VTSS_X_QSYS_CALCFG_CAL_CTRL_CAL_MODE(x)  VTSS_EXTRACT_BITFIELD(x,9,4)
#define  VTSS_F_QSYS_CALCFG_CAL_CTRL_CAL_AUTOCYCLES_10G(x)  VTSS_ENCODE_BITFIELD(x,2,7)
#define  VTSS_M_QSYS_CALCFG_CAL_CTRL_CAL_AUTOCYCLES_10G     VTSS_ENCODE_BITMASK(2,7)
#define  VTSS_X_QSYS_CALCFG_CAL_CTRL_CAL_AUTOCYCLES_10G(x)  VTSS_EXTRACT_BITFIELD(x,2,7)
#define  VTSS_F_QSYS_CALCFG_CAL_CTRL_CAL_AUTO_ERROR  VTSS_BIT(1)
#define  VTSS_F_QSYS_CALCFG_CAL_CTRL_CAL_VD_USE_IDLE_ENA  VTSS_BIT(0)

#define VTSS_QSYS_RAM_CTRL_RAM_INIT          VTSS_IOREG(VTSS_TO_QSYS,0x4fb)
#define  VTSS_F_QSYS_RAM_CTRL_RAM_INIT_RAM_INIT  VTSS_BIT(1)
#define  VTSS_F_QSYS_RAM_CTRL_RAM_INIT_RAM_ENA  VTSS_BIT(0)

#define VTSS_QSYS_COREMEM_CM_ADDR            VTSS_IOREG(VTSS_TO_QSYS,0x400)
#define  VTSS_F_QSYS_COREMEM_CM_ADDR_CM_ID(x)  VTSS_ENCODE_BITFIELD(x,22,8)
#define  VTSS_M_QSYS_COREMEM_CM_ADDR_CM_ID     VTSS_ENCODE_BITMASK(22,8)
#define  VTSS_X_QSYS_COREMEM_CM_ADDR_CM_ID(x)  VTSS_EXTRACT_BITFIELD(x,22,8)
#define  VTSS_F_QSYS_COREMEM_CM_ADDR_CM_ADDR(x)  VTSS_ENCODE_BITFIELD(x,0,22)
#define  VTSS_M_QSYS_COREMEM_CM_ADDR_CM_ADDR     VTSS_ENCODE_BITMASK(0,22)
#define  VTSS_X_QSYS_COREMEM_CM_ADDR_CM_ADDR(x)  VTSS_EXTRACT_BITFIELD(x,0,22)

#define VTSS_QSYS_COREMEM_CM_DATA            VTSS_IOREG(VTSS_TO_QSYS,0x401)


#endif /* _VTSS_JAGUAR2_REGS_QSYS_H_ */
