#ifndef _VTSS_JAGUAR2_REGS_ANA_L2_H_
#define _VTSS_JAGUAR2_REGS_ANA_L2_H_

/*
 *
 * VCore-III Register Definitions
 *
 * Copyright (C) 2012 Vitesse Semiconductor Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#include "vtss_jaguar2_regs_common.h"

#define VTSS_ANA_L2_COMMON_FWD_CFG           VTSS_IOREG(VTSS_TO_ANA_L2,0x228aa)
#define  VTSS_F_ANA_L2_COMMON_FWD_CFG_MAC_TBL_SPLIT_SEL(x)  VTSS_ENCODE_BITFIELD(x,20,2)
#define  VTSS_M_ANA_L2_COMMON_FWD_CFG_MAC_TBL_SPLIT_SEL     VTSS_ENCODE_BITMASK(20,2)
#define  VTSS_X_ANA_L2_COMMON_FWD_CFG_MAC_TBL_SPLIT_SEL(x)  VTSS_EXTRACT_BITFIELD(x,20,2)
#define  VTSS_F_ANA_L2_COMMON_FWD_CFG_ISDX_DEFAULT_DLB_ENA  VTSS_BIT(18)
#define  VTSS_F_ANA_L2_COMMON_FWD_CFG_ISDX_LOOKUP_ENA  VTSS_BIT(16)
#define  VTSS_F_ANA_L2_COMMON_FWD_CFG_CPU_DMAC_QU(x)  VTSS_ENCODE_BITFIELD(x,8,3)
#define  VTSS_M_ANA_L2_COMMON_FWD_CFG_CPU_DMAC_QU     VTSS_ENCODE_BITMASK(8,3)
#define  VTSS_X_ANA_L2_COMMON_FWD_CFG_CPU_DMAC_QU(x)  VTSS_EXTRACT_BITFIELD(x,8,3)
#define  VTSS_F_ANA_L2_COMMON_FWD_CFG_LOOPBACK_ENA  VTSS_BIT(7)
#define  VTSS_F_ANA_L2_COMMON_FWD_CFG_CPU_DMAC_COPY_ENA  VTSS_BIT(6)
#define  VTSS_F_ANA_L2_COMMON_FWD_CFG_FILTER_MODE_SEL  VTSS_BIT(4)
#define  VTSS_F_ANA_L2_COMMON_FWD_CFG_FLOOD_MIRROR_ENA  VTSS_BIT(3)
#define  VTSS_F_ANA_L2_COMMON_FWD_CFG_FLOOD_IGNORE_VLAN_ENA  VTSS_BIT(2)
#define  VTSS_F_ANA_L2_COMMON_FWD_CFG_FLOOD_CPU_COPY_ENA  VTSS_BIT(1)
#define  VTSS_F_ANA_L2_COMMON_FWD_CFG_FWD_ENA  VTSS_BIT(0)

#define VTSS_ANA_L2_COMMON_LRN_CFG           VTSS_IOREG(VTSS_TO_ANA_L2,0x228ab)
#define  VTSS_F_ANA_L2_COMMON_LRN_CFG_VSTAX_LRN_SKIP_ENA  VTSS_BIT(25)
#define  VTSS_F_ANA_L2_COMMON_LRN_CFG_IGNORE_MCIDX_PORTMOVE_ENA  VTSS_BIT(24)
#define  VTSS_F_ANA_L2_COMMON_LRN_CFG_CPU_FID_LIMIT_QU(x)  VTSS_ENCODE_BITFIELD(x,20,3)
#define  VTSS_M_ANA_L2_COMMON_LRN_CFG_CPU_FID_LIMIT_QU     VTSS_ENCODE_BITMASK(20,3)
#define  VTSS_X_ANA_L2_COMMON_LRN_CFG_CPU_FID_LIMIT_QU(x)  VTSS_EXTRACT_BITFIELD(x,20,3)
#define  VTSS_F_ANA_L2_COMMON_LRN_CFG_CPU_COPY_LRN_LIMIT_EXCEED_ENA  VTSS_BIT(19)
#define  VTSS_F_ANA_L2_COMMON_LRN_CFG_AGED_BEFORE_NONAGED  VTSS_BIT(18)
#define  VTSS_F_ANA_L2_COMMON_LRN_CFG_AGE_SIZE  VTSS_BIT(17)
#define  VTSS_F_ANA_L2_COMMON_LRN_CFG_VSTAX_BASIC_LRN_MODE_ENA  VTSS_BIT(16)
#define  VTSS_F_ANA_L2_COMMON_LRN_CFG_LRN_MOVE_CAM_ENTRY_BACK  VTSS_BIT(15)
#define  VTSS_F_ANA_L2_COMMON_LRN_CFG_AUTO_LRN_USE_MAC_CAM_ENA  VTSS_BIT(14)
#define  VTSS_F_ANA_L2_COMMON_LRN_CFG_AUTO_LRN_REPLACE_DIS  VTSS_BIT(13)
#define  VTSS_F_ANA_L2_COMMON_LRN_CFG_CPU_LRN_USE_MAC_CAM_ENA  VTSS_BIT(12)
#define  VTSS_F_ANA_L2_COMMON_LRN_CFG_CPU_LRN_QU(x)  VTSS_ENCODE_BITFIELD(x,4,3)
#define  VTSS_M_ANA_L2_COMMON_LRN_CFG_CPU_LRN_QU     VTSS_ENCODE_BITMASK(4,3)
#define  VTSS_X_ANA_L2_COMMON_LRN_CFG_CPU_LRN_QU(x)  VTSS_EXTRACT_BITFIELD(x,4,3)
#define  VTSS_F_ANA_L2_COMMON_LRN_CFG_AGE_LOCKED_ENA  VTSS_BIT(3)
#define  VTSS_F_ANA_L2_COMMON_LRN_CFG_LOCKED_PORTMOVE_COPY_ENA  VTSS_BIT(2)
#define  VTSS_F_ANA_L2_COMMON_LRN_CFG_LOCKED_PORTMOVE_DETECT_ENA  VTSS_BIT(1)
#define  VTSS_F_ANA_L2_COMMON_LRN_CFG_CPU_SMAC_COPY_ENA  VTSS_BIT(0)

#define VTSS_ANA_L2_COMMON_FILTER_OTHER_CTRL  VTSS_IOREG(VTSS_TO_ANA_L2,0x228ac)
#define  VTSS_F_ANA_L2_COMMON_FILTER_OTHER_CTRL_FILTER_REMOTE_ENA  VTSS_BIT(0)

#define VTSS_ANA_L2_COMMON_FILTER_LOCAL_CTRL  VTSS_IOREG(VTSS_TO_ANA_L2,0x228ad)

#define VTSS_ANA_L2_COMMON_FILTER_LOCAL_CTRL1  VTSS_IOREG(VTSS_TO_ANA_L2,0x228ae)
#define  VTSS_F_ANA_L2_COMMON_FILTER_LOCAL_CTRL1_FILTER_FRONTPORT_ENA1(x)  VTSS_ENCODE_BITFIELD(x,0,21)
#define  VTSS_M_ANA_L2_COMMON_FILTER_LOCAL_CTRL1_FILTER_FRONTPORT_ENA1     VTSS_ENCODE_BITMASK(0,21)
#define  VTSS_X_ANA_L2_COMMON_FILTER_LOCAL_CTRL1_FILTER_FRONTPORT_ENA1(x)  VTSS_EXTRACT_BITFIELD(x,0,21)

#define VTSS_ANA_L2_COMMON_AUTO_LRN_CFG      VTSS_IOREG(VTSS_TO_ANA_L2,0x228af)

#define VTSS_ANA_L2_COMMON_AUTO_LRN_CFG1     VTSS_IOREG(VTSS_TO_ANA_L2,0x228b0)
#define  VTSS_F_ANA_L2_COMMON_AUTO_LRN_CFG1_AUTO_LRN_ENA1(x)  VTSS_ENCODE_BITFIELD(x,0,21)
#define  VTSS_M_ANA_L2_COMMON_AUTO_LRN_CFG1_AUTO_LRN_ENA1     VTSS_ENCODE_BITMASK(0,21)
#define  VTSS_X_ANA_L2_COMMON_AUTO_LRN_CFG1_AUTO_LRN_ENA1(x)  VTSS_EXTRACT_BITFIELD(x,0,21)

#define VTSS_ANA_L2_COMMON_LRN_SECUR_CFG     VTSS_IOREG(VTSS_TO_ANA_L2,0x228b1)

#define VTSS_ANA_L2_COMMON_LRN_SECUR_CFG1    VTSS_IOREG(VTSS_TO_ANA_L2,0x228b2)
#define  VTSS_F_ANA_L2_COMMON_LRN_SECUR_CFG1_DROP_UNKNOWN_SRC_ENA1(x)  VTSS_ENCODE_BITFIELD(x,0,21)
#define  VTSS_M_ANA_L2_COMMON_LRN_SECUR_CFG1_DROP_UNKNOWN_SRC_ENA1     VTSS_ENCODE_BITMASK(0,21)
#define  VTSS_X_ANA_L2_COMMON_LRN_SECUR_CFG1_DROP_UNKNOWN_SRC_ENA1(x)  VTSS_EXTRACT_BITFIELD(x,0,21)

#define VTSS_ANA_L2_COMMON_LRN_SECUR_LOCKED_CFG  VTSS_IOREG(VTSS_TO_ANA_L2,0x228b3)

#define VTSS_ANA_L2_COMMON_LRN_SECUR_LOCKED_CFG1  VTSS_IOREG(VTSS_TO_ANA_L2,0x228b4)
#define  VTSS_F_ANA_L2_COMMON_LRN_SECUR_LOCKED_CFG1_DROP_MOVED_LOCKED_ENA1(x)  VTSS_ENCODE_BITFIELD(x,0,21)
#define  VTSS_M_ANA_L2_COMMON_LRN_SECUR_LOCKED_CFG1_DROP_MOVED_LOCKED_ENA1     VTSS_ENCODE_BITMASK(0,21)
#define  VTSS_X_ANA_L2_COMMON_LRN_SECUR_LOCKED_CFG1_DROP_MOVED_LOCKED_ENA1(x)  VTSS_EXTRACT_BITFIELD(x,0,21)

#define VTSS_ANA_L2_COMMON_LRN_COPY_CFG      VTSS_IOREG(VTSS_TO_ANA_L2,0x228b5)

#define VTSS_ANA_L2_COMMON_LRN_COPY_CFG1     VTSS_IOREG(VTSS_TO_ANA_L2,0x228b6)
#define  VTSS_F_ANA_L2_COMMON_LRN_COPY_CFG1_CPU_LRN_COPY_ENA1(x)  VTSS_ENCODE_BITFIELD(x,0,21)
#define  VTSS_M_ANA_L2_COMMON_LRN_COPY_CFG1_CPU_LRN_COPY_ENA1     VTSS_ENCODE_BITMASK(0,21)
#define  VTSS_X_ANA_L2_COMMON_LRN_COPY_CFG1_CPU_LRN_COPY_ENA1(x)  VTSS_EXTRACT_BITFIELD(x,0,21)

#define VTSS_ANA_L2_COMMON_PORT_DLB_CFG(ri)  VTSS_IOREG(VTSS_TO_ANA_L2,0x228b7 + (ri))
#define  VTSS_F_ANA_L2_COMMON_PORT_DLB_CFG_PORT_DLB_IDX(x)  VTSS_ENCODE_BITFIELD(x,0,12)
#define  VTSS_M_ANA_L2_COMMON_PORT_DLB_CFG_PORT_DLB_IDX     VTSS_ENCODE_BITMASK(0,12)
#define  VTSS_X_ANA_L2_COMMON_PORT_DLB_CFG_PORT_DLB_IDX(x)  VTSS_EXTRACT_BITFIELD(x,0,12)

#define VTSS_ANA_L2_COMMON_SCAN_FID_CTRL     VTSS_IOREG(VTSS_TO_ANA_L2,0x228ec)
#define  VTSS_F_ANA_L2_COMMON_SCAN_FID_CTRL_SCAN_FID_ENA  VTSS_BIT(0)

#define VTSS_ANA_L2_COMMON_SCAN_FID_CFG(ri)  VTSS_IOREG(VTSS_TO_ANA_L2,0x228ed + (ri))
#define  VTSS_F_ANA_L2_COMMON_SCAN_FID_CFG_SCAN_FID_VAL(x)  VTSS_ENCODE_BITFIELD(x,0,13)
#define  VTSS_M_ANA_L2_COMMON_SCAN_FID_CFG_SCAN_FID_VAL     VTSS_ENCODE_BITMASK(0,13)
#define  VTSS_X_ANA_L2_COMMON_SCAN_FID_CFG_SCAN_FID_VAL(x)  VTSS_EXTRACT_BITFIELD(x,0,13)

#define VTSS_ANA_L2_COMMON_MOVELOG_STICKY    VTSS_IOREG(VTSS_TO_ANA_L2,0x228fd)

#define VTSS_ANA_L2_COMMON_MOVELOG_STICKY1   VTSS_IOREG(VTSS_TO_ANA_L2,0x228fe)
#define  VTSS_F_ANA_L2_COMMON_MOVELOG_STICKY1_PORTMOVE_LOG_STICKY1(x)  VTSS_ENCODE_BITFIELD(x,0,21)
#define  VTSS_M_ANA_L2_COMMON_MOVELOG_STICKY1_PORTMOVE_LOG_STICKY1     VTSS_ENCODE_BITMASK(0,21)
#define  VTSS_X_ANA_L2_COMMON_MOVELOG_STICKY1_PORTMOVE_LOG_STICKY1(x)  VTSS_EXTRACT_BITFIELD(x,0,21)

#define VTSS_ANA_L2_COMMON_VSTAX_CTRL        VTSS_IOREG(VTSS_TO_ANA_L2,0x228ff)
#define  VTSS_F_ANA_L2_COMMON_VSTAX_CTRL_VSTAX2_NXT_LRN_ALL_RT_ACL_ENA  VTSS_BIT(25)
#define  VTSS_F_ANA_L2_COMMON_VSTAX_CTRL_VSTAX2_LCPU_CP_ACL_RT_ENA  VTSS_BIT(24)
#define  VTSS_F_ANA_L2_COMMON_VSTAX_CTRL_OWN_UPSID(x)  VTSS_ENCODE_BITFIELD(x,16,5)
#define  VTSS_M_ANA_L2_COMMON_VSTAX_CTRL_OWN_UPSID     VTSS_ENCODE_BITMASK(16,5)
#define  VTSS_X_ANA_L2_COMMON_VSTAX_CTRL_OWN_UPSID(x)  VTSS_EXTRACT_BITFIELD(x,16,5)
#define  VTSS_F_ANA_L2_COMMON_VSTAX_CTRL_CPU_VSTAX_QU(x)  VTSS_ENCODE_BITFIELD(x,12,3)
#define  VTSS_M_ANA_L2_COMMON_VSTAX_CTRL_CPU_VSTAX_QU     VTSS_ENCODE_BITMASK(12,3)
#define  VTSS_X_ANA_L2_COMMON_VSTAX_CTRL_CPU_VSTAX_QU(x)  VTSS_EXTRACT_BITFIELD(x,12,3)
#define  VTSS_F_ANA_L2_COMMON_VSTAX_CTRL_VSTAX2_LCPU_CP_UNEXP_DST_PORT_ENA  VTSS_BIT(11)
#define  VTSS_F_ANA_L2_COMMON_VSTAX_CTRL_VSTAX2_LCPU_CP_NXT_LRN_ALL_FRONT_ENA  VTSS_BIT(10)
#define  VTSS_F_ANA_L2_COMMON_VSTAX_CTRL_VSTAX2_LCPU_CP_REFRESH_STACK_ENA  VTSS_BIT(9)
#define  VTSS_F_ANA_L2_COMMON_VSTAX_CTRL_VSTAX2_LCPU_CP_REFRESH_FRONT_ENA  VTSS_BIT(8)
#define  VTSS_F_ANA_L2_COMMON_VSTAX_CTRL_VSTAX2_LCPU_CP_MOVE_STACK_ENA  VTSS_BIT(7)
#define  VTSS_F_ANA_L2_COMMON_VSTAX_CTRL_VSTAX2_LCPU_CP_NEW_STACK_ENA  VTSS_BIT(6)
#define  VTSS_F_ANA_L2_COMMON_VSTAX_CTRL_VSTAX2_LCPU_CP_MOVE_FRONT_ENA  VTSS_BIT(5)
#define  VTSS_F_ANA_L2_COMMON_VSTAX_CTRL_VSTAX2_LCPU_CP_NEW_FRONT_ENA  VTSS_BIT(4)
#define  VTSS_F_ANA_L2_COMMON_VSTAX_CTRL_VSTAX2_LRN_ALL_UNEXP_FLOOD_ENA  VTSS_BIT(3)
#define  VTSS_F_ANA_L2_COMMON_VSTAX_CTRL_VSTAX2_LRN_ALL_REFRESH_ENA  VTSS_BIT(2)
#define  VTSS_F_ANA_L2_COMMON_VSTAX_CTRL_VSTAX2_LRN_ALL_MOVE_ENA  VTSS_BIT(1)
#define  VTSS_F_ANA_L2_COMMON_VSTAX_CTRL_VSTAX2_LRN_ALL_NEW_ENA  VTSS_BIT(0)

#define VTSS_ANA_L2_COMMON_INTR              VTSS_IOREG(VTSS_TO_ANA_L2,0x22900)
#define  VTSS_F_ANA_L2_COMMON_INTR_LRN_ACCESS_COMPLETE_INTR  VTSS_BIT(3)
#define  VTSS_F_ANA_L2_COMMON_INTR_VCAP_S2_INTR  VTSS_BIT(2)
#define  VTSS_F_ANA_L2_COMMON_INTR_PORT_LRN_LIMIT_INTR  VTSS_BIT(1)
#define  VTSS_F_ANA_L2_COMMON_INTR_FID_LIMIT_INTR  VTSS_BIT(0)

#define VTSS_ANA_L2_COMMON_INTR_ENA          VTSS_IOREG(VTSS_TO_ANA_L2,0x22901)
#define  VTSS_F_ANA_L2_COMMON_INTR_ENA_LRN_ACCESS_COMPLETE_INTR_ENA  VTSS_BIT(3)
#define  VTSS_F_ANA_L2_COMMON_INTR_ENA_VCAP_S2_INTR_ENA  VTSS_BIT(2)
#define  VTSS_F_ANA_L2_COMMON_INTR_ENA_PORT_LRN_LIMIT_INTR_ENA  VTSS_BIT(1)
#define  VTSS_F_ANA_L2_COMMON_INTR_ENA_FID_LIMIT_INTR_ENA  VTSS_BIT(0)

#define VTSS_ANA_L2_COMMON_INTR_IDENT        VTSS_IOREG(VTSS_TO_ANA_L2,0x22902)
#define  VTSS_F_ANA_L2_COMMON_INTR_IDENT_LRN_ACCESS_COMPLETE_INTR_IDENT  VTSS_BIT(3)
#define  VTSS_F_ANA_L2_COMMON_INTR_IDENT_VCAP_S2_INTR_IDENT  VTSS_BIT(2)
#define  VTSS_F_ANA_L2_COMMON_INTR_IDENT_PORT_LRN_LIMIT_INTR_IDENT  VTSS_BIT(1)
#define  VTSS_F_ANA_L2_COMMON_INTR_IDENT_FID_LIMIT_INTR_IDENT  VTSS_BIT(0)

#define VTSS_ANA_L2_LRN_LIMIT_FID_LIMIT_STATUS(gi)  VTSS_IOREG_IX(VTSS_TO_ANA_L2,0x20000,gi,2,0,0)
#define  VTSS_F_ANA_L2_LRN_LIMIT_FID_LIMIT_STATUS_FID_LRN_LIMIT_EXCEEDED_STICKY  VTSS_BIT(16)
#define  VTSS_F_ANA_L2_LRN_LIMIT_FID_LIMIT_STATUS_FID_LRN_CNT(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_ANA_L2_LRN_LIMIT_FID_LIMIT_STATUS_FID_LRN_CNT     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_ANA_L2_LRN_LIMIT_FID_LIMIT_STATUS_FID_LRN_CNT(x)  VTSS_EXTRACT_BITFIELD(x,0,16)

#define VTSS_ANA_L2_LRN_LIMIT_FID_LIMIT_CTRL(gi)  VTSS_IOREG_IX(VTSS_TO_ANA_L2,0x20000,gi,2,0,1)
#define  VTSS_F_ANA_L2_LRN_LIMIT_FID_LIMIT_CTRL_FID_LIMIT_EXCEED_IRQ_ENA  VTSS_BIT(17)
#define  VTSS_F_ANA_L2_LRN_LIMIT_FID_LIMIT_CTRL_FID_LIMIT_EXCEED_SEL(x)  VTSS_ENCODE_BITFIELD(x,15,2)
#define  VTSS_M_ANA_L2_LRN_LIMIT_FID_LIMIT_CTRL_FID_LIMIT_EXCEED_SEL     VTSS_ENCODE_BITMASK(15,2)
#define  VTSS_X_ANA_L2_LRN_LIMIT_FID_LIMIT_CTRL_FID_LIMIT_EXCEED_SEL(x)  VTSS_EXTRACT_BITFIELD(x,15,2)
#define  VTSS_F_ANA_L2_LRN_LIMIT_FID_LIMIT_CTRL_FID_LRN_CNT_LIMIT(x)  VTSS_ENCODE_BITFIELD(x,0,15)
#define  VTSS_M_ANA_L2_LRN_LIMIT_FID_LIMIT_CTRL_FID_LRN_CNT_LIMIT     VTSS_ENCODE_BITMASK(0,15)
#define  VTSS_X_ANA_L2_LRN_LIMIT_FID_LIMIT_CTRL_FID_LRN_CNT_LIMIT(x)  VTSS_EXTRACT_BITFIELD(x,0,15)

#define VTSS_ANA_L2_PORT_LIMIT_PORT_LIMIT_STATUS(gi)  VTSS_IOREG_IX(VTSS_TO_ANA_L2,0x22800,gi,2,0,0)
#define  VTSS_F_ANA_L2_PORT_LIMIT_PORT_LIMIT_STATUS_PORT_LRN_LIMIT_EXCEEDED_STICKY  VTSS_BIT(16)
#define  VTSS_F_ANA_L2_PORT_LIMIT_PORT_LIMIT_STATUS_PORT_LRN_CNT(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_ANA_L2_PORT_LIMIT_PORT_LIMIT_STATUS_PORT_LRN_CNT     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_ANA_L2_PORT_LIMIT_PORT_LIMIT_STATUS_PORT_LRN_CNT(x)  VTSS_EXTRACT_BITFIELD(x,0,16)

#define VTSS_ANA_L2_PORT_LIMIT_PORT_LIMIT_CTRL(gi)  VTSS_IOREG_IX(VTSS_TO_ANA_L2,0x22800,gi,2,0,1)
#define  VTSS_F_ANA_L2_PORT_LIMIT_PORT_LIMIT_CTRL_PORT_LIMIT_EXCEED_IRQ_ENA  VTSS_BIT(17)
#define  VTSS_F_ANA_L2_PORT_LIMIT_PORT_LIMIT_CTRL_PORT_LIMIT_EXCEED_SEL(x)  VTSS_ENCODE_BITFIELD(x,15,2)
#define  VTSS_M_ANA_L2_PORT_LIMIT_PORT_LIMIT_CTRL_PORT_LIMIT_EXCEED_SEL     VTSS_ENCODE_BITMASK(15,2)
#define  VTSS_X_ANA_L2_PORT_LIMIT_PORT_LIMIT_CTRL_PORT_LIMIT_EXCEED_SEL(x)  VTSS_EXTRACT_BITFIELD(x,15,2)
#define  VTSS_F_ANA_L2_PORT_LIMIT_PORT_LIMIT_CTRL_PORT_LRN_CNT_LIMIT(x)  VTSS_ENCODE_BITFIELD(x,0,15)
#define  VTSS_M_ANA_L2_PORT_LIMIT_PORT_LIMIT_CTRL_PORT_LRN_CNT_LIMIT     VTSS_ENCODE_BITMASK(0,15)
#define  VTSS_X_ANA_L2_PORT_LIMIT_PORT_LIMIT_CTRL_PORT_LRN_CNT_LIMIT(x)  VTSS_EXTRACT_BITFIELD(x,0,15)

#define VTSS_ANA_L2_ISDX_PORT_MASK_CFG(gi)   VTSS_IOREG_IX(VTSS_TO_ANA_L2,0x0,gi,32,0,0)

#define VTSS_ANA_L2_ISDX_PORT_MASK_CFG1(gi)  VTSS_IOREG_IX(VTSS_TO_ANA_L2,0x0,gi,32,0,1)
#define  VTSS_F_ANA_L2_ISDX_PORT_MASK_CFG1_PORT_MASK1(x)  VTSS_ENCODE_BITFIELD(x,0,21)
#define  VTSS_M_ANA_L2_ISDX_PORT_MASK_CFG1_PORT_MASK1     VTSS_ENCODE_BITMASK(0,21)
#define  VTSS_X_ANA_L2_ISDX_PORT_MASK_CFG1_PORT_MASK1(x)  VTSS_EXTRACT_BITFIELD(x,0,21)

#define VTSS_ANA_L2_ISDX_SERVICE_CTRL(gi)    VTSS_IOREG_IX(VTSS_TO_ANA_L2,0x0,gi,32,0,2)
#define  VTSS_F_ANA_L2_ISDX_SERVICE_CTRL_PORT_MASK_REPLACE_ENA  VTSS_BIT(25)
#define  VTSS_F_ANA_L2_ISDX_SERVICE_CTRL_AGGR_VAL(x)  VTSS_ENCODE_BITFIELD(x,21,4)
#define  VTSS_M_ANA_L2_ISDX_SERVICE_CTRL_AGGR_VAL     VTSS_ENCODE_BITMASK(21,4)
#define  VTSS_X_ANA_L2_ISDX_SERVICE_CTRL_AGGR_VAL(x)  VTSS_EXTRACT_BITFIELD(x,21,4)
#define  VTSS_F_ANA_L2_ISDX_SERVICE_CTRL_SRC_MASK_DIS  VTSS_BIT(20)
#define  VTSS_F_ANA_L2_ISDX_SERVICE_CTRL_AGGR_REPLACE_ENA  VTSS_BIT(19)
#define  VTSS_F_ANA_L2_ISDX_SERVICE_CTRL_ES0_ISDX_KEY_ENA  VTSS_BIT(18)
#define  VTSS_F_ANA_L2_ISDX_SERVICE_CTRL_CDA_FWD_ENA  VTSS_BIT(17)
#define  VTSS_F_ANA_L2_ISDX_SERVICE_CTRL_ISDX_BASED_FWD_ENA  VTSS_BIT(16)
#define  VTSS_F_ANA_L2_ISDX_SERVICE_CTRL_ISDX_BASED_SRC_ENA  VTSS_BIT(15)
#define  VTSS_F_ANA_L2_ISDX_SERVICE_CTRL_FWD_TYPE(x)  VTSS_ENCODE_BITFIELD(x,12,3)
#define  VTSS_M_ANA_L2_ISDX_SERVICE_CTRL_FWD_TYPE     VTSS_ENCODE_BITMASK(12,3)
#define  VTSS_X_ANA_L2_ISDX_SERVICE_CTRL_FWD_TYPE(x)  VTSS_EXTRACT_BITFIELD(x,12,3)
#define  VTSS_F_ANA_L2_ISDX_SERVICE_CTRL_FWD_ADDR(x)  VTSS_ENCODE_BITFIELD(x,0,12)
#define  VTSS_M_ANA_L2_ISDX_SERVICE_CTRL_FWD_ADDR     VTSS_ENCODE_BITMASK(0,12)
#define  VTSS_X_ANA_L2_ISDX_SERVICE_CTRL_FWD_ADDR(x)  VTSS_EXTRACT_BITFIELD(x,0,12)

#define VTSS_ANA_L2_ISDX_DLB_CFG(gi)         VTSS_IOREG_IX(VTSS_TO_ANA_L2,0x0,gi,32,0,3)
#define  VTSS_F_ANA_L2_ISDX_DLB_CFG_DLB_IDX(x)  VTSS_ENCODE_BITFIELD(x,0,12)
#define  VTSS_M_ANA_L2_ISDX_DLB_CFG_DLB_IDX     VTSS_ENCODE_BITMASK(0,12)
#define  VTSS_X_ANA_L2_ISDX_DLB_CFG_DLB_IDX(x)  VTSS_EXTRACT_BITFIELD(x,0,12)

#define VTSS_ANA_L2_ISDX_DLB_COS_CFG(gi,ri)  VTSS_IOREG_IX(VTSS_TO_ANA_L2,0x0,gi,32,ri,4)
#define  VTSS_F_ANA_L2_ISDX_DLB_COS_CFG_DLB_COS_OFFSET(x)  VTSS_ENCODE_BITFIELD(x,0,3)
#define  VTSS_M_ANA_L2_ISDX_DLB_COS_CFG_DLB_COS_OFFSET     VTSS_ENCODE_BITMASK(0,3)
#define  VTSS_X_ANA_L2_ISDX_DLB_COS_CFG_DLB_COS_OFFSET(x)  VTSS_EXTRACT_BITFIELD(x,0,3)

#define VTSS_ANA_L2_ISDX_ISDX_BASE_CFG(gi)   VTSS_IOREG_IX(VTSS_TO_ANA_L2,0x0,gi,32,0,12)
#define  VTSS_F_ANA_L2_ISDX_ISDX_BASE_CFG_ISDX_BASE_ADDR(x)  VTSS_ENCODE_BITFIELD(x,0,13)
#define  VTSS_M_ANA_L2_ISDX_ISDX_BASE_CFG_ISDX_BASE_ADDR     VTSS_ENCODE_BITMASK(0,13)
#define  VTSS_X_ANA_L2_ISDX_ISDX_BASE_CFG_ISDX_BASE_ADDR(x)  VTSS_EXTRACT_BITFIELD(x,0,13)

#define VTSS_ANA_L2_ISDX_ISDX_COS_CFG(gi,ri)  VTSS_IOREG_IX(VTSS_TO_ANA_L2,0x0,gi,32,ri,13)
#define  VTSS_F_ANA_L2_ISDX_ISDX_COS_CFG_ISDX_COS_OFFSET(x)  VTSS_ENCODE_BITFIELD(x,0,3)
#define  VTSS_M_ANA_L2_ISDX_ISDX_COS_CFG_ISDX_COS_OFFSET     VTSS_ENCODE_BITMASK(0,3)
#define  VTSS_X_ANA_L2_ISDX_ISDX_COS_CFG_ISDX_COS_OFFSET(x)  VTSS_EXTRACT_BITFIELD(x,0,3)

#define VTSS_ANA_L2_STICKY_STICKY            VTSS_IOREG(VTSS_TO_ANA_L2,0x22903)
#define  VTSS_F_ANA_L2_STICKY_STICKY_AUTO_LRN_RATE_EXCEED_STICKY  VTSS_BIT(15)
#define  VTSS_F_ANA_L2_STICKY_STICKY_FWD_FLOOD_KILL_STICKY  VTSS_BIT(14)
#define  VTSS_F_ANA_L2_STICKY_STICKY_VLAN_IGNORE_STICKY  VTSS_BIT(13)
#define  VTSS_F_ANA_L2_STICKY_STICKY_SRC_IGNORE_STICKY  VTSS_BIT(12)
#define  VTSS_F_ANA_L2_STICKY_STICKY_LOCAL_TO_REMOTE_PORTMOVE_STICKY  VTSS_BIT(11)
#define  VTSS_F_ANA_L2_STICKY_STICKY_REMOTE_TO_LOCAL_PORTMOVE_STICKY  VTSS_BIT(10)
#define  VTSS_F_ANA_L2_STICKY_STICKY_REMOTE_TO_REMOTE_PORTMOVE_STICKY  VTSS_BIT(9)
#define  VTSS_F_ANA_L2_STICKY_STICKY_GLOBAL_TO_GLOBAL_PORTMOVE_STICKY  VTSS_BIT(8)
#define  VTSS_F_ANA_L2_STICKY_STICKY_GLOBAL_TO_LOCAL_PORTMOVE_STICKY  VTSS_BIT(7)
#define  VTSS_F_ANA_L2_STICKY_STICKY_LOCAL_TO_GLOBAL_PORTMOVE_STICKY  VTSS_BIT(6)
#define  VTSS_F_ANA_L2_STICKY_STICKY_LOCAL_TO_LOCAL_PORTMOVE_STICKY  VTSS_BIT(5)
#define  VTSS_F_ANA_L2_STICKY_STICKY_FWD_FLOOD_STICKY  VTSS_BIT(4)
#define  VTSS_F_ANA_L2_STICKY_STICKY_FWD_ENTRY_FOUND_STICKY  VTSS_BIT(3)
#define  VTSS_F_ANA_L2_STICKY_STICKY_DROP_UNKNOWN_SRC_STICKY  VTSS_BIT(2)
#define  VTSS_F_ANA_L2_STICKY_STICKY_LEARN_KNOWN_STICKY  VTSS_BIT(1)
#define  VTSS_F_ANA_L2_STICKY_STICKY_LEARN_UNKNOWN_STICKY  VTSS_BIT(0)

#define VTSS_ANA_L2_STICKY_MASK_STICKY_MASK(gi)  VTSS_IOREG_IX(VTSS_TO_ANA_L2,0x22904,gi,1,0,0)
#define  VTSS_F_ANA_L2_STICKY_MASK_STICKY_MASK_AUTO_LRN_RATE_EXCEED_STICKY_MASK  VTSS_BIT(15)
#define  VTSS_F_ANA_L2_STICKY_MASK_STICKY_MASK_FWD_FLOOD_KILL_STICKY_MASK  VTSS_BIT(14)
#define  VTSS_F_ANA_L2_STICKY_MASK_STICKY_MASK_VLAN_IGNORE_STICKY_MASK  VTSS_BIT(13)
#define  VTSS_F_ANA_L2_STICKY_MASK_STICKY_MASK_SRC_IGNORE_STICKY_MASK  VTSS_BIT(12)
#define  VTSS_F_ANA_L2_STICKY_MASK_STICKY_MASK_LOCAL_TO_REMOTE_PORTMOVE_STICKY_MASK  VTSS_BIT(11)
#define  VTSS_F_ANA_L2_STICKY_MASK_STICKY_MASK_REMOTE_TO_LOCAL_PORTMOVE_STICKY_MASK  VTSS_BIT(10)
#define  VTSS_F_ANA_L2_STICKY_MASK_STICKY_MASK_REMOTE_TO_REMOTE_PORTMOVE_STICKY_MASK  VTSS_BIT(9)
#define  VTSS_F_ANA_L2_STICKY_MASK_STICKY_MASK_GLOBAL_TO_GLOBAL_PORTMOVE_STICKY_MASK  VTSS_BIT(8)
#define  VTSS_F_ANA_L2_STICKY_MASK_STICKY_MASK_GLOBAL_TO_LOCAL_PORTMOVE_STICKY_MASK  VTSS_BIT(7)
#define  VTSS_F_ANA_L2_STICKY_MASK_STICKY_MASK_LOCAL_TO_GLOBAL_PORTMOVE_STICKY_MASK  VTSS_BIT(6)
#define  VTSS_F_ANA_L2_STICKY_MASK_STICKY_MASK_LOCAL_TO_LOCAL_PORTMOVE_STICKY_MASK  VTSS_BIT(5)
#define  VTSS_F_ANA_L2_STICKY_MASK_STICKY_MASK_FWD_FLOOD_STICKY_MASK  VTSS_BIT(4)
#define  VTSS_F_ANA_L2_STICKY_MASK_STICKY_MASK_FWD_ENTRY_FOUND_STICKY_MASK  VTSS_BIT(3)
#define  VTSS_F_ANA_L2_STICKY_MASK_STICKY_MASK_DROP_UNKNOWN_SRC_STICKY_MASK  VTSS_BIT(2)
#define  VTSS_F_ANA_L2_STICKY_MASK_STICKY_MASK_LEARN_KNOWN_STICKY_MASK  VTSS_BIT(1)
#define  VTSS_F_ANA_L2_STICKY_MASK_STICKY_MASK_LEARN_UNKNOWN_STICKY_MASK  VTSS_BIT(0)


#endif /* _VTSS_JAGUAR2_REGS_ANA_L2_H_ */
