#ifndef _VTSS_JAGUAR2_REGS_PCS_10GBASE_R_H_
#define _VTSS_JAGUAR2_REGS_PCS_10GBASE_R_H_

/*
 *
 * VCore-III Register Definitions
 *
 * Copyright (C) 2012 Vitesse Semiconductor Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#include "vtss_jaguar2_regs_common.h"

#define VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG(target)  VTSS_IOREG(target,0x0)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_PCS_ENA  VTSS_BIT(31)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_PMA_LOOPBACK_ENA  VTSS_BIT(30)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_SH_CNT_MAX(x)  VTSS_ENCODE_BITFIELD(x,24,6)
#define  VTSS_M_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_SH_CNT_MAX     VTSS_ENCODE_BITMASK(24,6)
#define  VTSS_X_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_SH_CNT_MAX(x)  VTSS_EXTRACT_BITFIELD(x,24,6)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_DATA_FLIP  VTSS_BIT(18)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RESYNC_ENA  VTSS_BIT(15)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_LF_GEN_DIS  VTSS_BIT(14)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_TEST_MODE  VTSS_BIT(13)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_RX_SCR_DISABLE  VTSS_BIT(12)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_DATA_FLIP  VTSS_BIT(7)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_AN_LINK_CTRL_ENA  VTSS_BIT(6)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_TEST_MODE  VTSS_BIT(4)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_CFG_TX_SCR_DISABLE  VTSS_BIT(3)

#define VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_SD_CFG(target)  VTSS_IOREG(target,0x1)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_SD_CFG_SD_SEL  VTSS_BIT(8)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_SD_CFG_SD_POL  VTSS_BIT(4)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_SD_CFG_SD_ENA  VTSS_BIT(0)

#define VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TX_SEEDA_MSB(target)  VTSS_IOREG(target,0x2)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TX_SEEDA_MSB_TX_SEEDA_MSB(x)  VTSS_ENCODE_BITFIELD(x,0,26)
#define  VTSS_M_PCS_10GBASE_R_PCS_10GBR_CFG_TX_SEEDA_MSB_TX_SEEDA_MSB     VTSS_ENCODE_BITMASK(0,26)
#define  VTSS_X_PCS_10GBASE_R_PCS_10GBR_CFG_TX_SEEDA_MSB_TX_SEEDA_MSB(x)  VTSS_EXTRACT_BITFIELD(x,0,26)

#define VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TX_SEEDA_LSB(target)  VTSS_IOREG(target,0x3)

#define VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TX_SEEDB_MSB(target)  VTSS_IOREG(target,0x4)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TX_SEEDB_MSB_TX_SEEDB_MSB(x)  VTSS_ENCODE_BITFIELD(x,0,26)
#define  VTSS_M_PCS_10GBASE_R_PCS_10GBR_CFG_TX_SEEDB_MSB_TX_SEEDB_MSB     VTSS_ENCODE_BITMASK(0,26)
#define  VTSS_X_PCS_10GBASE_R_PCS_10GBR_CFG_TX_SEEDB_MSB_TX_SEEDB_MSB(x)  VTSS_EXTRACT_BITFIELD(x,0,26)

#define VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TX_SEEDB_LSB(target)  VTSS_IOREG(target,0x5)

#define VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_RX_PRBS31_INIT(target)  VTSS_IOREG(target,0x6)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_RX_PRBS31_INIT_RX_PRBS31_INIT(x)  VTSS_ENCODE_BITFIELD(x,0,31)
#define  VTSS_M_PCS_10GBASE_R_PCS_10GBR_CFG_RX_PRBS31_INIT_RX_PRBS31_INIT     VTSS_ENCODE_BITMASK(0,31)
#define  VTSS_X_PCS_10GBASE_R_PCS_10GBR_CFG_RX_PRBS31_INIT_RX_PRBS31_INIT(x)  VTSS_EXTRACT_BITFIELD(x,0,31)

#define VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TX_DATAPAT_MSB(target)  VTSS_IOREG(target,0x7)

#define VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TX_DATAPAT_LSB(target)  VTSS_IOREG(target,0x8)

#define VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_RX_DATAPAT_MSB(target)  VTSS_IOREG(target,0x9)

#define VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_RX_DATAPAT_LSB(target)  VTSS_IOREG(target,0xa)

#define VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TEST_CFG(target)  VTSS_IOREG(target,0xb)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TEST_CFG_RX_DSBL_INV  VTSS_BIT(18)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TEST_CFG_RX_TESTPAT_SEL(x)  VTSS_ENCODE_BITFIELD(x,16,2)
#define  VTSS_M_PCS_10GBASE_R_PCS_10GBR_CFG_TEST_CFG_RX_TESTPAT_SEL     VTSS_ENCODE_BITMASK(16,2)
#define  VTSS_X_PCS_10GBASE_R_PCS_10GBR_CFG_TEST_CFG_RX_TESTPAT_SEL(x)  VTSS_EXTRACT_BITFIELD(x,16,2)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TEST_CFG_TX_DSBL_INV  VTSS_BIT(5)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TEST_CFG_TX_SQPW_4B(x)  VTSS_ENCODE_BITFIELD(x,2,3)
#define  VTSS_M_PCS_10GBASE_R_PCS_10GBR_CFG_TEST_CFG_TX_SQPW_4B     VTSS_ENCODE_BITMASK(2,3)
#define  VTSS_X_PCS_10GBASE_R_PCS_10GBR_CFG_TEST_CFG_TX_SQPW_4B(x)  VTSS_EXTRACT_BITFIELD(x,2,3)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TEST_CFG_TX_TESTPAT_SEL(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_PCS_10GBASE_R_PCS_10GBR_CFG_TEST_CFG_TX_TESTPAT_SEL     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_PCS_10GBASE_R_PCS_10GBR_CFG_TEST_CFG_TX_TESTPAT_SEL(x)  VTSS_EXTRACT_BITFIELD(x,0,2)

#define VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_INTR_MASK(target)  VTSS_IOREG(target,0xc)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_INTR_MASK_RX_FSET_FIFO_FULL_MASK  VTSS_BIT(12)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_INTR_MASK_RX_FSET_MASK  VTSS_BIT(11)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_INTR_MASK_XGMII_ERR_MASK  VTSS_BIT(10)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_INTR_MASK_RX_OSET_FIFO_FULL_MASK  VTSS_BIT(6)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_INTR_MASK_RX_OSET_MASK  VTSS_BIT(5)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_INTR_MASK_C64B66B_ERR_MASK  VTSS_BIT(4)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_INTR_MASK_LOCK_CHANGED_MASK  VTSS_BIT(3)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_PCS_INTR_MASK_RX_HI_BER_MASK  VTSS_BIT(0)

#define VTSS_PCS_10GBASE_R_PCS_10GBR_CFG_TIMER_125(target)  VTSS_IOREG(target,0xd)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_CFG_TIMER_125_TIMER_125(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_PCS_10GBASE_R_PCS_10GBR_CFG_TIMER_125_TIMER_125     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_PCS_10GBASE_R_PCS_10GBR_CFG_TIMER_125_TIMER_125(x)  VTSS_EXTRACT_BITFIELD(x,0,16)

#define VTSS_PCS_10GBASE_R_PCS_10GBR_STATUS_PCS_INTR_STAT(target)  VTSS_IOREG(target,0xe)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_STATUS_PCS_INTR_STAT_RX_FSET_FIFO_FULL_STICKY  VTSS_BIT(12)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_STATUS_PCS_INTR_STAT_RX_FSET_STICKY  VTSS_BIT(11)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_STATUS_PCS_INTR_STAT_XGMII_ERR_STICKY  VTSS_BIT(10)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_STATUS_PCS_INTR_STAT_RX_OSET_FIFO_FULL_STICKY  VTSS_BIT(6)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_STATUS_PCS_INTR_STAT_RX_OSET_STICKY  VTSS_BIT(5)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_STATUS_PCS_INTR_STAT_C64B66B_ERR_STICKY  VTSS_BIT(4)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_STATUS_PCS_INTR_STAT_LOCK_CHANGED_STICKY  VTSS_BIT(3)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_STATUS_PCS_INTR_STAT_RX_HI_BER_STICKY  VTSS_BIT(0)

#define VTSS_PCS_10GBASE_R_PCS_10GBR_STATUS_PCS_STATUS(target)  VTSS_IOREG(target,0xf)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_STATUS_PCS_STATUS_TESTPAT_MATCH  VTSS_BIT(4)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_STATUS_PCS_STATUS_RX_BLOCK_LOCK  VTSS_BIT(3)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_STATUS_PCS_STATUS_RX_HI_BER  VTSS_BIT(0)

#define VTSS_PCS_10GBASE_R_PCS_10GBR_HA_STATUS_TEST_ERR_CNT(target)  VTSS_IOREG(target,0x10)

#define VTSS_PCS_10GBASE_R_PCS_10GBR_HA_STATUS_TX_ERRBLK_CNT(target)  VTSS_IOREG(target,0x11)

#define VTSS_PCS_10GBASE_R_PCS_10GBR_HA_STATUS_TX_CHARERR_CNT(target)  VTSS_IOREG(target,0x12)

#define VTSS_PCS_10GBASE_R_PCS_10GBR_HA_STATUS_RX_BER_CNT(target)  VTSS_IOREG(target,0x13)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_HA_STATUS_RX_BER_CNT_RX_BER_CNT(x)  VTSS_ENCODE_BITFIELD(x,0,5)
#define  VTSS_M_PCS_10GBASE_R_PCS_10GBR_HA_STATUS_RX_BER_CNT_RX_BER_CNT     VTSS_ENCODE_BITMASK(0,5)
#define  VTSS_X_PCS_10GBASE_R_PCS_10GBR_HA_STATUS_RX_BER_CNT_RX_BER_CNT(x)  VTSS_EXTRACT_BITFIELD(x,0,5)

#define VTSS_PCS_10GBASE_R_PCS_10GBR_HA_STATUS_RX_ERRBLK_CNT(target)  VTSS_IOREG(target,0x14)

#define VTSS_PCS_10GBASE_R_PCS_10GBR_HA_STATUS_RX_CHARERR_CNT(target)  VTSS_IOREG(target,0x15)

#define VTSS_PCS_10GBASE_R_PCS_10GBR_HA_STATUS_RX_OSET_FIFO_STAT(target)  VTSS_IOREG(target,0x16)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_HA_STATUS_RX_OSET_FIFO_STAT_RX_OSET_FIFO_FULL  VTSS_BIT(4)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_HA_STATUS_RX_OSET_FIFO_STAT_RX_OSET_FIFO_NUM(x)  VTSS_ENCODE_BITFIELD(x,0,3)
#define  VTSS_M_PCS_10GBASE_R_PCS_10GBR_HA_STATUS_RX_OSET_FIFO_STAT_RX_OSET_FIFO_NUM     VTSS_ENCODE_BITMASK(0,3)
#define  VTSS_X_PCS_10GBASE_R_PCS_10GBR_HA_STATUS_RX_OSET_FIFO_STAT_RX_OSET_FIFO_NUM(x)  VTSS_EXTRACT_BITFIELD(x,0,3)

#define VTSS_PCS_10GBASE_R_PCS_10GBR_HA_STATUS_RX_OSET_FIFO_DATA(target)  VTSS_IOREG(target,0x17)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_HA_STATUS_RX_OSET_FIFO_DATA_RX_OSET_FIFO_DATA(x)  VTSS_ENCODE_BITFIELD(x,8,24)
#define  VTSS_M_PCS_10GBASE_R_PCS_10GBR_HA_STATUS_RX_OSET_FIFO_DATA_RX_OSET_FIFO_DATA     VTSS_ENCODE_BITMASK(8,24)
#define  VTSS_X_PCS_10GBASE_R_PCS_10GBR_HA_STATUS_RX_OSET_FIFO_DATA_RX_OSET_FIFO_DATA(x)  VTSS_EXTRACT_BITFIELD(x,8,24)

#define VTSS_PCS_10GBASE_R_PCS_10GBR_HA_STATUS_RX_FSET_FIFO_STAT(target)  VTSS_IOREG(target,0x18)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_HA_STATUS_RX_FSET_FIFO_STAT_RX_FSET_FIFO_FULL  VTSS_BIT(4)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_HA_STATUS_RX_FSET_FIFO_STAT_RX_FSET_FIFO_NUM(x)  VTSS_ENCODE_BITFIELD(x,0,3)
#define  VTSS_M_PCS_10GBASE_R_PCS_10GBR_HA_STATUS_RX_FSET_FIFO_STAT_RX_FSET_FIFO_NUM     VTSS_ENCODE_BITMASK(0,3)
#define  VTSS_X_PCS_10GBASE_R_PCS_10GBR_HA_STATUS_RX_FSET_FIFO_STAT_RX_FSET_FIFO_NUM(x)  VTSS_EXTRACT_BITFIELD(x,0,3)

#define VTSS_PCS_10GBASE_R_PCS_10GBR_HA_STATUS_RX_FSET_FIFO_DATA(target)  VTSS_IOREG(target,0x19)
#define  VTSS_F_PCS_10GBASE_R_PCS_10GBR_HA_STATUS_RX_FSET_FIFO_DATA_RX_FSET_FIFO_DATA(x)  VTSS_ENCODE_BITFIELD(x,8,24)
#define  VTSS_M_PCS_10GBASE_R_PCS_10GBR_HA_STATUS_RX_FSET_FIFO_DATA_RX_FSET_FIFO_DATA     VTSS_ENCODE_BITMASK(8,24)
#define  VTSS_X_PCS_10GBASE_R_PCS_10GBR_HA_STATUS_RX_FSET_FIFO_DATA_RX_FSET_FIFO_DATA(x)  VTSS_EXTRACT_BITFIELD(x,8,24)

#define VTSS_PCS_10GBASE_R_KR_FEC_CFG_KR_FEC_CFG(target)  VTSS_IOREG(target,0x1a)
#define  VTSS_F_PCS_10GBASE_R_KR_FEC_CFG_KR_FEC_CFG_ENABLE_ERROR_INDICATION  VTSS_BIT(16)
#define  VTSS_F_PCS_10GBASE_R_KR_FEC_CFG_KR_FEC_CFG_RESET_MONITOR_COUNTERS  VTSS_BIT(12)
#define  VTSS_F_PCS_10GBASE_R_KR_FEC_CFG_KR_FEC_CFG_TX_DATA_FLIP  VTSS_BIT(8)
#define  VTSS_F_PCS_10GBASE_R_KR_FEC_CFG_KR_FEC_CFG_RX_DATA_FLIP  VTSS_BIT(4)
#define  VTSS_F_PCS_10GBASE_R_KR_FEC_CFG_KR_FEC_CFG_AN_FEC_CTRL_ENA  VTSS_BIT(2)
#define  VTSS_F_PCS_10GBASE_R_KR_FEC_CFG_KR_FEC_CFG_FEC_ENA  VTSS_BIT(0)

#define VTSS_PCS_10GBASE_R_KR_FEC_THRESHOLD_CFG_FIXED_ERROR_COUNT_THRESHOLD(target)  VTSS_IOREG(target,0x1b)

#define VTSS_PCS_10GBASE_R_KR_FEC_THRESHOLD_CFG_UNFIXABLE_ERROR_COUNT_THRESHOLD(target)  VTSS_IOREG(target,0x1c)

#define VTSS_PCS_10GBASE_R_KR_FEC_HA_STATUS_KR_FEC_CORRECTED(target)  VTSS_IOREG(target,0x1d)

#define VTSS_PCS_10GBASE_R_KR_FEC_HA_STATUS_KR_FEC_UNCORRECTED(target)  VTSS_IOREG(target,0x1e)

#define VTSS_PCS_10GBASE_R_KR_FEC_STATUS_KR_FEC_STICKY(target)  VTSS_IOREG(target,0x1f)
#define  VTSS_F_PCS_10GBASE_R_KR_FEC_STATUS_KR_FEC_STICKY_FEC_FIXED_ERROR_COUNT_STICKY  VTSS_BIT(8)
#define  VTSS_F_PCS_10GBASE_R_KR_FEC_STATUS_KR_FEC_STICKY_FEC_UNFIXABLE_ERROR_COUNT_STICKY  VTSS_BIT(4)
#define  VTSS_F_PCS_10GBASE_R_KR_FEC_STATUS_KR_FEC_STICKY_FEC_FRAME_LOCK_STICKY  VTSS_BIT(0)

#define VTSS_PCS_10GBASE_R_KR_FEC_STATUS_KR_FEC_STICKY_MASK(target)  VTSS_IOREG(target,0x20)
#define  VTSS_F_PCS_10GBASE_R_KR_FEC_STATUS_KR_FEC_STICKY_MASK_FEC_FIXED_ERROR_COUNT_STICKY_MASK  VTSS_BIT(8)
#define  VTSS_F_PCS_10GBASE_R_KR_FEC_STATUS_KR_FEC_STICKY_MASK_FEC_UNFIXABLE_ERROR_COUNT_STICKY_MASK  VTSS_BIT(4)
#define  VTSS_F_PCS_10GBASE_R_KR_FEC_STATUS_KR_FEC_STICKY_MASK_FEC_FRAME_LOCK_STICKY_MASK  VTSS_BIT(0)

#define VTSS_PCS_10GBASE_R_KR_FEC_STATUS_KR_FEC_STATUS(target)  VTSS_IOREG(target,0x21)
#define  VTSS_F_PCS_10GBASE_R_KR_FEC_STATUS_KR_FEC_STATUS_FEC_FIXED_ERROR_COUNT_ERROR_STATUS  VTSS_BIT(1)
#define  VTSS_F_PCS_10GBASE_R_KR_FEC_STATUS_KR_FEC_STATUS_FEC_UNFIXABLE_ERROR_COUNT_ERROR_STATUS  VTSS_BIT(0)

#define VTSS_PCS_10GBASE_R_KR_FEC_CAPABILITY_KR_FEC_CAPABILITY(target)  VTSS_IOREG(target,0x22)
#define  VTSS_F_PCS_10GBASE_R_KR_FEC_CAPABILITY_KR_FEC_CAPABILITY_FEC_CAPABLE  VTSS_BIT(0)

#define VTSS_PCS_10GBASE_R_EEE_TIMER_CFG_ONE_US_TIMER_REG(target)  VTSS_IOREG(target,0x23)
#define  VTSS_F_PCS_10GBASE_R_EEE_TIMER_CFG_ONE_US_TIMER_REG_ONE_US_TIMER(x)  VTSS_ENCODE_BITFIELD(x,0,20)
#define  VTSS_M_PCS_10GBASE_R_EEE_TIMER_CFG_ONE_US_TIMER_REG_ONE_US_TIMER     VTSS_ENCODE_BITMASK(0,20)
#define  VTSS_X_PCS_10GBASE_R_EEE_TIMER_CFG_ONE_US_TIMER_REG_ONE_US_TIMER(x)  VTSS_EXTRACT_BITFIELD(x,0,20)

#define VTSS_PCS_10GBASE_R_EEE_TIMER_CFG_TX_TS_TIMER_REG(target)  VTSS_IOREG(target,0x24)
#define  VTSS_F_PCS_10GBASE_R_EEE_TIMER_CFG_TX_TS_TIMER_REG_TX_TS_TIMER(x)  VTSS_ENCODE_BITFIELD(x,0,20)
#define  VTSS_M_PCS_10GBASE_R_EEE_TIMER_CFG_TX_TS_TIMER_REG_TX_TS_TIMER     VTSS_ENCODE_BITMASK(0,20)
#define  VTSS_X_PCS_10GBASE_R_EEE_TIMER_CFG_TX_TS_TIMER_REG_TX_TS_TIMER(x)  VTSS_EXTRACT_BITFIELD(x,0,20)

#define VTSS_PCS_10GBASE_R_EEE_TIMER_CFG_TX_TQ_TIMER_REG(target)  VTSS_IOREG(target,0x25)
#define  VTSS_F_PCS_10GBASE_R_EEE_TIMER_CFG_TX_TQ_TIMER_REG_TX_TQ_TIMER(x)  VTSS_ENCODE_BITFIELD(x,0,20)
#define  VTSS_M_PCS_10GBASE_R_EEE_TIMER_CFG_TX_TQ_TIMER_REG_TX_TQ_TIMER     VTSS_ENCODE_BITMASK(0,20)
#define  VTSS_X_PCS_10GBASE_R_EEE_TIMER_CFG_TX_TQ_TIMER_REG_TX_TQ_TIMER(x)  VTSS_EXTRACT_BITFIELD(x,0,20)

#define VTSS_PCS_10GBASE_R_EEE_TIMER_CFG_TX_TW_TIMER_REG(target)  VTSS_IOREG(target,0x26)
#define  VTSS_F_PCS_10GBASE_R_EEE_TIMER_CFG_TX_TW_TIMER_REG_TX_TW_TIMER(x)  VTSS_ENCODE_BITFIELD(x,0,20)
#define  VTSS_M_PCS_10GBASE_R_EEE_TIMER_CFG_TX_TW_TIMER_REG_TX_TW_TIMER     VTSS_ENCODE_BITMASK(0,20)
#define  VTSS_X_PCS_10GBASE_R_EEE_TIMER_CFG_TX_TW_TIMER_REG_TX_TW_TIMER(x)  VTSS_EXTRACT_BITFIELD(x,0,20)

#define VTSS_PCS_10GBASE_R_EEE_TIMER_CFG_RX_TQ_TIMER_REG(target)  VTSS_IOREG(target,0x27)
#define  VTSS_F_PCS_10GBASE_R_EEE_TIMER_CFG_RX_TQ_TIMER_REG_RX_TQ_TIMER(x)  VTSS_ENCODE_BITFIELD(x,0,21)
#define  VTSS_M_PCS_10GBASE_R_EEE_TIMER_CFG_RX_TQ_TIMER_REG_RX_TQ_TIMER     VTSS_ENCODE_BITMASK(0,21)
#define  VTSS_X_PCS_10GBASE_R_EEE_TIMER_CFG_RX_TQ_TIMER_REG_RX_TQ_TIMER(x)  VTSS_EXTRACT_BITFIELD(x,0,21)

#define VTSS_PCS_10GBASE_R_EEE_TIMER_CFG_RX_TW_TIMER_REG(target)  VTSS_IOREG(target,0x28)
#define  VTSS_F_PCS_10GBASE_R_EEE_TIMER_CFG_RX_TW_TIMER_REG_RX_TW_TIMER(x)  VTSS_ENCODE_BITFIELD(x,0,21)
#define  VTSS_M_PCS_10GBASE_R_EEE_TIMER_CFG_RX_TW_TIMER_REG_RX_TW_TIMER     VTSS_ENCODE_BITMASK(0,21)
#define  VTSS_X_PCS_10GBASE_R_EEE_TIMER_CFG_RX_TW_TIMER_REG_RX_TW_TIMER(x)  VTSS_EXTRACT_BITFIELD(x,0,21)

#define VTSS_PCS_10GBASE_R_EEE_TIMER_CFG_RX_WF_TIMER_REG(target)  VTSS_IOREG(target,0x29)
#define  VTSS_F_PCS_10GBASE_R_EEE_TIMER_CFG_RX_WF_TIMER_REG_RX_WF_TIMER(x)  VTSS_ENCODE_BITFIELD(x,0,21)
#define  VTSS_M_PCS_10GBASE_R_EEE_TIMER_CFG_RX_WF_TIMER_REG_RX_WF_TIMER     VTSS_ENCODE_BITMASK(0,21)
#define  VTSS_X_PCS_10GBASE_R_EEE_TIMER_CFG_RX_WF_TIMER_REG_RX_WF_TIMER(x)  VTSS_EXTRACT_BITFIELD(x,0,21)

#define VTSS_PCS_10GBASE_R_EEE_STATS_WAKE_ERR_CNT(target)  VTSS_IOREG(target,0x2a)
#define  VTSS_F_PCS_10GBASE_R_EEE_STATS_WAKE_ERR_CNT_WAKE_ERR_CNT(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_PCS_10GBASE_R_EEE_STATS_WAKE_ERR_CNT_WAKE_ERR_CNT     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_PCS_10GBASE_R_EEE_STATS_WAKE_ERR_CNT_WAKE_ERR_CNT(x)  VTSS_EXTRACT_BITFIELD(x,0,16)

#define VTSS_PCS_10GBASE_R_EEE_STATS_EEE_STATUS(target)  VTSS_IOREG(target,0x2b)
#define  VTSS_F_PCS_10GBASE_R_EEE_STATS_EEE_STATUS_CLOCK_STOP_CAPABLE  VTSS_BIT(6)
#define  VTSS_F_PCS_10GBASE_R_EEE_STATS_EEE_STATUS_RX_LPI_INDICATION  VTSS_BIT(8)
#define  VTSS_F_PCS_10GBASE_R_EEE_STATS_EEE_STATUS_TX_LPI_INDICATION  VTSS_BIT(9)
#define  VTSS_F_PCS_10GBASE_R_EEE_STATS_EEE_STATUS_RX_LPI_RECEIVED  VTSS_BIT(10)
#define  VTSS_F_PCS_10GBASE_R_EEE_STATS_EEE_STATUS_TX_LPI_RECEIVED  VTSS_BIT(11)

#define VTSS_PCS_10GBASE_R_EEE_STATS_EEE_INTR_MASK(target)  VTSS_IOREG(target,0x2c)
#define  VTSS_F_PCS_10GBASE_R_EEE_STATS_EEE_INTR_MASK_RX_LPI_RECEIVED_MASK  VTSS_BIT(0)
#define  VTSS_F_PCS_10GBASE_R_EEE_STATS_EEE_INTR_MASK_TX_LPI_RECEIVED_MASK  VTSS_BIT(4)


#endif /* _VTSS_JAGUAR2_REGS_PCS_10GBASE_R_H_ */
