#ifndef _VTSS_JAGUAR2_REGS_LRN_H_
#define _VTSS_JAGUAR2_REGS_LRN_H_

/*
 *
 * VCore-III Register Definitions
 *
 * Copyright (C) 2012 Vitesse Semiconductor Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#include "vtss_jaguar2_regs_common.h"

#define VTSS_LRN_COMMON_COMMON_ACCESS_CTRL   VTSS_IOREG(VTSS_TO_LRN,0x0)
#define  VTSS_F_LRN_COMMON_COMMON_ACCESS_CTRL_CPU_ACCESS_DIRECT_COL(x)  VTSS_ENCODE_BITFIELD(x,20,2)
#define  VTSS_M_LRN_COMMON_COMMON_ACCESS_CTRL_CPU_ACCESS_DIRECT_COL     VTSS_ENCODE_BITMASK(20,2)
#define  VTSS_X_LRN_COMMON_COMMON_ACCESS_CTRL_CPU_ACCESS_DIRECT_COL(x)  VTSS_EXTRACT_BITFIELD(x,20,2)
#define  VTSS_F_LRN_COMMON_COMMON_ACCESS_CTRL_CPU_ACCESS_DIRECT_TYPE  VTSS_BIT(19)
#define  VTSS_F_LRN_COMMON_COMMON_ACCESS_CTRL_CPU_ACCESS_DIRECT_ROW(x)  VTSS_ENCODE_BITFIELD(x,5,14)
#define  VTSS_M_LRN_COMMON_COMMON_ACCESS_CTRL_CPU_ACCESS_DIRECT_ROW     VTSS_ENCODE_BITMASK(5,14)
#define  VTSS_X_LRN_COMMON_COMMON_ACCESS_CTRL_CPU_ACCESS_DIRECT_ROW(x)  VTSS_EXTRACT_BITFIELD(x,5,14)
#define  VTSS_F_LRN_COMMON_COMMON_ACCESS_CTRL_CPU_ACCESS_CMD(x)  VTSS_ENCODE_BITFIELD(x,1,4)
#define  VTSS_M_LRN_COMMON_COMMON_ACCESS_CTRL_CPU_ACCESS_CMD     VTSS_ENCODE_BITMASK(1,4)
#define  VTSS_X_LRN_COMMON_COMMON_ACCESS_CTRL_CPU_ACCESS_CMD(x)  VTSS_EXTRACT_BITFIELD(x,1,4)
#define  VTSS_F_LRN_COMMON_COMMON_ACCESS_CTRL_MAC_TABLE_ACCESS_SHOT  VTSS_BIT(0)

#define VTSS_LRN_COMMON_MAC_ACCESS_CFG_0     VTSS_IOREG(VTSS_TO_LRN,0x1)
#define  VTSS_F_LRN_COMMON_MAC_ACCESS_CFG_0_MAC_ENTRY_FID(x)  VTSS_ENCODE_BITFIELD(x,16,13)
#define  VTSS_M_LRN_COMMON_MAC_ACCESS_CFG_0_MAC_ENTRY_FID     VTSS_ENCODE_BITMASK(16,13)
#define  VTSS_X_LRN_COMMON_MAC_ACCESS_CFG_0_MAC_ENTRY_FID(x)  VTSS_EXTRACT_BITFIELD(x,16,13)
#define  VTSS_F_LRN_COMMON_MAC_ACCESS_CFG_0_MAC_ENTRY_MAC_MSB(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_LRN_COMMON_MAC_ACCESS_CFG_0_MAC_ENTRY_MAC_MSB     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_LRN_COMMON_MAC_ACCESS_CFG_0_MAC_ENTRY_MAC_MSB(x)  VTSS_EXTRACT_BITFIELD(x,0,16)

#define VTSS_LRN_COMMON_MAC_ACCESS_CFG_1     VTSS_IOREG(VTSS_TO_LRN,0x2)

#define VTSS_LRN_COMMON_MAC_ACCESS_CFG_2     VTSS_IOREG(VTSS_TO_LRN,0x3)
#define  VTSS_F_LRN_COMMON_MAC_ACCESS_CFG_2_MAC_ENTRY_SRC_KILL_FWD  VTSS_BIT(28)
#define  VTSS_F_LRN_COMMON_MAC_ACCESS_CFG_2_MAC_ENTRY_NXT_LRN_ALL  VTSS_BIT(27)
#define  VTSS_F_LRN_COMMON_MAC_ACCESS_CFG_2_MAC_ENTRY_CPU_QU(x)  VTSS_ENCODE_BITFIELD(x,24,3)
#define  VTSS_M_LRN_COMMON_MAC_ACCESS_CFG_2_MAC_ENTRY_CPU_QU     VTSS_ENCODE_BITMASK(24,3)
#define  VTSS_X_LRN_COMMON_MAC_ACCESS_CFG_2_MAC_ENTRY_CPU_QU(x)  VTSS_EXTRACT_BITFIELD(x,24,3)
#define  VTSS_F_LRN_COMMON_MAC_ACCESS_CFG_2_MAC_ENTRY_CPU_COPY  VTSS_BIT(23)
#define  VTSS_F_LRN_COMMON_MAC_ACCESS_CFG_2_MAC_ENTRY_VLAN_IGNORE  VTSS_BIT(22)
#define  VTSS_F_LRN_COMMON_MAC_ACCESS_CFG_2_MAC_ENTRY_MIRROR  VTSS_BIT(21)
#define  VTSS_F_LRN_COMMON_MAC_ACCESS_CFG_2_MAC_ENTRY_AGE_FLAG(x)  VTSS_ENCODE_BITFIELD(x,19,2)
#define  VTSS_M_LRN_COMMON_MAC_ACCESS_CFG_2_MAC_ENTRY_AGE_FLAG     VTSS_ENCODE_BITMASK(19,2)
#define  VTSS_X_LRN_COMMON_MAC_ACCESS_CFG_2_MAC_ENTRY_AGE_FLAG(x)  VTSS_EXTRACT_BITFIELD(x,19,2)
#define  VTSS_F_LRN_COMMON_MAC_ACCESS_CFG_2_MAC_ENTRY_AGE_INTERVAL(x)  VTSS_ENCODE_BITFIELD(x,17,2)
#define  VTSS_M_LRN_COMMON_MAC_ACCESS_CFG_2_MAC_ENTRY_AGE_INTERVAL     VTSS_ENCODE_BITMASK(17,2)
#define  VTSS_X_LRN_COMMON_MAC_ACCESS_CFG_2_MAC_ENTRY_AGE_INTERVAL(x)  VTSS_EXTRACT_BITFIELD(x,17,2)
#define  VTSS_F_LRN_COMMON_MAC_ACCESS_CFG_2_MAC_ENTRY_LOCKED  VTSS_BIT(16)
#define  VTSS_F_LRN_COMMON_MAC_ACCESS_CFG_2_MAC_ENTRY_VLD  VTSS_BIT(15)
#define  VTSS_F_LRN_COMMON_MAC_ACCESS_CFG_2_MAC_ENTRY_ADDR_TYPE(x)  VTSS_ENCODE_BITFIELD(x,12,3)
#define  VTSS_M_LRN_COMMON_MAC_ACCESS_CFG_2_MAC_ENTRY_ADDR_TYPE     VTSS_ENCODE_BITMASK(12,3)
#define  VTSS_X_LRN_COMMON_MAC_ACCESS_CFG_2_MAC_ENTRY_ADDR_TYPE(x)  VTSS_EXTRACT_BITFIELD(x,12,3)
#define  VTSS_F_LRN_COMMON_MAC_ACCESS_CFG_2_MAC_ENTRY_ADDR(x)  VTSS_ENCODE_BITFIELD(x,0,12)
#define  VTSS_M_LRN_COMMON_MAC_ACCESS_CFG_2_MAC_ENTRY_ADDR     VTSS_ENCODE_BITMASK(0,12)
#define  VTSS_X_LRN_COMMON_MAC_ACCESS_CFG_2_MAC_ENTRY_ADDR(x)  VTSS_EXTRACT_BITFIELD(x,0,12)

#define VTSS_LRN_COMMON_SCAN_NEXT_CFG        VTSS_IOREG(VTSS_TO_LRN,0x4)
#define  VTSS_F_LRN_COMMON_SCAN_NEXT_CFG_SCAN_AGE_FLAG_UPDATE_SEL(x)  VTSS_ENCODE_BITFIELD(x,18,3)
#define  VTSS_M_LRN_COMMON_SCAN_NEXT_CFG_SCAN_AGE_FLAG_UPDATE_SEL     VTSS_ENCODE_BITMASK(18,3)
#define  VTSS_X_LRN_COMMON_SCAN_NEXT_CFG_SCAN_AGE_FLAG_UPDATE_SEL(x)  VTSS_EXTRACT_BITFIELD(x,18,3)
#define  VTSS_F_LRN_COMMON_SCAN_NEXT_CFG_SCAN_NXT_LRN_ALL_UPDATE_SEL(x)  VTSS_ENCODE_BITFIELD(x,16,2)
#define  VTSS_M_LRN_COMMON_SCAN_NEXT_CFG_SCAN_NXT_LRN_ALL_UPDATE_SEL     VTSS_ENCODE_BITMASK(16,2)
#define  VTSS_X_LRN_COMMON_SCAN_NEXT_CFG_SCAN_NXT_LRN_ALL_UPDATE_SEL(x)  VTSS_EXTRACT_BITFIELD(x,16,2)
#define  VTSS_F_LRN_COMMON_SCAN_NEXT_CFG_SCAN_AGE_FILTER_SEL(x)  VTSS_ENCODE_BITFIELD(x,14,2)
#define  VTSS_M_LRN_COMMON_SCAN_NEXT_CFG_SCAN_AGE_FILTER_SEL     VTSS_ENCODE_BITMASK(14,2)
#define  VTSS_X_LRN_COMMON_SCAN_NEXT_CFG_SCAN_AGE_FILTER_SEL(x)  VTSS_EXTRACT_BITFIELD(x,14,2)
#define  VTSS_F_LRN_COMMON_SCAN_NEXT_CFG_SCAN_NEXT_MOVE_FOUND_ENA  VTSS_BIT(13)
#define  VTSS_F_LRN_COMMON_SCAN_NEXT_CFG_NXT_LRN_ALL_FILTER_ENA  VTSS_BIT(12)
#define  VTSS_F_LRN_COMMON_SCAN_NEXT_CFG_SCAN_USE_PORT_FILTER_ENA  VTSS_BIT(11)
#define  VTSS_F_LRN_COMMON_SCAN_NEXT_CFG_SCAN_NEXT_REMOVE_FOUND_ENA  VTSS_BIT(10)
#define  VTSS_F_LRN_COMMON_SCAN_NEXT_CFG_SCAN_NEXT_UNTIL_FOUND_ENA  VTSS_BIT(9)
#define  VTSS_F_LRN_COMMON_SCAN_NEXT_CFG_SCAN_NEXT_INC_AGE_BITS_ENA  VTSS_BIT(8)
#define  VTSS_F_LRN_COMMON_SCAN_NEXT_CFG_SCAN_NEXT_AGED_ONLY_ENA  VTSS_BIT(7)
#define  VTSS_F_LRN_COMMON_SCAN_NEXT_CFG_SCAN_NEXT_IGNORE_LOCKED_ENA  VTSS_BIT(6)
#define  VTSS_F_LRN_COMMON_SCAN_NEXT_CFG_SCAN_AGE_INTERVAL_MASK(x)  VTSS_ENCODE_BITFIELD(x,2,4)
#define  VTSS_M_LRN_COMMON_SCAN_NEXT_CFG_SCAN_AGE_INTERVAL_MASK     VTSS_ENCODE_BITMASK(2,4)
#define  VTSS_X_LRN_COMMON_SCAN_NEXT_CFG_SCAN_AGE_INTERVAL_MASK(x)  VTSS_EXTRACT_BITFIELD(x,2,4)
#define  VTSS_F_LRN_COMMON_SCAN_NEXT_CFG_FID_FILTER_ENA  VTSS_BIT(1)
#define  VTSS_F_LRN_COMMON_SCAN_NEXT_CFG_ADDR_FILTER_ENA  VTSS_BIT(0)

#define VTSS_LRN_COMMON_SCAN_NEXT_CFG_1      VTSS_IOREG(VTSS_TO_LRN,0x5)
#define  VTSS_F_LRN_COMMON_SCAN_NEXT_CFG_1_PORT_MOVE_NEW_ADDR(x)  VTSS_ENCODE_BITFIELD(x,16,15)
#define  VTSS_M_LRN_COMMON_SCAN_NEXT_CFG_1_PORT_MOVE_NEW_ADDR     VTSS_ENCODE_BITMASK(16,15)
#define  VTSS_X_LRN_COMMON_SCAN_NEXT_CFG_1_PORT_MOVE_NEW_ADDR(x)  VTSS_EXTRACT_BITFIELD(x,16,15)
#define  VTSS_F_LRN_COMMON_SCAN_NEXT_CFG_1_SCAN_ENTRY_ADDR_MASK(x)  VTSS_ENCODE_BITFIELD(x,0,15)
#define  VTSS_M_LRN_COMMON_SCAN_NEXT_CFG_1_SCAN_ENTRY_ADDR_MASK     VTSS_ENCODE_BITMASK(0,15)
#define  VTSS_X_LRN_COMMON_SCAN_NEXT_CFG_1_SCAN_ENTRY_ADDR_MASK(x)  VTSS_EXTRACT_BITFIELD(x,0,15)

#define VTSS_LRN_COMMON_SCAN_LAST_ROW_CFG    VTSS_IOREG(VTSS_TO_LRN,0x6)
#define  VTSS_F_LRN_COMMON_SCAN_LAST_ROW_CFG_SCAN_LAST_ROW(x)  VTSS_ENCODE_BITFIELD(x,0,14)
#define  VTSS_M_LRN_COMMON_SCAN_LAST_ROW_CFG_SCAN_LAST_ROW     VTSS_ENCODE_BITMASK(0,14)
#define  VTSS_X_LRN_COMMON_SCAN_LAST_ROW_CFG_SCAN_LAST_ROW(x)  VTSS_EXTRACT_BITFIELD(x,0,14)

#define VTSS_LRN_COMMON_SCAN_NEXT_CNT        VTSS_IOREG(VTSS_TO_LRN,0x7)
#define  VTSS_F_LRN_COMMON_SCAN_NEXT_CNT_SCAN_INC_AGE_AND_NXT_LRN_ALL_ENA  VTSS_BIT(31)
#define  VTSS_F_LRN_COMMON_SCAN_NEXT_CNT_SCAN_NEXT_CNT(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_LRN_COMMON_SCAN_NEXT_CNT_SCAN_NEXT_CNT     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_LRN_COMMON_SCAN_NEXT_CNT_SCAN_NEXT_CNT(x)  VTSS_EXTRACT_BITFIELD(x,0,16)

#define VTSS_LRN_COMMON_AUTOAGE_CFG(ri)      VTSS_IOREG(VTSS_TO_LRN,0x8 + (ri))
#define  VTSS_F_LRN_COMMON_AUTOAGE_CFG_UNIT_SIZE(x)  VTSS_ENCODE_BITFIELD(x,28,2)
#define  VTSS_M_LRN_COMMON_AUTOAGE_CFG_UNIT_SIZE     VTSS_ENCODE_BITMASK(28,2)
#define  VTSS_X_LRN_COMMON_AUTOAGE_CFG_UNIT_SIZE(x)  VTSS_EXTRACT_BITFIELD(x,28,2)
#define  VTSS_F_LRN_COMMON_AUTOAGE_CFG_PERIOD_VAL(x)  VTSS_ENCODE_BITFIELD(x,0,28)
#define  VTSS_M_LRN_COMMON_AUTOAGE_CFG_PERIOD_VAL     VTSS_ENCODE_BITMASK(0,28)
#define  VTSS_X_LRN_COMMON_AUTOAGE_CFG_PERIOD_VAL(x)  VTSS_EXTRACT_BITFIELD(x,0,28)

#define VTSS_LRN_COMMON_AUTOAGE_CFG_1        VTSS_IOREG(VTSS_TO_LRN,0xc)
#define  VTSS_F_LRN_COMMON_AUTOAGE_CFG_1_PAUSE_AUTO_AGE_ENA  VTSS_BIT(26)
#define  VTSS_F_LRN_COMMON_AUTOAGE_CFG_1_CELLS_BETWEEN_ENTRY_SCAN(x)  VTSS_ENCODE_BITFIELD(x,16,10)
#define  VTSS_M_LRN_COMMON_AUTOAGE_CFG_1_CELLS_BETWEEN_ENTRY_SCAN     VTSS_ENCODE_BITMASK(16,10)
#define  VTSS_X_LRN_COMMON_AUTOAGE_CFG_1_CELLS_BETWEEN_ENTRY_SCAN(x)  VTSS_EXTRACT_BITFIELD(x,16,10)
#define  VTSS_F_LRN_COMMON_AUTOAGE_CFG_1_BASE_UNIT_CLK_CNT(x)  VTSS_ENCODE_BITFIELD(x,7,9)
#define  VTSS_M_LRN_COMMON_AUTOAGE_CFG_1_BASE_UNIT_CLK_CNT     VTSS_ENCODE_BITMASK(7,9)
#define  VTSS_X_LRN_COMMON_AUTOAGE_CFG_1_BASE_UNIT_CLK_CNT(x)  VTSS_EXTRACT_BITFIELD(x,7,9)
#define  VTSS_F_LRN_COMMON_AUTOAGE_CFG_1_USE_PORT_FILTER_ENA  VTSS_BIT(6)
#define  VTSS_F_LRN_COMMON_AUTOAGE_CFG_1_FORCE_HW_SCAN_SHOT(x)  VTSS_ENCODE_BITFIELD(x,2,4)
#define  VTSS_M_LRN_COMMON_AUTOAGE_CFG_1_FORCE_HW_SCAN_SHOT     VTSS_ENCODE_BITMASK(2,4)
#define  VTSS_X_LRN_COMMON_AUTOAGE_CFG_1_FORCE_HW_SCAN_SHOT(x)  VTSS_EXTRACT_BITFIELD(x,2,4)
#define  VTSS_F_LRN_COMMON_AUTOAGE_CFG_1_FORCE_HW_SCAN_STOP_SHOT  VTSS_BIT(1)
#define  VTSS_F_LRN_COMMON_AUTOAGE_CFG_1_FORCE_IDLE_ENA  VTSS_BIT(0)

#define VTSS_LRN_COMMON_AUTOAGE_CFG_2        VTSS_IOREG(VTSS_TO_LRN,0xd)
#define  VTSS_F_LRN_COMMON_AUTOAGE_CFG_2_NEXT_ROW(x)  VTSS_ENCODE_BITFIELD(x,4,14)
#define  VTSS_M_LRN_COMMON_AUTOAGE_CFG_2_NEXT_ROW     VTSS_ENCODE_BITMASK(4,14)
#define  VTSS_X_LRN_COMMON_AUTOAGE_CFG_2_NEXT_ROW(x)  VTSS_EXTRACT_BITFIELD(x,4,14)
#define  VTSS_F_LRN_COMMON_AUTOAGE_CFG_2_SCAN_ONGOING_STATUS(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_LRN_COMMON_AUTOAGE_CFG_2_SCAN_ONGOING_STATUS     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_LRN_COMMON_AUTOAGE_CFG_2_SCAN_ONGOING_STATUS(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_LRN_COMMON_AUTO_LRN_CFG         VTSS_IOREG(VTSS_TO_LRN,0xe)
#define  VTSS_F_LRN_COMMON_AUTO_LRN_CFG_AUTO_LRN_SRC_KILL_FWD  VTSS_BIT(9)
#define  VTSS_F_LRN_COMMON_AUTO_LRN_CFG_AUTO_LRN_IGNORE_VLAN  VTSS_BIT(8)
#define  VTSS_F_LRN_COMMON_AUTO_LRN_CFG_AUTO_LRN_CPU_QU(x)  VTSS_ENCODE_BITFIELD(x,5,3)
#define  VTSS_M_LRN_COMMON_AUTO_LRN_CFG_AUTO_LRN_CPU_QU     VTSS_ENCODE_BITMASK(5,3)
#define  VTSS_X_LRN_COMMON_AUTO_LRN_CFG_AUTO_LRN_CPU_QU(x)  VTSS_EXTRACT_BITFIELD(x,5,3)
#define  VTSS_F_LRN_COMMON_AUTO_LRN_CFG_AUTO_LRN_CPU_COPY  VTSS_BIT(4)
#define  VTSS_F_LRN_COMMON_AUTO_LRN_CFG_AUTO_LRN_MIRROR  VTSS_BIT(3)
#define  VTSS_F_LRN_COMMON_AUTO_LRN_CFG_AUTO_AGE_INTERVAL(x)  VTSS_ENCODE_BITFIELD(x,1,2)
#define  VTSS_M_LRN_COMMON_AUTO_LRN_CFG_AUTO_AGE_INTERVAL     VTSS_ENCODE_BITMASK(1,2)
#define  VTSS_X_LRN_COMMON_AUTO_LRN_CFG_AUTO_AGE_INTERVAL(x)  VTSS_EXTRACT_BITFIELD(x,1,2)
#define  VTSS_F_LRN_COMMON_AUTO_LRN_CFG_AUTO_LRN_ENA  VTSS_BIT(0)

#define VTSS_LRN_COMMON_EVENT_STICKY         VTSS_IOREG(VTSS_TO_LRN,0xf)
#define  VTSS_F_LRN_COMMON_EVENT_STICKY_AUTOAGE_SCAN_COMPLETED_STICKY  VTSS_BIT(28)
#define  VTSS_F_LRN_COMMON_EVENT_STICKY_AUTOAGE_SCAN_STARTED_STICKY  VTSS_BIT(27)
#define  VTSS_F_LRN_COMMON_EVENT_STICKY_AUTOAGE_START_DELAYED_STICKY  VTSS_BIT(26)
#define  VTSS_F_LRN_COMMON_EVENT_STICKY_LRN_QUEUE_OVERFLOW_STICKY  VTSS_BIT(25)
#define  VTSS_F_LRN_COMMON_EVENT_STICKY_LRN_QUEUE_DATA_AVAIL_STICKY  VTSS_BIT(24)
#define  VTSS_F_LRN_COMMON_EVENT_STICKY_CPU_LRN_FID_LIMIT_EXCEEDED_STICKY  VTSS_BIT(23)
#define  VTSS_F_LRN_COMMON_EVENT_STICKY_AUTOAGE_AGED_STICKY  VTSS_BIT(22)
#define  VTSS_F_LRN_COMMON_EVENT_STICKY_AUTOAGE_REMOVE_STICKY  VTSS_BIT(21)
#define  VTSS_F_LRN_COMMON_EVENT_STICKY_ROW_WITH_SCAN_ENTRY_STICKY  VTSS_BIT(20)
#define  VTSS_F_LRN_COMMON_EVENT_STICKY_SCAN_REMOVED_STICKY  VTSS_BIT(19)
#define  VTSS_F_LRN_COMMON_EVENT_STICKY_AUTO_LRN_FID_LIMIT_EXCEEDED_STICKY  VTSS_BIT(18)
#define  VTSS_F_LRN_COMMON_EVENT_STICKY_AUTO_LRN_FAILED_STICKY  VTSS_BIT(17)
#define  VTSS_F_LRN_COMMON_EVENT_STICKY_AUTO_LRN_INSERT_CAM_STICKY  VTSS_BIT(16)
#define  VTSS_F_LRN_COMMON_EVENT_STICKY_AUTO_LRN_INSERT_STICKY  VTSS_BIT(15)
#define  VTSS_F_LRN_COMMON_EVENT_STICKY_AUTO_LRN_REFRESH_STICKY  VTSS_BIT(14)
#define  VTSS_F_LRN_COMMON_EVENT_STICKY_AUTO_LRN_REPLACE_FAILED_STICKY  VTSS_BIT(13)
#define  VTSS_F_LRN_COMMON_EVENT_STICKY_AUTO_LRN_REPLACE_STICKY  VTSS_BIT(12)
#define  VTSS_F_LRN_COMMON_EVENT_STICKY_LRN_MOVE_STICKY  VTSS_BIT(11)
#define  VTSS_F_LRN_COMMON_EVENT_STICKY_CPU_READ_DIRECT_STICKY  VTSS_BIT(10)
#define  VTSS_F_LRN_COMMON_EVENT_STICKY_CPU_WRITE_DIRECT_STICKY  VTSS_BIT(9)
#define  VTSS_F_LRN_COMMON_EVENT_STICKY_CPU_LOOKUP_FAILED_STICKY  VTSS_BIT(8)
#define  VTSS_F_LRN_COMMON_EVENT_STICKY_CPU_LOOKUP_STICKY  VTSS_BIT(7)
#define  VTSS_F_LRN_COMMON_EVENT_STICKY_CPU_UNLEARN_FAILED_STICKY  VTSS_BIT(6)
#define  VTSS_F_LRN_COMMON_EVENT_STICKY_CPU_UNLEARN_STICKY  VTSS_BIT(5)
#define  VTSS_F_LRN_COMMON_EVENT_STICKY_CPU_LRN_REPLACE_FAILED_STICKY  VTSS_BIT(4)
#define  VTSS_F_LRN_COMMON_EVENT_STICKY_CPU_LRN_REFRESH_STICKY  VTSS_BIT(3)
#define  VTSS_F_LRN_COMMON_EVENT_STICKY_CPU_LRN_REPLACE_STICKY  VTSS_BIT(2)
#define  VTSS_F_LRN_COMMON_EVENT_STICKY_CPU_LRN_INSERT_STICKY  VTSS_BIT(1)
#define  VTSS_F_LRN_COMMON_EVENT_STICKY_CPU_LRN_FAILED_STICKY  VTSS_BIT(0)

#define VTSS_LRN_COMMON_LATEST_POS_STATUS    VTSS_IOREG(VTSS_TO_LRN,0x10)
#define  VTSS_F_LRN_COMMON_LATEST_POS_STATUS_SCAN_NEXT_STATUS(x)  VTSS_ENCODE_BITFIELD(x,18,4)
#define  VTSS_M_LRN_COMMON_LATEST_POS_STATUS_SCAN_NEXT_STATUS     VTSS_ENCODE_BITMASK(18,4)
#define  VTSS_X_LRN_COMMON_LATEST_POS_STATUS_SCAN_NEXT_STATUS(x)  VTSS_EXTRACT_BITFIELD(x,18,4)
#define  VTSS_F_LRN_COMMON_LATEST_POS_STATUS_LATEST_TYPE  VTSS_BIT(24)
#define  VTSS_F_LRN_COMMON_LATEST_POS_STATUS_LATEST_ROW(x)  VTSS_ENCODE_BITFIELD(x,4,14)
#define  VTSS_M_LRN_COMMON_LATEST_POS_STATUS_LATEST_ROW     VTSS_ENCODE_BITMASK(4,14)
#define  VTSS_X_LRN_COMMON_LATEST_POS_STATUS_LATEST_ROW(x)  VTSS_EXTRACT_BITFIELD(x,4,14)
#define  VTSS_F_LRN_COMMON_LATEST_POS_STATUS_LATEST_COL(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_LRN_COMMON_LATEST_POS_STATUS_LATEST_COL     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_LRN_COMMON_LATEST_POS_STATUS_LATEST_COL(x)  VTSS_EXTRACT_BITFIELD(x,0,2)


#endif /* _VTSS_JAGUAR2_REGS_LRN_H_ */
