#ifndef _VTSS_JAGUAR2_REGS_VCAP_CORE_H_
#define _VTSS_JAGUAR2_REGS_VCAP_CORE_H_

/*
 *
 * VCore-III Register Definitions
 *
 * Copyright (C) 2012 Vitesse Semiconductor Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#include "vtss_jaguar2_regs_common.h"

#define VTSS_VCAP_CORE_VCAP_CORE_CFG_VCAP_UPDATE_CTRL(target)  VTSS_IOREG(target,0x0)
#define  VTSS_F_VCAP_CORE_VCAP_CORE_CFG_VCAP_UPDATE_CTRL_UPDATE_CMD(x)  VTSS_ENCODE_BITFIELD(x,22,3)
#define  VTSS_M_VCAP_CORE_VCAP_CORE_CFG_VCAP_UPDATE_CTRL_UPDATE_CMD     VTSS_ENCODE_BITMASK(22,3)
#define  VTSS_X_VCAP_CORE_VCAP_CORE_CFG_VCAP_UPDATE_CTRL_UPDATE_CMD(x)  VTSS_EXTRACT_BITFIELD(x,22,3)
#define  VTSS_F_VCAP_CORE_VCAP_CORE_CFG_VCAP_UPDATE_CTRL_UPDATE_ENTRY_DIS  VTSS_BIT(21)
#define  VTSS_F_VCAP_CORE_VCAP_CORE_CFG_VCAP_UPDATE_CTRL_UPDATE_ACTION_DIS  VTSS_BIT(20)
#define  VTSS_F_VCAP_CORE_VCAP_CORE_CFG_VCAP_UPDATE_CTRL_UPDATE_CNT_DIS  VTSS_BIT(19)
#define  VTSS_F_VCAP_CORE_VCAP_CORE_CFG_VCAP_UPDATE_CTRL_UPDATE_ADDR(x)  VTSS_ENCODE_BITFIELD(x,3,16)
#define  VTSS_M_VCAP_CORE_VCAP_CORE_CFG_VCAP_UPDATE_CTRL_UPDATE_ADDR     VTSS_ENCODE_BITMASK(3,16)
#define  VTSS_X_VCAP_CORE_VCAP_CORE_CFG_VCAP_UPDATE_CTRL_UPDATE_ADDR(x)  VTSS_EXTRACT_BITFIELD(x,3,16)
#define  VTSS_F_VCAP_CORE_VCAP_CORE_CFG_VCAP_UPDATE_CTRL_UPDATE_SHOT  VTSS_BIT(2)
#define  VTSS_F_VCAP_CORE_VCAP_CORE_CFG_VCAP_UPDATE_CTRL_CLEAR_CACHE  VTSS_BIT(1)
#define  VTSS_F_VCAP_CORE_VCAP_CORE_CFG_VCAP_UPDATE_CTRL_MV_TRAFFIC_IGN  VTSS_BIT(0)

#define VTSS_VCAP_CORE_VCAP_CORE_CFG_VCAP_MV_CFG(target)  VTSS_IOREG(target,0x1)
#define  VTSS_F_VCAP_CORE_VCAP_CORE_CFG_VCAP_MV_CFG_MV_NUM_POS(x)  VTSS_ENCODE_BITFIELD(x,16,16)
#define  VTSS_M_VCAP_CORE_VCAP_CORE_CFG_VCAP_MV_CFG_MV_NUM_POS     VTSS_ENCODE_BITMASK(16,16)
#define  VTSS_X_VCAP_CORE_VCAP_CORE_CFG_VCAP_MV_CFG_MV_NUM_POS(x)  VTSS_EXTRACT_BITFIELD(x,16,16)
#define  VTSS_F_VCAP_CORE_VCAP_CORE_CFG_VCAP_MV_CFG_MV_SIZE(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_VCAP_CORE_VCAP_CORE_CFG_VCAP_MV_CFG_MV_SIZE     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_VCAP_CORE_VCAP_CORE_CFG_VCAP_MV_CFG_MV_SIZE(x)  VTSS_EXTRACT_BITFIELD(x,0,16)

#define VTSS_VCAP_CORE_VCAP_CORE_CACHE_VCAP_ENTRY_DAT(target,ri)  VTSS_IOREG(target,0x2 + (ri))

#define VTSS_VCAP_CORE_VCAP_CORE_CACHE_VCAP_MASK_DAT(target,ri)  VTSS_IOREG(target,0x42 + (ri))

#define VTSS_VCAP_CORE_VCAP_CORE_CACHE_VCAP_ACTION_DAT(target,ri)  VTSS_IOREG(target,0x82 + (ri))

#define VTSS_VCAP_CORE_VCAP_CORE_CACHE_VCAP_CNT_DAT(target,ri)  VTSS_IOREG(target,0xc2 + (ri))

#define VTSS_VCAP_CORE_VCAP_CORE_CACHE_VCAP_TG_DAT(target)  VTSS_IOREG(target,0xe2)

#define VTSS_VCAP_CORE_VCAP_CORE_MAP_VCAP_CORE_IDX(target)  VTSS_IOREG(target,0xe3)
#define  VTSS_F_VCAP_CORE_VCAP_CORE_MAP_VCAP_CORE_IDX_CORE_IDX(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_VCAP_CORE_VCAP_CORE_MAP_VCAP_CORE_IDX_CORE_IDX     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_VCAP_CORE_VCAP_CORE_MAP_VCAP_CORE_IDX_CORE_IDX(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_VCAP_CORE_VCAP_CORE_MAP_VCAP_CORE_MAP(target)  VTSS_IOREG(target,0xe4)
#define  VTSS_F_VCAP_CORE_VCAP_CORE_MAP_VCAP_CORE_MAP_CORE_MAP(x)  VTSS_ENCODE_BITFIELD(x,0,3)
#define  VTSS_M_VCAP_CORE_VCAP_CORE_MAP_VCAP_CORE_MAP_CORE_MAP     VTSS_ENCODE_BITMASK(0,3)
#define  VTSS_X_VCAP_CORE_VCAP_CORE_MAP_VCAP_CORE_MAP_CORE_MAP(x)  VTSS_EXTRACT_BITFIELD(x,0,3)

#define VTSS_VCAP_CORE_VCAP_CORE_STICKY_VCAP_STICKY(target)  VTSS_IOREG(target,0xe5)
#define  VTSS_F_VCAP_CORE_VCAP_CORE_STICKY_VCAP_STICKY_VCAP_ROW_DELETED_STICKY  VTSS_BIT(0)

#define VTSS_VCAP_CORE_VCAP_CONST_VCAP_VER(target)  VTSS_IOREG(target,0xe6)

#define VTSS_VCAP_CORE_VCAP_CONST_ENTRY_WIDTH(target)  VTSS_IOREG(target,0xe7)

#define VTSS_VCAP_CORE_VCAP_CONST_ENTRY_CNT(target)  VTSS_IOREG(target,0xe8)

#define VTSS_VCAP_CORE_VCAP_CONST_ENTRY_SWCNT(target)  VTSS_IOREG(target,0xe9)

#define VTSS_VCAP_CORE_VCAP_CONST_ENTRY_TG_WIDTH(target)  VTSS_IOREG(target,0xea)

#define VTSS_VCAP_CORE_VCAP_CONST_ACTION_DEF_CNT(target)  VTSS_IOREG(target,0xeb)

#define VTSS_VCAP_CORE_VCAP_CONST_ACTION_WIDTH(target)  VTSS_IOREG(target,0xec)

#define VTSS_VCAP_CORE_VCAP_CONST_CNT_WIDTH(target)  VTSS_IOREG(target,0xed)

#define VTSS_VCAP_CORE_VCAP_CONST_CORE_CNT(target)  VTSS_IOREG(target,0xee)

#define VTSS_VCAP_CORE_VCAP_CONST_IF_CNT(target)  VTSS_IOREG(target,0xef)

#define VTSS_VCAP_CORE_TCAM_BIST_TCAM_CTRL(target)  VTSS_IOREG(target,0xf0)
#define  VTSS_F_VCAP_CORE_TCAM_BIST_TCAM_CTRL_TCAM_BIST  VTSS_BIT(1)
#define  VTSS_F_VCAP_CORE_TCAM_BIST_TCAM_CTRL_TCAM_INIT  VTSS_BIT(0)

#define VTSS_VCAP_CORE_TCAM_BIST_TCAM_CFG(target)  VTSS_IOREG(target,0xf1)
#define  VTSS_F_VCAP_CORE_TCAM_BIST_TCAM_CFG_TCAM_BIST_SOE_ENA  VTSS_BIT(8)
#define  VTSS_F_VCAP_CORE_TCAM_BIST_TCAM_CFG_TCAM_HCG_DIS  VTSS_BIT(7)
#define  VTSS_F_VCAP_CORE_TCAM_BIST_TCAM_CFG_TCAM_CG_DIS  VTSS_BIT(6)
#define  VTSS_F_VCAP_CORE_TCAM_BIST_TCAM_CFG_TCAM_BIAS(x)  VTSS_ENCODE_BITFIELD(x,0,6)
#define  VTSS_M_VCAP_CORE_TCAM_BIST_TCAM_CFG_TCAM_BIAS     VTSS_ENCODE_BITMASK(0,6)
#define  VTSS_X_VCAP_CORE_TCAM_BIST_TCAM_CFG_TCAM_BIAS(x)  VTSS_EXTRACT_BITFIELD(x,0,6)

#define VTSS_VCAP_CORE_TCAM_BIST_TCAM_STAT(target)  VTSS_IOREG(target,0xf2)
#define  VTSS_F_VCAP_CORE_TCAM_BIST_TCAM_STAT_BIST_RT_ERR  VTSS_BIT(15)
#define  VTSS_F_VCAP_CORE_TCAM_BIST_TCAM_STAT_BIST_PENC_ERR  VTSS_BIT(14)
#define  VTSS_F_VCAP_CORE_TCAM_BIST_TCAM_STAT_BIST_COMP_ERR  VTSS_BIT(13)
#define  VTSS_F_VCAP_CORE_TCAM_BIST_TCAM_STAT_BIST_ADDR_ERR  VTSS_BIT(12)
#define  VTSS_F_VCAP_CORE_TCAM_BIST_TCAM_STAT_BIST_BL1E_ERR  VTSS_BIT(11)
#define  VTSS_F_VCAP_CORE_TCAM_BIST_TCAM_STAT_BIST_BL1_ERR  VTSS_BIT(10)
#define  VTSS_F_VCAP_CORE_TCAM_BIST_TCAM_STAT_BIST_BL0E_ERR  VTSS_BIT(9)
#define  VTSS_F_VCAP_CORE_TCAM_BIST_TCAM_STAT_BIST_BL0_ERR  VTSS_BIT(8)
#define  VTSS_F_VCAP_CORE_TCAM_BIST_TCAM_STAT_BIST_PH1_ERR  VTSS_BIT(7)
#define  VTSS_F_VCAP_CORE_TCAM_BIST_TCAM_STAT_BIST_PH0_ERR  VTSS_BIT(6)
#define  VTSS_F_VCAP_CORE_TCAM_BIST_TCAM_STAT_BIST_PV1_ERR  VTSS_BIT(5)
#define  VTSS_F_VCAP_CORE_TCAM_BIST_TCAM_STAT_BIST_PV0_ERR  VTSS_BIT(4)
#define  VTSS_F_VCAP_CORE_TCAM_BIST_TCAM_STAT_BIST_RUN  VTSS_BIT(3)
#define  VTSS_F_VCAP_CORE_TCAM_BIST_TCAM_STAT_BIST_ERR  VTSS_BIT(2)
#define  VTSS_F_VCAP_CORE_TCAM_BIST_TCAM_STAT_BIST_BUSY  VTSS_BIT(1)
#define  VTSS_F_VCAP_CORE_TCAM_BIST_TCAM_STAT_TCAM_RDY  VTSS_BIT(0)


#endif /* _VTSS_JAGUAR2_REGS_VCAP_CORE_H_ */
