#ifndef _VTSS_JAGUAR2_REGS_AFI_H_
#define _VTSS_JAGUAR2_REGS_AFI_H_

/*
 *
 * VCore-III Register Definitions
 *
 * Copyright (C) 2012 Vitesse Semiconductor Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#include "vtss_jaguar2_regs_common.h"

#define VTSS_AFI_MISC_NEW_FRM_CTRL           VTSS_IOREG(VTSS_TO_AFI,0xa0f2)
#define  VTSS_F_AFI_MISC_NEW_FRM_CTRL_VLD     VTSS_BIT(0)

#define VTSS_AFI_MISC_NEW_FRM_INFO           VTSS_IOREG(VTSS_TO_AFI,0xa0f3)
#define  VTSS_F_AFI_MISC_NEW_FRM_INFO_FRM_INFO(x)  VTSS_ENCODE_BITFIELD(x,0,19)
#define  VTSS_M_AFI_MISC_NEW_FRM_INFO_FRM_INFO     VTSS_ENCODE_BITMASK(0,19)
#define  VTSS_X_AFI_MISC_NEW_FRM_INFO_FRM_INFO(x)  VTSS_EXTRACT_BITFIELD(x,0,19)

#define VTSS_AFI_MISC_ERR                    VTSS_IOREG(VTSS_TO_AFI,0xa0f4)
#define  VTSS_F_AFI_MISC_ERR_ERR_FRM_OUT_NEG_STICKY  VTSS_BIT(0)

#define VTSS_AFI_MISC_WARN                   VTSS_IOREG(VTSS_TO_AFI,0xa0f5)
#define  VTSS_F_AFI_MISC_WARN_WARN_NEW_FRM_VLD_STICKY  VTSS_BIT(0)
#define  VTSS_F_AFI_MISC_WARN_WARN_FRM_OUT_MAX_STICKY  VTSS_BIT(1)
#define  VTSS_F_AFI_MISC_WARN_WARN_ENQ_STOP_STICKY  VTSS_BIT(2)
#define  VTSS_F_AFI_MISC_WARN_WARN_TTI_BUSY_STICKY  VTSS_BIT(3)
#define  VTSS_F_AFI_MISC_WARN_WARN_DTI_CNT_DOWN_MAX_NEG_STICKY  VTSS_BIT(4)

#define VTSS_AFI_MISC_STICKY_INFO            VTSS_IOREG(VTSS_TO_AFI,0xa0f6)
#define  VTSS_F_AFI_MISC_STICKY_INFO_PORT_NUM(x)  VTSS_ENCODE_BITFIELD(x,0,6)
#define  VTSS_M_AFI_MISC_STICKY_INFO_PORT_NUM     VTSS_ENCODE_BITMASK(0,6)
#define  VTSS_X_AFI_MISC_STICKY_INFO_PORT_NUM(x)  VTSS_EXTRACT_BITFIELD(x,0,6)
#define  VTSS_F_AFI_MISC_STICKY_INFO_TTI_PTR(x)  VTSS_ENCODE_BITFIELD(x,8,12)
#define  VTSS_M_AFI_MISC_STICKY_INFO_TTI_PTR     VTSS_ENCODE_BITMASK(8,12)
#define  VTSS_X_AFI_MISC_STICKY_INFO_TTI_PTR(x)  VTSS_EXTRACT_BITFIELD(x,8,12)
#define  VTSS_F_AFI_MISC_STICKY_INFO_STICKY_INFO_WR_CNT(x)  VTSS_ENCODE_BITFIELD(x,28,4)
#define  VTSS_M_AFI_MISC_STICKY_INFO_STICKY_INFO_WR_CNT     VTSS_ENCODE_BITMASK(28,4)
#define  VTSS_X_AFI_MISC_STICKY_INFO_STICKY_INFO_WR_CNT(x)  VTSS_EXTRACT_BITFIELD(x,28,4)

#define VTSS_AFI_MISC_STICKY_INFO_ENA        VTSS_IOREG(VTSS_TO_AFI,0xa0f7)
#define  VTSS_F_AFI_MISC_STICKY_INFO_ENA_FRM_OUT_NEG_INFO_ENA  VTSS_BIT(0)
#define  VTSS_F_AFI_MISC_STICKY_INFO_ENA_FRM_OUT_MAX_INFO_ENA  VTSS_BIT(1)
#define  VTSS_F_AFI_MISC_STICKY_INFO_ENA_ENQ_STOP_INFO_ENA  VTSS_BIT(2)
#define  VTSS_F_AFI_MISC_STICKY_INFO_ENA_TTI_BUSY_INFO_ENA  VTSS_BIT(3)

#define VTSS_AFI_FRM_TBL_FRM_NEXT_AND_TYPE(gi)  VTSS_IOREG_IX(VTSS_TO_AFI,0x8000,gi,2,0,0)
#define  VTSS_F_AFI_FRM_TBL_FRM_NEXT_AND_TYPE_NEXT_PTR(x)  VTSS_ENCODE_BITFIELD(x,0,12)
#define  VTSS_M_AFI_FRM_TBL_FRM_NEXT_AND_TYPE_NEXT_PTR     VTSS_ENCODE_BITMASK(0,12)
#define  VTSS_X_AFI_FRM_TBL_FRM_NEXT_AND_TYPE_NEXT_PTR(x)  VTSS_EXTRACT_BITFIELD(x,0,12)
#define  VTSS_F_AFI_FRM_TBL_FRM_NEXT_AND_TYPE_ENTRY_TYPE  VTSS_BIT(16)

#define VTSS_AFI_FRM_TBL_FRM_ENTRY_PART0(gi)  VTSS_IOREG_IX(VTSS_TO_AFI,0x8000,gi,2,0,1)
#define  VTSS_F_AFI_FRM_TBL_FRM_ENTRY_PART0_PART0(x)  VTSS_ENCODE_BITFIELD(x,0,30)
#define  VTSS_M_AFI_FRM_TBL_FRM_ENTRY_PART0_PART0     VTSS_ENCODE_BITMASK(0,30)
#define  VTSS_X_AFI_FRM_TBL_FRM_ENTRY_PART0_PART0(x)  VTSS_EXTRACT_BITFIELD(x,0,30)

#define VTSS_AFI_DTI_TBL_DTI_MODE(gi)        VTSS_IOREG_IX(VTSS_TO_AFI,0xa000,gi,4,0,0)
#define  VTSS_F_AFI_DTI_TBL_DTI_MODE_MODE     VTSS_BIT(0)
#define  VTSS_F_AFI_DTI_TBL_DTI_MODE_TRAILING_DELAY_SEQ_CNT(x)  VTSS_ENCODE_BITFIELD(x,2,6)
#define  VTSS_M_AFI_DTI_TBL_DTI_MODE_TRAILING_DELAY_SEQ_CNT     VTSS_ENCODE_BITMASK(2,6)
#define  VTSS_X_AFI_DTI_TBL_DTI_MODE_TRAILING_DELAY_SEQ_CNT(x)  VTSS_EXTRACT_BITFIELD(x,2,6)
#define  VTSS_F_AFI_DTI_TBL_DTI_MODE_FRM_INJ_CNT(x)  VTSS_ENCODE_BITFIELD(x,8,8)
#define  VTSS_M_AFI_DTI_TBL_DTI_MODE_FRM_INJ_CNT     VTSS_ENCODE_BITMASK(8,8)
#define  VTSS_X_AFI_DTI_TBL_DTI_MODE_FRM_INJ_CNT(x)  VTSS_EXTRACT_BITFIELD(x,8,8)
#define  VTSS_F_AFI_DTI_TBL_DTI_MODE_FC_POSTPONE_LEN(x)  VTSS_ENCODE_BITFIELD(x,16,8)
#define  VTSS_M_AFI_DTI_TBL_DTI_MODE_FC_POSTPONE_LEN     VTSS_ENCODE_BITMASK(16,8)
#define  VTSS_X_AFI_DTI_TBL_DTI_MODE_FC_POSTPONE_LEN(x)  VTSS_EXTRACT_BITFIELD(x,16,8)
#define  VTSS_F_AFI_DTI_TBL_DTI_MODE_FC_POSTPONE_MODE  VTSS_BIT(24)

#define VTSS_AFI_DTI_TBL_DTI_PORT_QU(gi)     VTSS_IOREG_IX(VTSS_TO_AFI,0xa000,gi,4,0,1)
#define  VTSS_F_AFI_DTI_TBL_DTI_PORT_QU_PORT_NUM(x)  VTSS_ENCODE_BITFIELD(x,0,6)
#define  VTSS_M_AFI_DTI_TBL_DTI_PORT_QU_PORT_NUM     VTSS_ENCODE_BITMASK(0,6)
#define  VTSS_X_AFI_DTI_TBL_DTI_PORT_QU_PORT_NUM(x)  VTSS_EXTRACT_BITFIELD(x,0,6)
#define  VTSS_F_AFI_DTI_TBL_DTI_PORT_QU_SE_IDX(x)  VTSS_ENCODE_BITFIELD(x,8,12)
#define  VTSS_M_AFI_DTI_TBL_DTI_PORT_QU_SE_IDX     VTSS_ENCODE_BITMASK(8,12)
#define  VTSS_X_AFI_DTI_TBL_DTI_PORT_QU_SE_IDX(x)  VTSS_EXTRACT_BITFIELD(x,8,12)
#define  VTSS_F_AFI_DTI_TBL_DTI_PORT_QU_SE_INP(x)  VTSS_ENCODE_BITFIELD(x,24,6)
#define  VTSS_M_AFI_DTI_TBL_DTI_PORT_QU_SE_INP     VTSS_ENCODE_BITMASK(24,6)
#define  VTSS_X_AFI_DTI_TBL_DTI_PORT_QU_SE_INP(x)  VTSS_EXTRACT_BITFIELD(x,24,6)

#define VTSS_AFI_DTI_TBL_DTI_FRM(gi)         VTSS_IOREG_IX(VTSS_TO_AFI,0xa000,gi,4,0,2)
#define  VTSS_F_AFI_DTI_TBL_DTI_FRM_FIRST_FRM_PTR(x)  VTSS_ENCODE_BITFIELD(x,0,12)
#define  VTSS_M_AFI_DTI_TBL_DTI_FRM_FIRST_FRM_PTR     VTSS_ENCODE_BITMASK(0,12)
#define  VTSS_X_AFI_DTI_TBL_DTI_FRM_FIRST_FRM_PTR(x)  VTSS_EXTRACT_BITFIELD(x,0,12)
#define  VTSS_F_AFI_DTI_TBL_DTI_FRM_NEXT_FRM_PTR(x)  VTSS_ENCODE_BITFIELD(x,16,12)
#define  VTSS_M_AFI_DTI_TBL_DTI_FRM_NEXT_FRM_PTR     VTSS_ENCODE_BITMASK(16,12)
#define  VTSS_X_AFI_DTI_TBL_DTI_FRM_NEXT_FRM_PTR(x)  VTSS_EXTRACT_BITFIELD(x,16,12)

#define VTSS_AFI_DTI_TBL_DTI_CNT(gi)         VTSS_IOREG_IX(VTSS_TO_AFI,0xa000,gi,4,0,3)
#define  VTSS_F_AFI_DTI_TBL_DTI_CNT_CNT(x)    VTSS_ENCODE_BITFIELD(x,0,31)
#define  VTSS_M_AFI_DTI_TBL_DTI_CNT_CNT       VTSS_ENCODE_BITMASK(0,31)
#define  VTSS_X_AFI_DTI_TBL_DTI_CNT_CNT(x)    VTSS_EXTRACT_BITFIELD(x,0,31)

#define VTSS_AFI_DTI_MISC_DTI_FC_CNT_DOWN(gi)  VTSS_IOREG_IX(VTSS_TO_AFI,0xa0f8,gi,3,0,0)
#define  VTSS_F_AFI_DTI_MISC_DTI_FC_CNT_DOWN_FC_CNT_DOWN(x)  VTSS_ENCODE_BITFIELD(x,0,8)
#define  VTSS_M_AFI_DTI_MISC_DTI_FC_CNT_DOWN_FC_CNT_DOWN     VTSS_ENCODE_BITMASK(0,8)
#define  VTSS_X_AFI_DTI_MISC_DTI_FC_CNT_DOWN_FC_CNT_DOWN(x)  VTSS_EXTRACT_BITFIELD(x,0,8)

#define VTSS_AFI_DTI_MISC_DTI_CNT_DOWN(gi)   VTSS_IOREG_IX(VTSS_TO_AFI,0xa0f8,gi,3,0,1)
#define  VTSS_F_AFI_DTI_MISC_DTI_CNT_DOWN_CNT_DOWN(x)  VTSS_ENCODE_BITFIELD(x,0,31)
#define  VTSS_M_AFI_DTI_MISC_DTI_CNT_DOWN_CNT_DOWN     VTSS_ENCODE_BITMASK(0,31)
#define  VTSS_X_AFI_DTI_MISC_DTI_CNT_DOWN_CNT_DOWN(x)  VTSS_EXTRACT_BITFIELD(x,0,31)

#define VTSS_AFI_DTI_MISC_DTI_CTRL(gi)       VTSS_IOREG_IX(VTSS_TO_AFI,0xa0f8,gi,3,0,2)
#define  VTSS_F_AFI_DTI_MISC_DTI_CTRL_ENA     VTSS_BIT(0)
#define  VTSS_F_AFI_DTI_MISC_DTI_CTRL_BW      VTSS_BIT(1)

#define VTSS_AFI_TTI_TBL_TTI_PORT_QU(gi)     VTSS_IOREG_IX(VTSS_TO_AFI,0x0,gi,8,0,0)
#define  VTSS_F_AFI_TTI_TBL_TTI_PORT_QU_PORT_NUM(x)  VTSS_ENCODE_BITFIELD(x,0,6)
#define  VTSS_M_AFI_TTI_TBL_TTI_PORT_QU_PORT_NUM     VTSS_ENCODE_BITMASK(0,6)
#define  VTSS_X_AFI_TTI_TBL_TTI_PORT_QU_PORT_NUM(x)  VTSS_EXTRACT_BITFIELD(x,0,6)
#define  VTSS_F_AFI_TTI_TBL_TTI_PORT_QU_SE_IDX(x)  VTSS_ENCODE_BITFIELD(x,8,12)
#define  VTSS_M_AFI_TTI_TBL_TTI_PORT_QU_SE_IDX     VTSS_ENCODE_BITMASK(8,12)
#define  VTSS_X_AFI_TTI_TBL_TTI_PORT_QU_SE_IDX(x)  VTSS_EXTRACT_BITFIELD(x,8,12)
#define  VTSS_F_AFI_TTI_TBL_TTI_PORT_QU_SE_INP(x)  VTSS_ENCODE_BITFIELD(x,24,6)
#define  VTSS_M_AFI_TTI_TBL_TTI_PORT_QU_SE_INP     VTSS_ENCODE_BITMASK(24,6)
#define  VTSS_X_AFI_TTI_TBL_TTI_PORT_QU_SE_INP(x)  VTSS_EXTRACT_BITFIELD(x,24,6)

#define VTSS_AFI_TTI_TBL_TTI_TIMER(gi)       VTSS_IOREG_IX(VTSS_TO_AFI,0x0,gi,8,0,1)
#define  VTSS_F_AFI_TTI_TBL_TTI_TIMER_TICK_IDX(x)  VTSS_ENCODE_BITFIELD(x,0,3)
#define  VTSS_M_AFI_TTI_TBL_TTI_TIMER_TICK_IDX     VTSS_ENCODE_BITMASK(0,3)
#define  VTSS_X_AFI_TTI_TBL_TTI_TIMER_TICK_IDX(x)  VTSS_EXTRACT_BITFIELD(x,0,3)
#define  VTSS_F_AFI_TTI_TBL_TTI_TIMER_JITTER(x)  VTSS_ENCODE_BITFIELD(x,4,2)
#define  VTSS_M_AFI_TTI_TBL_TTI_TIMER_JITTER     VTSS_ENCODE_BITMASK(4,2)
#define  VTSS_X_AFI_TTI_TBL_TTI_TIMER_JITTER(x)  VTSS_EXTRACT_BITFIELD(x,4,2)
#define  VTSS_F_AFI_TTI_TBL_TTI_TIMER_TIMER_LEN(x)  VTSS_ENCODE_BITFIELD(x,16,9)
#define  VTSS_M_AFI_TTI_TBL_TTI_TIMER_TIMER_LEN     VTSS_ENCODE_BITMASK(16,9)
#define  VTSS_X_AFI_TTI_TBL_TTI_TIMER_TIMER_LEN(x)  VTSS_EXTRACT_BITFIELD(x,16,9)

#define VTSS_AFI_TTI_TBL_TTI_FRM(gi)         VTSS_IOREG_IX(VTSS_TO_AFI,0x0,gi,8,0,2)
#define  VTSS_F_AFI_TTI_TBL_TTI_FRM_FRM_PTR(x)  VTSS_ENCODE_BITFIELD(x,0,12)
#define  VTSS_M_AFI_TTI_TBL_TTI_FRM_FRM_PTR     VTSS_ENCODE_BITMASK(0,12)
#define  VTSS_X_AFI_TTI_TBL_TTI_FRM_FRM_PTR(x)  VTSS_EXTRACT_BITFIELD(x,0,12)

#define VTSS_AFI_TTI_TBL_TTI_TICKS(gi)       VTSS_IOREG_IX(VTSS_TO_AFI,0x0,gi,8,0,3)
#define  VTSS_F_AFI_TTI_TBL_TTI_TICKS_TICK_CNT(x)  VTSS_ENCODE_BITFIELD(x,0,9)
#define  VTSS_M_AFI_TTI_TBL_TTI_TICKS_TICK_CNT     VTSS_ENCODE_BITMASK(0,9)
#define  VTSS_X_AFI_TTI_TBL_TTI_TICKS_TICK_CNT(x)  VTSS_EXTRACT_BITFIELD(x,0,9)
#define  VTSS_F_AFI_TTI_TBL_TTI_TICKS_LAST_TICK_ERA  VTSS_BIT(16)

#define VTSS_AFI_TTI_TBL_TTI_MISC_CFG(gi)    VTSS_IOREG_IX(VTSS_TO_AFI,0x0,gi,8,0,4)
#define  VTSS_F_AFI_TTI_TBL_TTI_MISC_CFG_INJ_CNT_ENA  VTSS_BIT(0)

#define VTSS_AFI_TTI_TICKS_TTI_TICK_BASE     VTSS_IOREG(VTSS_TO_AFI,0xa158)
#define  VTSS_F_AFI_TTI_TICKS_TTI_TICK_BASE_BASE_LEN(x)  VTSS_ENCODE_BITFIELD(x,0,14)
#define  VTSS_M_AFI_TTI_TICKS_TTI_TICK_BASE_BASE_LEN     VTSS_ENCODE_BITMASK(0,14)
#define  VTSS_X_AFI_TTI_TICKS_TTI_TICK_BASE_BASE_LEN(x)  VTSS_EXTRACT_BITFIELD(x,0,14)
#define  VTSS_F_AFI_TTI_TICKS_TTI_TICK_BASE_BASE_CNT(x)  VTSS_ENCODE_BITFIELD(x,16,14)
#define  VTSS_M_AFI_TTI_TICKS_TTI_TICK_BASE_BASE_CNT     VTSS_ENCODE_BITMASK(16,14)
#define  VTSS_X_AFI_TTI_TICKS_TTI_TICK_BASE_BASE_CNT(x)  VTSS_EXTRACT_BITFIELD(x,16,14)

#define VTSS_AFI_TTI_TICKS_TTI_TICK_LEN_0_3  VTSS_IOREG(VTSS_TO_AFI,0xa159)
#define  VTSS_F_AFI_TTI_TICKS_TTI_TICK_LEN_0_3_LEN0(x)  VTSS_ENCODE_BITFIELD(x,0,8)
#define  VTSS_M_AFI_TTI_TICKS_TTI_TICK_LEN_0_3_LEN0     VTSS_ENCODE_BITMASK(0,8)
#define  VTSS_X_AFI_TTI_TICKS_TTI_TICK_LEN_0_3_LEN0(x)  VTSS_EXTRACT_BITFIELD(x,0,8)
#define  VTSS_F_AFI_TTI_TICKS_TTI_TICK_LEN_0_3_LEN1(x)  VTSS_ENCODE_BITFIELD(x,8,8)
#define  VTSS_M_AFI_TTI_TICKS_TTI_TICK_LEN_0_3_LEN1     VTSS_ENCODE_BITMASK(8,8)
#define  VTSS_X_AFI_TTI_TICKS_TTI_TICK_LEN_0_3_LEN1(x)  VTSS_EXTRACT_BITFIELD(x,8,8)
#define  VTSS_F_AFI_TTI_TICKS_TTI_TICK_LEN_0_3_LEN2(x)  VTSS_ENCODE_BITFIELD(x,16,8)
#define  VTSS_M_AFI_TTI_TICKS_TTI_TICK_LEN_0_3_LEN2     VTSS_ENCODE_BITMASK(16,8)
#define  VTSS_X_AFI_TTI_TICKS_TTI_TICK_LEN_0_3_LEN2(x)  VTSS_EXTRACT_BITFIELD(x,16,8)
#define  VTSS_F_AFI_TTI_TICKS_TTI_TICK_LEN_0_3_LEN3(x)  VTSS_ENCODE_BITFIELD(x,24,8)
#define  VTSS_M_AFI_TTI_TICKS_TTI_TICK_LEN_0_3_LEN3     VTSS_ENCODE_BITMASK(24,8)
#define  VTSS_X_AFI_TTI_TICKS_TTI_TICK_LEN_0_3_LEN3(x)  VTSS_EXTRACT_BITFIELD(x,24,8)

#define VTSS_AFI_TTI_TICKS_TTI_TICK_LEN_4_7  VTSS_IOREG(VTSS_TO_AFI,0xa15a)
#define  VTSS_F_AFI_TTI_TICKS_TTI_TICK_LEN_4_7_LEN4(x)  VTSS_ENCODE_BITFIELD(x,0,8)
#define  VTSS_M_AFI_TTI_TICKS_TTI_TICK_LEN_4_7_LEN4     VTSS_ENCODE_BITMASK(0,8)
#define  VTSS_X_AFI_TTI_TICKS_TTI_TICK_LEN_4_7_LEN4(x)  VTSS_EXTRACT_BITFIELD(x,0,8)
#define  VTSS_F_AFI_TTI_TICKS_TTI_TICK_LEN_4_7_LEN5(x)  VTSS_ENCODE_BITFIELD(x,8,8)
#define  VTSS_M_AFI_TTI_TICKS_TTI_TICK_LEN_4_7_LEN5     VTSS_ENCODE_BITMASK(8,8)
#define  VTSS_X_AFI_TTI_TICKS_TTI_TICK_LEN_4_7_LEN5(x)  VTSS_EXTRACT_BITFIELD(x,8,8)
#define  VTSS_F_AFI_TTI_TICKS_TTI_TICK_LEN_4_7_LEN6(x)  VTSS_ENCODE_BITFIELD(x,16,8)
#define  VTSS_M_AFI_TTI_TICKS_TTI_TICK_LEN_4_7_LEN6     VTSS_ENCODE_BITMASK(16,8)
#define  VTSS_X_AFI_TTI_TICKS_TTI_TICK_LEN_4_7_LEN6(x)  VTSS_EXTRACT_BITFIELD(x,16,8)
#define  VTSS_F_AFI_TTI_TICKS_TTI_TICK_LEN_4_7_LEN7(x)  VTSS_ENCODE_BITFIELD(x,24,8)
#define  VTSS_M_AFI_TTI_TICKS_TTI_TICK_LEN_4_7_LEN7     VTSS_ENCODE_BITMASK(24,8)
#define  VTSS_X_AFI_TTI_TICKS_TTI_TICK_LEN_4_7_LEN7(x)  VTSS_EXTRACT_BITFIELD(x,24,8)

#define VTSS_AFI_TTI_TICKS_TTI_TICK_STATE(ri)  VTSS_IOREG(VTSS_TO_AFI,0xa15b + (ri))
#define  VTSS_F_AFI_TTI_TICKS_TTI_TICK_STATE_TICK_CNT(x)  VTSS_ENCODE_BITFIELD(x,0,8)
#define  VTSS_M_AFI_TTI_TICKS_TTI_TICK_STATE_TICK_CNT     VTSS_ENCODE_BITMASK(0,8)
#define  VTSS_X_AFI_TTI_TICKS_TTI_TICK_STATE_TICK_CNT(x)  VTSS_EXTRACT_BITFIELD(x,0,8)
#define  VTSS_F_AFI_TTI_TICKS_TTI_TICK_STATE_TICK_ERA  VTSS_BIT(16)

#define VTSS_AFI_TTI_MISC_TTI_CAL_SLOT_PTRS(ri)  VTSS_IOREG(VTSS_TO_AFI,0xa163 + (ri))
#define  VTSS_F_AFI_TTI_MISC_TTI_CAL_SLOT_PTRS_SLOT_START_PTR(x)  VTSS_ENCODE_BITFIELD(x,0,12)
#define  VTSS_M_AFI_TTI_MISC_TTI_CAL_SLOT_PTRS_SLOT_START_PTR     VTSS_ENCODE_BITMASK(0,12)
#define  VTSS_X_AFI_TTI_MISC_TTI_CAL_SLOT_PTRS_SLOT_START_PTR(x)  VTSS_EXTRACT_BITFIELD(x,0,12)
#define  VTSS_F_AFI_TTI_MISC_TTI_CAL_SLOT_PTRS_SLOT_END_PTR(x)  VTSS_ENCODE_BITFIELD(x,16,12)
#define  VTSS_M_AFI_TTI_MISC_TTI_CAL_SLOT_PTRS_SLOT_END_PTR     VTSS_ENCODE_BITMASK(16,12)
#define  VTSS_X_AFI_TTI_MISC_TTI_CAL_SLOT_PTRS_SLOT_END_PTR(x)  VTSS_EXTRACT_BITFIELD(x,16,12)

#define VTSS_AFI_TTI_MISC_TTI_CAL_SLOT_CNT(ri)  VTSS_IOREG(VTSS_TO_AFI,0xa167 + (ri))
#define  VTSS_F_AFI_TTI_MISC_TTI_CAL_SLOT_CNT_SLOT_CNT(x)  VTSS_ENCODE_BITFIELD(x,0,8)
#define  VTSS_M_AFI_TTI_MISC_TTI_CAL_SLOT_CNT_SLOT_CNT     VTSS_ENCODE_BITMASK(0,8)
#define  VTSS_X_AFI_TTI_MISC_TTI_CAL_SLOT_CNT_SLOT_CNT(x)  VTSS_EXTRACT_BITFIELD(x,0,8)

#define VTSS_AFI_TTI_MISC_TTI_CAL_STATE(ri)  VTSS_IOREG(VTSS_TO_AFI,0xa16b + (ri))
#define  VTSS_F_AFI_TTI_MISC_TTI_CAL_STATE_SLOT_TTI_TBL_PTR(x)  VTSS_ENCODE_BITFIELD(x,0,12)
#define  VTSS_M_AFI_TTI_MISC_TTI_CAL_STATE_SLOT_TTI_TBL_PTR     VTSS_ENCODE_BITMASK(0,12)
#define  VTSS_X_AFI_TTI_MISC_TTI_CAL_STATE_SLOT_TTI_TBL_PTR(x)  VTSS_EXTRACT_BITFIELD(x,0,12)

#define VTSS_AFI_TTI_MISC_TTI_CTRL           VTSS_IOREG(VTSS_TO_AFI,0xa16f)
#define  VTSS_F_AFI_TTI_MISC_TTI_CTRL_TTI_ENA  VTSS_BIT(0)
#define  VTSS_F_AFI_TTI_MISC_TTI_CTRL_TTI_INIT  VTSS_BIT(1)
#define  VTSS_F_AFI_TTI_MISC_TTI_CTRL_TTI_SERIAL_ENA  VTSS_BIT(2)
#define  VTSS_F_AFI_TTI_MISC_TTI_CTRL_TTI_CAL_LEN(x)  VTSS_ENCODE_BITFIELD(x,4,2)
#define  VTSS_M_AFI_TTI_MISC_TTI_CTRL_TTI_CAL_LEN     VTSS_ENCODE_BITMASK(4,2)
#define  VTSS_X_AFI_TTI_MISC_TTI_CTRL_TTI_CAL_LEN(x)  VTSS_EXTRACT_BITFIELD(x,4,2)
#define  VTSS_F_AFI_TTI_MISC_TTI_CTRL_TTI_CSR_RSV(x)  VTSS_ENCODE_BITFIELD(x,8,8)
#define  VTSS_M_AFI_TTI_MISC_TTI_CTRL_TTI_CSR_RSV     VTSS_ENCODE_BITMASK(8,8)
#define  VTSS_X_AFI_TTI_MISC_TTI_CTRL_TTI_CSR_RSV(x)  VTSS_EXTRACT_BITFIELD(x,8,8)
#define  VTSS_F_AFI_TTI_MISC_TTI_CTRL_TTI_CAL_PTR(x)  VTSS_ENCODE_BITFIELD(x,16,2)
#define  VTSS_M_AFI_TTI_MISC_TTI_CTRL_TTI_CAL_PTR     VTSS_ENCODE_BITMASK(16,2)
#define  VTSS_X_AFI_TTI_MISC_TTI_CTRL_TTI_CAL_PTR(x)  VTSS_EXTRACT_BITFIELD(x,16,2)
#define  VTSS_F_AFI_TTI_MISC_TTI_CTRL_TTI_CAL_CNT(x)  VTSS_ENCODE_BITFIELD(x,20,8)
#define  VTSS_M_AFI_TTI_MISC_TTI_CTRL_TTI_CAL_CNT     VTSS_ENCODE_BITMASK(20,8)
#define  VTSS_X_AFI_TTI_MISC_TTI_CTRL_TTI_CAL_CNT(x)  VTSS_EXTRACT_BITFIELD(x,20,8)

#define VTSS_AFI_TTI_MISC_TTI_INJ_CNT        VTSS_IOREG(VTSS_TO_AFI,0xa170)
#define  VTSS_F_AFI_TTI_MISC_TTI_INJ_CNT_TTI_INJ_CNT(x)  VTSS_ENCODE_BITFIELD(x,0,30)
#define  VTSS_M_AFI_TTI_MISC_TTI_INJ_CNT_TTI_INJ_CNT     VTSS_ENCODE_BITMASK(0,30)
#define  VTSS_X_AFI_TTI_MISC_TTI_INJ_CNT_TTI_INJ_CNT(x)  VTSS_EXTRACT_BITFIELD(x,0,30)

#define VTSS_AFI_TTI_MISC_TTI_RAND_STATE     VTSS_IOREG(VTSS_TO_AFI,0xa171)
#define  VTSS_F_AFI_TTI_MISC_TTI_RAND_STATE_TTI_RAND_STATE(x)  VTSS_ENCODE_BITFIELD(x,0,18)
#define  VTSS_M_AFI_TTI_MISC_TTI_RAND_STATE_TTI_RAND_STATE     VTSS_ENCODE_BITMASK(0,18)
#define  VTSS_X_AFI_TTI_MISC_TTI_RAND_STATE_TTI_RAND_STATE(x)  VTSS_EXTRACT_BITFIELD(x,0,18)

#define VTSS_AFI_TTI_MISC_TTI_PORT_FRM_OUT   VTSS_IOREG(VTSS_TO_AFI,0xa172)
#define  VTSS_F_AFI_TTI_MISC_TTI_PORT_FRM_OUT_TTI_FRM_OUT_MAX(x)  VTSS_ENCODE_BITFIELD(x,0,10)
#define  VTSS_M_AFI_TTI_MISC_TTI_PORT_FRM_OUT_TTI_FRM_OUT_MAX     VTSS_ENCODE_BITMASK(0,10)
#define  VTSS_X_AFI_TTI_MISC_TTI_PORT_FRM_OUT_TTI_FRM_OUT_MAX(x)  VTSS_EXTRACT_BITFIELD(x,0,10)

#define VTSS_AFI_PORT_TBL_PORT_FRM_OUT(gi)   VTSS_IOREG_IX(VTSS_TO_AFI,0xa080,gi,2,0,0)
#define  VTSS_F_AFI_PORT_TBL_PORT_FRM_OUT_FRM_OUT_CNT(x)  VTSS_ENCODE_BITFIELD(x,16,11)
#define  VTSS_M_AFI_PORT_TBL_PORT_FRM_OUT_FRM_OUT_CNT     VTSS_ENCODE_BITMASK(16,11)
#define  VTSS_X_AFI_PORT_TBL_PORT_FRM_OUT_FRM_OUT_CNT(x)  VTSS_EXTRACT_BITFIELD(x,16,11)

#define VTSS_AFI_PORT_TBL_PORT_CFG(gi)       VTSS_IOREG_IX(VTSS_TO_AFI,0xa080,gi,2,0,1)
#define  VTSS_F_AFI_PORT_TBL_PORT_CFG_FRM_OUT_MAX(x)  VTSS_ENCODE_BITFIELD(x,0,10)
#define  VTSS_M_AFI_PORT_TBL_PORT_CFG_FRM_OUT_MAX     VTSS_ENCODE_BITMASK(0,10)
#define  VTSS_X_AFI_PORT_TBL_PORT_CFG_FRM_OUT_MAX(x)  VTSS_EXTRACT_BITFIELD(x,0,10)
#define  VTSS_F_AFI_PORT_TBL_PORT_CFG_FC_SKIP_TTI_INJ  VTSS_BIT(16)


#endif /* _VTSS_JAGUAR2_REGS_AFI_H_ */
