#ifndef _VTSS_JAGUAR2_REGS_ANA_AC_POL_H_
#define _VTSS_JAGUAR2_REGS_ANA_AC_POL_H_

/*
 *
 * VCore-III Register Definitions
 *
 * Copyright (C) 2012 Vitesse Semiconductor Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#include "vtss_jaguar2_regs_common.h"

#define VTSS_ANA_AC_POL_POL_ALL_CFG_POL_STORM_RATE_CFG(ri)  VTSS_IOREG(VTSS_TO_ANA_AC_POL,0x8fc8 + (ri))
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_STORM_RATE_CFG_STORM_RATE(x)  VTSS_ENCODE_BITFIELD(x,0,19)
#define  VTSS_M_ANA_AC_POL_POL_ALL_CFG_POL_STORM_RATE_CFG_STORM_RATE     VTSS_ENCODE_BITMASK(0,19)
#define  VTSS_X_ANA_AC_POL_POL_ALL_CFG_POL_STORM_RATE_CFG_STORM_RATE(x)  VTSS_EXTRACT_BITFIELD(x,0,19)

#define VTSS_ANA_AC_POL_POL_ALL_CFG_POL_STORM_THRES_CFG(ri)  VTSS_IOREG(VTSS_TO_ANA_AC_POL,0x8fd0 + (ri))
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_STORM_THRES_CFG_STORM_THRES(x)  VTSS_ENCODE_BITFIELD(x,0,6)
#define  VTSS_M_ANA_AC_POL_POL_ALL_CFG_POL_STORM_THRES_CFG_STORM_THRES     VTSS_ENCODE_BITMASK(0,6)
#define  VTSS_X_ANA_AC_POL_POL_ALL_CFG_POL_STORM_THRES_CFG_STORM_THRES(x)  VTSS_EXTRACT_BITFIELD(x,0,6)

#define VTSS_ANA_AC_POL_POL_ALL_CFG_POL_STORM_CTRL(ri)  VTSS_IOREG(VTSS_TO_ANA_AC_POL,0x8fd8 + (ri))
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_STORM_CTRL_STORM_FRAME_RATE_ENA  VTSS_BIT(18)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_STORM_CTRL_STORM_CPU_QU_MASK(x)  VTSS_ENCODE_BITFIELD(x,10,8)
#define  VTSS_M_ANA_AC_POL_POL_ALL_CFG_POL_STORM_CTRL_STORM_CPU_QU_MASK     VTSS_ENCODE_BITMASK(10,8)
#define  VTSS_X_ANA_AC_POL_POL_ALL_CFG_POL_STORM_CTRL_STORM_CPU_QU_MASK(x)  VTSS_EXTRACT_BITFIELD(x,10,8)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_STORM_CTRL_STORM_LIMIT_NONCPU_TRAFFIC_ENA  VTSS_BIT(9)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_STORM_CTRL_STORM_LIMIT_CPU_TRAFFIC_ENA  VTSS_BIT(8)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_STORM_CTRL_STORM_TRAFFIC_TYPE_MASK(x)  VTSS_ENCODE_BITFIELD(x,0,8)
#define  VTSS_M_ANA_AC_POL_POL_ALL_CFG_POL_STORM_CTRL_STORM_TRAFFIC_TYPE_MASK     VTSS_ENCODE_BITMASK(0,8)
#define  VTSS_X_ANA_AC_POL_POL_ALL_CFG_POL_STORM_CTRL_STORM_TRAFFIC_TYPE_MASK(x)  VTSS_EXTRACT_BITFIELD(x,0,8)

#define VTSS_ANA_AC_POL_POL_ALL_CFG_POL_ACL_RATE_CFG(ri)  VTSS_IOREG(VTSS_TO_ANA_AC_POL,0x8fe0 + (ri))
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_ACL_RATE_CFG_ACL_RATE(x)  VTSS_ENCODE_BITFIELD(x,0,19)
#define  VTSS_M_ANA_AC_POL_POL_ALL_CFG_POL_ACL_RATE_CFG_ACL_RATE     VTSS_ENCODE_BITMASK(0,19)
#define  VTSS_X_ANA_AC_POL_POL_ALL_CFG_POL_ACL_RATE_CFG_ACL_RATE(x)  VTSS_EXTRACT_BITFIELD(x,0,19)

#define VTSS_ANA_AC_POL_POL_ALL_CFG_POL_ACL_THRES_CFG(ri)  VTSS_IOREG(VTSS_TO_ANA_AC_POL,0x9000 + (ri))
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_ACL_THRES_CFG_ACL_THRES(x)  VTSS_ENCODE_BITFIELD(x,0,6)
#define  VTSS_M_ANA_AC_POL_POL_ALL_CFG_POL_ACL_THRES_CFG_ACL_THRES     VTSS_ENCODE_BITMASK(0,6)
#define  VTSS_X_ANA_AC_POL_POL_ALL_CFG_POL_ACL_THRES_CFG_ACL_THRES(x)  VTSS_EXTRACT_BITFIELD(x,0,6)

#define VTSS_ANA_AC_POL_POL_ALL_CFG_POL_ACL_CTRL(ri)  VTSS_IOREG(VTSS_TO_ANA_AC_POL,0x9020 + (ri))
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_ACL_CTRL_DP_BYPASS_LVL(x)  VTSS_ENCODE_BITFIELD(x,16,2)
#define  VTSS_M_ANA_AC_POL_POL_ALL_CFG_POL_ACL_CTRL_DP_BYPASS_LVL     VTSS_ENCODE_BITMASK(16,2)
#define  VTSS_X_ANA_AC_POL_POL_ALL_CFG_POL_ACL_CTRL_DP_BYPASS_LVL(x)  VTSS_EXTRACT_BITFIELD(x,16,2)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_ACL_CTRL_GAP_VALUE(x)  VTSS_ENCODE_BITFIELD(x,8,7)
#define  VTSS_M_ANA_AC_POL_POL_ALL_CFG_POL_ACL_CTRL_GAP_VALUE     VTSS_ENCODE_BITMASK(8,7)
#define  VTSS_X_ANA_AC_POL_POL_ALL_CFG_POL_ACL_CTRL_GAP_VALUE(x)  VTSS_EXTRACT_BITFIELD(x,8,7)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_ACL_CTRL_ACL_TRAFFIC_TYPE_MASK(x)  VTSS_ENCODE_BITFIELD(x,1,2)
#define  VTSS_M_ANA_AC_POL_POL_ALL_CFG_POL_ACL_CTRL_ACL_TRAFFIC_TYPE_MASK     VTSS_ENCODE_BITMASK(1,2)
#define  VTSS_X_ANA_AC_POL_POL_ALL_CFG_POL_ACL_CTRL_ACL_TRAFFIC_TYPE_MASK(x)  VTSS_EXTRACT_BITFIELD(x,1,2)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_ACL_CTRL_FRAME_RATE_ENA  VTSS_BIT(0)

#define VTSS_ANA_AC_POL_POL_ALL_CFG_POL_PORT_FC_CFG(ri)  VTSS_IOREG(VTSS_TO_ANA_AC_POL,0x9040 + (ri))
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_PORT_FC_CFG_FC_STATE  VTSS_BIT(8)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_PORT_FC_CFG_FC_ENA(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_ANA_AC_POL_POL_ALL_CFG_POL_PORT_FC_CFG_FC_ENA     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_ANA_AC_POL_POL_ALL_CFG_POL_PORT_FC_CFG_FC_ENA(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_ANA_AC_POL_POL_ALL_CFG_POL_ALL_CFG  VTSS_IOREG(VTSS_TO_ANA_AC_POL,0x9079)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_ALL_CFG_DBG_DP_CHG_PRIO_ENA  VTSS_BIT(31)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_ALL_CFG_STORM_GAP_VALUE(x)  VTSS_ENCODE_BITFIELD(x,24,7)
#define  VTSS_M_ANA_AC_POL_POL_ALL_CFG_POL_ALL_CFG_STORM_GAP_VALUE     VTSS_ENCODE_BITMASK(24,7)
#define  VTSS_X_ANA_AC_POL_POL_ALL_CFG_POL_ALL_CFG_STORM_GAP_VALUE(x)  VTSS_EXTRACT_BITFIELD(x,24,7)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_ALL_CFG_USE_SDLB_COLOR_ENA  VTSS_BIT(20)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_ALL_CFG_DP_TO_COLOR_MAP(x)  VTSS_ENCODE_BITFIELD(x,16,4)
#define  VTSS_M_ANA_AC_POL_POL_ALL_CFG_POL_ALL_CFG_DP_TO_COLOR_MAP     VTSS_ENCODE_BITMASK(16,4)
#define  VTSS_X_ANA_AC_POL_POL_ALL_CFG_POL_ALL_CFG_DP_TO_COLOR_MAP(x)  VTSS_EXTRACT_BITFIELD(x,16,4)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_ALL_CFG_PORT_FC_ENA  VTSS_BIT(14)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_ALL_CFG_PORT_POL_IN_PARALLEL_ENA  VTSS_BIT(13)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_ALL_CFG_STORM_FORCE_CLOSE  VTSS_BIT(12)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_ALL_CFG_STORM_FORCE_OPEN  VTSS_BIT(11)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_ALL_CFG_STORM_FORCE_INIT  VTSS_BIT(10)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_ALL_CFG_PRIO_FORCE_CLOSE  VTSS_BIT(9)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_ALL_CFG_PRIO_FORCE_OPEN  VTSS_BIT(8)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_ALL_CFG_PRIO_FORCE_INIT  VTSS_BIT(7)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_ALL_CFG_ACL_FORCE_CLOSE  VTSS_BIT(6)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_ALL_CFG_ACL_FORCE_OPEN  VTSS_BIT(5)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_ALL_CFG_ACL_FORCE_INIT  VTSS_BIT(4)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_ALL_CFG_FORCE_OPEN  VTSS_BIT(3)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_ALL_CFG_FORCE_CLOSE  VTSS_BIT(2)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_ALL_CFG_LPORT_POLICE_ENA  VTSS_BIT(1)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_ALL_CFG_FORCE_INIT  VTSS_BIT(0)

#define VTSS_ANA_AC_POL_POL_ALL_CFG_POL_STICKY  VTSS_IOREG(VTSS_TO_ANA_AC_POL,0x907a)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_STICKY_POL_STORM_ACTIVE_STICKY(x)  VTSS_ENCODE_BITFIELD(x,22,8)
#define  VTSS_M_ANA_AC_POL_POL_ALL_CFG_POL_STICKY_POL_STORM_ACTIVE_STICKY     VTSS_ENCODE_BITMASK(22,8)
#define  VTSS_X_ANA_AC_POL_POL_ALL_CFG_POL_STICKY_POL_STORM_ACTIVE_STICKY(x)  VTSS_EXTRACT_BITFIELD(x,22,8)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_STICKY_POL_STORM_DROP_FWD_STICKY  VTSS_BIT(21)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_STICKY_POL_STORM_DROP_CPU_STICKY  VTSS_BIT(20)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_STICKY_POL_DLB_PT_BYPASS_STICKY  VTSS_BIT(19)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_STICKY_POL_DLB_DROP_STICKY  VTSS_BIT(18)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_STICKY_POL_PRIO_PT_BYPASS_STICKY  VTSS_BIT(17)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_STICKY_POL_PRIO_ACTIVE_STICKY  VTSS_BIT(16)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_STICKY_POL_PRIO_DROP_STICKY  VTSS_BIT(15)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_STICKY_POL_PRIO_BYPASS_STICKY  VTSS_BIT(14)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_STICKY_POL_ACL_PT_BYPASS_STICKY  VTSS_BIT(13)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_STICKY_POL_ACL_ACTIVE_STICKY  VTSS_BIT(12)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_STICKY_POL_ACL_DROP_STICKY  VTSS_BIT(11)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_STICKY_POL_ACL_BYPASS_STICKY  VTSS_BIT(10)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_STICKY_POL_PORT_PT_BYPASS_STICKY  VTSS_BIT(9)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_STICKY_POL_PORT_ACTIVE_STICKY(x)  VTSS_ENCODE_BITFIELD(x,5,4)
#define  VTSS_M_ANA_AC_POL_POL_ALL_CFG_POL_STICKY_POL_PORT_ACTIVE_STICKY     VTSS_ENCODE_BITMASK(5,4)
#define  VTSS_X_ANA_AC_POL_POL_ALL_CFG_POL_STICKY_POL_PORT_ACTIVE_STICKY(x)  VTSS_EXTRACT_BITFIELD(x,5,4)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_STICKY_POL_PORT_FC_CLEAR_STICKY  VTSS_BIT(4)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_STICKY_POL_PORT_FC_STICKY  VTSS_BIT(3)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_STICKY_POL_PORT_DROP_FWD_STICKY  VTSS_BIT(2)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_STICKY_POL_PORT_DROP_CPU_STICKY  VTSS_BIT(1)
#define  VTSS_F_ANA_AC_POL_POL_ALL_CFG_POL_STICKY_POL_PORT_BYPASS_STICKY  VTSS_BIT(0)

#define VTSS_ANA_AC_POL_POL_PORT_CFG_POL_PORT_THRES_CFG_0(ri)  VTSS_IOREG(VTSS_TO_ANA_AC_POL,0x8000 + (ri))
#define  VTSS_F_ANA_AC_POL_POL_PORT_CFG_POL_PORT_THRES_CFG_0_PORT_THRES0(x)  VTSS_ENCODE_BITFIELD(x,0,6)
#define  VTSS_M_ANA_AC_POL_POL_PORT_CFG_POL_PORT_THRES_CFG_0_PORT_THRES0     VTSS_ENCODE_BITMASK(0,6)
#define  VTSS_X_ANA_AC_POL_POL_PORT_CFG_POL_PORT_THRES_CFG_0_PORT_THRES0(x)  VTSS_EXTRACT_BITFIELD(x,0,6)

#define VTSS_ANA_AC_POL_POL_PORT_CFG_POL_PORT_THRES_CFG_1(ri)  VTSS_IOREG(VTSS_TO_ANA_AC_POL,0x8100 + (ri))
#define  VTSS_F_ANA_AC_POL_POL_PORT_CFG_POL_PORT_THRES_CFG_1_PORT_THRES1(x)  VTSS_ENCODE_BITFIELD(x,0,6)
#define  VTSS_M_ANA_AC_POL_POL_PORT_CFG_POL_PORT_THRES_CFG_1_PORT_THRES1     VTSS_ENCODE_BITMASK(0,6)
#define  VTSS_X_ANA_AC_POL_POL_PORT_CFG_POL_PORT_THRES_CFG_1_PORT_THRES1(x)  VTSS_EXTRACT_BITFIELD(x,0,6)

#define VTSS_ANA_AC_POL_POL_PORT_CFG_POL_PORT_RATE_CFG(ri)  VTSS_IOREG(VTSS_TO_ANA_AC_POL,0x8200 + (ri))
#define  VTSS_F_ANA_AC_POL_POL_PORT_CFG_POL_PORT_RATE_CFG_PORT_RATE(x)  VTSS_ENCODE_BITFIELD(x,0,19)
#define  VTSS_M_ANA_AC_POL_POL_PORT_CFG_POL_PORT_RATE_CFG_PORT_RATE     VTSS_ENCODE_BITMASK(0,19)
#define  VTSS_X_ANA_AC_POL_POL_PORT_CFG_POL_PORT_RATE_CFG_PORT_RATE(x)  VTSS_EXTRACT_BITFIELD(x,0,19)

#define VTSS_ANA_AC_POL_POL_PORT_CTRL_POL_PORT_GAP(gi)  VTSS_IOREG_IX(VTSS_TO_ANA_AC_POL,0x8e00,gi,8,0,0)
#define  VTSS_F_ANA_AC_POL_POL_PORT_CTRL_POL_PORT_GAP_GAP_VALUE(x)  VTSS_ENCODE_BITFIELD(x,0,7)
#define  VTSS_M_ANA_AC_POL_POL_PORT_CTRL_POL_PORT_GAP_GAP_VALUE     VTSS_ENCODE_BITMASK(0,7)
#define  VTSS_X_ANA_AC_POL_POL_PORT_CTRL_POL_PORT_GAP_GAP_VALUE(x)  VTSS_EXTRACT_BITFIELD(x,0,7)

#define VTSS_ANA_AC_POL_POL_PORT_CTRL_POL_PORT_CFG(gi,ri)  VTSS_IOREG_IX(VTSS_TO_ANA_AC_POL,0x8e00,gi,8,ri,1)
#define  VTSS_F_ANA_AC_POL_POL_PORT_CTRL_POL_PORT_CFG_CPU_QU_MASK(x)  VTSS_ENCODE_BITFIELD(x,16,8)
#define  VTSS_M_ANA_AC_POL_POL_PORT_CTRL_POL_PORT_CFG_CPU_QU_MASK     VTSS_ENCODE_BITMASK(16,8)
#define  VTSS_X_ANA_AC_POL_POL_PORT_CTRL_POL_PORT_CFG_CPU_QU_MASK(x)  VTSS_EXTRACT_BITFIELD(x,16,8)
#define  VTSS_F_ANA_AC_POL_POL_PORT_CTRL_POL_PORT_CFG_DP_BYPASS_LVL(x)  VTSS_ENCODE_BITFIELD(x,12,2)
#define  VTSS_M_ANA_AC_POL_POL_PORT_CTRL_POL_PORT_CFG_DP_BYPASS_LVL     VTSS_ENCODE_BITMASK(12,2)
#define  VTSS_X_ANA_AC_POL_POL_PORT_CTRL_POL_PORT_CFG_DP_BYPASS_LVL(x)  VTSS_EXTRACT_BITFIELD(x,12,2)
#define  VTSS_F_ANA_AC_POL_POL_PORT_CTRL_POL_PORT_CFG_FRAME_RATE_ENA  VTSS_BIT(11)
#define  VTSS_F_ANA_AC_POL_POL_PORT_CTRL_POL_PORT_CFG_LIMIT_NONCPU_TRAFFIC_ENA  VTSS_BIT(10)
#define  VTSS_F_ANA_AC_POL_POL_PORT_CTRL_POL_PORT_CFG_LIMIT_CPU_TRAFFIC_ENA  VTSS_BIT(9)
#define  VTSS_F_ANA_AC_POL_POL_PORT_CTRL_POL_PORT_CFG_TRAFFIC_TYPE_MASK(x)  VTSS_ENCODE_BITFIELD(x,0,8)
#define  VTSS_M_ANA_AC_POL_POL_PORT_CTRL_POL_PORT_CFG_TRAFFIC_TYPE_MASK     VTSS_ENCODE_BITMASK(0,8)
#define  VTSS_X_ANA_AC_POL_POL_PORT_CTRL_POL_PORT_CFG_TRAFFIC_TYPE_MASK(x)  VTSS_EXTRACT_BITFIELD(x,0,8)

#define VTSS_ANA_AC_POL_POL_PRIO_CFG_POL_PRIO_RATE_CFG(ri)  VTSS_IOREG(VTSS_TO_ANA_AC_POL,0x8400 + (ri))
#define  VTSS_F_ANA_AC_POL_POL_PRIO_CFG_POL_PRIO_RATE_CFG_PRIO_RATE(x)  VTSS_ENCODE_BITFIELD(x,0,19)
#define  VTSS_M_ANA_AC_POL_POL_PRIO_CFG_POL_PRIO_RATE_CFG_PRIO_RATE     VTSS_ENCODE_BITMASK(0,19)
#define  VTSS_X_ANA_AC_POL_POL_PRIO_CFG_POL_PRIO_RATE_CFG_PRIO_RATE(x)  VTSS_EXTRACT_BITFIELD(x,0,19)

#define VTSS_ANA_AC_POL_POL_PRIO_CFG_POL_PRIO_THRES_CFG(ri)  VTSS_IOREG(VTSS_TO_ANA_AC_POL,0x8600 + (ri))
#define  VTSS_F_ANA_AC_POL_POL_PRIO_CFG_POL_PRIO_THRES_CFG_PRIO_THRES(x)  VTSS_ENCODE_BITFIELD(x,0,6)
#define  VTSS_M_ANA_AC_POL_POL_PRIO_CFG_POL_PRIO_THRES_CFG_PRIO_THRES     VTSS_ENCODE_BITMASK(0,6)
#define  VTSS_X_ANA_AC_POL_POL_PRIO_CFG_POL_PRIO_THRES_CFG_PRIO_THRES(x)  VTSS_EXTRACT_BITFIELD(x,0,6)

#define VTSS_ANA_AC_POL_POL_PRIO_CTRL_POL_PRIO_GAP(gi)  VTSS_IOREG_IX(VTSS_TO_ANA_AC_POL,0x8800,gi,2,0,0)
#define  VTSS_F_ANA_AC_POL_POL_PRIO_CTRL_POL_PRIO_GAP_GAP_VALUE(x)  VTSS_ENCODE_BITFIELD(x,0,7)
#define  VTSS_M_ANA_AC_POL_POL_PRIO_CTRL_POL_PRIO_GAP_GAP_VALUE     VTSS_ENCODE_BITMASK(0,7)
#define  VTSS_X_ANA_AC_POL_POL_PRIO_CTRL_POL_PRIO_GAP_GAP_VALUE(x)  VTSS_EXTRACT_BITFIELD(x,0,7)

#define VTSS_ANA_AC_POL_POL_PRIO_CTRL_POL_PRIO_CFG(gi)  VTSS_IOREG_IX(VTSS_TO_ANA_AC_POL,0x8800,gi,2,0,1)
#define  VTSS_F_ANA_AC_POL_POL_PRIO_CTRL_POL_PRIO_CFG_TRAFFIC_TYPE_MASK(x)  VTSS_ENCODE_BITFIELD(x,2,2)
#define  VTSS_M_ANA_AC_POL_POL_PRIO_CTRL_POL_PRIO_CFG_TRAFFIC_TYPE_MASK     VTSS_ENCODE_BITMASK(2,2)
#define  VTSS_X_ANA_AC_POL_POL_PRIO_CTRL_POL_PRIO_CFG_TRAFFIC_TYPE_MASK(x)  VTSS_EXTRACT_BITFIELD(x,2,2)
#define  VTSS_F_ANA_AC_POL_POL_PRIO_CTRL_POL_PRIO_CFG_DP_BYPASS_LVL(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_ANA_AC_POL_POL_PRIO_CTRL_POL_PRIO_CFG_DP_BYPASS_LVL     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_ANA_AC_POL_POL_PRIO_CTRL_POL_PRIO_CFG_DP_BYPASS_LVL(x)  VTSS_EXTRACT_BITFIELD(x,0,2)

#define VTSS_ANA_AC_POL_PORT_PT_CTRL_ACTION_CTRL(gi,ri)  VTSS_IOREG_IX(VTSS_TO_ANA_AC_POL,0x8c00,gi,8,ri,0)
#define  VTSS_F_ANA_AC_POL_PORT_PT_CTRL_ACTION_CTRL_ISDX_PT(x)  VTSS_ENCODE_BITFIELD(x,14,4)
#define  VTSS_M_ANA_AC_POL_PORT_PT_CTRL_ACTION_CTRL_ISDX_PT     VTSS_ENCODE_BITMASK(14,4)
#define  VTSS_X_ANA_AC_POL_PORT_PT_CTRL_ACTION_CTRL_ISDX_PT(x)  VTSS_EXTRACT_BITFIELD(x,14,4)
#define  VTSS_F_ANA_AC_POL_PORT_PT_CTRL_ACTION_CTRL_PVOE_DIS  VTSS_BIT(13)
#define  VTSS_F_ANA_AC_POL_PORT_PT_CTRL_ACTION_CTRL_PSTAT_DIS  VTSS_BIT(12)
#define  VTSS_F_ANA_AC_POL_PORT_PT_CTRL_ACTION_CTRL_IN_ACL_PT(x)  VTSS_ENCODE_BITFIELD(x,8,4)
#define  VTSS_M_ANA_AC_POL_PORT_PT_CTRL_ACTION_CTRL_IN_ACL_PT     VTSS_ENCODE_BITMASK(8,4)
#define  VTSS_X_ANA_AC_POL_PORT_PT_CTRL_ACTION_CTRL_IN_ACL_PT(x)  VTSS_EXTRACT_BITFIELD(x,8,4)
#define  VTSS_F_ANA_AC_POL_PORT_PT_CTRL_ACTION_CTRL_OU_ACL_PT(x)  VTSS_ENCODE_BITFIELD(x,4,4)
#define  VTSS_M_ANA_AC_POL_PORT_PT_CTRL_ACTION_CTRL_OU_ACL_PT     VTSS_ENCODE_BITMASK(4,4)
#define  VTSS_X_ANA_AC_POL_PORT_PT_CTRL_ACTION_CTRL_OU_ACL_PT(x)  VTSS_EXTRACT_BITFIELD(x,4,4)
#define  VTSS_F_ANA_AC_POL_PORT_PT_CTRL_ACTION_CTRL_PORT_PT(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_ANA_AC_POL_PORT_PT_CTRL_ACTION_CTRL_PORT_PT     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_ANA_AC_POL_PORT_PT_CTRL_ACTION_CTRL_PORT_PT(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_ANA_AC_POL_COMMON_SDLB_DLB_CTRL  VTSS_IOREG(VTSS_TO_ANA_AC_POL,0x8b90)
#define  VTSS_F_ANA_AC_POL_COMMON_SDLB_DLB_CTRL_BASE_TICK_CNT(x)  VTSS_ENCODE_BITFIELD(x,4,13)
#define  VTSS_M_ANA_AC_POL_COMMON_SDLB_DLB_CTRL_BASE_TICK_CNT     VTSS_ENCODE_BITMASK(4,13)
#define  VTSS_X_ANA_AC_POL_COMMON_SDLB_DLB_CTRL_BASE_TICK_CNT(x)  VTSS_EXTRACT_BITFIELD(x,4,13)
#define  VTSS_F_ANA_AC_POL_COMMON_SDLB_DLB_CTRL_LEAK_ENA  VTSS_BIT(1)
#define  VTSS_F_ANA_AC_POL_COMMON_SDLB_DLB_CTRL_DLB_ADD_ENA  VTSS_BIT(0)

#define VTSS_ANA_AC_POL_COMMON_SDLB_BURST_CTRL  VTSS_IOREG(VTSS_TO_ANA_AC_POL,0x8b91)
#define  VTSS_F_ANA_AC_POL_COMMON_SDLB_BURST_CTRL_DLB_BURST_ADJ_VAL(x)  VTSS_ENCODE_BITFIELD(x,4,16)
#define  VTSS_M_ANA_AC_POL_COMMON_SDLB_BURST_CTRL_DLB_BURST_ADJ_VAL     VTSS_ENCODE_BITMASK(4,16)
#define  VTSS_X_ANA_AC_POL_COMMON_SDLB_BURST_CTRL_DLB_BURST_ADJ_VAL(x)  VTSS_EXTRACT_BITFIELD(x,4,16)
#define  VTSS_F_ANA_AC_POL_COMMON_SDLB_BURST_CTRL_DLB_BURST_ADJ_ENA  VTSS_BIT(0)

#define VTSS_ANA_AC_POL_COMMON_SDLB_DLB_STICKY  VTSS_IOREG(VTSS_TO_ANA_AC_POL,0x8b92)
#define  VTSS_F_ANA_AC_POL_COMMON_SDLB_DLB_STICKY_LEAK_SCAN_COMPLETED_STICKY  VTSS_BIT(31)
#define  VTSS_F_ANA_AC_POL_COMMON_SDLB_DLB_STICKY_LEAK_SCAN_STARTED_STICKY  VTSS_BIT(30)
#define  VTSS_F_ANA_AC_POL_COMMON_SDLB_DLB_STICKY_LEAK_START_DELAYED_STICKY  VTSS_BIT(29)
#define  VTSS_F_ANA_AC_POL_COMMON_SDLB_DLB_STICKY_PIR_EXCEEDED_STICKY  VTSS_BIT(2)
#define  VTSS_F_ANA_AC_POL_COMMON_SDLB_DLB_STICKY_CIR_EXCEEDED_STICKY  VTSS_BIT(1)
#define  VTSS_F_ANA_AC_POL_COMMON_SDLB_DLB_STICKY_CIR_PIR_OPEN_STICKY  VTSS_BIT(0)

#define VTSS_ANA_AC_POL_SDLB_DLB_CFG(gi)     VTSS_IOREG_IX(VTSS_TO_ANA_AC_POL,0x0,gi,8,0,0)
#define  VTSS_F_ANA_AC_POL_SDLB_DLB_CFG_TIMESTAMP_VAL(x)  VTSS_ENCODE_BITFIELD(x,17,11)
#define  VTSS_M_ANA_AC_POL_SDLB_DLB_CFG_TIMESTAMP_VAL     VTSS_ENCODE_BITMASK(17,11)
#define  VTSS_X_ANA_AC_POL_SDLB_DLB_CFG_TIMESTAMP_VAL(x)  VTSS_EXTRACT_BITFIELD(x,17,11)
#define  VTSS_F_ANA_AC_POL_SDLB_DLB_CFG_COUPLING_MODE  VTSS_BIT(16)
#define  VTSS_F_ANA_AC_POL_SDLB_DLB_CFG_COLOR_AWARE_LVL(x)  VTSS_ENCODE_BITFIELD(x,14,2)
#define  VTSS_M_ANA_AC_POL_SDLB_DLB_CFG_COLOR_AWARE_LVL     VTSS_ENCODE_BITMASK(14,2)
#define  VTSS_X_ANA_AC_POL_SDLB_DLB_CFG_COLOR_AWARE_LVL(x)  VTSS_EXTRACT_BITFIELD(x,14,2)
#define  VTSS_F_ANA_AC_POL_SDLB_DLB_CFG_CIR_INC_DP_VAL(x)  VTSS_ENCODE_BITFIELD(x,12,2)
#define  VTSS_M_ANA_AC_POL_SDLB_DLB_CFG_CIR_INC_DP_VAL     VTSS_ENCODE_BITMASK(12,2)
#define  VTSS_X_ANA_AC_POL_SDLB_DLB_CFG_CIR_INC_DP_VAL(x)  VTSS_EXTRACT_BITFIELD(x,12,2)
#define  VTSS_F_ANA_AC_POL_SDLB_DLB_CFG_TRAFFIC_TYPE_MASK(x)  VTSS_ENCODE_BITFIELD(x,10,2)
#define  VTSS_M_ANA_AC_POL_SDLB_DLB_CFG_TRAFFIC_TYPE_MASK     VTSS_ENCODE_BITMASK(10,2)
#define  VTSS_X_ANA_AC_POL_SDLB_DLB_CFG_TRAFFIC_TYPE_MASK(x)  VTSS_EXTRACT_BITFIELD(x,10,2)
#define  VTSS_F_ANA_AC_POL_SDLB_DLB_CFG_ENCAP_DATA_DIS  VTSS_BIT(9)
#define  VTSS_F_ANA_AC_POL_SDLB_DLB_CFG_GAP_VAL(x)  VTSS_ENCODE_BITFIELD(x,2,7)
#define  VTSS_M_ANA_AC_POL_SDLB_DLB_CFG_GAP_VAL     VTSS_ENCODE_BITMASK(2,7)
#define  VTSS_X_ANA_AC_POL_SDLB_DLB_CFG_GAP_VAL(x)  VTSS_EXTRACT_BITFIELD(x,2,7)
#define  VTSS_F_ANA_AC_POL_SDLB_DLB_CFG_TIMESCALE_VAL(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_ANA_AC_POL_SDLB_DLB_CFG_TIMESCALE_VAL     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_ANA_AC_POL_SDLB_DLB_CFG_TIMESCALE_VAL(x)  VTSS_EXTRACT_BITFIELD(x,0,2)

#define VTSS_ANA_AC_POL_SDLB_LB_CFG(gi,ri)   VTSS_IOREG_IX(VTSS_TO_ANA_AC_POL,0x0,gi,8,ri,1)
#define  VTSS_F_ANA_AC_POL_SDLB_LB_CFG_THRES_VAL(x)  VTSS_ENCODE_BITFIELD(x,16,7)
#define  VTSS_M_ANA_AC_POL_SDLB_LB_CFG_THRES_VAL     VTSS_ENCODE_BITMASK(16,7)
#define  VTSS_X_ANA_AC_POL_SDLB_LB_CFG_THRES_VAL(x)  VTSS_EXTRACT_BITFIELD(x,16,7)
#define  VTSS_F_ANA_AC_POL_SDLB_LB_CFG_RATE_VAL(x)  VTSS_ENCODE_BITFIELD(x,0,11)
#define  VTSS_M_ANA_AC_POL_SDLB_LB_CFG_RATE_VAL     VTSS_ENCODE_BITMASK(0,11)
#define  VTSS_X_ANA_AC_POL_SDLB_LB_CFG_RATE_VAL(x)  VTSS_EXTRACT_BITFIELD(x,0,11)

#define VTSS_ANA_AC_POL_SDLB_LB_BUCKET_VAL(gi,ri)  VTSS_IOREG_IX(VTSS_TO_ANA_AC_POL,0x0,gi,8,ri,3)
#define  VTSS_F_ANA_AC_POL_SDLB_LB_BUCKET_VAL_BUCKET_VAL(x)  VTSS_ENCODE_BITFIELD(x,9,19)
#define  VTSS_M_ANA_AC_POL_SDLB_LB_BUCKET_VAL_BUCKET_VAL     VTSS_ENCODE_BITMASK(9,19)
#define  VTSS_X_ANA_AC_POL_SDLB_LB_BUCKET_VAL_BUCKET_VAL(x)  VTSS_EXTRACT_BITFIELD(x,9,19)
#define  VTSS_F_ANA_AC_POL_SDLB_LB_BUCKET_VAL_REM_VAL(x)  VTSS_ENCODE_BITFIELD(x,0,9)
#define  VTSS_M_ANA_AC_POL_SDLB_LB_BUCKET_VAL_REM_VAL     VTSS_ENCODE_BITMASK(0,9)
#define  VTSS_X_ANA_AC_POL_SDLB_LB_BUCKET_VAL_REM_VAL(x)  VTSS_EXTRACT_BITFIELD(x,0,9)


#endif /* _VTSS_JAGUAR2_REGS_ANA_AC_POL_H_ */
