#ifndef _VTSS_JAGUAR2_REGS_ANA_L3_H_
#define _VTSS_JAGUAR2_REGS_ANA_L3_H_

/*
 *
 * VCore-III Register Definitions
 *
 * Copyright (C) 2012 Vitesse Semiconductor Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#include "vtss_jaguar2_regs_common.h"

#define VTSS_ANA_L3_COMMON_MISC_CTRL         VTSS_IOREG(VTSS_TO_ANA_L3,0xd508)
#define  VTSS_F_ANA_L3_COMMON_MISC_CTRL_AC_UPDATE_ENA  VTSS_BIT(0)

#define VTSS_ANA_L3_COMMON_VLAN_CTRL         VTSS_IOREG(VTSS_TO_ANA_L3,0xd509)
#define  VTSS_F_ANA_L3_COMMON_VLAN_CTRL_VLAN_ENA  VTSS_BIT(0)

#define VTSS_ANA_L3_COMMON_L3_UC_ENA         VTSS_IOREG(VTSS_TO_ANA_L3,0xd50a)

#define VTSS_ANA_L3_COMMON_L3_UC_ENA1        VTSS_IOREG(VTSS_TO_ANA_L3,0xd50b)
#define  VTSS_F_ANA_L3_COMMON_L3_UC_ENA1_L3_UC_ENA1(x)  VTSS_ENCODE_BITFIELD(x,0,21)
#define  VTSS_M_ANA_L3_COMMON_L3_UC_ENA1_L3_UC_ENA1     VTSS_ENCODE_BITMASK(0,21)
#define  VTSS_X_ANA_L3_COMMON_L3_UC_ENA1_L3_UC_ENA1(x)  VTSS_EXTRACT_BITFIELD(x,0,21)

#define VTSS_ANA_L3_COMMON_L3_MC_ENA         VTSS_IOREG(VTSS_TO_ANA_L3,0xd50c)

#define VTSS_ANA_L3_COMMON_L3_MC_ENA1        VTSS_IOREG(VTSS_TO_ANA_L3,0xd50d)
#define  VTSS_F_ANA_L3_COMMON_L3_MC_ENA1_L3_MC_ENA1(x)  VTSS_ENCODE_BITFIELD(x,0,21)
#define  VTSS_M_ANA_L3_COMMON_L3_MC_ENA1_L3_MC_ENA1     VTSS_ENCODE_BITMASK(0,21)
#define  VTSS_X_ANA_L3_COMMON_L3_MC_ENA1_L3_MC_ENA1(x)  VTSS_EXTRACT_BITFIELD(x,0,21)

#define VTSS_ANA_L3_COMMON_PORT_FWD_CTRL     VTSS_IOREG(VTSS_TO_ANA_L3,0xd50e)

#define VTSS_ANA_L3_COMMON_PORT_FWD_CTRL1    VTSS_IOREG(VTSS_TO_ANA_L3,0xd50f)
#define  VTSS_F_ANA_L3_COMMON_PORT_FWD_CTRL1_PORT_FWD_ENA1(x)  VTSS_ENCODE_BITFIELD(x,0,21)
#define  VTSS_M_ANA_L3_COMMON_PORT_FWD_CTRL1_PORT_FWD_ENA1     VTSS_ENCODE_BITMASK(0,21)
#define  VTSS_X_ANA_L3_COMMON_PORT_FWD_CTRL1_PORT_FWD_ENA1(x)  VTSS_EXTRACT_BITFIELD(x,0,21)

#define VTSS_ANA_L3_COMMON_PORT_LRN_CTRL     VTSS_IOREG(VTSS_TO_ANA_L3,0xd510)

#define VTSS_ANA_L3_COMMON_PORT_LRN_CTRL1    VTSS_IOREG(VTSS_TO_ANA_L3,0xd511)
#define  VTSS_F_ANA_L3_COMMON_PORT_LRN_CTRL1_PORT_LRN_ENA1(x)  VTSS_ENCODE_BITFIELD(x,0,21)
#define  VTSS_M_ANA_L3_COMMON_PORT_LRN_CTRL1_PORT_LRN_ENA1     VTSS_ENCODE_BITMASK(0,21)
#define  VTSS_X_ANA_L3_COMMON_PORT_LRN_CTRL1_PORT_LRN_ENA1(x)  VTSS_EXTRACT_BITFIELD(x,0,21)

#define VTSS_ANA_L3_COMMON_VLAN_FILTER_CTRL  VTSS_IOREG(VTSS_TO_ANA_L3,0xd512)

#define VTSS_ANA_L3_COMMON_VLAN_FILTER_CTRL1  VTSS_IOREG(VTSS_TO_ANA_L3,0xd513)
#define  VTSS_F_ANA_L3_COMMON_VLAN_FILTER_CTRL1_VLAN_IGR_FILTER_ENA1(x)  VTSS_ENCODE_BITFIELD(x,0,21)
#define  VTSS_M_ANA_L3_COMMON_VLAN_FILTER_CTRL1_VLAN_IGR_FILTER_ENA1     VTSS_ENCODE_BITMASK(0,21)
#define  VTSS_X_ANA_L3_COMMON_VLAN_FILTER_CTRL1_VLAN_IGR_FILTER_ENA1(x)  VTSS_EXTRACT_BITFIELD(x,0,21)

#define VTSS_ANA_L3_COMMON_VLAN_ISOLATED_CFG  VTSS_IOREG(VTSS_TO_ANA_L3,0xd514)

#define VTSS_ANA_L3_COMMON_VLAN_ISOLATED_CFG1  VTSS_IOREG(VTSS_TO_ANA_L3,0xd515)
#define  VTSS_F_ANA_L3_COMMON_VLAN_ISOLATED_CFG1_VLAN_ISOLATED_MASK1(x)  VTSS_ENCODE_BITFIELD(x,0,21)
#define  VTSS_M_ANA_L3_COMMON_VLAN_ISOLATED_CFG1_VLAN_ISOLATED_MASK1     VTSS_ENCODE_BITMASK(0,21)
#define  VTSS_X_ANA_L3_COMMON_VLAN_ISOLATED_CFG1_VLAN_ISOLATED_MASK1(x)  VTSS_EXTRACT_BITFIELD(x,0,21)

#define VTSS_ANA_L3_COMMON_VLAN_COMMUNITY_CFG  VTSS_IOREG(VTSS_TO_ANA_L3,0xd516)

#define VTSS_ANA_L3_COMMON_VLAN_COMMUNITY_CFG1  VTSS_IOREG(VTSS_TO_ANA_L3,0xd517)
#define  VTSS_F_ANA_L3_COMMON_VLAN_COMMUNITY_CFG1_VLAN_COMMUNITY_MASK1(x)  VTSS_ENCODE_BITFIELD(x,0,21)
#define  VTSS_M_ANA_L3_COMMON_VLAN_COMMUNITY_CFG1_VLAN_COMMUNITY_MASK1     VTSS_ENCODE_BITMASK(0,21)
#define  VTSS_X_ANA_L3_COMMON_VLAN_COMMUNITY_CFG1_VLAN_COMMUNITY_MASK1(x)  VTSS_EXTRACT_BITFIELD(x,0,21)

#define VTSS_ANA_L3_COMMON_ROUTING_CFG       VTSS_IOREG(VTSS_TO_ANA_L3,0xd518)
#define  VTSS_F_ANA_L3_COMMON_ROUTING_CFG_RT_SMAC_UPDATE_ENA  VTSS_BIT(26)
#define  VTSS_F_ANA_L3_COMMON_ROUTING_CFG_RLEG_NONIP_UC_REDIR_MODE(x)  VTSS_ENCODE_BITFIELD(x,24,2)
#define  VTSS_M_ANA_L3_COMMON_ROUTING_CFG_RLEG_NONIP_UC_REDIR_MODE     VTSS_ENCODE_BITMASK(24,2)
#define  VTSS_X_ANA_L3_COMMON_ROUTING_CFG_RLEG_NONIP_UC_REDIR_MODE(x)  VTSS_EXTRACT_BITFIELD(x,24,2)
#define  VTSS_F_ANA_L3_COMMON_ROUTING_CFG_IP6_LEN_REDIR  VTSS_BIT(22)
#define  VTSS_F_ANA_L3_COMMON_ROUTING_CFG_IP4_LEN_REDIR  VTSS_BIT(21)
#define  VTSS_F_ANA_L3_COMMON_ROUTING_CFG_IP6_L2_BC_COPY_ENA  VTSS_BIT(20)
#define  VTSS_F_ANA_L3_COMMON_ROUTING_CFG_IP4_L2_BC_COPY_ENA  VTSS_BIT(19)
#define  VTSS_F_ANA_L3_COMMON_ROUTING_CFG_RLEG_IP6_SIP_RPF_REDIR_ENA  VTSS_BIT(18)
#define  VTSS_F_ANA_L3_COMMON_ROUTING_CFG_RLEG_IP4_SIP_RPF_REDIR_ENA  VTSS_BIT(17)
#define  VTSS_F_ANA_L3_COMMON_ROUTING_CFG_IP6_DIP_ADDR_VIOLATION_REDIR_ENA(x)  VTSS_ENCODE_BITFIELD(x,15,2)
#define  VTSS_M_ANA_L3_COMMON_ROUTING_CFG_IP6_DIP_ADDR_VIOLATION_REDIR_ENA     VTSS_ENCODE_BITMASK(15,2)
#define  VTSS_X_ANA_L3_COMMON_ROUTING_CFG_IP6_DIP_ADDR_VIOLATION_REDIR_ENA(x)  VTSS_EXTRACT_BITFIELD(x,15,2)
#define  VTSS_F_ANA_L3_COMMON_ROUTING_CFG_IP4_DIP_ADDR_VIOLATION_REDIR_ENA(x)  VTSS_ENCODE_BITFIELD(x,11,3)
#define  VTSS_M_ANA_L3_COMMON_ROUTING_CFG_IP4_DIP_ADDR_VIOLATION_REDIR_ENA     VTSS_ENCODE_BITMASK(11,3)
#define  VTSS_X_ANA_L3_COMMON_ROUTING_CFG_IP4_DIP_ADDR_VIOLATION_REDIR_ENA(x)  VTSS_EXTRACT_BITFIELD(x,11,3)
#define  VTSS_F_ANA_L3_COMMON_ROUTING_CFG_IP6_SIP_ADDR_VIOLATION_REDIR_ENA(x)  VTSS_ENCODE_BITFIELD(x,8,3)
#define  VTSS_M_ANA_L3_COMMON_ROUTING_CFG_IP6_SIP_ADDR_VIOLATION_REDIR_ENA     VTSS_ENCODE_BITMASK(8,3)
#define  VTSS_X_ANA_L3_COMMON_ROUTING_CFG_IP6_SIP_ADDR_VIOLATION_REDIR_ENA(x)  VTSS_EXTRACT_BITFIELD(x,8,3)
#define  VTSS_F_ANA_L3_COMMON_ROUTING_CFG_IP4_SIP_ADDR_VIOLATION_REDIR_ENA(x)  VTSS_ENCODE_BITFIELD(x,5,3)
#define  VTSS_M_ANA_L3_COMMON_ROUTING_CFG_IP4_SIP_ADDR_VIOLATION_REDIR_ENA     VTSS_ENCODE_BITMASK(5,3)
#define  VTSS_X_ANA_L3_COMMON_ROUTING_CFG_IP4_SIP_ADDR_VIOLATION_REDIR_ENA(x)  VTSS_EXTRACT_BITFIELD(x,5,3)
#define  VTSS_F_ANA_L3_COMMON_ROUTING_CFG_CPU_RLEG_IP_HDR_FAIL_REDIR_ENA  VTSS_BIT(4)
#define  VTSS_F_ANA_L3_COMMON_ROUTING_CFG_CPU_IP6_HOPBYHOP_REDIR_ENA  VTSS_BIT(3)
#define  VTSS_F_ANA_L3_COMMON_ROUTING_CFG_CPU_IP4_OPTIONS_REDIR_ENA  VTSS_BIT(2)
#define  VTSS_F_ANA_L3_COMMON_ROUTING_CFG_IP6_HC_REDIR_ENA  VTSS_BIT(1)
#define  VTSS_F_ANA_L3_COMMON_ROUTING_CFG_IP4_TTL_REDIR_ENA  VTSS_BIT(0)

#define VTSS_ANA_L3_COMMON_RLEG_CFG_0        VTSS_IOREG(VTSS_TO_ANA_L3,0xd519)
#define  VTSS_F_ANA_L3_COMMON_RLEG_CFG_0_RLEG_MAC_LSB(x)  VTSS_ENCODE_BITFIELD(x,8,24)
#define  VTSS_M_ANA_L3_COMMON_RLEG_CFG_0_RLEG_MAC_LSB     VTSS_ENCODE_BITMASK(8,24)
#define  VTSS_X_ANA_L3_COMMON_RLEG_CFG_0_RLEG_MAC_LSB(x)  VTSS_EXTRACT_BITFIELD(x,8,24)

#define VTSS_ANA_L3_COMMON_RLEG_CFG_1        VTSS_IOREG(VTSS_TO_ANA_L3,0xd51a)
#define  VTSS_F_ANA_L3_COMMON_RLEG_CFG_1_RLEG_MAC_TYPE_SEL(x)  VTSS_ENCODE_BITFIELD(x,24,2)
#define  VTSS_M_ANA_L3_COMMON_RLEG_CFG_1_RLEG_MAC_TYPE_SEL     VTSS_ENCODE_BITMASK(24,2)
#define  VTSS_X_ANA_L3_COMMON_RLEG_CFG_1_RLEG_MAC_TYPE_SEL(x)  VTSS_EXTRACT_BITFIELD(x,24,2)
#define  VTSS_F_ANA_L3_COMMON_RLEG_CFG_1_RLEG_MAC_MSB(x)  VTSS_ENCODE_BITFIELD(x,0,24)
#define  VTSS_M_ANA_L3_COMMON_RLEG_CFG_1_RLEG_MAC_MSB     VTSS_ENCODE_BITMASK(0,24)
#define  VTSS_X_ANA_L3_COMMON_RLEG_CFG_1_RLEG_MAC_MSB(x)  VTSS_EXTRACT_BITFIELD(x,0,24)

#define VTSS_ANA_L3_COMMON_CPU_QU_CFG        VTSS_IOREG(VTSS_TO_ANA_L3,0xd51b)
#define  VTSS_F_ANA_L3_COMMON_CPU_QU_CFG_CPU_RLEG_QU(x)  VTSS_ENCODE_BITFIELD(x,28,3)
#define  VTSS_M_ANA_L3_COMMON_CPU_QU_CFG_CPU_RLEG_QU     VTSS_ENCODE_BITMASK(28,3)
#define  VTSS_X_ANA_L3_COMMON_CPU_QU_CFG_CPU_RLEG_QU(x)  VTSS_EXTRACT_BITFIELD(x,28,3)
#define  VTSS_F_ANA_L3_COMMON_CPU_QU_CFG_CPU_RLEG_IP_OPT_QU(x)  VTSS_ENCODE_BITFIELD(x,24,3)
#define  VTSS_M_ANA_L3_COMMON_CPU_QU_CFG_CPU_RLEG_IP_OPT_QU     VTSS_ENCODE_BITMASK(24,3)
#define  VTSS_X_ANA_L3_COMMON_CPU_QU_CFG_CPU_RLEG_IP_OPT_QU(x)  VTSS_EXTRACT_BITFIELD(x,24,3)
#define  VTSS_F_ANA_L3_COMMON_CPU_QU_CFG_CPU_RLEG_IP_HDR_FAIL_QU(x)  VTSS_ENCODE_BITFIELD(x,20,3)
#define  VTSS_M_ANA_L3_COMMON_CPU_QU_CFG_CPU_RLEG_IP_HDR_FAIL_QU     VTSS_ENCODE_BITMASK(20,3)
#define  VTSS_X_ANA_L3_COMMON_CPU_QU_CFG_CPU_RLEG_IP_HDR_FAIL_QU(x)  VTSS_EXTRACT_BITFIELD(x,20,3)
#define  VTSS_F_ANA_L3_COMMON_CPU_QU_CFG_CPU_SIP_RPF_QU(x)  VTSS_ENCODE_BITFIELD(x,16,3)
#define  VTSS_M_ANA_L3_COMMON_CPU_QU_CFG_CPU_SIP_RPF_QU     VTSS_ENCODE_BITMASK(16,3)
#define  VTSS_X_ANA_L3_COMMON_CPU_QU_CFG_CPU_SIP_RPF_QU(x)  VTSS_EXTRACT_BITFIELD(x,16,3)
#define  VTSS_F_ANA_L3_COMMON_CPU_QU_CFG_CPU_IP_LEN_QU(x)  VTSS_ENCODE_BITFIELD(x,12,3)
#define  VTSS_M_ANA_L3_COMMON_CPU_QU_CFG_CPU_IP_LEN_QU     VTSS_ENCODE_BITMASK(12,3)
#define  VTSS_X_ANA_L3_COMMON_CPU_QU_CFG_CPU_IP_LEN_QU(x)  VTSS_EXTRACT_BITFIELD(x,12,3)
#define  VTSS_F_ANA_L3_COMMON_CPU_QU_CFG_CPU_MC_FAIL_QU(x)  VTSS_ENCODE_BITFIELD(x,8,3)
#define  VTSS_M_ANA_L3_COMMON_CPU_QU_CFG_CPU_MC_FAIL_QU     VTSS_ENCODE_BITMASK(8,3)
#define  VTSS_X_ANA_L3_COMMON_CPU_QU_CFG_CPU_MC_FAIL_QU(x)  VTSS_EXTRACT_BITFIELD(x,8,3)
#define  VTSS_F_ANA_L3_COMMON_CPU_QU_CFG_CPU_UC_FAIL_QU(x)  VTSS_ENCODE_BITFIELD(x,4,3)
#define  VTSS_M_ANA_L3_COMMON_CPU_QU_CFG_CPU_UC_FAIL_QU     VTSS_ENCODE_BITMASK(4,3)
#define  VTSS_X_ANA_L3_COMMON_CPU_QU_CFG_CPU_UC_FAIL_QU(x)  VTSS_EXTRACT_BITFIELD(x,4,3)
#define  VTSS_F_ANA_L3_COMMON_CPU_QU_CFG_CPU_IP_TTL_FAIL_QU(x)  VTSS_ENCODE_BITFIELD(x,0,3)
#define  VTSS_M_ANA_L3_COMMON_CPU_QU_CFG_CPU_IP_TTL_FAIL_QU     VTSS_ENCODE_BITMASK(0,3)
#define  VTSS_X_ANA_L3_COMMON_CPU_QU_CFG_CPU_IP_TTL_FAIL_QU(x)  VTSS_EXTRACT_BITFIELD(x,0,3)

#define VTSS_ANA_L3_COMMON_VRRP_IP4_CFG_0    VTSS_IOREG(VTSS_TO_ANA_L3,0xd51c)
#define  VTSS_F_ANA_L3_COMMON_VRRP_IP4_CFG_0_VRRP_IP4_BASE_MAC_MID(x)  VTSS_ENCODE_BITFIELD(x,8,24)
#define  VTSS_M_ANA_L3_COMMON_VRRP_IP4_CFG_0_VRRP_IP4_BASE_MAC_MID     VTSS_ENCODE_BITMASK(8,24)
#define  VTSS_X_ANA_L3_COMMON_VRRP_IP4_CFG_0_VRRP_IP4_BASE_MAC_MID(x)  VTSS_EXTRACT_BITFIELD(x,8,24)

#define VTSS_ANA_L3_COMMON_VRRP_IP4_CFG_1    VTSS_IOREG(VTSS_TO_ANA_L3,0xd51d)
#define  VTSS_F_ANA_L3_COMMON_VRRP_IP4_CFG_1_VRRP_IP4_BASE_MAC_HIGH(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_ANA_L3_COMMON_VRRP_IP4_CFG_1_VRRP_IP4_BASE_MAC_HIGH     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_ANA_L3_COMMON_VRRP_IP4_CFG_1_VRRP_IP4_BASE_MAC_HIGH(x)  VTSS_EXTRACT_BITFIELD(x,0,16)

#define VTSS_ANA_L3_COMMON_VRRP_IP6_CFG_0    VTSS_IOREG(VTSS_TO_ANA_L3,0xd51e)
#define  VTSS_F_ANA_L3_COMMON_VRRP_IP6_CFG_0_VRRP_IP6_BASE_MAC_MID(x)  VTSS_ENCODE_BITFIELD(x,0,24)
#define  VTSS_M_ANA_L3_COMMON_VRRP_IP6_CFG_0_VRRP_IP6_BASE_MAC_MID     VTSS_ENCODE_BITMASK(0,24)
#define  VTSS_X_ANA_L3_COMMON_VRRP_IP6_CFG_0_VRRP_IP6_BASE_MAC_MID(x)  VTSS_EXTRACT_BITFIELD(x,0,24)

#define VTSS_ANA_L3_COMMON_VRRP_IP6_CFG_1    VTSS_IOREG(VTSS_TO_ANA_L3,0xd51f)
#define  VTSS_F_ANA_L3_COMMON_VRRP_IP6_CFG_1_VRRP_IP6_BASE_MAC_HIGH(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_ANA_L3_COMMON_VRRP_IP6_CFG_1_VRRP_IP6_BASE_MAC_HIGH     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_ANA_L3_COMMON_VRRP_IP6_CFG_1_VRRP_IP6_BASE_MAC_HIGH(x)  VTSS_EXTRACT_BITFIELD(x,0,16)

#define VTSS_ANA_L3_COMMON_SIP_SECURE_ENA    VTSS_IOREG(VTSS_TO_ANA_L3,0xd520)

#define VTSS_ANA_L3_COMMON_SIP_SECURE_ENA1   VTSS_IOREG(VTSS_TO_ANA_L3,0xd521)
#define  VTSS_F_ANA_L3_COMMON_SIP_SECURE_ENA1_SIP_CMP_ENA1(x)  VTSS_ENCODE_BITFIELD(x,0,21)
#define  VTSS_M_ANA_L3_COMMON_SIP_SECURE_ENA1_SIP_CMP_ENA1     VTSS_ENCODE_BITMASK(0,21)
#define  VTSS_X_ANA_L3_COMMON_SIP_SECURE_ENA1_SIP_CMP_ENA1(x)  VTSS_EXTRACT_BITFIELD(x,0,21)

#define VTSS_ANA_L3_COMMON_DIP_SECURE_ENA    VTSS_IOREG(VTSS_TO_ANA_L3,0xd522)

#define VTSS_ANA_L3_COMMON_DIP_SECURE_ENA1   VTSS_IOREG(VTSS_TO_ANA_L3,0xd523)
#define  VTSS_F_ANA_L3_COMMON_DIP_SECURE_ENA1_DIP_CMP_ENA1(x)  VTSS_ENCODE_BITFIELD(x,0,21)
#define  VTSS_M_ANA_L3_COMMON_DIP_SECURE_ENA1_DIP_CMP_ENA1     VTSS_ENCODE_BITMASK(0,21)
#define  VTSS_X_ANA_L3_COMMON_DIP_SECURE_ENA1_DIP_CMP_ENA1(x)  VTSS_EXTRACT_BITFIELD(x,0,21)

#define VTSS_ANA_L3_COMMON_SIP_RPF_ENA       VTSS_IOREG(VTSS_TO_ANA_L3,0xd524)

#define VTSS_ANA_L3_COMMON_SIP_RPF_ENA1      VTSS_IOREG(VTSS_TO_ANA_L3,0xd525)
#define  VTSS_F_ANA_L3_COMMON_SIP_RPF_ENA1_SIP_RPF_ENA1(x)  VTSS_ENCODE_BITFIELD(x,0,21)
#define  VTSS_M_ANA_L3_COMMON_SIP_RPF_ENA1_SIP_RPF_ENA1     VTSS_ENCODE_BITMASK(0,21)
#define  VTSS_X_ANA_L3_COMMON_SIP_RPF_ENA1_SIP_RPF_ENA1(x)  VTSS_EXTRACT_BITFIELD(x,0,21)

#define VTSS_ANA_L3_COMMON_SERVICE_CFG       VTSS_IOREG(VTSS_TO_ANA_L3,0xd526)
#define  VTSS_F_ANA_L3_COMMON_SERVICE_CFG_VSI_FORCE_MC_EFID_ENA  VTSS_BIT(1)
#define  VTSS_F_ANA_L3_COMMON_SERVICE_CFG_ISDX_FORCE_MC_EFID_ENA  VTSS_BIT(0)

#define VTSS_ANA_L3_TUPE_TUPE_MISC           VTSS_IOREG(VTSS_TO_ANA_L3,0xd527)
#define  VTSS_F_ANA_L3_TUPE_TUPE_MISC_TUPE_START  VTSS_BIT(0)
#define  VTSS_F_ANA_L3_TUPE_TUPE_MISC_TUPE_CTRL_VAL_ENA  VTSS_BIT(1)
#define  VTSS_F_ANA_L3_TUPE_TUPE_MISC_TUPE_CTRL_BIT_ENA  VTSS_BIT(2)
#define  VTSS_F_ANA_L3_TUPE_TUPE_MISC_TUPE_PORT_MASK_A_ENA  VTSS_BIT(3)
#define  VTSS_F_ANA_L3_TUPE_TUPE_MISC_TUPE_PORT_MASK_B_ENA  VTSS_BIT(4)
#define  VTSS_F_ANA_L3_TUPE_TUPE_MISC_TUPE_COMB_MASK_ENA  VTSS_BIT(5)

#define VTSS_ANA_L3_TUPE_TUPE_ADDR           VTSS_IOREG(VTSS_TO_ANA_L3,0xd528)
#define  VTSS_F_ANA_L3_TUPE_TUPE_ADDR_TUPE_START_ADDR(x)  VTSS_ENCODE_BITFIELD(x,0,13)
#define  VTSS_M_ANA_L3_TUPE_TUPE_ADDR_TUPE_START_ADDR     VTSS_ENCODE_BITMASK(0,13)
#define  VTSS_X_ANA_L3_TUPE_TUPE_ADDR_TUPE_START_ADDR(x)  VTSS_EXTRACT_BITFIELD(x,0,13)
#define  VTSS_F_ANA_L3_TUPE_TUPE_ADDR_TUPE_END_ADDR(x)  VTSS_ENCODE_BITFIELD(x,16,13)
#define  VTSS_M_ANA_L3_TUPE_TUPE_ADDR_TUPE_END_ADDR     VTSS_ENCODE_BITMASK(16,13)
#define  VTSS_X_ANA_L3_TUPE_TUPE_ADDR_TUPE_END_ADDR(x)  VTSS_EXTRACT_BITFIELD(x,16,13)

#define VTSS_ANA_L3_TUPE_TUPE_CMD_PORT_MASK_CLR  VTSS_IOREG(VTSS_TO_ANA_L3,0xd529)

#define VTSS_ANA_L3_TUPE_TUPE_CMD_PORT_MASK_CLR1  VTSS_IOREG(VTSS_TO_ANA_L3,0xd52a)
#define  VTSS_F_ANA_L3_TUPE_TUPE_CMD_PORT_MASK_CLR1_TUPE_CMD_PORT_MASK_CLR1(x)  VTSS_ENCODE_BITFIELD(x,0,21)
#define  VTSS_M_ANA_L3_TUPE_TUPE_CMD_PORT_MASK_CLR1_TUPE_CMD_PORT_MASK_CLR1     VTSS_ENCODE_BITMASK(0,21)
#define  VTSS_X_ANA_L3_TUPE_TUPE_CMD_PORT_MASK_CLR1_TUPE_CMD_PORT_MASK_CLR1(x)  VTSS_EXTRACT_BITFIELD(x,0,21)

#define VTSS_ANA_L3_TUPE_TUPE_CMD_PORT_MASK_SET  VTSS_IOREG(VTSS_TO_ANA_L3,0xd52b)

#define VTSS_ANA_L3_TUPE_TUPE_CMD_PORT_MASK_SET1  VTSS_IOREG(VTSS_TO_ANA_L3,0xd52c)
#define  VTSS_F_ANA_L3_TUPE_TUPE_CMD_PORT_MASK_SET1_TUPE_CMD_PORT_MASK_SET1(x)  VTSS_ENCODE_BITFIELD(x,0,21)
#define  VTSS_M_ANA_L3_TUPE_TUPE_CMD_PORT_MASK_SET1_TUPE_CMD_PORT_MASK_SET1     VTSS_ENCODE_BITMASK(0,21)
#define  VTSS_X_ANA_L3_TUPE_TUPE_CMD_PORT_MASK_SET1_TUPE_CMD_PORT_MASK_SET1(x)  VTSS_EXTRACT_BITFIELD(x,0,21)

#define VTSS_ANA_L3_TUPE_TUPE_CTRL_VAL       VTSS_IOREG(VTSS_TO_ANA_L3,0xd52d)
#define  VTSS_F_ANA_L3_TUPE_TUPE_CTRL_VAL_TUPE_CTRL_VAL(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_ANA_L3_TUPE_TUPE_CTRL_VAL_TUPE_CTRL_VAL     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_ANA_L3_TUPE_TUPE_CTRL_VAL_TUPE_CTRL_VAL(x)  VTSS_EXTRACT_BITFIELD(x,0,16)

#define VTSS_ANA_L3_TUPE_TUPE_CTRL_VAL_MASK  VTSS_IOREG(VTSS_TO_ANA_L3,0xd52e)
#define  VTSS_F_ANA_L3_TUPE_TUPE_CTRL_VAL_MASK_TUPE_CTRL_VAL_MASK(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_ANA_L3_TUPE_TUPE_CTRL_VAL_MASK_TUPE_CTRL_VAL_MASK     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_ANA_L3_TUPE_TUPE_CTRL_VAL_MASK_TUPE_CTRL_VAL_MASK(x)  VTSS_EXTRACT_BITFIELD(x,0,16)

#define VTSS_ANA_L3_TUPE_TUPE_CTRL_BIT_MASK  VTSS_IOREG(VTSS_TO_ANA_L3,0xd52f)
#define  VTSS_F_ANA_L3_TUPE_TUPE_CTRL_BIT_MASK_TUPE_CTRL_BIT_MASK(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_ANA_L3_TUPE_TUPE_CTRL_BIT_MASK_TUPE_CTRL_BIT_MASK     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_ANA_L3_TUPE_TUPE_CTRL_BIT_MASK_TUPE_CTRL_BIT_MASK(x)  VTSS_EXTRACT_BITFIELD(x,0,16)

#define VTSS_ANA_L3_TUPE_TUPE_PORT_MASK_A    VTSS_IOREG(VTSS_TO_ANA_L3,0xd530)

#define VTSS_ANA_L3_TUPE_TUPE_PORT_MASK_A1   VTSS_IOREG(VTSS_TO_ANA_L3,0xd531)
#define  VTSS_F_ANA_L3_TUPE_TUPE_PORT_MASK_A1_TUPE_PORT_MASK_A1(x)  VTSS_ENCODE_BITFIELD(x,0,21)
#define  VTSS_M_ANA_L3_TUPE_TUPE_PORT_MASK_A1_TUPE_PORT_MASK_A1     VTSS_ENCODE_BITMASK(0,21)
#define  VTSS_X_ANA_L3_TUPE_TUPE_PORT_MASK_A1_TUPE_PORT_MASK_A1(x)  VTSS_EXTRACT_BITFIELD(x,0,21)

#define VTSS_ANA_L3_TUPE_TUPE_PORT_MASK_B    VTSS_IOREG(VTSS_TO_ANA_L3,0xd532)

#define VTSS_ANA_L3_TUPE_TUPE_PORT_MASK_B1   VTSS_IOREG(VTSS_TO_ANA_L3,0xd533)
#define  VTSS_F_ANA_L3_TUPE_TUPE_PORT_MASK_B1_TUPE_PORT_MASK_B1(x)  VTSS_ENCODE_BITFIELD(x,0,21)
#define  VTSS_M_ANA_L3_TUPE_TUPE_PORT_MASK_B1_TUPE_PORT_MASK_B1     VTSS_ENCODE_BITMASK(0,21)
#define  VTSS_X_ANA_L3_TUPE_TUPE_PORT_MASK_B1_TUPE_PORT_MASK_B1(x)  VTSS_EXTRACT_BITFIELD(x,0,21)

#define VTSS_ANA_L3_VLAN_VMID_CFG(gi)        VTSS_IOREG_IX(VTSS_TO_ANA_L3,0x0,gi,8,0,0)
#define  VTSS_F_ANA_L3_VLAN_VMID_CFG_VMID(x)  VTSS_ENCODE_BITFIELD(x,0,7)
#define  VTSS_M_ANA_L3_VLAN_VMID_CFG_VMID     VTSS_ENCODE_BITMASK(0,7)
#define  VTSS_X_ANA_L3_VLAN_VMID_CFG_VMID(x)  VTSS_EXTRACT_BITFIELD(x,0,7)

#define VTSS_ANA_L3_VLAN_VLAN_CFG(gi)        VTSS_IOREG_IX(VTSS_TO_ANA_L3,0x0,gi,8,0,1)
#define  VTSS_F_ANA_L3_VLAN_VLAN_CFG_VLAN_MSTP_PTR(x)  VTSS_ENCODE_BITFIELD(x,24,7)
#define  VTSS_M_ANA_L3_VLAN_VLAN_CFG_VLAN_MSTP_PTR     VTSS_ENCODE_BITMASK(24,7)
#define  VTSS_X_ANA_L3_VLAN_VLAN_CFG_VLAN_MSTP_PTR(x)  VTSS_EXTRACT_BITFIELD(x,24,7)
#define  VTSS_F_ANA_L3_VLAN_VLAN_CFG_VLAN_FID(x)  VTSS_ENCODE_BITFIELD(x,8,13)
#define  VTSS_M_ANA_L3_VLAN_VLAN_CFG_VLAN_FID     VTSS_ENCODE_BITMASK(8,13)
#define  VTSS_X_ANA_L3_VLAN_VLAN_CFG_VLAN_FID(x)  VTSS_EXTRACT_BITFIELD(x,8,13)
#define  VTSS_F_ANA_L3_VLAN_VLAN_CFG_VLAN_SEC_FWD_ENA  VTSS_BIT(5)
#define  VTSS_F_ANA_L3_VLAN_VLAN_CFG_VLAN_FLOOD_DIS  VTSS_BIT(4)
#define  VTSS_F_ANA_L3_VLAN_VLAN_CFG_VLAN_LRN_DIS  VTSS_BIT(3)
#define  VTSS_F_ANA_L3_VLAN_VLAN_CFG_VLAN_RLEG_ENA  VTSS_BIT(2)
#define  VTSS_F_ANA_L3_VLAN_VLAN_CFG_VLAN_PRIVATE_ENA  VTSS_BIT(1)
#define  VTSS_F_ANA_L3_VLAN_VLAN_CFG_VLAN_MIRROR_ENA  VTSS_BIT(0)

#define VTSS_ANA_L3_VLAN_TUPE_CTRL(gi)       VTSS_IOREG_IX(VTSS_TO_ANA_L3,0x0,gi,8,0,2)
#define  VTSS_F_ANA_L3_VLAN_TUPE_CTRL_TUPE_CTRL(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_ANA_L3_VLAN_TUPE_CTRL_TUPE_CTRL     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_ANA_L3_VLAN_TUPE_CTRL_TUPE_CTRL(x)  VTSS_EXTRACT_BITFIELD(x,0,16)

#define VTSS_ANA_L3_VLAN_VLAN_MASK_CFG(gi)   VTSS_IOREG_IX(VTSS_TO_ANA_L3,0x0,gi,8,0,3)

#define VTSS_ANA_L3_VLAN_VLAN_MASK_CFG1(gi)  VTSS_IOREG_IX(VTSS_TO_ANA_L3,0x0,gi,8,0,4)
#define  VTSS_F_ANA_L3_VLAN_VLAN_MASK_CFG1_VLAN_PORT_MASK1(x)  VTSS_ENCODE_BITFIELD(x,0,21)
#define  VTSS_M_ANA_L3_VLAN_VLAN_MASK_CFG1_VLAN_PORT_MASK1     VTSS_ENCODE_BITMASK(0,21)
#define  VTSS_X_ANA_L3_VLAN_VLAN_MASK_CFG1_VLAN_PORT_MASK1(x)  VTSS_EXTRACT_BITFIELD(x,0,21)

#define VTSS_ANA_L3_MSTP_MSTP_FWD_CFG(gi)    VTSS_IOREG_IX(VTSS_TO_ANA_L3,0xd400,gi,4,0,0)

#define VTSS_ANA_L3_MSTP_MSTP_FWD_CFG1(gi)   VTSS_IOREG_IX(VTSS_TO_ANA_L3,0xd400,gi,4,0,1)
#define  VTSS_F_ANA_L3_MSTP_MSTP_FWD_CFG1_MSTP_FWD_MASK1(x)  VTSS_ENCODE_BITFIELD(x,0,21)
#define  VTSS_M_ANA_L3_MSTP_MSTP_FWD_CFG1_MSTP_FWD_MASK1     VTSS_ENCODE_BITMASK(0,21)
#define  VTSS_X_ANA_L3_MSTP_MSTP_FWD_CFG1_MSTP_FWD_MASK1(x)  VTSS_EXTRACT_BITFIELD(x,0,21)

#define VTSS_ANA_L3_MSTP_MSTP_LRN_CFG(gi)    VTSS_IOREG_IX(VTSS_TO_ANA_L3,0xd400,gi,4,0,2)

#define VTSS_ANA_L3_MSTP_MSTP_LRN_CFG1(gi)   VTSS_IOREG_IX(VTSS_TO_ANA_L3,0xd400,gi,4,0,3)
#define  VTSS_F_ANA_L3_MSTP_MSTP_LRN_CFG1_MSTP_LRN_MASK1(x)  VTSS_ENCODE_BITFIELD(x,0,21)
#define  VTSS_M_ANA_L3_MSTP_MSTP_LRN_CFG1_MSTP_LRN_MASK1     VTSS_ENCODE_BITMASK(0,21)
#define  VTSS_X_ANA_L3_MSTP_MSTP_LRN_CFG1_MSTP_LRN_MASK1(x)  VTSS_EXTRACT_BITFIELD(x,0,21)

#define VTSS_ANA_L3_VMID_RLEG_CTRL(gi)       VTSS_IOREG_IX(VTSS_TO_ANA_L3,0xd000,gi,8,0,0)
#define  VTSS_F_ANA_L3_VMID_RLEG_CTRL_RLEG_EVID(x)  VTSS_ENCODE_BITFIELD(x,16,12)
#define  VTSS_M_ANA_L3_VMID_RLEG_CTRL_RLEG_EVID     VTSS_ENCODE_BITMASK(16,12)
#define  VTSS_X_ANA_L3_VMID_RLEG_CTRL_RLEG_EVID(x)  VTSS_EXTRACT_BITFIELD(x,16,12)
#define  VTSS_F_ANA_L3_VMID_RLEG_CTRL_RLEG_IP6_SIP_RPF_MODE(x)  VTSS_ENCODE_BITFIELD(x,10,2)
#define  VTSS_M_ANA_L3_VMID_RLEG_CTRL_RLEG_IP6_SIP_RPF_MODE     VTSS_ENCODE_BITMASK(10,2)
#define  VTSS_X_ANA_L3_VMID_RLEG_CTRL_RLEG_IP6_SIP_RPF_MODE(x)  VTSS_EXTRACT_BITFIELD(x,10,2)
#define  VTSS_F_ANA_L3_VMID_RLEG_CTRL_RLEG_IP4_SIP_RPF_MODE(x)  VTSS_ENCODE_BITFIELD(x,8,2)
#define  VTSS_M_ANA_L3_VMID_RLEG_CTRL_RLEG_IP4_SIP_RPF_MODE     VTSS_ENCODE_BITMASK(8,2)
#define  VTSS_X_ANA_L3_VMID_RLEG_CTRL_RLEG_IP4_SIP_RPF_MODE(x)  VTSS_EXTRACT_BITFIELD(x,8,2)
#define  VTSS_F_ANA_L3_VMID_RLEG_CTRL_RLEG_IP6_UC_ENA  VTSS_BIT(7)
#define  VTSS_F_ANA_L3_VMID_RLEG_CTRL_RLEG_IP4_UC_ENA  VTSS_BIT(6)
#define  VTSS_F_ANA_L3_VMID_RLEG_CTRL_RLEG_IP6_MC_ENA  VTSS_BIT(5)
#define  VTSS_F_ANA_L3_VMID_RLEG_CTRL_RLEG_IP4_MC_ENA  VTSS_BIT(4)
#define  VTSS_F_ANA_L3_VMID_RLEG_CTRL_RLEG_IP6_ICMP_REDIR_ENA  VTSS_BIT(3)
#define  VTSS_F_ANA_L3_VMID_RLEG_CTRL_RLEG_IP4_ICMP_REDIR_ENA  VTSS_BIT(2)
#define  VTSS_F_ANA_L3_VMID_RLEG_CTRL_RLEG_IP6_VRID_ENA  VTSS_BIT(1)
#define  VTSS_F_ANA_L3_VMID_RLEG_CTRL_RLEG_IP4_VRID_ENA  VTSS_BIT(0)

#define VTSS_ANA_L3_VMID_VRRP_CFG(gi,ri)     VTSS_IOREG_IX(VTSS_TO_ANA_L3,0xd000,gi,8,ri,1)
#define  VTSS_F_ANA_L3_VMID_VRRP_CFG_RLEG_IP4_VRID(x)  VTSS_ENCODE_BITFIELD(x,0,8)
#define  VTSS_M_ANA_L3_VMID_VRRP_CFG_RLEG_IP4_VRID     VTSS_ENCODE_BITMASK(0,8)
#define  VTSS_X_ANA_L3_VMID_VRRP_CFG_RLEG_IP4_VRID(x)  VTSS_EXTRACT_BITFIELD(x,0,8)
#define  VTSS_F_ANA_L3_VMID_VRRP_CFG_RLEG_IP6_VRID(x)  VTSS_ENCODE_BITFIELD(x,8,8)
#define  VTSS_M_ANA_L3_VMID_VRRP_CFG_RLEG_IP6_VRID     VTSS_ENCODE_BITMASK(8,8)
#define  VTSS_X_ANA_L3_VMID_VRRP_CFG_RLEG_IP6_VRID(x)  VTSS_EXTRACT_BITFIELD(x,8,8)

#define VTSS_ANA_L3_VMID_VMID_MC(gi)         VTSS_IOREG_IX(VTSS_TO_ANA_L3,0xd000,gi,8,0,3)
#define  VTSS_F_ANA_L3_VMID_VMID_MC_RLEG_IP6_MC_DMAC_CHK_ENA  VTSS_BIT(17)
#define  VTSS_F_ANA_L3_VMID_VMID_MC_RLEG_IP4_MC_DMAC_CHK_ENA  VTSS_BIT(16)
#define  VTSS_F_ANA_L3_VMID_VMID_MC_RLEG_IP4_MC_TTL(x)  VTSS_ENCODE_BITFIELD(x,0,8)
#define  VTSS_M_ANA_L3_VMID_VMID_MC_RLEG_IP4_MC_TTL     VTSS_ENCODE_BITMASK(0,8)
#define  VTSS_X_ANA_L3_VMID_VMID_MC_RLEG_IP4_MC_TTL(x)  VTSS_EXTRACT_BITFIELD(x,0,8)
#define  VTSS_F_ANA_L3_VMID_VMID_MC_RLEG_IP6_MC_TTL(x)  VTSS_ENCODE_BITFIELD(x,8,8)
#define  VTSS_M_ANA_L3_VMID_VMID_MC_RLEG_IP6_MC_TTL     VTSS_ENCODE_BITMASK(8,8)
#define  VTSS_X_ANA_L3_VMID_VMID_MC_RLEG_IP6_MC_TTL(x)  VTSS_EXTRACT_BITFIELD(x,8,8)

#define VTSS_ANA_L3_VMID_SIP_RPF(gi)         VTSS_IOREG_IX(VTSS_TO_ANA_L3,0xd000,gi,8,0,4)
#define  VTSS_F_ANA_L3_VMID_SIP_RPF_RLEG_RGID_MASK(x)  VTSS_ENCODE_BITFIELD(x,0,8)
#define  VTSS_M_ANA_L3_VMID_SIP_RPF_RLEG_RGID_MASK     VTSS_ENCODE_BITMASK(0,8)
#define  VTSS_X_ANA_L3_VMID_SIP_RPF_RLEG_RGID_MASK(x)  VTSS_EXTRACT_BITFIELD(x,0,8)

#define VTSS_ANA_L3_VMID_MAX_LEN(gi)         VTSS_IOREG_IX(VTSS_TO_ANA_L3,0xd000,gi,8,0,5)
#define  VTSS_F_ANA_L3_VMID_MAX_LEN_IP6_MAX_LEN(x)  VTSS_ENCODE_BITFIELD(x,16,16)
#define  VTSS_M_ANA_L3_VMID_MAX_LEN_IP6_MAX_LEN     VTSS_ENCODE_BITMASK(16,16)
#define  VTSS_X_ANA_L3_VMID_MAX_LEN_IP6_MAX_LEN(x)  VTSS_EXTRACT_BITFIELD(x,16,16)
#define  VTSS_F_ANA_L3_VMID_MAX_LEN_IP4_MAX_LEN(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_ANA_L3_VMID_MAX_LEN_IP4_MAX_LEN     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_ANA_L3_VMID_MAX_LEN_IP4_MAX_LEN(x)  VTSS_EXTRACT_BITFIELD(x,0,16)

#define VTSS_ANA_L3_ARP_ARP_CFG_0(gi)        VTSS_IOREG_IX(VTSS_TO_ANA_L3,0xc000,gi,2,0,0)
#define  VTSS_F_ANA_L3_ARP_ARP_CFG_0_MAC_MSB(x)  VTSS_ENCODE_BITFIELD(x,16,16)
#define  VTSS_M_ANA_L3_ARP_ARP_CFG_0_MAC_MSB     VTSS_ENCODE_BITMASK(16,16)
#define  VTSS_X_ANA_L3_ARP_ARP_CFG_0_MAC_MSB(x)  VTSS_EXTRACT_BITFIELD(x,16,16)
#define  VTSS_F_ANA_L3_ARP_ARP_CFG_0_ARP_VMID(x)  VTSS_ENCODE_BITFIELD(x,8,7)
#define  VTSS_M_ANA_L3_ARP_ARP_CFG_0_ARP_VMID     VTSS_ENCODE_BITMASK(8,7)
#define  VTSS_X_ANA_L3_ARP_ARP_CFG_0_ARP_VMID(x)  VTSS_EXTRACT_BITFIELD(x,8,7)
#define  VTSS_F_ANA_L3_ARP_ARP_CFG_0_ZERO_DMAC_CPU_QU(x)  VTSS_ENCODE_BITFIELD(x,4,3)
#define  VTSS_M_ANA_L3_ARP_ARP_CFG_0_ZERO_DMAC_CPU_QU     VTSS_ENCODE_BITMASK(4,3)
#define  VTSS_X_ANA_L3_ARP_ARP_CFG_0_ZERO_DMAC_CPU_QU(x)  VTSS_EXTRACT_BITFIELD(x,4,3)
#define  VTSS_F_ANA_L3_ARP_ARP_CFG_0_SIP_RPF_ENA  VTSS_BIT(3)
#define  VTSS_F_ANA_L3_ARP_ARP_CFG_0_SECUR_MATCH_VMID_ENA  VTSS_BIT(2)
#define  VTSS_F_ANA_L3_ARP_ARP_CFG_0_SECUR_MATCH_MAC_ENA  VTSS_BIT(1)
#define  VTSS_F_ANA_L3_ARP_ARP_CFG_0_ARP_ENA  VTSS_BIT(0)

#define VTSS_ANA_L3_ARP_ARP_CFG_1(gi)        VTSS_IOREG_IX(VTSS_TO_ANA_L3,0xc000,gi,2,0,1)

#define VTSS_ANA_L3_L3MC_EVMID_MASK_CFG(gi,ri)  VTSS_IOREG_IX(VTSS_TO_ANA_L3,0xa000,gi,8,ri,0)

#define VTSS_ANA_L3_L3MC_L3MC_CTRL(gi)       VTSS_IOREG_IX(VTSS_TO_ANA_L3,0xa000,gi,8,0,4)
#define  VTSS_F_ANA_L3_L3MC_L3MC_CTRL_RPF_VMID(x)  VTSS_ENCODE_BITFIELD(x,8,7)
#define  VTSS_M_ANA_L3_L3MC_L3MC_CTRL_RPF_VMID     VTSS_ENCODE_BITMASK(8,7)
#define  VTSS_X_ANA_L3_L3MC_L3MC_CTRL_RPF_VMID(x)  VTSS_EXTRACT_BITFIELD(x,8,7)
#define  VTSS_F_ANA_L3_L3MC_L3MC_CTRL_CPU_QU(x)  VTSS_ENCODE_BITFIELD(x,4,3)
#define  VTSS_M_ANA_L3_L3MC_L3MC_CTRL_CPU_QU     VTSS_ENCODE_BITMASK(4,3)
#define  VTSS_X_ANA_L3_L3MC_L3MC_CTRL_CPU_QU(x)  VTSS_EXTRACT_BITFIELD(x,4,3)
#define  VTSS_F_ANA_L3_L3MC_L3MC_CTRL_CPU_REDIR_MODE(x)  VTSS_ENCODE_BITFIELD(x,2,2)
#define  VTSS_M_ANA_L3_L3MC_L3MC_CTRL_CPU_REDIR_MODE     VTSS_ENCODE_BITMASK(2,2)
#define  VTSS_X_ANA_L3_L3MC_L3MC_CTRL_CPU_REDIR_MODE(x)  VTSS_EXTRACT_BITFIELD(x,2,2)
#define  VTSS_F_ANA_L3_L3MC_L3MC_CTRL_RPF_CHK_ENA  VTSS_BIT(1)
#define  VTSS_F_ANA_L3_L3MC_L3MC_CTRL_IPMC_TTL_COPY_ENA  VTSS_BIT(0)

#define VTSS_ANA_L3_LPM_REMAP_STICKY_L3_LPM_REMAP_STICKY  VTSS_IOREG(VTSS_TO_ANA_L3,0xd534)
#define  VTSS_F_ANA_L3_LPM_REMAP_STICKY_L3_LPM_REMAP_STICKY_SECUR_IP6_LPM_FOUND_STICKY  VTSS_BIT(5)
#define  VTSS_F_ANA_L3_LPM_REMAP_STICKY_L3_LPM_REMAP_STICKY_SECUR_IP4_LPM_FOUND_STICKY  VTSS_BIT(4)
#define  VTSS_F_ANA_L3_LPM_REMAP_STICKY_L3_LPM_REMAP_STICKY_LPM_IP6UC_FOUND_STICKY  VTSS_BIT(3)
#define  VTSS_F_ANA_L3_LPM_REMAP_STICKY_L3_LPM_REMAP_STICKY_LPM_IP4UC_FOUND_STICKY  VTSS_BIT(2)
#define  VTSS_F_ANA_L3_LPM_REMAP_STICKY_L3_LPM_REMAP_STICKY_LPM_IP6MC_FOUND_STICKY  VTSS_BIT(1)
#define  VTSS_F_ANA_L3_LPM_REMAP_STICKY_L3_LPM_REMAP_STICKY_LPM_IP4MC_FOUND_STICKY  VTSS_BIT(0)

#define VTSS_ANA_L3_VLAN_ARP_L3MC_STICKY_VLAN_STICKY  VTSS_IOREG(VTSS_TO_ANA_L3,0xd535)
#define  VTSS_F_ANA_L3_VLAN_ARP_L3MC_STICKY_VLAN_STICKY_PORT_LRN_DENY_STICKY  VTSS_BIT(16)
#define  VTSS_F_ANA_L3_VLAN_ARP_L3MC_STICKY_VLAN_STICKY_PORT_FWD_DENY_STICKY  VTSS_BIT(15)
#define  VTSS_F_ANA_L3_VLAN_ARP_L3MC_STICKY_VLAN_STICKY_MSTP_FWD_ALLOWED_STICKY  VTSS_BIT(6)
#define  VTSS_F_ANA_L3_VLAN_ARP_L3MC_STICKY_VLAN_STICKY_MSTP_DISCARD_STICKY  VTSS_BIT(5)
#define  VTSS_F_ANA_L3_VLAN_ARP_L3MC_STICKY_VLAN_STICKY_VLAN_LRN_DENY_STICKY  VTSS_BIT(4)
#define  VTSS_F_ANA_L3_VLAN_ARP_L3MC_STICKY_VLAN_STICKY_MSTP_LRN_DENY_STICKY  VTSS_BIT(3)
#define  VTSS_F_ANA_L3_VLAN_ARP_L3MC_STICKY_VLAN_STICKY_MSTP_LRN_ALLOWED_STICKY  VTSS_BIT(2)
#define  VTSS_F_ANA_L3_VLAN_ARP_L3MC_STICKY_VLAN_STICKY_VLAN_LOOKUP_INVLD_STICKY  VTSS_BIT(1)
#define  VTSS_F_ANA_L3_VLAN_ARP_L3MC_STICKY_VLAN_STICKY_VLAN_IGR_FILTER_STICKY  VTSS_BIT(0)

#define VTSS_ANA_L3_VLAN_ARP_L3MC_STICKY_L3_ARP_IPMC_STICKY  VTSS_IOREG(VTSS_TO_ANA_L3,0xd536)
#define  VTSS_F_ANA_L3_VLAN_ARP_L3MC_STICKY_L3_ARP_IPMC_STICKY_WRONG_SIP_LPM_ACTION_TYPE_STICKY  VTSS_BIT(29)
#define  VTSS_F_ANA_L3_VLAN_ARP_L3MC_STICKY_L3_ARP_IPMC_STICKY_WRONG_DIP_LPM_ACTION_TYPE_STICKY  VTSS_BIT(28)
#define  VTSS_F_ANA_L3_VLAN_ARP_L3MC_STICKY_L3_ARP_IPMC_STICKY_IP6_SIP_RPF_FILTER_STICKY  VTSS_BIT(27)
#define  VTSS_F_ANA_L3_VLAN_ARP_L3MC_STICKY_L3_ARP_IPMC_STICKY_IP4_SIP_RPF_FILTER_STICKY  VTSS_BIT(26)
#define  VTSS_F_ANA_L3_VLAN_ARP_L3MC_STICKY_L3_ARP_IPMC_STICKY_NO_MC_VMID_AVAIL_STICKY  VTSS_BIT(25)
#define  VTSS_F_ANA_L3_VLAN_ARP_L3MC_STICKY_L3_ARP_IPMC_STICKY_IP_MAX_LEN_EXCEEDED_STICKY  VTSS_BIT(24)
#define  VTSS_F_ANA_L3_VLAN_ARP_L3MC_STICKY_L3_ARP_IPMC_STICKY_ENTRY_NOT_FOUND_STICKY  VTSS_BIT(23)
#define  VTSS_F_ANA_L3_VLAN_ARP_L3MC_STICKY_L3_ARP_IPMC_STICKY_MC_LOOPED_CP_STICKY  VTSS_BIT(22)
#define  VTSS_F_ANA_L3_VLAN_ARP_L3MC_STICKY_L3_ARP_IPMC_STICKY_NO_MC_FWD_STICKY  VTSS_BIT(21)
#define  VTSS_F_ANA_L3_VLAN_ARP_L3MC_STICKY_L3_ARP_IPMC_STICKY_L3_MC_FWD_STICKY  VTSS_BIT(20)
#define  VTSS_F_ANA_L3_VLAN_ARP_L3MC_STICKY_L3_ARP_IPMC_STICKY_MC_RPF_FILTER_STICKY  VTSS_BIT(19)
#define  VTSS_F_ANA_L3_VLAN_ARP_L3MC_STICKY_L3_ARP_IPMC_STICKY_L2_MC_FWD_STICKY  VTSS_BIT(18)
#define  VTSS_F_ANA_L3_VLAN_ARP_L3MC_STICKY_L3_ARP_IPMC_STICKY_UC_ICMP_REDIR_STICKY  VTSS_BIT(17)
#define  VTSS_F_ANA_L3_VLAN_ARP_L3MC_STICKY_L3_ARP_IPMC_STICKY_UC_ZERO_DMAC_FOUND_STICKY  VTSS_BIT(16)
#define  VTSS_F_ANA_L3_VLAN_ARP_L3MC_STICKY_L3_ARP_IPMC_STICKY_UC_TTL_FILTERING_STICKY  VTSS_BIT(15)
#define  VTSS_F_ANA_L3_VLAN_ARP_L3MC_STICKY_L3_ARP_IPMC_STICKY_UC_ENTRY_FOUND_STICKY  VTSS_BIT(14)
#define  VTSS_F_ANA_L3_VLAN_ARP_L3MC_STICKY_L3_ARP_IPMC_STICKY_RLEG_MC_TTL_STICKY  VTSS_BIT(13)
#define  VTSS_F_ANA_L3_VLAN_ARP_L3MC_STICKY_L3_ARP_IPMC_STICKY_SECUR_IP4_SIP_MATCH_STICKY  VTSS_BIT(12)
#define  VTSS_F_ANA_L3_VLAN_ARP_L3MC_STICKY_L3_ARP_IPMC_STICKY_SECUR_IP6_DIP_MATCH_STICKY  VTSS_BIT(11)
#define  VTSS_F_ANA_L3_VLAN_ARP_L3MC_STICKY_L3_ARP_IPMC_STICKY_SECUR_IP4_DIP_MATCH_STICKY  VTSS_BIT(10)
#define  VTSS_F_ANA_L3_VLAN_ARP_L3MC_STICKY_L3_ARP_IPMC_STICKY_SECUR_IP6_SIP_MATCH_STICKY  VTSS_BIT(9)
#define  VTSS_F_ANA_L3_VLAN_ARP_L3MC_STICKY_L3_ARP_IPMC_STICKY_SECUR_DIP_FAIL_STICKY  VTSS_BIT(8)
#define  VTSS_F_ANA_L3_VLAN_ARP_L3MC_STICKY_L3_ARP_IPMC_STICKY_SECUR_SIP_FAIL_STICKY  VTSS_BIT(7)
#define  VTSS_F_ANA_L3_VLAN_ARP_L3MC_STICKY_L3_ARP_IPMC_STICKY_RLEG_MC_HIT_STICKY  VTSS_BIT(6)
#define  VTSS_F_ANA_L3_VLAN_ARP_L3MC_STICKY_L3_ARP_IPMC_STICKY_RLEG_UC_HIT_STICKY  VTSS_BIT(5)
#define  VTSS_F_ANA_L3_VLAN_ARP_L3MC_STICKY_L3_ARP_IPMC_STICKY_RLEG_MC_IP_OPT_REDIR_STICKY  VTSS_BIT(4)
#define  VTSS_F_ANA_L3_VLAN_ARP_L3MC_STICKY_L3_ARP_IPMC_STICKY_RLEG_UC_IP_OPT_REDIR_STICKY  VTSS_BIT(3)
#define  VTSS_F_ANA_L3_VLAN_ARP_L3MC_STICKY_L3_ARP_IPMC_STICKY_RLEG_MC_HDR_ERR_REDIR_STICKY  VTSS_BIT(2)
#define  VTSS_F_ANA_L3_VLAN_ARP_L3MC_STICKY_L3_ARP_IPMC_STICKY_RLEG_UC_HDR_ERR_REDIR_STICKY  VTSS_BIT(1)
#define  VTSS_F_ANA_L3_VLAN_ARP_L3MC_STICKY_L3_ARP_IPMC_STICKY_RLEG_NONIP_UC_REDIR_STICKY  VTSS_BIT(0)

#define VTSS_ANA_L3_L3_STICKY_MASK_RLEG_STICKY_MASK(gi)  VTSS_IOREG_IX(VTSS_TO_ANA_L3,0xd537,gi,4,0,0)
#define  VTSS_F_ANA_L3_L3_STICKY_MASK_RLEG_STICKY_MASK_RLEG_UC_IP_OPT_REDIR_STICKY_MASK  VTSS_BIT(7)
#define  VTSS_F_ANA_L3_L3_STICKY_MASK_RLEG_STICKY_MASK_RLEG_UC_HIT_STICKY_MASK  VTSS_BIT(6)
#define  VTSS_F_ANA_L3_L3_STICKY_MASK_RLEG_STICKY_MASK_RLEG_UC_HDR_ERR_REDIR_STICKY_MASK  VTSS_BIT(5)
#define  VTSS_F_ANA_L3_L3_STICKY_MASK_RLEG_STICKY_MASK_RLEG_MC_TTL_STICKY_MASK  VTSS_BIT(4)
#define  VTSS_F_ANA_L3_L3_STICKY_MASK_RLEG_STICKY_MASK_RLEG_MC_IP_OPT_REDIR_STICKY_MASK  VTSS_BIT(3)
#define  VTSS_F_ANA_L3_L3_STICKY_MASK_RLEG_STICKY_MASK_RLEG_MC_HIT_STICKY_MASK  VTSS_BIT(2)
#define  VTSS_F_ANA_L3_L3_STICKY_MASK_RLEG_STICKY_MASK_RLEG_MC_HDR_ERR_REDIR_STICKY_MASK  VTSS_BIT(1)
#define  VTSS_F_ANA_L3_L3_STICKY_MASK_RLEG_STICKY_MASK_RLEG_NONIP_UC_REDIR_STICKY_MASK  VTSS_BIT(0)

#define VTSS_ANA_L3_L3_STICKY_MASK_ROUT_STICKY_MASK(gi)  VTSS_IOREG_IX(VTSS_TO_ANA_L3,0xd537,gi,4,0,1)
#define  VTSS_F_ANA_L3_L3_STICKY_MASK_ROUT_STICKY_MASK_WRONG_SIP_LPM_ACTION_TYPE_STICKY_MASK  VTSS_BIT(19)
#define  VTSS_F_ANA_L3_L3_STICKY_MASK_ROUT_STICKY_MASK_WRONG_DIP_LPM_ACTION_TYPE_STICKY_MASK  VTSS_BIT(18)
#define  VTSS_F_ANA_L3_L3_STICKY_MASK_ROUT_STICKY_MASK_IP6_SIP_RPF_FILTER_STICKY_MASK  VTSS_BIT(17)
#define  VTSS_F_ANA_L3_L3_STICKY_MASK_ROUT_STICKY_MASK_IP4_SIP_RPF_FILTER_STICKY_MASK  VTSS_BIT(16)
#define  VTSS_F_ANA_L3_L3_STICKY_MASK_ROUT_STICKY_MASK_NO_MC_VMID_AVAIL_STICKY_MASK  VTSS_BIT(15)
#define  VTSS_F_ANA_L3_L3_STICKY_MASK_ROUT_STICKY_MASK_ENTRY_NOT_FOUND_STICKY_MASK  VTSS_BIT(14)
#define  VTSS_F_ANA_L3_L3_STICKY_MASK_ROUT_STICKY_MASK_MC_LOOPED_CP_STICKY_MASK  VTSS_BIT(13)
#define  VTSS_F_ANA_L3_L3_STICKY_MASK_ROUT_STICKY_MASK_UC_ZERO_DMAC_FOUND_STICKY_MASK  VTSS_BIT(12)
#define  VTSS_F_ANA_L3_L3_STICKY_MASK_ROUT_STICKY_MASK_UC_TTL_FILTERING_STICKY_MASK  VTSS_BIT(11)
#define  VTSS_F_ANA_L3_L3_STICKY_MASK_ROUT_STICKY_MASK_UC_ICMP_REDIR_STICKY_MASK  VTSS_BIT(10)
#define  VTSS_F_ANA_L3_L3_STICKY_MASK_ROUT_STICKY_MASK_UC_ENTRY_FOUND_STICKY_MASK  VTSS_BIT(9)
#define  VTSS_F_ANA_L3_L3_STICKY_MASK_ROUT_STICKY_MASK_NO_MC_FWD_STICKY_MASK  VTSS_BIT(8)
#define  VTSS_F_ANA_L3_L3_STICKY_MASK_ROUT_STICKY_MASK_L3_MC_FWD_STICKY_MASK  VTSS_BIT(7)
#define  VTSS_F_ANA_L3_L3_STICKY_MASK_ROUT_STICKY_MASK_MC_RPF_FILTER_STICKY_MASK  VTSS_BIT(6)
#define  VTSS_F_ANA_L3_L3_STICKY_MASK_ROUT_STICKY_MASK_L2_MC_FWD_STICKY_MASK  VTSS_BIT(5)
#define  VTSS_F_ANA_L3_L3_STICKY_MASK_ROUT_STICKY_MASK_IP_MAX_LEN_EXCEEDED_STICKY_MASK  VTSS_BIT(4)
#define  VTSS_F_ANA_L3_L3_STICKY_MASK_ROUT_STICKY_MASK_LPM_IP6UC_FOUND_STICKY_MASK  VTSS_BIT(3)
#define  VTSS_F_ANA_L3_L3_STICKY_MASK_ROUT_STICKY_MASK_LPM_IP4UC_FOUND_STICKY_MASK  VTSS_BIT(2)
#define  VTSS_F_ANA_L3_L3_STICKY_MASK_ROUT_STICKY_MASK_LPM_IP6MC_FOUND_STICKY_MASK  VTSS_BIT(1)
#define  VTSS_F_ANA_L3_L3_STICKY_MASK_ROUT_STICKY_MASK_LPM_IP4MC_FOUND_STICKY_MASK  VTSS_BIT(0)

#define VTSS_ANA_L3_L3_STICKY_MASK_SECUR_STICKY_MASK(gi)  VTSS_IOREG_IX(VTSS_TO_ANA_L3,0xd537,gi,4,0,2)
#define  VTSS_F_ANA_L3_L3_STICKY_MASK_SECUR_STICKY_MASK_SECUR_IP6_DIP_MATCH_STICKY_MASK  VTSS_BIT(7)
#define  VTSS_F_ANA_L3_L3_STICKY_MASK_SECUR_STICKY_MASK_SECUR_IP4_SIP_MATCH_STICKY_MASK  VTSS_BIT(6)
#define  VTSS_F_ANA_L3_L3_STICKY_MASK_SECUR_STICKY_MASK_SECUR_SIP_FAIL_STICKY_MASK  VTSS_BIT(5)
#define  VTSS_F_ANA_L3_L3_STICKY_MASK_SECUR_STICKY_MASK_SECUR_IP6_SIP_MATCH_STICKY_MASK  VTSS_BIT(4)
#define  VTSS_F_ANA_L3_L3_STICKY_MASK_SECUR_STICKY_MASK_SECUR_IP6_LPM_FOUND_STICKY_MASK  VTSS_BIT(3)
#define  VTSS_F_ANA_L3_L3_STICKY_MASK_SECUR_STICKY_MASK_SECUR_IP4_DIP_MATCH_STICKY_MASK  VTSS_BIT(2)
#define  VTSS_F_ANA_L3_L3_STICKY_MASK_SECUR_STICKY_MASK_SECUR_IP4_LPM_FOUND_STICKY_MASK  VTSS_BIT(1)
#define  VTSS_F_ANA_L3_L3_STICKY_MASK_SECUR_STICKY_MASK_SECUR_DIP_FAIL_STICKY_MASK  VTSS_BIT(0)

#define VTSS_ANA_L3_L3_STICKY_MASK_VLAN_MSTP_STICKY_MASK(gi)  VTSS_IOREG_IX(VTSS_TO_ANA_L3,0xd537,gi,4,0,3)
#define  VTSS_F_ANA_L3_L3_STICKY_MASK_VLAN_MSTP_STICKY_MASK_PORT_LRN_DENY_STICKY_MASK  VTSS_BIT(16)
#define  VTSS_F_ANA_L3_L3_STICKY_MASK_VLAN_MSTP_STICKY_MASK_PORT_FWD_DENY_STICKY_MASK  VTSS_BIT(15)
#define  VTSS_F_ANA_L3_L3_STICKY_MASK_VLAN_MSTP_STICKY_MASK_MSTP_FWD_ALLOWED_STICKY_MASK  VTSS_BIT(6)
#define  VTSS_F_ANA_L3_L3_STICKY_MASK_VLAN_MSTP_STICKY_MASK_MSTP_DISCARD_STICKY_MASK  VTSS_BIT(5)
#define  VTSS_F_ANA_L3_L3_STICKY_MASK_VLAN_MSTP_STICKY_MASK_VLAN_LRN_DENY_STICKY_MASK  VTSS_BIT(4)
#define  VTSS_F_ANA_L3_L3_STICKY_MASK_VLAN_MSTP_STICKY_MASK_MSTP_LRN_DENY_STICKY_MASK  VTSS_BIT(3)
#define  VTSS_F_ANA_L3_L3_STICKY_MASK_VLAN_MSTP_STICKY_MASK_MSTP_LRN_ALLOWED_STICKY_MASK  VTSS_BIT(2)
#define  VTSS_F_ANA_L3_L3_STICKY_MASK_VLAN_MSTP_STICKY_MASK_VLAN_LOOKUP_INVLD_STICKY_MASK  VTSS_BIT(1)
#define  VTSS_F_ANA_L3_L3_STICKY_MASK_VLAN_MSTP_STICKY_MASK_VLAN_IGR_FILTER_STICKY_MASK  VTSS_BIT(0)


#endif /* _VTSS_JAGUAR2_REGS_ANA_L3_H_ */
