#ifndef _VTSS_JAGUAR2_REGS_DEVCPU_GCB_H_
#define _VTSS_JAGUAR2_REGS_DEVCPU_GCB_H_

/*
 *
 * VCore-III Register Definitions
 *
 * Copyright (C) 2012 Vitesse Semiconductor Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#include "vtss_jaguar2_regs_common.h"

#define VTSS_DEVCPU_GCB_CHIP_REGS_CHIP_ID    VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0x0)
#define  VTSS_F_DEVCPU_GCB_CHIP_REGS_CHIP_ID_REV_ID(x)  VTSS_ENCODE_BITFIELD(x,28,4)
#define  VTSS_M_DEVCPU_GCB_CHIP_REGS_CHIP_ID_REV_ID     VTSS_ENCODE_BITMASK(28,4)
#define  VTSS_X_DEVCPU_GCB_CHIP_REGS_CHIP_ID_REV_ID(x)  VTSS_EXTRACT_BITFIELD(x,28,4)
#define  VTSS_F_DEVCPU_GCB_CHIP_REGS_CHIP_ID_PART_ID(x)  VTSS_ENCODE_BITFIELD(x,12,16)
#define  VTSS_M_DEVCPU_GCB_CHIP_REGS_CHIP_ID_PART_ID     VTSS_ENCODE_BITMASK(12,16)
#define  VTSS_X_DEVCPU_GCB_CHIP_REGS_CHIP_ID_PART_ID(x)  VTSS_EXTRACT_BITFIELD(x,12,16)
#define  VTSS_F_DEVCPU_GCB_CHIP_REGS_CHIP_ID_MFG_ID(x)  VTSS_ENCODE_BITFIELD(x,1,11)
#define  VTSS_M_DEVCPU_GCB_CHIP_REGS_CHIP_ID_MFG_ID     VTSS_ENCODE_BITMASK(1,11)
#define  VTSS_X_DEVCPU_GCB_CHIP_REGS_CHIP_ID_MFG_ID(x)  VTSS_EXTRACT_BITFIELD(x,1,11)
#define  VTSS_F_DEVCPU_GCB_CHIP_REGS_CHIP_ID_ONE  VTSS_BIT(0)

#define VTSS_DEVCPU_GCB_CHIP_REGS_GPR        VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0x1)

#define VTSS_DEVCPU_GCB_CHIP_REGS_SOFT_RST   VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0x2)
#define  VTSS_F_DEVCPU_GCB_CHIP_REGS_SOFT_RST_SOFT_NON_CFG_RST  VTSS_BIT(2)
#define  VTSS_F_DEVCPU_GCB_CHIP_REGS_SOFT_RST_SOFT_SWC_RST  VTSS_BIT(1)
#define  VTSS_F_DEVCPU_GCB_CHIP_REGS_SOFT_RST_SOFT_CHIP_RST  VTSS_BIT(0)

#define VTSS_DEVCPU_GCB_CHIP_REGS_HW_CFG     VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0x3)
#define  VTSS_F_DEVCPU_GCB_CHIP_REGS_HW_CFG_DFT_STAT_ENA  VTSS_BIT(1)
#define  VTSS_F_DEVCPU_GCB_CHIP_REGS_HW_CFG_DFT_CLK_MON_ENA  VTSS_BIT(0)

#define VTSS_DEVCPU_GCB_CHIP_REGS_HW_STAT    VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0x4)
#define  VTSS_F_DEVCPU_GCB_CHIP_REGS_HW_STAT_MEM_FAIL  VTSS_BIT(0)

#define VTSS_DEVCPU_GCB_CHIP_REGS_HW_SGPIO_SD_CFG  VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0x5)
#define  VTSS_F_DEVCPU_GCB_CHIP_REGS_HW_SGPIO_SD_CFG_SD_HIGH_ENA(x)  VTSS_ENCODE_BITFIELD(x,0,29)
#define  VTSS_M_DEVCPU_GCB_CHIP_REGS_HW_SGPIO_SD_CFG_SD_HIGH_ENA     VTSS_ENCODE_BITMASK(0,29)
#define  VTSS_X_DEVCPU_GCB_CHIP_REGS_HW_SGPIO_SD_CFG_SD_HIGH_ENA(x)  VTSS_EXTRACT_BITFIELD(x,0,29)

#define VTSS_DEVCPU_GCB_CHIP_REGS_FEA_STAT   VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0x6)

#define VTSS_DEVCPU_GCB_CHIP_REGS_FEA_DIS    VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0x7)

#define VTSS_DEVCPU_GCB_SW_REGS_SW_INTR      VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0x8)
#define  VTSS_F_DEVCPU_GCB_SW_REGS_SW_INTR_SW1_INTR  VTSS_BIT(1)
#define  VTSS_F_DEVCPU_GCB_SW_REGS_SW_INTR_SW0_INTR  VTSS_BIT(0)

#define VTSS_DEVCPU_GCB_VCORE_ACCESS_VA_CTRL  VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0x9)
#define  VTSS_F_DEVCPU_GCB_VCORE_ACCESS_VA_CTRL_VA_SIZE(x)  VTSS_ENCODE_BITFIELD(x,4,2)
#define  VTSS_M_DEVCPU_GCB_VCORE_ACCESS_VA_CTRL_VA_SIZE     VTSS_ENCODE_BITMASK(4,2)
#define  VTSS_X_DEVCPU_GCB_VCORE_ACCESS_VA_CTRL_VA_SIZE(x)  VTSS_EXTRACT_BITFIELD(x,4,2)
#define  VTSS_F_DEVCPU_GCB_VCORE_ACCESS_VA_CTRL_VA_ERR(x)  VTSS_ENCODE_BITFIELD(x,2,2)
#define  VTSS_M_DEVCPU_GCB_VCORE_ACCESS_VA_CTRL_VA_ERR     VTSS_ENCODE_BITMASK(2,2)
#define  VTSS_X_DEVCPU_GCB_VCORE_ACCESS_VA_CTRL_VA_ERR(x)  VTSS_EXTRACT_BITFIELD(x,2,2)
#define  VTSS_F_DEVCPU_GCB_VCORE_ACCESS_VA_CTRL_VA_BUSY_RD  VTSS_BIT(1)
#define  VTSS_F_DEVCPU_GCB_VCORE_ACCESS_VA_CTRL_VA_BUSY  VTSS_BIT(0)

#define VTSS_DEVCPU_GCB_VCORE_ACCESS_VA_ADDR  VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0xa)

#define VTSS_DEVCPU_GCB_VCORE_ACCESS_VA_DATA  VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0xb)

#define VTSS_DEVCPU_GCB_VCORE_ACCESS_VA_DATA_INCR  VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0xc)

#define VTSS_DEVCPU_GCB_VCORE_ACCESS_VA_DATA_INERT  VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0xd)

#define VTSS_DEVCPU_GCB_GPIO_GPIO_OUT_SET    VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0xe)

#define VTSS_DEVCPU_GCB_GPIO_GPIO_OUT_SET1   VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0xf)

#define VTSS_DEVCPU_GCB_GPIO_GPIO_OUT_CLR    VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0x10)

#define VTSS_DEVCPU_GCB_GPIO_GPIO_OUT_CLR1   VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0x11)

#define VTSS_DEVCPU_GCB_GPIO_GPIO_OUT        VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0x12)

#define VTSS_DEVCPU_GCB_GPIO_GPIO_OUT1       VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0x13)

#define VTSS_DEVCPU_GCB_GPIO_GPIO_IN         VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0x14)

#define VTSS_DEVCPU_GCB_GPIO_GPIO_IN1        VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0x15)

#define VTSS_DEVCPU_GCB_GPIO_GPIO_OE         VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0x16)

#define VTSS_DEVCPU_GCB_GPIO_GPIO_OE1        VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0x17)

#define VTSS_DEVCPU_GCB_GPIO_GPIO_INTR       VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0x18)

#define VTSS_DEVCPU_GCB_GPIO_GPIO_INTR1      VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0x19)

#define VTSS_DEVCPU_GCB_GPIO_GPIO_INTR_ENA   VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0x1a)

#define VTSS_DEVCPU_GCB_GPIO_GPIO_INTR_ENA1  VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0x1b)

#define VTSS_DEVCPU_GCB_GPIO_GPIO_INTR_IDENT  VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0x1c)

#define VTSS_DEVCPU_GCB_GPIO_GPIO_INTR_IDENT1  VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0x1d)

#define VTSS_DEVCPU_GCB_GPIO_GPIO_ALT(ri)    VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0x1e + (ri))

#define VTSS_DEVCPU_GCB_GPIO_GPIO_ALT1(ri)   VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0x20 + (ri))

#define VTSS_DEVCPU_GCB_GPIO_GPIO_SD_MAP(ri)  VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0x22 + (ri))
#define  VTSS_F_DEVCPU_GCB_GPIO_GPIO_SD_MAP_G_SD_MAP(x)  VTSS_ENCODE_BITFIELD(x,0,6)
#define  VTSS_M_DEVCPU_GCB_GPIO_GPIO_SD_MAP_G_SD_MAP     VTSS_ENCODE_BITMASK(0,6)
#define  VTSS_X_DEVCPU_GCB_GPIO_GPIO_SD_MAP_G_SD_MAP(x)  VTSS_EXTRACT_BITFIELD(x,0,6)

#define VTSS_DEVCPU_GCB_MIIM_MII_STATUS(gi)  VTSS_IOREG_IX(VTSS_TO_DEVCPU_GCB,0x32,gi,9,0,0)
#define  VTSS_F_DEVCPU_GCB_MIIM_MII_STATUS_MIIM_STAT_BUSY  VTSS_BIT(3)
#define  VTSS_F_DEVCPU_GCB_MIIM_MII_STATUS_MIIM_STAT_OPR_PEND  VTSS_BIT(2)
#define  VTSS_F_DEVCPU_GCB_MIIM_MII_STATUS_MIIM_STAT_PENDING_RD  VTSS_BIT(1)
#define  VTSS_F_DEVCPU_GCB_MIIM_MII_STATUS_MIIM_STAT_PENDING_WR  VTSS_BIT(0)
#define  VTSS_F_DEVCPU_GCB_MIIM_MII_STATUS_MIIM_SCAN_COMPLETE  VTSS_BIT(4)

#define VTSS_DEVCPU_GCB_MIIM_MII_CFG_7226(gi)  VTSS_IOREG_IX(VTSS_TO_DEVCPU_GCB,0x32,gi,9,0,1)
#define  VTSS_F_DEVCPU_GCB_MIIM_MII_CFG_7226_MIIM_7226_CFG_FIELD  VTSS_BIT(9)

#define VTSS_DEVCPU_GCB_MIIM_MII_CMD(gi)     VTSS_IOREG_IX(VTSS_TO_DEVCPU_GCB,0x32,gi,9,0,2)
#define  VTSS_F_DEVCPU_GCB_MIIM_MII_CMD_MIIM_CMD_VLD  VTSS_BIT(31)
#define  VTSS_F_DEVCPU_GCB_MIIM_MII_CMD_MIIM_CMD_PHYAD(x)  VTSS_ENCODE_BITFIELD(x,25,5)
#define  VTSS_M_DEVCPU_GCB_MIIM_MII_CMD_MIIM_CMD_PHYAD     VTSS_ENCODE_BITMASK(25,5)
#define  VTSS_X_DEVCPU_GCB_MIIM_MII_CMD_MIIM_CMD_PHYAD(x)  VTSS_EXTRACT_BITFIELD(x,25,5)
#define  VTSS_F_DEVCPU_GCB_MIIM_MII_CMD_MIIM_CMD_REGAD(x)  VTSS_ENCODE_BITFIELD(x,20,5)
#define  VTSS_M_DEVCPU_GCB_MIIM_MII_CMD_MIIM_CMD_REGAD     VTSS_ENCODE_BITMASK(20,5)
#define  VTSS_X_DEVCPU_GCB_MIIM_MII_CMD_MIIM_CMD_REGAD(x)  VTSS_EXTRACT_BITFIELD(x,20,5)
#define  VTSS_F_DEVCPU_GCB_MIIM_MII_CMD_MIIM_CMD_WRDATA(x)  VTSS_ENCODE_BITFIELD(x,4,16)
#define  VTSS_M_DEVCPU_GCB_MIIM_MII_CMD_MIIM_CMD_WRDATA     VTSS_ENCODE_BITMASK(4,16)
#define  VTSS_X_DEVCPU_GCB_MIIM_MII_CMD_MIIM_CMD_WRDATA(x)  VTSS_EXTRACT_BITFIELD(x,4,16)
#define  VTSS_F_DEVCPU_GCB_MIIM_MII_CMD_MIIM_CMD_SINGLE_SCAN  VTSS_BIT(3)
#define  VTSS_F_DEVCPU_GCB_MIIM_MII_CMD_MIIM_CMD_OPR_FIELD(x)  VTSS_ENCODE_BITFIELD(x,1,2)
#define  VTSS_M_DEVCPU_GCB_MIIM_MII_CMD_MIIM_CMD_OPR_FIELD     VTSS_ENCODE_BITMASK(1,2)
#define  VTSS_X_DEVCPU_GCB_MIIM_MII_CMD_MIIM_CMD_OPR_FIELD(x)  VTSS_EXTRACT_BITFIELD(x,1,2)
#define  VTSS_F_DEVCPU_GCB_MIIM_MII_CMD_MIIM_CMD_SCAN  VTSS_BIT(0)

#define VTSS_DEVCPU_GCB_MIIM_MII_DATA(gi)    VTSS_IOREG_IX(VTSS_TO_DEVCPU_GCB,0x32,gi,9,0,3)
#define  VTSS_F_DEVCPU_GCB_MIIM_MII_DATA_MIIM_DATA_SUCCESS(x)  VTSS_ENCODE_BITFIELD(x,16,2)
#define  VTSS_M_DEVCPU_GCB_MIIM_MII_DATA_MIIM_DATA_SUCCESS     VTSS_ENCODE_BITMASK(16,2)
#define  VTSS_X_DEVCPU_GCB_MIIM_MII_DATA_MIIM_DATA_SUCCESS(x)  VTSS_EXTRACT_BITFIELD(x,16,2)
#define  VTSS_F_DEVCPU_GCB_MIIM_MII_DATA_MIIM_DATA_RDDATA(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_DEVCPU_GCB_MIIM_MII_DATA_MIIM_DATA_RDDATA     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_DEVCPU_GCB_MIIM_MII_DATA_MIIM_DATA_RDDATA(x)  VTSS_EXTRACT_BITFIELD(x,0,16)

#define VTSS_DEVCPU_GCB_MIIM_MII_CFG(gi)     VTSS_IOREG_IX(VTSS_TO_DEVCPU_GCB,0x32,gi,9,0,4)
#define  VTSS_F_DEVCPU_GCB_MIIM_MII_CFG_DEADLOCK_FIX_DIS  VTSS_BIT(11)
#define  VTSS_F_DEVCPU_GCB_MIIM_MII_CFG_MIIM_CFG_PRESCALE(x)  VTSS_ENCODE_BITFIELD(x,0,8)
#define  VTSS_M_DEVCPU_GCB_MIIM_MII_CFG_MIIM_CFG_PRESCALE     VTSS_ENCODE_BITMASK(0,8)
#define  VTSS_X_DEVCPU_GCB_MIIM_MII_CFG_MIIM_CFG_PRESCALE(x)  VTSS_EXTRACT_BITFIELD(x,0,8)
#define  VTSS_F_DEVCPU_GCB_MIIM_MII_CFG_MIIM_ST_CFG_FIELD(x)  VTSS_ENCODE_BITFIELD(x,9,2)
#define  VTSS_M_DEVCPU_GCB_MIIM_MII_CFG_MIIM_ST_CFG_FIELD     VTSS_ENCODE_BITMASK(9,2)
#define  VTSS_X_DEVCPU_GCB_MIIM_MII_CFG_MIIM_ST_CFG_FIELD(x)  VTSS_EXTRACT_BITFIELD(x,9,2)
#define  VTSS_F_DEVCPU_GCB_MIIM_MII_CFG_MIIM_CFG_DBG  VTSS_BIT(8)

#define VTSS_DEVCPU_GCB_MIIM_MII_SCAN_0(gi)  VTSS_IOREG_IX(VTSS_TO_DEVCPU_GCB,0x32,gi,9,0,5)
#define  VTSS_F_DEVCPU_GCB_MIIM_MII_SCAN_0_MIIM_SCAN_PHYADHI(x)  VTSS_ENCODE_BITFIELD(x,5,5)
#define  VTSS_M_DEVCPU_GCB_MIIM_MII_SCAN_0_MIIM_SCAN_PHYADHI     VTSS_ENCODE_BITMASK(5,5)
#define  VTSS_X_DEVCPU_GCB_MIIM_MII_SCAN_0_MIIM_SCAN_PHYADHI(x)  VTSS_EXTRACT_BITFIELD(x,5,5)
#define  VTSS_F_DEVCPU_GCB_MIIM_MII_SCAN_0_MIIM_SCAN_PHYADLO(x)  VTSS_ENCODE_BITFIELD(x,0,5)
#define  VTSS_M_DEVCPU_GCB_MIIM_MII_SCAN_0_MIIM_SCAN_PHYADLO     VTSS_ENCODE_BITMASK(0,5)
#define  VTSS_X_DEVCPU_GCB_MIIM_MII_SCAN_0_MIIM_SCAN_PHYADLO(x)  VTSS_EXTRACT_BITFIELD(x,0,5)

#define VTSS_DEVCPU_GCB_MIIM_MII_SCAN_1(gi)  VTSS_IOREG_IX(VTSS_TO_DEVCPU_GCB,0x32,gi,9,0,6)
#define  VTSS_F_DEVCPU_GCB_MIIM_MII_SCAN_1_MIIM_SCAN_MASK(x)  VTSS_ENCODE_BITFIELD(x,16,16)
#define  VTSS_M_DEVCPU_GCB_MIIM_MII_SCAN_1_MIIM_SCAN_MASK     VTSS_ENCODE_BITMASK(16,16)
#define  VTSS_X_DEVCPU_GCB_MIIM_MII_SCAN_1_MIIM_SCAN_MASK(x)  VTSS_EXTRACT_BITFIELD(x,16,16)
#define  VTSS_F_DEVCPU_GCB_MIIM_MII_SCAN_1_MIIM_SCAN_EXPECT(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_DEVCPU_GCB_MIIM_MII_SCAN_1_MIIM_SCAN_EXPECT     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_DEVCPU_GCB_MIIM_MII_SCAN_1_MIIM_SCAN_EXPECT(x)  VTSS_EXTRACT_BITFIELD(x,0,16)

#define VTSS_DEVCPU_GCB_MIIM_MII_SCAN_LAST_RSLTS(gi)  VTSS_IOREG_IX(VTSS_TO_DEVCPU_GCB,0x32,gi,9,0,7)

#define VTSS_DEVCPU_GCB_MIIM_MII_SCAN_LAST_RSLTS_VLD(gi)  VTSS_IOREG_IX(VTSS_TO_DEVCPU_GCB,0x32,gi,9,0,8)

#define VTSS_DEVCPU_GCB_MIIM_READ_SCAN_MII_SCAN_RSLTS_STICKY(ri)  VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0x4d + (ri))

#define VTSS_DEVCPU_GCB_TEMP_SENSOR_TEMP_SENSOR_CTRL  VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0x50)
#define  VTSS_F_DEVCPU_GCB_TEMP_SENSOR_TEMP_SENSOR_CTRL_FORCE_TEMP_RD  VTSS_BIT(5)
#define  VTSS_F_DEVCPU_GCB_TEMP_SENSOR_TEMP_SENSOR_CTRL_FORCE_RUN  VTSS_BIT(4)
#define  VTSS_F_DEVCPU_GCB_TEMP_SENSOR_TEMP_SENSOR_CTRL_FORCE_NO_RST  VTSS_BIT(3)
#define  VTSS_F_DEVCPU_GCB_TEMP_SENSOR_TEMP_SENSOR_CTRL_FORCE_POWER_UP  VTSS_BIT(2)
#define  VTSS_F_DEVCPU_GCB_TEMP_SENSOR_TEMP_SENSOR_CTRL_FORCE_CLK  VTSS_BIT(1)
#define  VTSS_F_DEVCPU_GCB_TEMP_SENSOR_TEMP_SENSOR_CTRL_SAMPLE_ENA  VTSS_BIT(0)

#define VTSS_DEVCPU_GCB_TEMP_SENSOR_TEMP_SENSOR_CFG  VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0x51)
#define  VTSS_F_DEVCPU_GCB_TEMP_SENSOR_TEMP_SENSOR_CFG_RUN_WID(x)  VTSS_ENCODE_BITFIELD(x,8,8)
#define  VTSS_M_DEVCPU_GCB_TEMP_SENSOR_TEMP_SENSOR_CFG_RUN_WID     VTSS_ENCODE_BITMASK(8,8)
#define  VTSS_X_DEVCPU_GCB_TEMP_SENSOR_TEMP_SENSOR_CFG_RUN_WID(x)  VTSS_EXTRACT_BITFIELD(x,8,8)
#define  VTSS_F_DEVCPU_GCB_TEMP_SENSOR_TEMP_SENSOR_CFG_SAMPLE_PER(x)  VTSS_ENCODE_BITFIELD(x,0,8)
#define  VTSS_M_DEVCPU_GCB_TEMP_SENSOR_TEMP_SENSOR_CFG_SAMPLE_PER     VTSS_ENCODE_BITMASK(0,8)
#define  VTSS_X_DEVCPU_GCB_TEMP_SENSOR_TEMP_SENSOR_CFG_SAMPLE_PER(x)  VTSS_EXTRACT_BITFIELD(x,0,8)

#define VTSS_DEVCPU_GCB_TEMP_SENSOR_TEMP_SENSOR_STAT  VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0x52)
#define  VTSS_F_DEVCPU_GCB_TEMP_SENSOR_TEMP_SENSOR_STAT_TEMP_VALID  VTSS_BIT(8)
#define  VTSS_F_DEVCPU_GCB_TEMP_SENSOR_TEMP_SENSOR_STAT_TEMP(x)  VTSS_ENCODE_BITFIELD(x,0,8)
#define  VTSS_M_DEVCPU_GCB_TEMP_SENSOR_TEMP_SENSOR_STAT_TEMP     VTSS_ENCODE_BITMASK(0,8)
#define  VTSS_X_DEVCPU_GCB_TEMP_SENSOR_TEMP_SENSOR_STAT_TEMP(x)  VTSS_EXTRACT_BITFIELD(x,0,8)

#define VTSS_DEVCPU_GCB_MIIM_SLAVE_MIIM_SLAVE_CFG  VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0x53)
#define  VTSS_F_DEVCPU_GCB_MIIM_SLAVE_MIIM_SLAVE_CFG_SPIKE_FILTER_CFG(x)  VTSS_ENCODE_BITFIELD(x,1,5)
#define  VTSS_M_DEVCPU_GCB_MIIM_SLAVE_MIIM_SLAVE_CFG_SPIKE_FILTER_CFG     VTSS_ENCODE_BITMASK(1,5)
#define  VTSS_X_DEVCPU_GCB_MIIM_SLAVE_MIIM_SLAVE_CFG_SPIKE_FILTER_CFG(x)  VTSS_EXTRACT_BITFIELD(x,1,5)
#define  VTSS_F_DEVCPU_GCB_MIIM_SLAVE_MIIM_SLAVE_CFG_SPIKE_FILTER_ENA  VTSS_BIT(0)

#define VTSS_DEVCPU_GCB_SIO_CTRL_SIO_INPUT_DATA(gi,ri)  VTSS_IOREG_IX(VTSS_TO_DEVCPU_GCB,0x54,gi,67,ri,0)

#define VTSS_DEVCPU_GCB_SIO_CTRL_SIO_CFG(gi)  VTSS_IOREG_IX(VTSS_TO_DEVCPU_GCB,0x54,gi,67,0,4)
#define  VTSS_F_DEVCPU_GCB_SIO_CTRL_SIO_CFG_SIO_BMODE_1(x)  VTSS_ENCODE_BITFIELD(x,21,2)
#define  VTSS_M_DEVCPU_GCB_SIO_CTRL_SIO_CFG_SIO_BMODE_1     VTSS_ENCODE_BITMASK(21,2)
#define  VTSS_X_DEVCPU_GCB_SIO_CTRL_SIO_CFG_SIO_BMODE_1(x)  VTSS_EXTRACT_BITFIELD(x,21,2)
#define  VTSS_F_DEVCPU_GCB_SIO_CTRL_SIO_CFG_SIO_BMODE_0(x)  VTSS_ENCODE_BITFIELD(x,19,2)
#define  VTSS_M_DEVCPU_GCB_SIO_CTRL_SIO_CFG_SIO_BMODE_0     VTSS_ENCODE_BITMASK(19,2)
#define  VTSS_X_DEVCPU_GCB_SIO_CTRL_SIO_CFG_SIO_BMODE_0(x)  VTSS_EXTRACT_BITFIELD(x,19,2)
#define  VTSS_F_DEVCPU_GCB_SIO_CTRL_SIO_CFG_SIO_BLINK_RESET  VTSS_BIT(18)
#define  VTSS_F_DEVCPU_GCB_SIO_CTRL_SIO_CFG_SIO_BURST_GAP_DIS  VTSS_BIT(17)
#define  VTSS_F_DEVCPU_GCB_SIO_CTRL_SIO_CFG_SIO_BURST_GAP(x)  VTSS_ENCODE_BITFIELD(x,12,5)
#define  VTSS_M_DEVCPU_GCB_SIO_CTRL_SIO_CFG_SIO_BURST_GAP     VTSS_ENCODE_BITMASK(12,5)
#define  VTSS_X_DEVCPU_GCB_SIO_CTRL_SIO_CFG_SIO_BURST_GAP(x)  VTSS_EXTRACT_BITFIELD(x,12,5)
#define  VTSS_F_DEVCPU_GCB_SIO_CTRL_SIO_CFG_SIO_SINGLE_SHOT  VTSS_BIT(11)
#define  VTSS_F_DEVCPU_GCB_SIO_CTRL_SIO_CFG_SIO_AUTO_REPEAT  VTSS_BIT(10)
#define  VTSS_F_DEVCPU_GCB_SIO_CTRL_SIO_CFG_SIO_LD_POLARITY  VTSS_BIT(9)
#define  VTSS_F_DEVCPU_GCB_SIO_CTRL_SIO_CFG_SIO_PORT_WIDTH(x)  VTSS_ENCODE_BITFIELD(x,7,2)
#define  VTSS_M_DEVCPU_GCB_SIO_CTRL_SIO_CFG_SIO_PORT_WIDTH     VTSS_ENCODE_BITMASK(7,2)
#define  VTSS_X_DEVCPU_GCB_SIO_CTRL_SIO_CFG_SIO_PORT_WIDTH(x)  VTSS_EXTRACT_BITFIELD(x,7,2)
#define  VTSS_F_DEVCPU_GCB_SIO_CTRL_SIO_CFG_SIO_REVERSE_OUTPUT  VTSS_BIT(6)
#define  VTSS_F_DEVCPU_GCB_SIO_CTRL_SIO_CFG_SIO_REVERSE_INPUT  VTSS_BIT(5)
#define  VTSS_F_DEVCPU_GCB_SIO_CTRL_SIO_CFG_SIO_GPIO_INTR_ENA(x)  VTSS_ENCODE_BITFIELD(x,1,4)
#define  VTSS_M_DEVCPU_GCB_SIO_CTRL_SIO_CFG_SIO_GPIO_INTR_ENA     VTSS_ENCODE_BITMASK(1,4)
#define  VTSS_X_DEVCPU_GCB_SIO_CTRL_SIO_CFG_SIO_GPIO_INTR_ENA(x)  VTSS_EXTRACT_BITFIELD(x,1,4)
#define  VTSS_F_DEVCPU_GCB_SIO_CTRL_SIO_CFG_SIO_MASTER_INTR_ENA  VTSS_BIT(0)

#define VTSS_DEVCPU_GCB_SIO_CTRL_SIO_CLOCK(gi)  VTSS_IOREG_IX(VTSS_TO_DEVCPU_GCB,0x54,gi,67,0,5)
#define  VTSS_F_DEVCPU_GCB_SIO_CTRL_SIO_CLOCK_SIO_CLK_FREQ(x)  VTSS_ENCODE_BITFIELD(x,0,12)
#define  VTSS_M_DEVCPU_GCB_SIO_CTRL_SIO_CLOCK_SIO_CLK_FREQ     VTSS_ENCODE_BITMASK(0,12)
#define  VTSS_X_DEVCPU_GCB_SIO_CTRL_SIO_CLOCK_SIO_CLK_FREQ(x)  VTSS_EXTRACT_BITFIELD(x,0,12)

#define VTSS_DEVCPU_GCB_SIO_CTRL_SIO_PORT_CFG(gi,ri)  VTSS_IOREG_IX(VTSS_TO_DEVCPU_GCB,0x54,gi,67,ri,6)
#define  VTSS_F_DEVCPU_GCB_SIO_CTRL_SIO_PORT_CFG_BIT_SOURCE(x)  VTSS_ENCODE_BITFIELD(x,12,12)
#define  VTSS_M_DEVCPU_GCB_SIO_CTRL_SIO_PORT_CFG_BIT_SOURCE     VTSS_ENCODE_BITMASK(12,12)
#define  VTSS_X_DEVCPU_GCB_SIO_CTRL_SIO_PORT_CFG_BIT_SOURCE(x)  VTSS_EXTRACT_BITFIELD(x,12,12)
#define  VTSS_F_DEVCPU_GCB_SIO_CTRL_SIO_PORT_CFG_PWM_SOURCE(x)  VTSS_ENCODE_BITFIELD(x,4,8)
#define  VTSS_M_DEVCPU_GCB_SIO_CTRL_SIO_PORT_CFG_PWM_SOURCE     VTSS_ENCODE_BITMASK(4,8)
#define  VTSS_X_DEVCPU_GCB_SIO_CTRL_SIO_PORT_CFG_PWM_SOURCE(x)  VTSS_EXTRACT_BITFIELD(x,4,8)
#define  VTSS_F_DEVCPU_GCB_SIO_CTRL_SIO_PORT_CFG_BIT_POLARITY(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_DEVCPU_GCB_SIO_CTRL_SIO_PORT_CFG_BIT_POLARITY     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_DEVCPU_GCB_SIO_CTRL_SIO_PORT_CFG_BIT_POLARITY(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_DEVCPU_GCB_SIO_CTRL_SIO_PORT_ENA(gi)  VTSS_IOREG_IX(VTSS_TO_DEVCPU_GCB,0x54,gi,67,0,38)

#define VTSS_DEVCPU_GCB_SIO_CTRL_SIO_PWM_CFG(gi,ri)  VTSS_IOREG_IX(VTSS_TO_DEVCPU_GCB,0x54,gi,67,ri,39)
#define  VTSS_F_DEVCPU_GCB_SIO_CTRL_SIO_PWM_CFG_PWM_DUTY_CYCLE(x)  VTSS_ENCODE_BITFIELD(x,0,8)
#define  VTSS_M_DEVCPU_GCB_SIO_CTRL_SIO_PWM_CFG_PWM_DUTY_CYCLE     VTSS_ENCODE_BITMASK(0,8)
#define  VTSS_X_DEVCPU_GCB_SIO_CTRL_SIO_PWM_CFG_PWM_DUTY_CYCLE(x)  VTSS_EXTRACT_BITFIELD(x,0,8)

#define VTSS_DEVCPU_GCB_SIO_CTRL_SIO_INTR_POL(gi,ri)  VTSS_IOREG_IX(VTSS_TO_DEVCPU_GCB,0x54,gi,67,ri,42)

#define VTSS_DEVCPU_GCB_SIO_CTRL_SIO_INTR_RAW(gi,ri)  VTSS_IOREG_IX(VTSS_TO_DEVCPU_GCB,0x54,gi,67,ri,46)

#define VTSS_DEVCPU_GCB_SIO_CTRL_SIO_INTR_TRIGGER0(gi,ri)  VTSS_IOREG_IX(VTSS_TO_DEVCPU_GCB,0x54,gi,67,ri,50)

#define VTSS_DEVCPU_GCB_SIO_CTRL_SIO_INTR_TRIGGER1(gi,ri)  VTSS_IOREG_IX(VTSS_TO_DEVCPU_GCB,0x54,gi,67,ri,54)

#define VTSS_DEVCPU_GCB_SIO_CTRL_SIO_INTR(gi,ri)  VTSS_IOREG_IX(VTSS_TO_DEVCPU_GCB,0x54,gi,67,ri,58)

#define VTSS_DEVCPU_GCB_SIO_CTRL_SIO_INTR_ENA(gi)  VTSS_IOREG_IX(VTSS_TO_DEVCPU_GCB,0x54,gi,67,0,62)

#define VTSS_DEVCPU_GCB_SIO_CTRL_SIO_INTR_IDENT(gi,ri)  VTSS_IOREG_IX(VTSS_TO_DEVCPU_GCB,0x54,gi,67,ri,63)

#define VTSS_DEVCPU_GCB_FAN_CTRL_FAN_CFG     VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0x11d)
#define  VTSS_F_DEVCPU_GCB_FAN_CTRL_FAN_CFG_DUTY_CYCLE(x)  VTSS_ENCODE_BITFIELD(x,16,8)
#define  VTSS_M_DEVCPU_GCB_FAN_CTRL_FAN_CFG_DUTY_CYCLE     VTSS_ENCODE_BITMASK(16,8)
#define  VTSS_X_DEVCPU_GCB_FAN_CTRL_FAN_CFG_DUTY_CYCLE(x)  VTSS_EXTRACT_BITFIELD(x,16,8)
#define  VTSS_F_DEVCPU_GCB_FAN_CTRL_FAN_CFG_PWM_FREQ(x)  VTSS_ENCODE_BITFIELD(x,4,3)
#define  VTSS_M_DEVCPU_GCB_FAN_CTRL_FAN_CFG_PWM_FREQ     VTSS_ENCODE_BITMASK(4,3)
#define  VTSS_X_DEVCPU_GCB_FAN_CTRL_FAN_CFG_PWM_FREQ(x)  VTSS_EXTRACT_BITFIELD(x,4,3)
#define  VTSS_F_DEVCPU_GCB_FAN_CTRL_FAN_CFG_INV_POL  VTSS_BIT(3)
#define  VTSS_F_DEVCPU_GCB_FAN_CTRL_FAN_CFG_GATE_ENA  VTSS_BIT(2)
#define  VTSS_F_DEVCPU_GCB_FAN_CTRL_FAN_CFG_PWM_OPEN_COL_ENA  VTSS_BIT(1)
#define  VTSS_F_DEVCPU_GCB_FAN_CTRL_FAN_CFG_FAN_STAT_CFG  VTSS_BIT(0)

#define VTSS_DEVCPU_GCB_FAN_CTRL_FAN_CNT     VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0x11e)
#define  VTSS_F_DEVCPU_GCB_FAN_CTRL_FAN_CNT_FAN_CNT(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_DEVCPU_GCB_FAN_CTRL_FAN_CNT_FAN_CNT     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_DEVCPU_GCB_FAN_CTRL_FAN_CNT_FAN_CNT(x)  VTSS_EXTRACT_BITFIELD(x,0,16)

#define VTSS_DEVCPU_GCB_MEMITGR_MEMITGR_CTRL  VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0x11f)
#define  VTSS_F_DEVCPU_GCB_MEMITGR_MEMITGR_CTRL_ACTIVATE  VTSS_BIT(0)

#define VTSS_DEVCPU_GCB_MEMITGR_MEMITGR_STAT  VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0x120)
#define  VTSS_F_DEVCPU_GCB_MEMITGR_MEMITGR_STAT_INDICATION_OVF  VTSS_BIT(5)
#define  VTSS_F_DEVCPU_GCB_MEMITGR_MEMITGR_STAT_INDICATION  VTSS_BIT(4)
#define  VTSS_F_DEVCPU_GCB_MEMITGR_MEMITGR_STAT_MODE_LISTEN  VTSS_BIT(3)
#define  VTSS_F_DEVCPU_GCB_MEMITGR_MEMITGR_STAT_MODE_DETECT  VTSS_BIT(2)
#define  VTSS_F_DEVCPU_GCB_MEMITGR_MEMITGR_STAT_MODE_IDLE  VTSS_BIT(1)
#define  VTSS_F_DEVCPU_GCB_MEMITGR_MEMITGR_STAT_MODE_BUSY  VTSS_BIT(0)

#define VTSS_DEVCPU_GCB_MEMITGR_MEMITGR_INFO  VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0x121)
#define  VTSS_F_DEVCPU_GCB_MEMITGR_MEMITGR_INFO_MEM_ERR  VTSS_BIT(31)
#define  VTSS_F_DEVCPU_GCB_MEMITGR_MEMITGR_INFO_MEM_COR  VTSS_BIT(30)
#define  VTSS_F_DEVCPU_GCB_MEMITGR_MEMITGR_INFO_MEM_ERR_OVF  VTSS_BIT(29)
#define  VTSS_F_DEVCPU_GCB_MEMITGR_MEMITGR_INFO_MEM_COR_OVF  VTSS_BIT(28)
#define  VTSS_F_DEVCPU_GCB_MEMITGR_MEMITGR_INFO_MEM_ADDR(x)  VTSS_ENCODE_BITFIELD(x,0,28)
#define  VTSS_M_DEVCPU_GCB_MEMITGR_MEMITGR_INFO_MEM_ADDR     VTSS_ENCODE_BITMASK(0,28)
#define  VTSS_X_DEVCPU_GCB_MEMITGR_MEMITGR_INFO_MEM_ADDR(x)  VTSS_EXTRACT_BITFIELD(x,0,28)

#define VTSS_DEVCPU_GCB_MEMITGR_MEMITGR_IDX  VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0x122)
#define  VTSS_F_DEVCPU_GCB_MEMITGR_MEMITGR_IDX_MEM_IDX(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_DEVCPU_GCB_MEMITGR_MEMITGR_IDX_MEM_IDX     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_DEVCPU_GCB_MEMITGR_MEMITGR_IDX_MEM_IDX(x)  VTSS_EXTRACT_BITFIELD(x,0,16)

#define VTSS_DEVCPU_GCB_MEMITGR_MEMITGR_DIV  VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0x123)
#define  VTSS_F_DEVCPU_GCB_MEMITGR_MEMITGR_DIV_MEM_DIV(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_DEVCPU_GCB_MEMITGR_MEMITGR_DIV_MEM_DIV     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_DEVCPU_GCB_MEMITGR_MEMITGR_DIV_MEM_DIV(x)  VTSS_EXTRACT_BITFIELD(x,0,16)

#define VTSS_DEVCPU_GCB_MEMITGR_MEMITGR_DBG  VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0x124)
#define  VTSS_F_DEVCPU_GCB_MEMITGR_MEMITGR_DBG_MEM_DIV_SENSE  VTSS_BIT(9)
#define  VTSS_F_DEVCPU_GCB_MEMITGR_MEMITGR_DBG_FORCE_INTR  VTSS_BIT(8)
#define  VTSS_F_DEVCPU_GCB_MEMITGR_MEMITGR_DBG_SYNC_IN  VTSS_BIT(7)
#define  VTSS_F_DEVCPU_GCB_MEMITGR_MEMITGR_DBG_ENA_IN  VTSS_BIT(6)
#define  VTSS_F_DEVCPU_GCB_MEMITGR_MEMITGR_DBG_DATA_IN  VTSS_BIT(5)
#define  VTSS_F_DEVCPU_GCB_MEMITGR_MEMITGR_DBG_INTR_IN  VTSS_BIT(4)
#define  VTSS_F_DEVCPU_GCB_MEMITGR_MEMITGR_DBG_SYNC_OUT  VTSS_BIT(3)
#define  VTSS_F_DEVCPU_GCB_MEMITGR_MEMITGR_DBG_ENA_OUT  VTSS_BIT(2)
#define  VTSS_F_DEVCPU_GCB_MEMITGR_MEMITGR_DBG_FORCE_ENA  VTSS_BIT(1)
#define  VTSS_F_DEVCPU_GCB_MEMITGR_MEMITGR_DBG_DETECT_ENA  VTSS_BIT(0)

#define VTSS_DEVCPU_GCB_ETHERACCESS_VRAP_ACCESS_STAT  VTSS_IOREG(VTSS_TO_DEVCPU_GCB,0x125)
#define  VTSS_F_DEVCPU_GCB_ETHERACCESS_VRAP_ACCESS_STAT_FRM_RECV_STICKY  VTSS_BIT(3)
#define  VTSS_F_DEVCPU_GCB_ETHERACCESS_VRAP_ACCESS_STAT_CMD_INVALID_STICKY  VTSS_BIT(2)
#define  VTSS_F_DEVCPU_GCB_ETHERACCESS_VRAP_ACCESS_STAT_FRM_INVALID_STICKY  VTSS_BIT(1)
#define  VTSS_F_DEVCPU_GCB_ETHERACCESS_VRAP_ACCESS_STAT_REPLY_ABORT_STICKY  VTSS_BIT(0)


#endif /* _VTSS_JAGUAR2_REGS_DEVCPU_GCB_H_ */
