#ifndef _VTSS_JAGUAR2_REGS_VOP_MPLS_H_
#define _VTSS_JAGUAR2_REGS_VOP_MPLS_H_

/*
 *
 * VCore-III Register Definitions
 *
 * Copyright (C) 2012 Vitesse Semiconductor Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#include "vtss_jaguar2_regs_common.h"

#define VTSS_VOP_MPLS_VOE_CONF_MPLS_VOE_CTRL_MPLS(gi)  VTSS_IOREG_IX(VTSS_TO_VOP_MPLS,0x10000,gi,16,0,0)
#define  VTSS_F_VOP_MPLS_VOE_CONF_MPLS_VOE_CTRL_MPLS_VOE_ENA  VTSS_BIT(2)
#define  VTSS_F_VOP_MPLS_VOE_CONF_MPLS_VOE_CTRL_MPLS_UPMEP_ENA  VTSS_BIT(1)
#define  VTSS_F_VOP_MPLS_VOE_CONF_MPLS_VOE_CTRL_MPLS_VOE_IS_PATH  VTSS_BIT(0)

#define VTSS_VOP_MPLS_VOE_CONF_MPLS_CPU_COPY_CTRL_MPLS(gi)  VTSS_IOREG_IX(VTSS_TO_VOP_MPLS,0x10000,gi,16,0,1)
#define  VTSS_F_VOP_MPLS_VOE_CONF_MPLS_CPU_COPY_CTRL_MPLS_GENERIC_COPY_MASK(x)  VTSS_ENCODE_BITFIELD(x,3,8)
#define  VTSS_M_VOP_MPLS_VOE_CONF_MPLS_CPU_COPY_CTRL_MPLS_GENERIC_COPY_MASK     VTSS_ENCODE_BITMASK(3,8)
#define  VTSS_X_VOP_MPLS_VOE_CONF_MPLS_CPU_COPY_CTRL_MPLS_GENERIC_COPY_MASK(x)  VTSS_EXTRACT_BITFIELD(x,3,8)
#define  VTSS_F_VOP_MPLS_VOE_CONF_MPLS_CPU_COPY_CTRL_MPLS_UNK_CPT_CPU_COPY_ENA  VTSS_BIT(2)
#define  VTSS_F_VOP_MPLS_VOE_CONF_MPLS_CPU_COPY_CTRL_MPLS_BFD_CC_CPU_COPY_ENA  VTSS_BIT(1)
#define  VTSS_F_VOP_MPLS_VOE_CONF_MPLS_CPU_COPY_CTRL_MPLS_BFD_CV_CPU_COPY_ENA  VTSS_BIT(0)

#define VTSS_VOP_MPLS_VOE_CONF_MPLS_OAM_HW_CTRL_MPLS(gi)  VTSS_IOREG_IX(VTSS_TO_VOP_MPLS,0x10000,gi,16,0,2)
#define  VTSS_F_VOP_MPLS_VOE_CONF_MPLS_OAM_HW_CTRL_MPLS_BFD_CC_ENA  VTSS_BIT(1)
#define  VTSS_F_VOP_MPLS_VOE_CONF_MPLS_OAM_HW_CTRL_MPLS_BFD_CV_ENA  VTSS_BIT(0)

#define VTSS_VOP_MPLS_VOE_CONF_MPLS_OAM_CNT_SEL_MPLS(gi)  VTSS_IOREG_IX(VTSS_TO_VOP_MPLS,0x10000,gi,16,0,3)
#define  VTSS_F_VOP_MPLS_VOE_CONF_MPLS_OAM_CNT_SEL_MPLS_GENERIC_CPT_CNT_SEL_MASK(x)  VTSS_ENCODE_BITFIELD(x,3,8)
#define  VTSS_M_VOP_MPLS_VOE_CONF_MPLS_OAM_CNT_SEL_MPLS_GENERIC_CPT_CNT_SEL_MASK     VTSS_ENCODE_BITMASK(3,8)
#define  VTSS_X_VOP_MPLS_VOE_CONF_MPLS_OAM_CNT_SEL_MPLS_GENERIC_CPT_CNT_SEL_MASK(x)  VTSS_EXTRACT_BITFIELD(x,3,8)
#define  VTSS_F_VOP_MPLS_VOE_CONF_MPLS_OAM_CNT_SEL_MPLS_UNK_CPT_CNT_SEL_ENA  VTSS_BIT(2)
#define  VTSS_F_VOP_MPLS_VOE_CONF_MPLS_OAM_CNT_SEL_MPLS_BFD_CC_CNT_SEL_ENA  VTSS_BIT(1)
#define  VTSS_F_VOP_MPLS_VOE_CONF_MPLS_OAM_CNT_SEL_MPLS_BFD_CV_CNT_SEL_ENA  VTSS_BIT(0)

#define VTSS_VOP_MPLS_VOE_CONF_MPLS_OAM_CNT_DATA_MPLS(gi)  VTSS_IOREG_IX(VTSS_TO_VOP_MPLS,0x10000,gi,16,0,4)
#define  VTSS_F_VOP_MPLS_VOE_CONF_MPLS_OAM_CNT_DATA_MPLS_GENERIC_CPT_CNT_DATA_MASK(x)  VTSS_ENCODE_BITFIELD(x,3,8)
#define  VTSS_M_VOP_MPLS_VOE_CONF_MPLS_OAM_CNT_DATA_MPLS_GENERIC_CPT_CNT_DATA_MASK     VTSS_ENCODE_BITMASK(3,8)
#define  VTSS_X_VOP_MPLS_VOE_CONF_MPLS_OAM_CNT_DATA_MPLS_GENERIC_CPT_CNT_DATA_MASK(x)  VTSS_EXTRACT_BITFIELD(x,3,8)
#define  VTSS_F_VOP_MPLS_VOE_CONF_MPLS_OAM_CNT_DATA_MPLS_UNK_CPT_CNT_DATA_ENA  VTSS_BIT(2)
#define  VTSS_F_VOP_MPLS_VOE_CONF_MPLS_OAM_CNT_DATA_MPLS_BFD_CC_CNT_DATA_ENA  VTSS_BIT(1)
#define  VTSS_F_VOP_MPLS_VOE_CONF_MPLS_OAM_CNT_DATA_MPLS_BFD_CV_CNT_DATA_ENA  VTSS_BIT(0)

#define VTSS_VOP_MPLS_VOE_CONF_MPLS_PATH_VOE_MPLS(gi)  VTSS_IOREG_IX(VTSS_TO_VOP_MPLS,0x10000,gi,16,0,5)
#define  VTSS_F_VOP_MPLS_VOE_CONF_MPLS_PATH_VOE_MPLS_PATH_VOE_ENA  VTSS_BIT(10)
#define  VTSS_F_VOP_MPLS_VOE_CONF_MPLS_PATH_VOE_MPLS_PATH_VOEID(x)  VTSS_ENCODE_BITFIELD(x,0,10)
#define  VTSS_M_VOP_MPLS_VOE_CONF_MPLS_PATH_VOE_MPLS_PATH_VOEID     VTSS_ENCODE_BITMASK(0,10)
#define  VTSS_X_VOP_MPLS_VOE_CONF_MPLS_PATH_VOE_MPLS_PATH_VOEID(x)  VTSS_EXTRACT_BITFIELD(x,0,10)

#define VTSS_VOP_MPLS_VOE_CONF_MPLS_BFD_CONFIG(gi)  VTSS_IOREG_IX(VTSS_TO_VOP_MPLS,0x10000,gi,16,0,6)
#define  VTSS_F_VOP_MPLS_VOE_CONF_MPLS_BFD_CONFIG_BFD_CC_RFC6428  VTSS_BIT(22)
#define  VTSS_F_VOP_MPLS_VOE_CONF_MPLS_BFD_CONFIG_BFD_SCAN_PERIOD(x)  VTSS_ENCODE_BITFIELD(x,19,3)
#define  VTSS_M_VOP_MPLS_VOE_CONF_MPLS_BFD_CONFIG_BFD_SCAN_PERIOD     VTSS_ENCODE_BITMASK(19,3)
#define  VTSS_X_VOP_MPLS_VOE_CONF_MPLS_BFD_CONFIG_BFD_SCAN_PERIOD(x)  VTSS_EXTRACT_BITFIELD(x,19,3)
#define  VTSS_F_VOP_MPLS_VOE_CONF_MPLS_BFD_CONFIG_BFD_RX_SAMPLE_ENA  VTSS_BIT(18)
#define  VTSS_F_VOP_MPLS_VOE_CONF_MPLS_BFD_CONFIG_BFD_TX_UPDATE_ENA  VTSS_BIT(17)
#define  VTSS_F_VOP_MPLS_VOE_CONF_MPLS_BFD_CONFIG_BFD_COORDINATED_MODE_ENA  VTSS_BIT(16)
#define  VTSS_F_VOP_MPLS_VOE_CONF_MPLS_BFD_CONFIG_BFD_RX_VERIFY_CC_ENA  VTSS_BIT(15)
#define  VTSS_F_VOP_MPLS_VOE_CONF_MPLS_BFD_CONFIG_BFD_RX_VERIFY_CV_ENA  VTSS_BIT(14)
#define  VTSS_F_VOP_MPLS_VOE_CONF_MPLS_BFD_CONFIG_BFD_RX_VERIFY_VERSION_ENA  VTSS_BIT(13)
#define  VTSS_F_VOP_MPLS_VOE_CONF_MPLS_BFD_CONFIG_BFD_RX_VERIFY_MIN_LEN_ENA  VTSS_BIT(12)
#define  VTSS_F_VOP_MPLS_VOE_CONF_MPLS_BFD_CONFIG_BFD_RX_VERIFY_DISCR_ENA  VTSS_BIT(11)
#define  VTSS_F_VOP_MPLS_VOE_CONF_MPLS_BFD_CONFIG_BFD_RX_VERIFY_FLAGS_ENA  VTSS_BIT(10)
#define  VTSS_F_VOP_MPLS_VOE_CONF_MPLS_BFD_CONFIG_BFD_CC_AUTH_ENA  VTSS_BIT(9)
#define  VTSS_F_VOP_MPLS_VOE_CONF_MPLS_BFD_CONFIG_BFD_CV_AUTH_ENA  VTSS_BIT(8)
#define  VTSS_F_VOP_MPLS_VOE_CONF_MPLS_BFD_CONFIG_BFD_MAX_LEN(x)  VTSS_ENCODE_BITFIELD(x,0,8)
#define  VTSS_M_VOP_MPLS_VOE_CONF_MPLS_BFD_CONFIG_BFD_MAX_LEN     VTSS_ENCODE_BITMASK(0,8)
#define  VTSS_X_VOP_MPLS_VOE_CONF_MPLS_BFD_CONFIG_BFD_MAX_LEN(x)  VTSS_EXTRACT_BITFIELD(x,0,8)

#define VTSS_VOP_MPLS_VOE_CONF_MPLS_BFD_LOCAL_DISCR_SRC(gi)  VTSS_IOREG_IX(VTSS_TO_VOP_MPLS,0x10000,gi,16,0,7)

#define VTSS_VOP_MPLS_VOE_CONF_MPLS_BFD_REMOTE_DISCR_SRC(gi)  VTSS_IOREG_IX(VTSS_TO_VOP_MPLS,0x10000,gi,16,0,8)

#define VTSS_VOP_MPLS_VOE_CONF_MPLS_BFD_LOCAL_DISCR_SINK(gi)  VTSS_IOREG_IX(VTSS_TO_VOP_MPLS,0x10000,gi,16,0,9)

#define VTSS_VOP_MPLS_VOE_CONF_MPLS_BFD_REMOTE_DISCR_SINK(gi)  VTSS_IOREG_IX(VTSS_TO_VOP_MPLS,0x10000,gi,16,0,10)

#define VTSS_VOP_MPLS_VOE_STAT_MPLS_RX_CNT_SEL_OAM_MPLS(gi)  VTSS_IOREG_IX(VTSS_TO_VOP_MPLS,0x0,gi,32,0,0)

#define VTSS_VOP_MPLS_VOE_STAT_MPLS_RX_CNT_NON_SEL_OAM_MPLS(gi)  VTSS_IOREG_IX(VTSS_TO_VOP_MPLS,0x0,gi,32,0,1)

#define VTSS_VOP_MPLS_VOE_STAT_MPLS_TX_CNT_SEL_OAM_MPLS(gi)  VTSS_IOREG_IX(VTSS_TO_VOP_MPLS,0x0,gi,32,0,2)

#define VTSS_VOP_MPLS_VOE_STAT_MPLS_TX_CNT_NON_SEL_OAM_MPLS(gi)  VTSS_IOREG_IX(VTSS_TO_VOP_MPLS,0x0,gi,32,0,3)

#define VTSS_VOP_MPLS_VOE_STAT_MPLS_BFD_SRC_INFO(gi)  VTSS_IOREG_IX(VTSS_TO_VOP_MPLS,0x0,gi,32,0,4)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_BFD_SRC_INFO_BFD_LOCAL_STATE_SRC(x)  VTSS_ENCODE_BITFIELD(x,28,2)
#define  VTSS_M_VOP_MPLS_VOE_STAT_MPLS_BFD_SRC_INFO_BFD_LOCAL_STATE_SRC     VTSS_ENCODE_BITMASK(28,2)
#define  VTSS_X_VOP_MPLS_VOE_STAT_MPLS_BFD_SRC_INFO_BFD_LOCAL_STATE_SRC(x)  VTSS_EXTRACT_BITFIELD(x,28,2)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_BFD_SRC_INFO_BFD_REMOTE_STATE_SRC(x)  VTSS_ENCODE_BITFIELD(x,26,2)
#define  VTSS_M_VOP_MPLS_VOE_STAT_MPLS_BFD_SRC_INFO_BFD_REMOTE_STATE_SRC     VTSS_ENCODE_BITMASK(26,2)
#define  VTSS_X_VOP_MPLS_VOE_STAT_MPLS_BFD_SRC_INFO_BFD_REMOTE_STATE_SRC(x)  VTSS_EXTRACT_BITFIELD(x,26,2)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_BFD_SRC_INFO_BFD_LOCAL_DIAG_SRC(x)  VTSS_ENCODE_BITFIELD(x,21,5)
#define  VTSS_M_VOP_MPLS_VOE_STAT_MPLS_BFD_SRC_INFO_BFD_LOCAL_DIAG_SRC     VTSS_ENCODE_BITMASK(21,5)
#define  VTSS_X_VOP_MPLS_VOE_STAT_MPLS_BFD_SRC_INFO_BFD_LOCAL_DIAG_SRC(x)  VTSS_EXTRACT_BITFIELD(x,21,5)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_BFD_SRC_INFO_BFD_REMOTE_DIAG_SRC(x)  VTSS_ENCODE_BITFIELD(x,16,5)
#define  VTSS_M_VOP_MPLS_VOE_STAT_MPLS_BFD_SRC_INFO_BFD_REMOTE_DIAG_SRC     VTSS_ENCODE_BITMASK(16,5)
#define  VTSS_X_VOP_MPLS_VOE_STAT_MPLS_BFD_SRC_INFO_BFD_REMOTE_DIAG_SRC(x)  VTSS_EXTRACT_BITFIELD(x,16,5)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_BFD_SRC_INFO_BFD_LOCAL_DM_SRC(x)  VTSS_ENCODE_BITFIELD(x,8,8)
#define  VTSS_M_VOP_MPLS_VOE_STAT_MPLS_BFD_SRC_INFO_BFD_LOCAL_DM_SRC     VTSS_ENCODE_BITMASK(8,8)
#define  VTSS_X_VOP_MPLS_VOE_STAT_MPLS_BFD_SRC_INFO_BFD_LOCAL_DM_SRC(x)  VTSS_EXTRACT_BITFIELD(x,8,8)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_BFD_SRC_INFO_BFD_REMOTE_DM_SRC(x)  VTSS_ENCODE_BITFIELD(x,0,8)
#define  VTSS_M_VOP_MPLS_VOE_STAT_MPLS_BFD_SRC_INFO_BFD_REMOTE_DM_SRC     VTSS_ENCODE_BITMASK(0,8)
#define  VTSS_X_VOP_MPLS_VOE_STAT_MPLS_BFD_SRC_INFO_BFD_REMOTE_DM_SRC(x)  VTSS_EXTRACT_BITFIELD(x,0,8)

#define VTSS_VOP_MPLS_VOE_STAT_MPLS_BFD_SINK_INFO(gi)  VTSS_IOREG_IX(VTSS_TO_VOP_MPLS,0x0,gi,32,0,5)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_BFD_SINK_INFO_BFD_LOCAL_STATE_SINK(x)  VTSS_ENCODE_BITFIELD(x,28,2)
#define  VTSS_M_VOP_MPLS_VOE_STAT_MPLS_BFD_SINK_INFO_BFD_LOCAL_STATE_SINK     VTSS_ENCODE_BITMASK(28,2)
#define  VTSS_X_VOP_MPLS_VOE_STAT_MPLS_BFD_SINK_INFO_BFD_LOCAL_STATE_SINK(x)  VTSS_EXTRACT_BITFIELD(x,28,2)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_BFD_SINK_INFO_BFD_REMOTE_STATE_SINK(x)  VTSS_ENCODE_BITFIELD(x,26,2)
#define  VTSS_M_VOP_MPLS_VOE_STAT_MPLS_BFD_SINK_INFO_BFD_REMOTE_STATE_SINK     VTSS_ENCODE_BITMASK(26,2)
#define  VTSS_X_VOP_MPLS_VOE_STAT_MPLS_BFD_SINK_INFO_BFD_REMOTE_STATE_SINK(x)  VTSS_EXTRACT_BITFIELD(x,26,2)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_BFD_SINK_INFO_BFD_LOCAL_DIAG_SINK(x)  VTSS_ENCODE_BITFIELD(x,21,5)
#define  VTSS_M_VOP_MPLS_VOE_STAT_MPLS_BFD_SINK_INFO_BFD_LOCAL_DIAG_SINK     VTSS_ENCODE_BITMASK(21,5)
#define  VTSS_X_VOP_MPLS_VOE_STAT_MPLS_BFD_SINK_INFO_BFD_LOCAL_DIAG_SINK(x)  VTSS_EXTRACT_BITFIELD(x,21,5)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_BFD_SINK_INFO_BFD_REMOTE_DIAG_SINK(x)  VTSS_ENCODE_BITFIELD(x,16,5)
#define  VTSS_M_VOP_MPLS_VOE_STAT_MPLS_BFD_SINK_INFO_BFD_REMOTE_DIAG_SINK     VTSS_ENCODE_BITMASK(16,5)
#define  VTSS_X_VOP_MPLS_VOE_STAT_MPLS_BFD_SINK_INFO_BFD_REMOTE_DIAG_SINK(x)  VTSS_EXTRACT_BITFIELD(x,16,5)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_BFD_SINK_INFO_BFD_LOCAL_DM_SINK(x)  VTSS_ENCODE_BITFIELD(x,8,8)
#define  VTSS_M_VOP_MPLS_VOE_STAT_MPLS_BFD_SINK_INFO_BFD_LOCAL_DM_SINK     VTSS_ENCODE_BITMASK(8,8)
#define  VTSS_X_VOP_MPLS_VOE_STAT_MPLS_BFD_SINK_INFO_BFD_LOCAL_DM_SINK(x)  VTSS_EXTRACT_BITFIELD(x,8,8)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_BFD_SINK_INFO_BFD_REMOTE_DM_SINK(x)  VTSS_ENCODE_BITFIELD(x,0,8)
#define  VTSS_M_VOP_MPLS_VOE_STAT_MPLS_BFD_SINK_INFO_BFD_REMOTE_DM_SINK     VTSS_ENCODE_BITMASK(0,8)
#define  VTSS_X_VOP_MPLS_VOE_STAT_MPLS_BFD_SINK_INFO_BFD_REMOTE_DM_SINK(x)  VTSS_EXTRACT_BITFIELD(x,0,8)

#define VTSS_VOP_MPLS_VOE_STAT_MPLS_BFD_STAT(gi)  VTSS_IOREG_IX(VTSS_TO_VOP_MPLS,0x0,gi,32,0,6)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_BFD_STAT_BFD_MISS_CNT(x)  VTSS_ENCODE_BITFIELD(x,0,9)
#define  VTSS_M_VOP_MPLS_VOE_STAT_MPLS_BFD_STAT_BFD_MISS_CNT     VTSS_ENCODE_BITMASK(0,9)
#define  VTSS_X_VOP_MPLS_VOE_STAT_MPLS_BFD_STAT_BFD_MISS_CNT(x)  VTSS_EXTRACT_BITFIELD(x,0,9)

#define VTSS_VOP_MPLS_VOE_STAT_MPLS_BFD_RX_LAST(gi)  VTSS_IOREG_IX(VTSS_TO_VOP_MPLS,0x0,gi,32,0,7)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_BFD_RX_LAST_BFD_LOC_DEFECT  VTSS_BIT(0)

#define VTSS_VOP_MPLS_VOE_STAT_MPLS_INTR_STICKY_MPLS(gi)  VTSS_IOREG_IX(VTSS_TO_VOP_MPLS,0x0,gi,32,0,8)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_INTR_STICKY_MPLS_BFD_LOC_CHANGE_STICKY  VTSS_BIT(10)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_INTR_STICKY_MPLS_BFD_RX_DM_CHANGE_SRC_STICKY  VTSS_BIT(9)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_INTR_STICKY_MPLS_BFD_RX_STATE_CHANGE_SRC_STICKY  VTSS_BIT(8)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_INTR_STICKY_MPLS_BFD_RX_DIAG_CHANGE_SRC_STICKY  VTSS_BIT(7)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_INTR_STICKY_MPLS_BFD_RX_P_SET_SRC_STICKY  VTSS_BIT(6)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_INTR_STICKY_MPLS_BFD_RX_F_SET_SRC_STICKY  VTSS_BIT(5)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_INTR_STICKY_MPLS_BFD_RX_DM_CHANGE_SINK_STICKY  VTSS_BIT(4)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_INTR_STICKY_MPLS_BFD_RX_STATE_CHANGE_SINK_STICKY  VTSS_BIT(3)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_INTR_STICKY_MPLS_BFD_RX_DIAG_CHANGE_SINK_STICKY  VTSS_BIT(2)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_INTR_STICKY_MPLS_BFD_RX_P_SET_SINK_STICKY  VTSS_BIT(1)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_INTR_STICKY_MPLS_BFD_RX_F_SET_SINK_STICKY  VTSS_BIT(0)

#define VTSS_VOP_MPLS_VOE_STAT_MPLS_INTR_ENA_MPLS(gi)  VTSS_IOREG_IX(VTSS_TO_VOP_MPLS,0x0,gi,32,0,9)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_INTR_ENA_MPLS_BFD_LOC_CHANGE_INT_ENA  VTSS_BIT(10)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_INTR_ENA_MPLS_BFD_RX_DM_CHANGE_SRC_INT_ENA  VTSS_BIT(9)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_INTR_ENA_MPLS_BFD_RX_STATE_CHANGE_SRC_INT_ENA  VTSS_BIT(8)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_INTR_ENA_MPLS_BFD_RX_DIAG_CHANGE_SRC_INT_ENA  VTSS_BIT(7)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_INTR_ENA_MPLS_BFD_RX_P_SET_SRC_INT_ENA  VTSS_BIT(6)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_INTR_ENA_MPLS_BFD_RX_F_SET_SRC_INT_ENA  VTSS_BIT(5)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_INTR_ENA_MPLS_BFD_RX_DM_CHANGE_SINK_INT_ENA  VTSS_BIT(4)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_INTR_ENA_MPLS_BFD_RX_STATE_CHANGE_SINK_INT_ENA  VTSS_BIT(3)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_INTR_ENA_MPLS_BFD_RX_DIAG_CHANGE_SINK_INT_ENA  VTSS_BIT(2)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_INTR_ENA_MPLS_BFD_RX_P_SET_SINK_INT_ENA  VTSS_BIT(1)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_INTR_ENA_MPLS_BFD_RX_F_SET_SINK_INT_ENA  VTSS_BIT(0)

#define VTSS_VOP_MPLS_VOE_STAT_MPLS_CPT_RX_STICKY_MPLS(gi)  VTSS_IOREG_IX(VTSS_TO_VOP_MPLS,0x0,gi,32,0,10)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_CPT_RX_STICKY_MPLS_GENERIC_CPT_RX_STICKY_MASK(x)  VTSS_ENCODE_BITFIELD(x,3,8)
#define  VTSS_M_VOP_MPLS_VOE_STAT_MPLS_CPT_RX_STICKY_MPLS_GENERIC_CPT_RX_STICKY_MASK     VTSS_ENCODE_BITMASK(3,8)
#define  VTSS_X_VOP_MPLS_VOE_STAT_MPLS_CPT_RX_STICKY_MPLS_GENERIC_CPT_RX_STICKY_MASK(x)  VTSS_EXTRACT_BITFIELD(x,3,8)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_CPT_RX_STICKY_MPLS_UNK_CPT_RX_STICKY  VTSS_BIT(2)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_CPT_RX_STICKY_MPLS_BFD_CC_RX_STICKY  VTSS_BIT(1)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_CPT_RX_STICKY_MPLS_BFD_CV_RX_STICKY  VTSS_BIT(0)

#define VTSS_VOP_MPLS_VOE_STAT_MPLS_PDU_EXTRACT_MPLS(gi)  VTSS_IOREG_IX(VTSS_TO_VOP_MPLS,0x0,gi,32,0,11)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_PDU_EXTRACT_MPLS_BFD_CC_RX_NEXT_GOOD_EXTR  VTSS_BIT(7)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_PDU_EXTRACT_MPLS_BFD_CV_RX_NEXT_GOOD_EXTR  VTSS_BIT(6)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_PDU_EXTRACT_MPLS_EXTRACT_HIT_ME_ONCE  VTSS_BIT(5)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_PDU_EXTRACT_MPLS_BFD_RX_PARAM_CHANGE_EXTR  VTSS_BIT(4)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_PDU_EXTRACT_MPLS_BFD_RX_P_SET_EXTR  VTSS_BIT(3)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_PDU_EXTRACT_MPLS_BFD_RX_F_SET_EXTR  VTSS_BIT(2)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_PDU_EXTRACT_MPLS_BFD_RX_ERR_EXTR  VTSS_BIT(1)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_PDU_EXTRACT_MPLS_BFD_TX_ERR_EXTR  VTSS_BIT(0)

#define VTSS_VOP_MPLS_VOE_STAT_MPLS_BFD_RX_STICKY(gi)  VTSS_IOREG_IX(VTSS_TO_VOP_MPLS,0x0,gi,32,0,12)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_BFD_RX_STICKY_VERSION_ERR_STICKY  VTSS_BIT(9)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_BFD_RX_STICKY_MIN_LEN_ERR_STICKY  VTSS_BIT(8)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_BFD_RX_STICKY_MAX_LEN_ERR_STICKY  VTSS_BIT(7)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_BFD_RX_STICKY_DM_ZERO_ERR_STICKY  VTSS_BIT(6)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_BFD_RX_STICKY_M_BIT_SET_ERR_STICKY  VTSS_BIT(5)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_BFD_RX_STICKY_MY_DISCR_ERR_STICKY  VTSS_BIT(4)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_BFD_RX_STICKY_YOUR_DISCR_ERR_STICKY  VTSS_BIT(3)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_BFD_RX_STICKY_AUTH_MISMATCH_ERR_STICKY  VTSS_BIT(2)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_BFD_RX_STICKY_D_BIT_SET_ERR_STICKY  VTSS_BIT(1)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_BFD_RX_STICKY_P_AND_F_BIT_SET_ERR_STICKY  VTSS_BIT(0)

#define VTSS_VOP_MPLS_VOE_STAT_MPLS_BFD_TX_STICKY(gi)  VTSS_IOREG_IX(VTSS_TO_VOP_MPLS,0x0,gi,32,0,13)
#define  VTSS_F_VOP_MPLS_VOE_STAT_MPLS_BFD_TX_STICKY_TX_MY_DISCR_MISMATCH  VTSS_BIT(0)

#define VTSS_VOP_MPLS_VOE_STAT_MPLS_BFD_CC_TX_CNT_REG(gi)  VTSS_IOREG_IX(VTSS_TO_VOP_MPLS,0x0,gi,32,0,14)

#define VTSS_VOP_MPLS_VOE_STAT_MPLS_BFD_CV_TX_CNT_REG(gi)  VTSS_IOREG_IX(VTSS_TO_VOP_MPLS,0x0,gi,32,0,15)

#define VTSS_VOP_MPLS_VOE_STAT_MPLS_BFD_CC_RX_VLD_CNT_REG(gi)  VTSS_IOREG_IX(VTSS_TO_VOP_MPLS,0x0,gi,32,0,16)

#define VTSS_VOP_MPLS_VOE_STAT_MPLS_BFD_CV_RX_VLD_CNT_REG(gi)  VTSS_IOREG_IX(VTSS_TO_VOP_MPLS,0x0,gi,32,0,17)

#define VTSS_VOP_MPLS_VOE_STAT_MPLS_BFD_CC_RX_INVLD_CNT_REG(gi)  VTSS_IOREG_IX(VTSS_TO_VOP_MPLS,0x0,gi,32,0,18)

#define VTSS_VOP_MPLS_VOE_STAT_MPLS_BFD_CV_RX_INVLD_CNT_REG(gi)  VTSS_IOREG_IX(VTSS_TO_VOP_MPLS,0x0,gi,32,0,19)


#endif /* _VTSS_JAGUAR2_REGS_VOP_MPLS_H_ */
