#ifndef _VTSS_JAGUAR2_REGS_QRES_H_
#define _VTSS_JAGUAR2_REGS_QRES_H_

/*
 *
 * VCore-III Register Definitions
 *
 * Copyright (C) 2012 Vitesse Semiconductor Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#include "vtss_jaguar2_regs_common.h"

#define VTSS_QRES_RES_WRED_WRED_PROFILE(gi)  VTSS_IOREG_IX(VTSS_TO_QRES,0x5000,gi,1,0,0)
#define  VTSS_F_QRES_RES_WRED_WRED_PROFILE_WM_RED_LOW(x)  VTSS_ENCODE_BITFIELD(x,11,11)
#define  VTSS_M_QRES_RES_WRED_WRED_PROFILE_WM_RED_LOW     VTSS_ENCODE_BITMASK(11,11)
#define  VTSS_X_QRES_RES_WRED_WRED_PROFILE_WM_RED_LOW(x)  VTSS_EXTRACT_BITFIELD(x,11,11)
#define  VTSS_F_QRES_RES_WRED_WRED_PROFILE_WM_RED_HIGH(x)  VTSS_ENCODE_BITFIELD(x,0,11)
#define  VTSS_M_QRES_RES_WRED_WRED_PROFILE_WM_RED_HIGH     VTSS_ENCODE_BITMASK(0,11)
#define  VTSS_X_QRES_RES_WRED_WRED_PROFILE_WM_RED_HIGH(x)  VTSS_EXTRACT_BITFIELD(x,0,11)

#define VTSS_QRES_RES_QOS_ADV_WRED_GROUP(ri)  VTSS_IOREG(VTSS_TO_QRES,0x5048 + (ri))
#define  VTSS_F_QRES_RES_QOS_ADV_WRED_GROUP_WRED_GROUP(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_QRES_RES_QOS_ADV_WRED_GROUP_WRED_GROUP     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_QRES_RES_QOS_ADV_WRED_GROUP_WRED_GROUP(x)  VTSS_EXTRACT_BITFIELD(x,0,2)

#define VTSS_QRES_RES_QOS_ADV_RES_QOS_MODE   VTSS_IOREG(VTSS_TO_QRES,0x5081)
#define  VTSS_F_QRES_RES_QOS_ADV_RES_QOS_MODE_RES_QOS_RSRVD(x)  VTSS_ENCODE_BITFIELD(x,0,8)
#define  VTSS_M_QRES_RES_QOS_ADV_RES_QOS_MODE_RES_QOS_RSRVD     VTSS_ENCODE_BITMASK(0,8)
#define  VTSS_X_QRES_RES_QOS_ADV_RES_QOS_MODE_RES_QOS_RSRVD(x)  VTSS_EXTRACT_BITFIELD(x,0,8)

#define VTSS_QRES_RES_QOS_ADV_PFC_CFG(ri)    VTSS_IOREG(VTSS_TO_QRES,0x5082 + (ri))
#define  VTSS_F_QRES_RES_QOS_ADV_PFC_CFG_TX_PFC_ENA(x)  VTSS_ENCODE_BITFIELD(x,1,8)
#define  VTSS_M_QRES_RES_QOS_ADV_PFC_CFG_TX_PFC_ENA     VTSS_ENCODE_BITMASK(1,8)
#define  VTSS_X_QRES_RES_QOS_ADV_PFC_CFG_TX_PFC_ENA(x)  VTSS_EXTRACT_BITFIELD(x,1,8)
#define  VTSS_F_QRES_RES_QOS_ADV_PFC_CFG_TX_PFC_MODE  VTSS_BIT(0)

#define VTSS_QRES_RES_CTRL_RES_CFG(gi)       VTSS_IOREG_IX(VTSS_TO_QRES,0x0,gi,4,0,0)
#define  VTSS_F_QRES_RES_CTRL_RES_CFG_WM_HIGH(x)  VTSS_ENCODE_BITFIELD(x,0,12)
#define  VTSS_M_QRES_RES_CTRL_RES_CFG_WM_HIGH     VTSS_ENCODE_BITMASK(0,12)
#define  VTSS_X_QRES_RES_CTRL_RES_CFG_WM_HIGH(x)  VTSS_EXTRACT_BITFIELD(x,0,12)

#define VTSS_QRES_RES_CTRL_RES_STAT(gi)      VTSS_IOREG_IX(VTSS_TO_QRES,0x0,gi,4,0,1)
#define  VTSS_F_QRES_RES_CTRL_RES_STAT_MAXUSE(x)  VTSS_ENCODE_BITFIELD(x,0,21)
#define  VTSS_M_QRES_RES_CTRL_RES_STAT_MAXUSE     VTSS_ENCODE_BITMASK(0,21)
#define  VTSS_X_QRES_RES_CTRL_RES_STAT_MAXUSE(x)  VTSS_EXTRACT_BITFIELD(x,0,21)

#define VTSS_QRES_RES_CTRL_RES_STAT_CUR(gi)  VTSS_IOREG_IX(VTSS_TO_QRES,0x0,gi,4,0,2)
#define  VTSS_F_QRES_RES_CTRL_RES_STAT_CUR_INUSE(x)  VTSS_ENCODE_BITFIELD(x,0,21)
#define  VTSS_M_QRES_RES_CTRL_RES_STAT_CUR_INUSE     VTSS_ENCODE_BITMASK(0,21)
#define  VTSS_X_QRES_RES_CTRL_RES_STAT_CUR_INUSE(x)  VTSS_EXTRACT_BITFIELD(x,0,21)


#endif /* _VTSS_JAGUAR2_REGS_QRES_H_ */
