/*

 Vitesse Switch Software.

 Copyright (c) 2002-2013 Vitesse Semiconductor Corporation "Vitesse". All
 Rights Reserved.

 Unpublished rights reserved under the copyright laws of the United States of
 America, other countries and international treaties. Permission to use, copy,
 store and modify, the software and its source code is granted. Permission to
 integrate into other products, disclose, transmit and distribute the software
 in an absolute machine readable format (e.g. HEX file) is also granted.  The
 source code of the software may not be disclosed, transmitted or distributed
 without the written permission of Vitesse. The software and its source code
 may only be used in products utilizing the Vitesse switch products.

 This copyright notice must appear in any copy, modification, disclosure,
 transmission or distribution of the software. Vitesse retains all ownership,
 copyright, trade secret and proprietary rights in the software.

 THIS SOFTWARE HAS BEEN PROVIDED "AS IS," WITHOUT EXPRESS OR IMPLIED WARRANTY
 INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS
 FOR A PARTICULAR USE AND NON-INFRINGEMENT.

*/
#ifndef _VTSS_DAYTONA_REG_INIT_RAB_H
#define _VTSS_DAYTONA_REG_INIT_RAB_H

// Settings for mode MAC

#define  VTSS_RAB_RAB_BASE_RAB_CONTROL_RX_CLK_ENA_MAC                                               VTSS_F_RAB_RAB_BASE_RAB_CONTROL_RX_CLK_ENA(0x1)
#define  VTSS_RAB_RAB_BASE_RAB_CONTROL_RX_BYPASS_SELECT_MAC                                         VTSS_F_RAB_RAB_BASE_RAB_CONTROL_RX_BYPASS_SELECT(0x0)
#define  VTSS_RAB_RAB_BASE_RAB_CONTROL_TX_CLK_ENA_MAC                                               VTSS_F_RAB_RAB_BASE_RAB_CONTROL_TX_CLK_ENA(0x1)
#define  VTSS_RAB_RAB_BASE_RAB_CONTROL_TX_BYPASS_SELECT_MAC                                         VTSS_F_RAB_RAB_BASE_RAB_CONTROL_TX_BYPASS_SELECT(0x0)
#define  VTSS_RAB_RX_FIFO_RX_FIFO_CONTROL_RX_FIFO_INPUT_SELECT_MAC                                  VTSS_F_RAB_RX_FIFO_RX_FIFO_CONTROL_RX_FIFO_INPUT_SELECT(0x0)
#define  VTSS_RAB_RX_FIFO_RX_FIFO_CONTROL_RX_FIFO_OUTPUT_SELECT_MAC                                 VTSS_F_RAB_RX_FIFO_RX_FIFO_CONTROL_RX_FIFO_OUTPUT_SELECT(0x0)
#define  VTSS_RAB_RX_FIFO_RX_FIFO_CONTROL_RX_FIFO_CUT_THRU_MAC                                      VTSS_F_RAB_RX_FIFO_RX_FIFO_CONTROL_RX_FIFO_CUT_THRU(0x1)
#define  VTSS_RAB_TX_FIFO_TX_FIFO_CONTROL_TX_FIFO_INPUT_SELECT_MAC                                  VTSS_F_RAB_TX_FIFO_TX_FIFO_CONTROL_TX_FIFO_INPUT_SELECT(0x0)
#define  VTSS_RAB_TX_FIFO_TX_FIFO_CONTROL_TX_FIFO_OUTPUT_SELECT_MAC                                 VTSS_F_RAB_TX_FIFO_TX_FIFO_CONTROL_TX_FIFO_OUTPUT_SELECT(0x0)
#define  VTSS_RAB_TX_FIFO_TX_FIFO_CONTROL_TX_FIFO_CUT_THRU_MAC                                      VTSS_F_RAB_TX_FIFO_TX_FIFO_CONTROL_TX_FIFO_CUT_THRU(0x1)
#define  VTSS_RAB_RX_FIFO_RX_FIFO_FLUSH_RX_FIFO_FLUSH_MAC                                           VTSS_F_RAB_RX_FIFO_RX_FIFO_FLUSH_RX_FIFO_FLUSH(0x1)
#define  VTSS_RAB_TX_FIFO_TX_FIFO_FLUSH_TX_FIFO_FLUSH_MAC                                           VTSS_F_RAB_TX_FIFO_TX_FIFO_FLUSH_TX_FIFO_FLUSH(0x1)
#define  VTSS_RAB_RX_EXTRACT_RX_EXTRACT_STATUS_RX_EXTRACT_FLUSH_MAC                                 VTSS_F_RAB_RX_EXTRACT_RX_EXTRACT_STATUS_RX_EXTRACT_FLUSH(0x1)
#define  VTSS_RAB_TX_EXTRACT_TX_EXTRACT_STATUS_TX_EXTRACT_FLUSH_MAC                                 VTSS_F_RAB_TX_EXTRACT_TX_EXTRACT_STATUS_TX_EXTRACT_FLUSH(0x1)
#define  VTSS_RAB_RX_FIFO_RX_FIFO_ADAPT_THRESH_RX_FIFO_ADAPT_THRESH_MAC                             VTSS_F_RAB_RX_FIFO_RX_FIFO_ADAPT_THRESH_RX_FIFO_ADAPT_THRESH(0x0)
#define  VTSS_RAB_TX_FIFO_TX_FIFO_ADAPT_THRESH_TX_FIFO_ADAPT_THRESH_MAC                             VTSS_F_RAB_TX_FIFO_TX_FIFO_ADAPT_THRESH_TX_FIFO_ADAPT_THRESH(0x0)


// Settings for mode GFP2

#define  VTSS_RAB_RAB_BASE_RAB_CONTROL_RX_CLK_ENA_GFP2                                              VTSS_F_RAB_RAB_BASE_RAB_CONTROL_RX_CLK_ENA(0x1)
#define  VTSS_RAB_RAB_BASE_RAB_CONTROL_RX_BYPASS_SELECT_GFP2                                        VTSS_F_RAB_RAB_BASE_RAB_CONTROL_RX_BYPASS_SELECT(0x0)
#define  VTSS_RAB_RAB_BASE_RAB_CONTROL_TX_CLK_ENA_GFP2                                              VTSS_F_RAB_RAB_BASE_RAB_CONTROL_TX_CLK_ENA(0x1)
#define  VTSS_RAB_RAB_BASE_RAB_CONTROL_TX_BYPASS_SELECT_GFP2                                        VTSS_F_RAB_RAB_BASE_RAB_CONTROL_TX_BYPASS_SELECT(0x0)
#define  VTSS_RAB_RX_FIFO_RX_FIFO_CONTROL_RX_FIFO_INPUT_SELECT_GFP2                                 VTSS_F_RAB_RX_FIFO_RX_FIFO_CONTROL_RX_FIFO_INPUT_SELECT(0x2)
#define  VTSS_RAB_RX_FIFO_RX_FIFO_CONTROL_RX_FIFO_OUTPUT_SELECT_GFP2                                VTSS_F_RAB_RX_FIFO_RX_FIFO_CONTROL_RX_FIFO_OUTPUT_SELECT(0x0)
#define  VTSS_RAB_RX_FIFO_RX_FIFO_CONTROL_RX_FIFO_CUT_THRU_GFP2                                     VTSS_F_RAB_RX_FIFO_RX_FIFO_CONTROL_RX_FIFO_CUT_THRU(0x1)
#define  VTSS_RAB_TX_FIFO_TX_FIFO_CONTROL_TX_FIFO_INPUT_SELECT_GFP2                                 VTSS_F_RAB_TX_FIFO_TX_FIFO_CONTROL_TX_FIFO_INPUT_SELECT(0x0)
#define  VTSS_RAB_TX_FIFO_TX_FIFO_CONTROL_TX_FIFO_OUTPUT_SELECT_GFP2                                VTSS_F_RAB_TX_FIFO_TX_FIFO_CONTROL_TX_FIFO_OUTPUT_SELECT(0x1)
#define  VTSS_RAB_TX_FIFO_TX_FIFO_CONTROL_TX_FIFO_CUT_THRU_GFP2                                     VTSS_F_RAB_TX_FIFO_TX_FIFO_CONTROL_TX_FIFO_CUT_THRU(0x0)
#define  VTSS_RAB_RX_FIFO_RX_FIFO_FLUSH_RX_FIFO_FLUSH_GFP2                                          VTSS_F_RAB_RX_FIFO_RX_FIFO_FLUSH_RX_FIFO_FLUSH(0x1)
#define  VTSS_RAB_TX_FIFO_TX_FIFO_FLUSH_TX_FIFO_FLUSH_GFP2                                          VTSS_F_RAB_TX_FIFO_TX_FIFO_FLUSH_TX_FIFO_FLUSH(0x1)
#define  VTSS_RAB_RX_EXTRACT_RX_EXTRACT_STATUS_RX_EXTRACT_FLUSH_GFP2                                VTSS_F_RAB_RX_EXTRACT_RX_EXTRACT_STATUS_RX_EXTRACT_FLUSH(0x1)
#define  VTSS_RAB_TX_EXTRACT_TX_EXTRACT_STATUS_TX_EXTRACT_FLUSH_GFP2                                VTSS_F_RAB_TX_EXTRACT_TX_EXTRACT_STATUS_TX_EXTRACT_FLUSH(0x1)
#define  VTSS_RAB_RX_FIFO_RX_FIFO_ADAPT_THRESH_RX_FIFO_ADAPT_THRESH_GFP2                            VTSS_F_RAB_RX_FIFO_RX_FIFO_ADAPT_THRESH_RX_FIFO_ADAPT_THRESH(0x0)
#define  VTSS_RAB_TX_FIFO_TX_FIFO_ADAPT_THRESH_TX_FIFO_ADAPT_THRESH_GFP2                            VTSS_F_RAB_TX_FIFO_TX_FIFO_ADAPT_THRESH_TX_FIFO_ADAPT_THRESH(0xf80)


// Settings for mode GFP2_PPOS

#define  VTSS_RAB_RAB_BASE_RAB_CONTROL_RX_CLK_ENA_GFP2_PPOS                                         VTSS_F_RAB_RAB_BASE_RAB_CONTROL_RX_CLK_ENA(0x0)
#define  VTSS_RAB_RAB_BASE_RAB_CONTROL_RX_BYPASS_SELECT_GFP2_PPOS                                   VTSS_F_RAB_RAB_BASE_RAB_CONTROL_RX_BYPASS_SELECT(0x1)
#define  VTSS_RAB_RAB_BASE_RAB_CONTROL_TX_CLK_ENA_GFP2_PPOS                                         VTSS_F_RAB_RAB_BASE_RAB_CONTROL_TX_CLK_ENA(0x1)
#define  VTSS_RAB_RAB_BASE_RAB_CONTROL_TX_BYPASS_SELECT_GFP2_PPOS                                   VTSS_F_RAB_RAB_BASE_RAB_CONTROL_TX_BYPASS_SELECT(0x0)
#define  VTSS_RAB_RX_FIFO_RX_FIFO_CONTROL_RX_FIFO_INPUT_SELECT_GFP2_PPOS                            VTSS_F_RAB_RX_FIFO_RX_FIFO_CONTROL_RX_FIFO_INPUT_SELECT(0x0)
#define  VTSS_RAB_RX_FIFO_RX_FIFO_CONTROL_RX_FIFO_OUTPUT_SELECT_GFP2_PPOS                           VTSS_F_RAB_RX_FIFO_RX_FIFO_CONTROL_RX_FIFO_OUTPUT_SELECT(0x0)
#define  VTSS_RAB_RX_FIFO_RX_FIFO_CONTROL_RX_FIFO_CUT_THRU_GFP2_PPOS                                VTSS_F_RAB_RX_FIFO_RX_FIFO_CONTROL_RX_FIFO_CUT_THRU(0x1)
#define  VTSS_RAB_TX_FIFO_TX_FIFO_CONTROL_TX_FIFO_INPUT_SELECT_GFP2_PPOS                            VTSS_F_RAB_TX_FIFO_TX_FIFO_CONTROL_TX_FIFO_INPUT_SELECT(0x1)
#define  VTSS_RAB_TX_FIFO_TX_FIFO_CONTROL_TX_FIFO_OUTPUT_SELECT_GFP2_PPOS                           VTSS_F_RAB_TX_FIFO_TX_FIFO_CONTROL_TX_FIFO_OUTPUT_SELECT(0x1)
#define  VTSS_RAB_TX_FIFO_TX_FIFO_CONTROL_TX_FIFO_CUT_THRU_GFP2_PPOS                                VTSS_F_RAB_TX_FIFO_TX_FIFO_CONTROL_TX_FIFO_CUT_THRU(0x0)
#define  VTSS_RAB_RX_FIFO_RX_FIFO_FLUSH_RX_FIFO_FLUSH_GFP2_PPOS                                     VTSS_F_RAB_RX_FIFO_RX_FIFO_FLUSH_RX_FIFO_FLUSH(0x1)
#define  VTSS_RAB_TX_FIFO_TX_FIFO_FLUSH_TX_FIFO_FLUSH_GFP2_PPOS                                     VTSS_F_RAB_TX_FIFO_TX_FIFO_FLUSH_TX_FIFO_FLUSH(0x1)
#define  VTSS_RAB_RX_EXTRACT_RX_EXTRACT_STATUS_RX_EXTRACT_FLUSH_GFP2_PPOS                           VTSS_F_RAB_RX_EXTRACT_RX_EXTRACT_STATUS_RX_EXTRACT_FLUSH(0x1)
#define  VTSS_RAB_TX_EXTRACT_TX_EXTRACT_STATUS_TX_EXTRACT_FLUSH_GFP2_PPOS                           VTSS_F_RAB_TX_EXTRACT_TX_EXTRACT_STATUS_TX_EXTRACT_FLUSH(0x1)
#define  VTSS_RAB_RX_FIFO_RX_FIFO_ADAPT_THRESH_RX_FIFO_ADAPT_THRESH_GFP2_PPOS                       VTSS_F_RAB_RX_FIFO_RX_FIFO_ADAPT_THRESH_RX_FIFO_ADAPT_THRESH(0x0)
#define  VTSS_RAB_TX_FIFO_TX_FIFO_ADAPT_THRESH_TX_FIFO_ADAPT_THRESH_GFP2_PPOS                       VTSS_F_RAB_TX_FIFO_TX_FIFO_ADAPT_THRESH_TX_FIFO_ADAPT_THRESH(0xf80)


// Settings for mode GFP1

#define  VTSS_RAB_RAB_BASE_RAB_CONTROL_RX_CLK_ENA_GFP1                                              VTSS_F_RAB_RAB_BASE_RAB_CONTROL_RX_CLK_ENA(0x1)
#define  VTSS_RAB_RAB_BASE_RAB_CONTROL_RX_BYPASS_SELECT_GFP1                                        VTSS_F_RAB_RAB_BASE_RAB_CONTROL_RX_BYPASS_SELECT(0x0)
#define  VTSS_RAB_RAB_BASE_RAB_CONTROL_TX_CLK_ENA_GFP1                                              VTSS_F_RAB_RAB_BASE_RAB_CONTROL_TX_CLK_ENA(0x1)
#define  VTSS_RAB_RAB_BASE_RAB_CONTROL_TX_BYPASS_SELECT_GFP1                                        VTSS_F_RAB_RAB_BASE_RAB_CONTROL_TX_BYPASS_SELECT(0x0)
#define  VTSS_RAB_RX_FIFO_RX_FIFO_CONTROL_RX_FIFO_INPUT_SELECT_GFP1                                 VTSS_F_RAB_RX_FIFO_RX_FIFO_CONTROL_RX_FIFO_INPUT_SELECT(0x0)
#define  VTSS_RAB_RX_FIFO_RX_FIFO_CONTROL_RX_FIFO_OUTPUT_SELECT_GFP1                                VTSS_F_RAB_RX_FIFO_RX_FIFO_CONTROL_RX_FIFO_OUTPUT_SELECT(0x1)
#define  VTSS_RAB_RX_FIFO_RX_FIFO_CONTROL_RX_FIFO_CUT_THRU_GFP1                                     VTSS_F_RAB_RX_FIFO_RX_FIFO_CONTROL_RX_FIFO_CUT_THRU(0x0)
#define  VTSS_RAB_TX_FIFO_TX_FIFO_CONTROL_TX_FIFO_INPUT_SELECT_GFP1                                 VTSS_F_RAB_TX_FIFO_TX_FIFO_CONTROL_TX_FIFO_INPUT_SELECT(0x2)
#define  VTSS_RAB_TX_FIFO_TX_FIFO_CONTROL_TX_FIFO_OUTPUT_SELECT_GFP1                                VTSS_F_RAB_TX_FIFO_TX_FIFO_CONTROL_TX_FIFO_OUTPUT_SELECT(0x0)
#define  VTSS_RAB_TX_FIFO_TX_FIFO_CONTROL_TX_FIFO_CUT_THRU_GFP1                                     VTSS_F_RAB_TX_FIFO_TX_FIFO_CONTROL_TX_FIFO_CUT_THRU(0x1)
#define  VTSS_RAB_RX_FIFO_RX_FIFO_FLUSH_RX_FIFO_FLUSH_GFP1                                          VTSS_F_RAB_RX_FIFO_RX_FIFO_FLUSH_RX_FIFO_FLUSH(0x1)
#define  VTSS_RAB_TX_FIFO_TX_FIFO_FLUSH_TX_FIFO_FLUSH_GFP1                                          VTSS_F_RAB_TX_FIFO_TX_FIFO_FLUSH_TX_FIFO_FLUSH(0x1)
#define  VTSS_RAB_RX_EXTRACT_RX_EXTRACT_STATUS_RX_EXTRACT_FLUSH_GFP1                                VTSS_F_RAB_RX_EXTRACT_RX_EXTRACT_STATUS_RX_EXTRACT_FLUSH(0x1)
#define  VTSS_RAB_TX_EXTRACT_TX_EXTRACT_STATUS_TX_EXTRACT_FLUSH_GFP1                                VTSS_F_RAB_TX_EXTRACT_TX_EXTRACT_STATUS_TX_EXTRACT_FLUSH(0x1)
#define  VTSS_RAB_RX_FIFO_RX_FIFO_ADAPT_THRESH_RX_FIFO_ADAPT_THRESH_GFP1                            VTSS_F_RAB_RX_FIFO_RX_FIFO_ADAPT_THRESH_RX_FIFO_ADAPT_THRESH(0x1f80)
#define  VTSS_RAB_TX_FIFO_TX_FIFO_ADAPT_THRESH_TX_FIFO_ADAPT_THRESH_GFP1                            VTSS_F_RAB_TX_FIFO_TX_FIFO_ADAPT_THRESH_TX_FIFO_ADAPT_THRESH(0x0)


// Settings for mode GFP1_PPOS

#define  VTSS_RAB_RAB_BASE_RAB_CONTROL_RX_CLK_ENA_GFP1_PPOS                                         VTSS_F_RAB_RAB_BASE_RAB_CONTROL_RX_CLK_ENA(0x1)
#define  VTSS_RAB_RAB_BASE_RAB_CONTROL_RX_BYPASS_SELECT_GFP1_PPOS                                   VTSS_F_RAB_RAB_BASE_RAB_CONTROL_RX_BYPASS_SELECT(0x0)
#define  VTSS_RAB_RAB_BASE_RAB_CONTROL_TX_CLK_ENA_GFP1_PPOS                                         VTSS_F_RAB_RAB_BASE_RAB_CONTROL_TX_CLK_ENA(0x0)
#define  VTSS_RAB_RAB_BASE_RAB_CONTROL_TX_BYPASS_SELECT_GFP1_PPOS                                   VTSS_F_RAB_RAB_BASE_RAB_CONTROL_TX_BYPASS_SELECT(0x1)
#define  VTSS_RAB_RX_FIFO_RX_FIFO_CONTROL_RX_FIFO_INPUT_SELECT_GFP1_PPOS                            VTSS_F_RAB_RX_FIFO_RX_FIFO_CONTROL_RX_FIFO_INPUT_SELECT(0x1)
#define  VTSS_RAB_RX_FIFO_RX_FIFO_CONTROL_RX_FIFO_OUTPUT_SELECT_GFP1_PPOS                           VTSS_F_RAB_RX_FIFO_RX_FIFO_CONTROL_RX_FIFO_OUTPUT_SELECT(0x1)
#define  VTSS_RAB_RX_FIFO_RX_FIFO_CONTROL_RX_FIFO_CUT_THRU_GFP1_PPOS                                VTSS_F_RAB_RX_FIFO_RX_FIFO_CONTROL_RX_FIFO_CUT_THRU(0x0)
#define  VTSS_RAB_TX_FIFO_TX_FIFO_CONTROL_TX_FIFO_INPUT_SELECT_GFP1_PPOS                            VTSS_F_RAB_TX_FIFO_TX_FIFO_CONTROL_TX_FIFO_INPUT_SELECT(0x0)
#define  VTSS_RAB_TX_FIFO_TX_FIFO_CONTROL_TX_FIFO_OUTPUT_SELECT_GFP1_PPOS                           VTSS_F_RAB_TX_FIFO_TX_FIFO_CONTROL_TX_FIFO_OUTPUT_SELECT(0x0)
#define  VTSS_RAB_TX_FIFO_TX_FIFO_CONTROL_TX_FIFO_CUT_THRU_GFP1_PPOS                                VTSS_F_RAB_TX_FIFO_TX_FIFO_CONTROL_TX_FIFO_CUT_THRU(0x1)
#define  VTSS_RAB_RX_FIFO_RX_FIFO_FLUSH_RX_FIFO_FLUSH_GFP1_PPOS                                     VTSS_F_RAB_RX_FIFO_RX_FIFO_FLUSH_RX_FIFO_FLUSH(0x1)
#define  VTSS_RAB_TX_FIFO_TX_FIFO_FLUSH_TX_FIFO_FLUSH_GFP1_PPOS                                     VTSS_F_RAB_TX_FIFO_TX_FIFO_FLUSH_TX_FIFO_FLUSH(0x1)
#define  VTSS_RAB_RX_EXTRACT_RX_EXTRACT_STATUS_RX_EXTRACT_FLUSH_GFP1_PPOS                           VTSS_F_RAB_RX_EXTRACT_RX_EXTRACT_STATUS_RX_EXTRACT_FLUSH(0x1)
#define  VTSS_RAB_TX_EXTRACT_TX_EXTRACT_STATUS_TX_EXTRACT_FLUSH_GFP1_PPOS                           VTSS_F_RAB_TX_EXTRACT_TX_EXTRACT_STATUS_TX_EXTRACT_FLUSH(0x1)
#define  VTSS_RAB_RX_FIFO_RX_FIFO_ADAPT_THRESH_RX_FIFO_ADAPT_THRESH_GFP1_PPOS                       VTSS_F_RAB_RX_FIFO_RX_FIFO_ADAPT_THRESH_RX_FIFO_ADAPT_THRESH(0x1f80)
#define  VTSS_RAB_TX_FIFO_TX_FIFO_ADAPT_THRESH_TX_FIFO_ADAPT_THRESH_GFP1_PPOS                       VTSS_F_RAB_TX_FIFO_TX_FIFO_ADAPT_THRESH_TX_FIFO_ADAPT_THRESH(0x0)


// Settings for mode BYP

#define  VTSS_RAB_RAB_BASE_RAB_CONTROL_RX_CLK_ENA_BYP                                               VTSS_F_RAB_RAB_BASE_RAB_CONTROL_RX_CLK_ENA(0x0)
#define  VTSS_RAB_RAB_BASE_RAB_CONTROL_RX_BYPASS_SELECT_BYP                                         VTSS_F_RAB_RAB_BASE_RAB_CONTROL_RX_BYPASS_SELECT(0x0)
#define  VTSS_RAB_RAB_BASE_RAB_CONTROL_TX_CLK_ENA_BYP                                               VTSS_F_RAB_RAB_BASE_RAB_CONTROL_TX_CLK_ENA(0x0)
#define  VTSS_RAB_RAB_BASE_RAB_CONTROL_TX_BYPASS_SELECT_BYP                                         VTSS_F_RAB_RAB_BASE_RAB_CONTROL_TX_BYPASS_SELECT(0x0)
#define  VTSS_RAB_RX_FIFO_RX_FIFO_CONTROL_RX_FIFO_INPUT_SELECT_BYP                                  VTSS_F_RAB_RX_FIFO_RX_FIFO_CONTROL_RX_FIFO_INPUT_SELECT(0x0)
#define  VTSS_RAB_RX_FIFO_RX_FIFO_CONTROL_RX_FIFO_OUTPUT_SELECT_BYP                                 VTSS_F_RAB_RX_FIFO_RX_FIFO_CONTROL_RX_FIFO_OUTPUT_SELECT(0x0)
#define  VTSS_RAB_RX_FIFO_RX_FIFO_CONTROL_RX_FIFO_CUT_THRU_BYP                                      VTSS_F_RAB_RX_FIFO_RX_FIFO_CONTROL_RX_FIFO_CUT_THRU(0x1)
#define  VTSS_RAB_TX_FIFO_TX_FIFO_CONTROL_TX_FIFO_INPUT_SELECT_BYP                                  VTSS_F_RAB_TX_FIFO_TX_FIFO_CONTROL_TX_FIFO_INPUT_SELECT(0x0)
#define  VTSS_RAB_TX_FIFO_TX_FIFO_CONTROL_TX_FIFO_OUTPUT_SELECT_BYP                                 VTSS_F_RAB_TX_FIFO_TX_FIFO_CONTROL_TX_FIFO_OUTPUT_SELECT(0x0)
#define  VTSS_RAB_TX_FIFO_TX_FIFO_CONTROL_TX_FIFO_CUT_THRU_BYP                                      VTSS_F_RAB_TX_FIFO_TX_FIFO_CONTROL_TX_FIFO_CUT_THRU(0x1)
#define  VTSS_RAB_RX_FIFO_RX_FIFO_FLUSH_RX_FIFO_FLUSH_BYP                                           VTSS_F_RAB_RX_FIFO_RX_FIFO_FLUSH_RX_FIFO_FLUSH(0x1)
#define  VTSS_RAB_TX_FIFO_TX_FIFO_FLUSH_TX_FIFO_FLUSH_BYP                                           VTSS_F_RAB_TX_FIFO_TX_FIFO_FLUSH_TX_FIFO_FLUSH(0x1)
#define  VTSS_RAB_RX_EXTRACT_RX_EXTRACT_STATUS_RX_EXTRACT_FLUSH_BYP                                 VTSS_F_RAB_RX_EXTRACT_RX_EXTRACT_STATUS_RX_EXTRACT_FLUSH(0x1)
#define  VTSS_RAB_TX_EXTRACT_TX_EXTRACT_STATUS_TX_EXTRACT_FLUSH_BYP                                 VTSS_F_RAB_TX_EXTRACT_TX_EXTRACT_STATUS_TX_EXTRACT_FLUSH(0x1)
#define  VTSS_RAB_RX_FIFO_RX_FIFO_ADAPT_THRESH_RX_FIFO_ADAPT_THRESH_BYP                             VTSS_F_RAB_RX_FIFO_RX_FIFO_ADAPT_THRESH_RX_FIFO_ADAPT_THRESH(0x1f80)
#define  VTSS_RAB_TX_FIFO_TX_FIFO_ADAPT_THRESH_TX_FIFO_ADAPT_THRESH_BYP                             VTSS_F_RAB_TX_FIFO_TX_FIFO_ADAPT_THRESH_TX_FIFO_ADAPT_THRESH(0xf80)




typedef enum {
    BM_RAB_MAC,
    BM_RAB_GFP2,
    BM_RAB_GFP2_PPOS,
    BM_RAB_GFP1,
    BM_RAB_GFP1_PPOS,
    BM_RAB_BYP,
    BM_RAB_LAST
} block_rab_mode_t;

#endif /* _VTSS_DAYTONA_REG_INIT_RAB_H */
