/*

 Vitesse Switch Software.

 Copyright (c) 2002-2010 Vitesse Semiconductor Corporation "Vitesse". All
 Rights Reserved.

 Unpublished rights reserved under the copyright laws of the United States of
 America, other countries and international treaties. Permission to use, copy,
 store and modify, the software and its source code is granted. Permission to
 integrate into other products, disclose, transmit and distribute the software
 in an absolute machine readable format (e.g. HEX file) is also granted.  The
 source code of the software may not be disclosed, transmitted or distributed
 without the written permission of Vitesse. The software and its source code
 may only be used in products utilizing the Vitesse switch products.

 This copyright notice must appear in any copy, modification, disclosure,
 transmission or distribution of the software. Vitesse retains all ownership,
 copyright, trade secret and proprietary rights in the software.

 THIS SOFTWARE HAS BEEN PROVIDED "AS IS," WITHOUT EXPRESS OR IMPLIED WARRANTY
 INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS
 FOR A PARTICULAR USE AND NON-INFRINGEMENT.

*/
/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf
 */

#ifndef RFC3635_ETHERLIKE_H
#define RFC3635_ETHERLIKE_H

#define RFC3635_SUPPORTED_TRANSMISSION     1

/*
 * function declarations
 */
#if RFC3635_SUPPORTED_TRANSMISSION
/* transmission ----------------------------------------------------------*/
void            init_transmission(void);
FindVarMethod   var_transmission;
FindVarMethod   var_dot3HCStatsTable;
FindVarMethod   var_dot3ControlTable;
FindVarMethod   var_dot3StatsTable;
FindVarMethod   var_dot3CollTable;
FindVarMethod   var_dot3PauseTable;
WriteMethod     write_dot3PauseAdminMode;
#endif /* RFC3635_SUPPORTED_TRANSMISSION */

#endif                          /* RFC3635_ETHERLIKE_H */

