/*

 Vitesse Switch Software.

 Copyright (c) 2002-2012 Vitesse Semiconductor Corporation "Vitesse". All
 Rights Reserved.

 Unpublished rights reserved under the copyright laws of the United States of
 America, other countries and international treaties. Permission to use, copy,
 store and modify, the software and its source code is granted. Permission to
 integrate into other products, disclose, transmit and distribute the software
 in an absolute machine readable format (e.g. HEX file) is also granted.  The
 source code of the software may not be disclosed, transmitted or distributed
 without the written permission of Vitesse. The software and its source code
 may only be used in products utilizing the Vitesse switch products.

 This copyright notice must appear in any copy, modification, disclosure,
 transmission or distribution of the software. Vitesse retains all ownership,
 copyright, trade secret and proprietary rights in the software.

 THIS SOFTWARE HAS BEEN PROVIDED "AS IS," WITHOUT EXPRESS OR IMPLIED WARRANTY
 INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS
 FOR A PARTICULAR USE AND NON-INFRINGEMENT.

*/
/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef DOT1DTP_H
#define DOT1DTP_H

#define RFC4188_SUPPORTED_DOT1D_BRIDGE      1
#define RFC4188_SUPPORTED_DOT1DBASE
#define RFC4188_SUPPORTED_DOT1DTP

void init_dot1dBridge(void);

#ifdef RFC4188_SUPPORTED_DOT1DBASE
/* function declarations: dot1dBase */
void init_dot1dBase(void);
FindVarMethod var_dot1dBase;
FindVarMethod var_dot1dBasePortTable;
#endif /* RFC4188_SUPPORTED_DOT1DBASE */

#ifdef RFC4188_SUPPORTED_DOT1DTP
/* function declarations: dot1dTp */
void init_dot1dTp(void);
FindVarMethod var_dot1dTp;
FindVarMethod var_dot1dTpFdbTable;
FindVarMethod var_dot1dTpPortTable;
FindVarMethod var_dot1dTpHCPortTable;
FindVarMethod var_dot1dTpPortOverflowTable;
WriteMethod write_dot1dTpAgingTime;
#endif /* RFC4188_SUPPORTED_DOT1DTP */

#endif /* DOT1DTP_H */

