/*

 Vitesse Switch Software.

 Copyright (c) 2002-2011 Vitesse Semiconductor Corporation "Vitesse". All
 Rights Reserved.

 Unpublished rights reserved under the copyright laws of the United States of
 America, other countries and international treaties. Permission to use, copy,
 store and modify, the software and its source code is granted. Permission to
 integrate into other products, disclose, transmit and distribute the software
 in an absolute machine readable format (e.g. HEX file) is also granted.  The
 source code of the software may not be disclosed, transmitted or distributed
 without the written permission of Vitesse. The software and its source code
 may only be used in products utilizing the Vitesse switch products.

 This copyright notice must appear in any copy, modification, disclosure,
 transmission or distribution of the software. Vitesse retains all ownership,
 copyright, trade secret and proprietary rights in the software.

 THIS SOFTWARE HAS BEEN PROVIDED "AS IS," WITHOUT EXPRESS OR IMPLIED WARRANTY
 INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS
 FOR A PARTICULAR USE AND NON-INFRINGEMENT.

*/
/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf
 */

#ifndef RFC4133_ENTITY_H
#define RFC4133_ENTITY_H

#define RFC4133_SUPPORTED_ENTITY                        1
#define RFC4133_SUPPORTED_PHYSICAL              1
#define RFC4133_SUPPORTED_LOGICAL               0
#define RFC4133_SUPPORTED_MAPPING               0
#define RFC4133_SUPPORTED_PHYSICAL_WRITE    0
#define RFC4133_SUPPORTED_TRAPS                 1

/*
 * function declarations
 */
#if RFC4133_SUPPORTED_ENTITY
void            init_entityMIB(void);
FindVarMethod   var_entityMIB;
void            init_entityMIBObjects(void);
FindVarMethod   var_entityMIBObjects;

#if RFC4133_SUPPORTED_PHYSICAL
FindVarMethod   var_entPhysicalTable;
#endif /*RFC4133_SUPPORTED_PHYSICAL*/

#if RFC4133_SUPPORTED_LOGICAL
FindVarMethod   var_entLogicalTable;
#endif /*RFC4133_SUPPORTED_LOGICAL*/

#if RFC4133_SUPPORTED_MAPPING
FindVarMethod   var_entLPMappingTable;
FindVarMethod   var_entAliasMappingTable;
FindVarMethod   var_entPhysicalContainsTable;
#endif /*RFC4133_SUPPORTED_MAPPING*/

#if RFC4133_SUPPORTED_PHYSICAL_WRITE
WriteMethod     write_entPhysicalSerialNum;
WriteMethod     write_entPhysicalAlias;
WriteMethod     write_entPhysicalAssetID;
WriteMethod     write_entPhysicalUris;
#endif /*RFC4133_SUPPORTED_PHYSICAL*/

vtss_rc entConfigChange(vtss_isid_t isid);
#if RFC4133_SUPPORTED_TRAPS
void            init_entityMIBTraps(void);
FindVarMethod   var_entityMIBTraps;
#endif /*RFC4133_SUPPORTED_TRAPS*/

#endif /* RFC4133_SUPPORTED_ENTITY */

#endif                          /* ENTITYMIB_H */

